### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by MARIASUAM** [NetLogo/NetLogo#1023]
Maybe someone can help me with this error, it appears when I do set up. Thanks!

java.lang.NoClassDefFoundError: org/joda/time/ReadablePartial
 at TimeExtension$NewLogoTime.report(TimeExtension.java:1445)
 at org.nlogo.prim._externreport.report(_externreport.java:50)
 at org.nlogo.prim._asm_proceduresetup_setobservervariable_1.perform()
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:91)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.java:82)
 at org.nlogo.job.JobThread.org$nlogo$job$JobThread$$runPrimaryJobs(JobThread.scala:143)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply$mcV$sp(JobThread.scala:78)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at scala.util.control.Exception$Catch.apply(Exception.scala:88)
 at org.nlogo.util.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:75)
Caused by: java.lang.ClassNotFoundException: org.joda.time.ReadablePartial
 at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
 at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
 ... 12 more

NetLogo 5.3.1
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_74 (Oracle Corporation; 1.8.0_74-b02)
operating system: Windows 7 6.1 (amd64 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: INSTAR

09:57:42.725 TickStateChangeEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
09:57:42.709 OutputEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:57:42.678 AddJobEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
09:57:42.600 InputBoxLoseFocusEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
09:57:42.600 AddJobEvent (org.nlogo.window.MonitorWidget) AWT-EventQueue-0
09:57:42.600 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
09:57:42.600 AddJobEvent (org.nlogo.window.MonitorWidget) AWT-EventQueue-0
09:57:42.600 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
09:57:42.600 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:57:42.600 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread

**Comment by mrerrormessage** [comment]
This appears to be a bug with the time extension due to joda-time not being on the classpath. You should reach out to the modeler who provided you with the model first to see if they forgot to distribute the joda-time jar with the model and/or reinstall the NetLogo time extension. I'm closing this as an issue, but please feel free to comment if you continue to encounter problems and I'll try to help you work through them.

**Comment by MARIASUAM** [comment]
Actually, I just got the code, and when trying to open it I had to install the time extension (together with extension rnd) as the program as me to do so. 

I have tried deleting the time extension and downloading it again, but does not seem to work, I get the same error as before. Could it be some incompatibility between versions? I'm running NetLogo 5.3.1 at the moment.

**Comment by SethTisue** [comment]
I'd suggest taking it up with the author of the extension.

**Comment by MARIASUAM** [comment]
Finally, it was solved by installing the time extension again but this time including in the extensions folder the whole downloaded folder, apparently like this NetLogo is able to compile it for the right version.

Thanks for the help!
