### ISSUE TITLE
M6: file-close-all throws ClassNotFound

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#1041]
Try running `file-close-all` in the command center, or opening any model that uses it. You will immediately get:

```
java.security.PrivilegedActionException: java.security.PrivilegedActionException: java.lang.ClassNotFoundException: org.nlogo.prim.etc._filecloseall
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.security.PrivilegedActionException: java.lang.ClassNotFoundException: org.nlogo.prim.etc._filecloseall
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.awt.EventQueue$4.run(EventQueue.java:729)
 ... 9 more
Caused by: java.lang.ClassNotFoundException: org.nlogo.prim.etc._filecloseall
 at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
 at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
 at java.lang.Class.forName0(Native Method)
 at java.lang.Class.forName(Class.java:264)
 at org.nlogo.compiler.Backifier.fallback(Backifier.scala:127)
 at org.nlogo.compiler.Backifier.apply(Backifier.scala:152)
 at org.nlogo.compiler.ASTBackifier.backify(ASTBackifier.scala:35)
 at org.nlogo.compiler.ASTBackifier$$anonfun$backify$1.apply(ASTBackifier.scala:29)
 at org.nlogo.compiler.ASTBackifier$$anonfun$backify$1.apply(ASTBackifier.scala:29)
 at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
 at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
 at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
 at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
 at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
 at scala.collection.AbstractTraversable.map(Traversable.scala:104)
 at org.nlogo.compiler.ASTBackifier.backify(ASTBackifier.scala:29)
 at org.nlogo.compiler.ASTBackifier.backifyProcedure(ASTBackifier.scala:18)
 at org.nlogo.compiler.CompilerBridge$$anonfun$3.apply(CompilerBridge.scala:28)
 at org.nlogo.compiler.CompilerBridge$$anonfun$3.apply(CompilerBridge.scala:28)
 at scala.Function2$$anonfun$tupled$1.apply(Function2.scala:48)
 at scala.Function2$$anonfun$tupled$1.apply(Function2.scala:47)
 at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
 at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
 at scala.collection.immutable.List.foreach(List.scala:381)
 at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
 at scala.collection.immutable.List.map(List.scala:285)
 at org.nlogo.compiler.CompilerBridge$.apply(CompilerBridge.scala:28)
 at org.nlogo.compiler.CompilerMain$.compile(CompilerMain.scala:30)
 at org.nlogo.compiler.Compiler.compileMoreCode(Compiler.scala:63)
 at org.nlogo.window.CompilerManager.handle(CompilerManager.java:239)
 at org.nlogo.window.Events$CompileMoreSourceEvent.beHandledBy(Events.java:190)
 at org.nlogo.window.Event.doRaise(Event.java:198)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.window.JobWidget.source(JobWidget.scala:120)
 at org.nlogo.app.CommandLine.executeCurrentBuffer(CommandLine.scala:157)
 at org.nlogo.app.CommandLine.keyPressed(CommandLine.scala:118)
 at java.awt.Component.processKeyEvent(Component.java:6491)
 at javax.swing.JComponent.processKeyEvent(JComponent.java:2832)
 at java.awt.Component.processEvent(Component.java:6310)
 at java.awt.Container.processEvent(Container.java:2236)
 at java.awt.Component.dispatchEventImpl(Component.java:4889)
 at java.awt.Container.dispatchEventImpl(Container.java:2294)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
 at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
 at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
 at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
 at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
 at java.awt.Component.dispatchEventImpl(Component.java:4760)
 at java.awt.Container.dispatchEventImpl(Container.java:2294)
 at java.awt.Window.dispatchEventImpl(Window.java:2746)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 ... 14 more
```

**Comment by SethTisue** [comment]
seems like an easy mistake to make; is there missing test coverage here that could make this mistake impossible to make?
