### ISSUE TITLE
Hexy model loading: Model saved in post model-loading merge with empty input box causes exception when loaded in M6

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#1054]
This is only a bug if 6.0 nlogo files are supposed to be backwards compatible (and I think they are). To reproduce:

1. Create a model in using master.
2. Add an input widget (tested with string type)
3. Save.
4. Load in M6 or earlier. You'll get:

```
java.lang.reflect.InvocationTargetException
 at java.awt.EventQueue.invokeAndWait(EventQueue.java:1321)
 at java.awt.EventQueue.invokeAndWait(EventQueue.java:1296)
 at org.nlogo.awt.EventQueue$.invokeAndWait(EventQueue.scala:19)
 at org.nlogo.swing.ModalProgressTask$Boss.run(ModalProgressTask.scala:70)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 6
 at org.nlogo.window.InputBox.load(InputBox.scala:317)
 at org.nlogo.window.InputBox.load(InputBox.scala:23)
 at org.nlogo.app.InterfacePanel.loadWidget(InterfacePanel.java:293)
 at org.nlogo.app.InterfacePanel.loadWidget(InterfacePanel.java:233)
 at org.nlogo.app.WidgetPanel.loadWidgets(WidgetPanel.java:716)
 at org.nlogo.app.InterfacePanel.handle(InterfacePanel.java:377)
 at org.nlogo.window.Events$LoadSectionEvent.beHandledBy(Events.java:470)
 at org.nlogo.window.Event.doRaise(Event.java:198)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.window.ModelLoader$Loader$$anonfun$loadHelper$1.apply(ModelLoader.scala:102)
 at org.nlogo.window.ModelLoader$Loader$$anonfun$loadHelper$1.apply(ModelLoader.scala:102)
 at scala.collection.immutable.List.foreach(List.scala:381)
 at org.nlogo.window.ModelLoader$Loader.loadHelper(ModelLoader.scala:102)
 at org.nlogo.window.ModelLoader$.load(ModelLoader.scala:17)
 at org.nlogo.window.ModelLoader.load(ModelLoader.scala)
 at org.nlogo.app.FileMenu$1.run(FileMenu.java:764)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
 at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
 at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
 at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
 at java.awt.Dialog.show(Dialog.java:1084)
 at java.awt.Component.show(Component.java:1671)
 at java.awt.Component.setVisible(Component.java:1623)
 at java.awt.Window.setVisible(Window.java:1014)
 at java.awt.Dialog.setVisible(Dialog.java:1005)
 at org.nlogo.swing.ModalProgressTask$.apply(ModalProgressTask.scala:43)
 at org.nlogo.swing.ModalProgressTask.apply(ModalProgressTask.scala)
 at org.nlogo.app.FileMenu.openFromMap(FileMenu.java:773)
 at org.nlogo.app.FileMenu.openFromSource(FileMenu.java:745)
 at org.nlogo.app.FileMenu.openFromPath(FileMenu.java:699)
 at org.nlogo.app.App$$anonfun$open$1.apply$mcV$sp(App.scala:818)
 at org.nlogo.app.App$$anonfun$open$1.apply(App.scala:818)
 at org.nlogo.app.App$$anonfun$open$1.apply(App.scala:818)
 at org.nlogo.app.App.dispatchThreadOrBust(App.scala:1071)
 at org.nlogo.app.App.open(App.scala:818)
 at org.nlogo.app.App.loadDefaultModel(App.scala:518)
 at org.nlogo.app.App.org$nlogo$app$App$$finishStartup(App.scala:455)
 at org.nlogo.app.App$$anonfun$mainWithAppHandler$1.apply$mcV$sp(App.scala:156)
 at org.nlogo.swing.Implicits$$anon$17.run(Implicits.scala:13)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

NetLogo 6.0-M6
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_92 (Oracle Corporation; 1.8.0_92-b14)
operating system: Mac OS X 10.11.4 (x86_64 processor)
Scala version 2.11.8
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: test-load

05:14:46.580 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
05:14:46.562 ResizeViewEvent (org.nlogo.window.ViewWidget) AWT-EventQueue-0
05:14:46.562 ResizeViewEvent (org.nlogo.window.ViewWidget) AWT-EventQueue-0
05:14:46.561 LoadSectionEvent (org.nlogo.window.ModelLoader$Loader (java.lang.Object)) AWT-EventQueue-0
05:14:46.534 LoadSectionEvent (org.nlogo.window.ModelLoader$Loader (java.lang.Object)) AWT-EventQueue-0
05:14:46.534 RemoveAllJobsEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
05:14:46.534 CompileAllEvent (org.nlogo.app.MainCodeTab) AWT-EventQueue-0
05:14:46.534 LoadSectionEvent (org.nlogo.window.ModelLoader$Loader (java.lang.Object)) AWT-EventQueue-0
05:14:46.534 LoadSectionEvent (org.nlogo.window.ModelLoader$Loader (java.lang.Object)) AWT-EventQueue-0
05:14:46.533 LoadBeginEvent (org.nlogo.window.ModelLoader$Loader (java.lang.Object)) AWT-EventQueue-0
```

**Comment by qiemem** [comment]
Note that you do correctly the get the version number warning.

**Comment by qiemem** [comment]
Ah, this only happens when the input is blank. My guess is the reader is reading to a blank line, storing that in an array, and then the array is short a few elements.

Previously, empty inputs would be stored as `NIL`.

**Comment by mrerrormessage** [comment]
Fixed in https://github.com/NetLogo/NetLogo/commit/912667be391299963a77a5ff80d7ac17772361f5
