### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by juni3227** [NetLogo/NetLogo#1066]
java.lang.reflect.InvocationTargetException
 at java.awt.EventQueue.invokeAndWait(EventQueue.java:1321)
 at java.awt.EventQueue.invokeAndWait(EventQueue.java:1296)
 at org.nlogo.awt.EventQueue$.invokeAndWait(EventQueue.scala:19)
 at org.nlogo.swing.ModalProgressTask$Boss.run(ModalProgressTask.scala:61)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
 at java.lang.Double.valueOf(Double.java:519)
 at org.nlogo.agent.Patch.<init>(Patch.java:82)
 at org.nlogo.agent.World.createPatches(World.java:735)
 at org.nlogo.window.WorldViewSettings2D$1.run(WorldViewSettings2D.java:76)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
 at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
 at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
 at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
 at java.awt.Dialog.show(Dialog.java:1084)
 at java.awt.Component.show(Component.java:1673)
 at java.awt.Component.setVisible(Component.java:1625)
 at java.awt.Window.setVisible(Window.java:1014)
 at java.awt.Dialog.setVisible(Dialog.java:1005)
 at org.nlogo.swing.ModalProgressTask$.apply(ModalProgressTask.scala:43)
 at org.nlogo.swing.ModalProgressTask.apply(ModalProgressTask.scala)
 at org.nlogo.window.WorldViewSettings2D.resizeWithProgress(WorldViewSettings2D.java:109)
 at org.nlogo.window.WorldViewSettings2D.editFinished(WorldViewSettings2D.java:34)
 at org.nlogo.properties.EditDialog$$anonfun$1.apply$mcV$sp(EditDialog.scala:51)
 at org.nlogo.swing.Implicits$$anon$5.actionPerformed(Implicits.scala:15)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)

NetLogo 5.3.1
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_74 (Oracle Corporation; 1.8.0_74-b02)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: practice

02:48:49.679 AddJobEvent (org.nlogo.window.MonitorWidget) AWT-EventQueue-0
02:48:49.679 AddJobEvent (org.nlogo.window.MonitorWidget) AWT-EventQueue-0
02:48:49.679 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
02:48:49.679 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:48:49.679 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
02:48:49.679 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
02:46:38.923 RemoveAllJobsEvent (org.nlogo.window.ViewWidget) AWT-EventQueue-0
02:46:38.884 DirtyEvent (org.nlogo.app.InterfacePanel) AWT-EventQueue-0
02:46:38.883 WidgetEditedEvent (org.nlogo.window.ViewWidget) AWT-EventQueue-0
02:46:38.817 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0

     This happens when I increase world size more than 1000 time 1000

also 

error (ArrayIndexOutOfBoundsException)
 while observer running CREATE-TURTLES
  called by procedure SETUP-TURTLES
  called by procedure SETUP
  called by Button 'setup'

NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.lang.ArrayIndexOutOfBoundsException: 2002000
 at org.nlogo.agent.World.getPatchAtWrap(World.java:548)
 at org.nlogo.agent.Turtle.getPatchHere(Turtle.java:248)
 at org.nlogo.agent.Turtle.<init>(Turtle.java:90)
 at org.nlogo.agent.Turtle.<init>(Turtle.java:72)
 at org.nlogo.agent.World.createTurtle(World.java:384)
 at org.nlogo.prim._createturtles.perform(_createturtles.java:51)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:91)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.java:82)
 at org.nlogo.job.JobThread.org$nlogo$job$JobThread$$runPrimaryJobs(JobThread.scala:143)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply$mcV$sp(JobThread.scala:78)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at scala.util.control.Exception$Catch.apply(Exception.scala:88)
 at org.nlogo.util.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:75)

NetLogo 5.3.1
main: org.nlogo.app.AppFrame
thread: JobThread
Java HotSpot(TM) 64-Bit Server VM 1.8.0_74 (Oracle Corporation; 1.8.0_74-b02)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: practice

02:51:11.385 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
02:51:11.384 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
02:51:11.381 RuntimeErrorEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:51:11.320 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
02:51:11.320 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:51:11.313 TickStateChangeEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
02:51:11.310 OutputEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:51:11.305 AddJobEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
02:51:11.218 InputBoxLoseFocusEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
02:51:11.203 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0

Also, this happens when i setup code in that 1000 times 1000 world

if you need my code to reproduce bug, email me.

**Comment by SethTisue** [comment]
http://ccl.northwestern.edu/netlogo/docs/faq.html#howbig

**Comment by SethTisue** [comment]
also relevant: #25
