### ISSUE TITLE
behavior space error

### ISSUE THREAD

**Issue by kaliz001** [NetLogo/NetLogo#1087]
NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.security.PrivilegedActionException: java.security.PrivilegedActionException: Expected a number here, rather than a list or block. at position 38 in 
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:687)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.security.PrivilegedActionException: Expected a number here, rather than a list or block. at position 38 in 
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:690)
 at java.awt.EventQueue$3.run(EventQueue.java:688)
 ... 9 more
Caused by: Expected a number here, rather than a list or block. at position 38 in 
 at org.nlogo.compiler.CompilerExceptionThrowers$.exception(CompilerExceptionThrowers.scala:28)
 at org.nlogo.compiler.ExpressionParser.parseDelayedBlock(ExpressionParser.scala:572)
 at org.nlogo.compiler.ExpressionParser.resolveType(ExpressionParser.scala:246)
 at org.nlogo.compiler.ExpressionParser.resolveTypes(ExpressionParser.scala:215)
 at org.nlogo.compiler.ExpressionParser.parseArguments(ExpressionParser.scala:113)
 at org.nlogo.compiler.ExpressionParser.parseStatement(ExpressionParser.scala:80)
 at org.nlogo.compiler.ExpressionParser.parse(ExpressionParser.scala:55)
 at org.nlogo.compiler.CompilerMain$$anonfun$compile$1.apply(CompilerMain.scala:34)
 at org.nlogo.compiler.CompilerMain$$anonfun$compile$1.apply(CompilerMain.scala:29)
 at scala.collection.Iterator$class.foreach(Iterator.scala:772)
 at scala.collection.JavaConversions$JIteratorWrapper.foreach(JavaConversions.scala:573)
 at scala.collection.IterableLike$class.foreach(IterableLike.scala:73)
 at scala.collection.JavaConversions$JCollectionWrapper.foreach(JavaConversions.scala:592)
 at org.nlogo.compiler.CompilerMain$.compile(CompilerMain.scala:29)
 at org.nlogo.compiler.Compiler$.compileMoreCode(Compiler.scala:34)
 at org.nlogo.workspace.Evaluator.org$nlogo$workspace$Evaluator$$invokeCompiler(Evaluator.scala:175)
 at org.nlogo.workspace.Evaluator$MyLogoThunk.<init>(Evaluator.scala:136)
 at org.nlogo.workspace.Evaluator$$anon$2.<init>(Evaluator.scala:127)
 at org.nlogo.workspace.Evaluator.makeCommandThunk(Evaluator.scala:127)
 at org.nlogo.workspace.AbstractWorkspaceTraits$Evaluating$class.makeCommandThunk(AbstractWorkspaceScala.scala:159)
 at org.nlogo.workspace.AbstractWorkspaceScala.makeCommandThunk(AbstractWorkspaceScala.scala:19)
 at org.nlogo.plot.PlotManager.compile$1(PlotManager.scala:81)
 at org.nlogo.plot.PlotManager$$anonfun$2.apply(PlotManager.scala:97)
 at org.nlogo.plot.PlotManager$$anonfun$2.apply(PlotManager.scala:95)
 at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:697)
 at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
 at scala.collection.immutable.List.foreach(List.scala:76)
 at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:696)
 at org.nlogo.plot.PlotManager.compilePlot(PlotManager.scala:95)
 at org.nlogo.plot.PlotManager$$anonfun$compileAllPlots$1.apply(PlotManager.scala:76)
 at org.nlogo.plot.PlotManager$$anonfun$compileAllPlots$1.apply(PlotManager.scala:76)
 at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:239)
 at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:239)
 at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
 at scala.collection.immutable.List.foreach(List.scala:76)
 at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:239)
 at scala.collection.immutable.List.flatMap(List.scala:76)
 at org.nlogo.plot.PlotManager.compileAllPlots(PlotManager.scala:76)
 at org.nlogo.headless.HeadlessModelOpener.finish(HeadlessModelOpener.scala:91)
 at org.nlogo.headless.HeadlessModelOpener.openFromMap(HeadlessModelOpener.scala:75)
 at org.nlogo.headless.HeadlessWorkspace.openString(HeadlessWorkspace.scala:525)
 at org.nlogo.app.App$$anon$6.newInstance(App.scala:140)
 at org.nlogo.lab.gui.Supervisor$$anonfun$start$1.apply$mcVI$sp(Supervisor.scala:90)
 at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:78)
 at org.nlogo.lab.gui.Supervisor.start(Supervisor.scala:89)
 at org.nlogo.lab.gui.ManagerDialog.org$nlogo$lab$gui$ManagerDialog$$run(ManagerDialog.scala:90)
 at org.nlogo.lab.gui.ManagerDialog$$anonfun$6.apply$mcV$sp(ManagerDialog.scala:27)
 at org.nlogo.lab.gui.ManagerDialog$$anon$1.actionPerformed(ManagerDialog.scala:21)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2028)
 at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2351)
 at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:387)
 at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:242)
 at ch.randelshofer.quaqua.QuaquaButtonListener.mouseReleased(QuaquaButtonListener.java:110)
 at java.awt.Component.processMouseEvent(Component.java:6414)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3275)
 at java.awt.Component.processEvent(Component.java:6179)
 at java.awt.Container.processEvent(Container.java:2084)
 at java.awt.Component.dispatchEventImpl(Component.java:4776)
 at java.awt.Container.dispatchEventImpl(Container.java:2142)
 at java.awt.Component.dispatchEvent(Component.java:4604)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4618)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4279)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4209)
 at java.awt.Container.dispatchEventImpl(Container.java:2128)
 at java.awt.Window.dispatchEventImpl(Window.java:2492)
 at java.awt.Component.dispatchEvent(Component.java:4604)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:717)
 at java.awt.EventQueue.access$400(EventQueue.java:82)
 at java.awt.EventQueue$2.run(EventQueue.java:676)
 at java.awt.EventQueue$2.run(EventQueue.java:674)
 ... 14 more

NetLogo 5.0.4
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.6.0_65 (Apple Inc.; 1.6.0_65-b14-466.1-11M4716)
operating system: Mac OS X 10.10.5 (x86_64 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: dissertation_al_nlogo 22062016

10:39:13.986 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
10:39:13.986 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
10:39:13.986 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
10:39:13.986 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
10:39:13.986 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
10:39:13.986 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
10:39:13.986 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
10:39:13.986 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
10:39:13.986 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
10:39:13.986 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0

**Comment by mrerrormessage** [comment]
This error is thrown when one of your plots contains invalid code. Check through your plots and make sure none of them are red (indicating code that failed to compile). By the way, this exception will be fixed in the next major release of NetLogo.

Related: https://github.com/NetLogo/NetLogo/issues/660

**Comment by kaliz001** [comment]
thanks yes that was the problem

**Comment by mrerrormessage** [comment]
I'm going to reopen this just to track that we shouldn't display an error while the behaviorspace run is ongoing that isn't clear about the problem. We should either not display an error or (better) display a useful error and allow the experiment to continue.

**Comment by ERSUCC** [comment]
In NetLogo 7, it no longer displays an error during a BehaviorSpace experiment if that experiment references a plot with compilation errors. Not sure if that's better or worse, although it's pretty tough to get to that state, since the plot name goes red before you open the BehaviorSpace window.
