### ISSUE TITLE
NETLOGO Extension external jars import issue

### ISSUE THREAD

**Issue by smas1** [NetLogo/NetLogo#1112]
I am trying to call a function from Custom Netlogo Extension which i developed in Java.
function is being called when i dont import any external jar but when i have to use external jar this gives me the error.

Please note that i am importing jars in DefaultClassManager's methods additionalJars(). Also i am packing these jars in extension jar file.

NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.lang.NoClassDefFoundError: org/apache/mahout/cf/taste/common/TasteException
 at MahoutRecommenderExtension.load(MahoutRecommenderExtension.java:22)
 at org.nlogo.workspace.ExtensionManager.importExtension(ExtensionManager.java:214)
 at org.nlogo.compiler.StructureParser.parseImport(StructureParser.scala:459)
 at org.nlogo.compiler.StructureParser.parse(StructureParser.scala:196)
 at org.nlogo.compiler.CompilerMain$.compile(CompilerMain.scala:25)
 at org.nlogo.compiler.Compiler$.compileProgram(Compiler.scala:28)
 at org.nlogo.window.CompilerManager.compileProcedures(CompilerManager.java:107)
 at org.nlogo.window.CompilerManager.compileAll(CompilerManager.java:87)
 at org.nlogo.window.CompilerManager.handle(CompilerManager.java:309)
 at org.nlogo.window.Events$CompileAllEvent.beHandledBy(Events.java:175)
 at org.nlogo.window.Event.doRaise(Event.java:198)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.app.ProceduresTab$CompileAction.actionPerformed(ProceduresTab.scala:60)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
 at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
 at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
 at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
 at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
 at java.awt.Component.processMouseEvent(Component.java:6535)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
 at java.awt.Component.processEvent(Component.java:6300)
 at java.awt.Container.processEvent(Container.java:2236)
 at java.awt.Component.dispatchEventImpl(Component.java:4891)
 at java.awt.Container.dispatchEventImpl(Container.java:2294)
 at java.awt.Component.dispatchEvent(Component.java:4713)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
 at java.awt.Container.dispatchEventImpl(Container.java:2280)
 at java.awt.Window.dispatchEventImpl(Window.java:2750)
 at java.awt.Component.dispatchEvent(Component.java:4713)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.awt.EventQueue$4.run(EventQueue.java:729)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: org.apache.mahout.cf.taste.common.TasteException
 at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
 at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
 ... 49 more

NetLogo 5.3.1
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_74 (Oracle Corporation; 1.8.0_74-b02)
operating system: Windows 7 6.1 (amd64 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: roadDemo

08:41:38.239 RemoveAllJobsEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
08:41:38.239 CompileAllEvent (org.nlogo.app.MainProceduresTab) AWT-EventQueue-0
08:41:38.186 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
08:41:38.186 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
08:41:38.186 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
08:41:38.186 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
08:41:38.186 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
08:41:37.986 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
08:41:37.986 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
08:41:37.986 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0

**Comment by mrerrormessage** [comment]
Thanks for posting, but I believe this bug is in the extension code and not in NetLogo. It's also hard to tell what the exact problem might be without knowing anything about the extension. Here are some ideas to help debug extension loading:

* Extensions are loaded in their own class loader, so you *will* run into problems if you're obtaining a class loader by doing something like `org.nlogo.api.ExtensionManager.class.getClassLoader()`.
* Any additional loading of resources should be done in the `runOnce` method (for loading that only needs to be done once) or in the `startFullCompilation` method (for loading that needs to be done on each compile) of the `ExtensionManager`.
* `additionalJars` was used by applets, but those are no longer supported, consider this method deprecated. 
* NetLogo will load any jars located in the same directory as the jar the extension is in (for instance, if your extension is named `foo`, and the jar is at `foo/foo.jar`, NetLogo will look for `foo/*.jar`).  

I'm closing this issue for now, but if more information is provided and we see that this is a bug, I will gladly reopen it.
