### ISSUE TITLE
Error in ITEM but user code visible

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/NetLogo#1135]
The error message should provide more information. Given the following it is unclear where the problem is.

ITEM expected input to be a string or list but got the number 0 instead.

org.nlogo.nvm.ArgumentTypeException: ITEM expected input to be a string or list but got the number 0 instead.
 at org.nlogo.nvm.CommandTask.perform(Task.scala:87)
 at org.nlogo.prim.etc._foreach.perform(_foreach.scala:36)
 at org.nlogo.nvm.Context.callReporterProcedure(Context.java:243)
 at org.nlogo.prim._asm_procedurego_if_0.perform(:2)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:91)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.java:82)
 at org.nlogo.job.JobThread.org$nlogo$job$JobThread$$runPrimaryJobs(JobThread.scala:143)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply$mcV$sp(JobThread.scala:78)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at scala.util.control.Exception$Catch.apply(Exception.scala:88)
 at org.nlogo.util.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:75)

NetLogo 3D 5.3.1
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_74 (Oracle Corporation; 1.8.0_74-b02)
operating system: Windows 7 6.1 (amd64 processor)
Scala version 2.9.2
JOGL: 2.3.2
OpenGL graphics: Intel(R) HD Graphics 4400
OpenGL version: 4.0.0 - Build 9.18.10.3220
OpenGL vendor: Intel
model: cancer

07:35:15.051 OutputEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
07:35:15.004 TickStateChangeEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
07:35:14.988 TickStateChangeEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
07:35:14.974 OutputEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
07:35:14.908 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
07:35:14.908 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
07:35:14.908 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
07:35:14.908 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
07:35:14.908 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
07:35:14.908 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0

**Comment by mrerrormessage** [comment]
This will involve modifying `ArgumentTypeException` to include the index of the argument which is incorrectly passed. `ArgumentTypeException` is already passed the data, the fix will just need to alter the error text and then go through all the language tests and update them to reflect the index of the improper argument. This has the label "quickfix" because the fix is known, but this will actually take quite a bit of time as there are hundreds of language tests, many of which will have to be changed for this.
