### ISSUE TITLE
Exceptions raised while running experiments headless can cause huge log files

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/NetLogo#1153]
We had a simple error caused by read-from-string and it caused a 5GB log file. I tried to reproduce it and saw that after reporting errors for the first 4 runs new errors were reported for those runs over and over again.  Shouldn't the run terminate if when it first encounters an exception?

(The 5GB log file exceeded our quota on a virtual server and cause our service to have errors writing additional files until we discovered the problem.)

Here's a small sample:

c:\Program Files\NetLogo 5.3.1\app>java -Xmx32g -Dfile.encoding=UTF-8 -classpath NetLogo.jar org.nlogo.headless.Main --model "C:\Users\Ken\Documents\Cancer ABM\cancer.nlogo" --setup-file "C:\Users\Ken\Documents\Cancer ABM\run_experiment.xml"
java -Xmx32g -Dfile.encoding=UTF-8 -classpath NetLogo.jar org.nlogo.headless.Main --model "C:\Users\Ken\Documents\Cancer ABM\cancer.nlogo" --setup-file "C:\Users\Ken\Documents\Cancer ABM\run_experiment.xml"
Run #1, RUNTIME ERROR: Illegal number format
error while object 2 running READ-FROM-STRING
  called by (command task from: procedure -INITIAL-GROUP-IDS-27)
  called by procedure -INITIAL-GROUP-IDS-27
  called by procedure THE-MODEL
  called by procedure START
  called by procedure SETUP-EXCEPT
  called by procedure SETUP
  called by procedure __EVALUATOR
org.nlogo.nvm.EngineException: Illegal number format
	at org.nlogo.nvm.CommandTask.perform(Task.scala:87)
	at org.nlogo.prim.etc._foreach.perform(_foreach.scala:36)
	at org.nlogo.nvm.Context.runExclusive(Context.java:119)
	at org.nlogo.nvm.ExclusiveJob.run(ExclusiveJob.java:57)
	at org.nlogo.nvm.Context.runExclusiveJob(Context.java:162)
	at org.nlogo.prim._asm_procedurethemodel_ask_61.perform(:1)
	at org.nlogo.nvm.Context.stepConcurrent(Context.java:91)
	at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.java:82)
	at org.nlogo.job.JobThread.org$nlogo$job$JobThread$$runPrimaryJobs(JobThread.scala:143)
	at org.nlogo.job.JobThread$$anonfun$run$1.apply$mcV$sp(JobThread.scala:78)
	at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
	at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
	at scala.util.control.Exception$Catch.apply(Exception.scala:88)
	at org.nlogo.util.Exceptions$.handling(Exceptions.scala:41)
	at org.nlogo.job.JobThread.run(JobThread.scala:75)
Run #2, RUNTIME ERROR: Illegal number format
error while object 2 running READ-FROM-STRING
  called by (command task from: procedure -INITIAL-GROUP-IDS-27)
  called by procedure -INITIAL-GROUP-IDS-27
  called by procedure THE-MODEL
  called by procedure START
  called by procedure SETUP-EXCEPT
  called by procedure SETUP
  called by procedure __EVALUATOR
org.nlogo.nvm.EngineException: Illegal number format
	at org.nlogo.nvm.CommandTask.perform(Task.scala:87)
	at org.nlogo.prim.etc._foreach.perform(_foreach.scala:36)
	at org.nlogo.nvm.Context.runExclusive(Context.java:119)
	at org.nlogo.nvm.ExclusiveJob.run(ExclusiveJob.java:57)
	at org.nlogo.nvm.Context.runExclusiveJob(Context.java:162)
	at org.nlogo.prim._asm_procedurethemodel_ask_61.perform(:1)
	at org.nlogo.nvm.Context.stepConcurrent(Context.java:91)
	at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.java:82)
	at org.nlogo.job.JobThread.org$nlogo$job$JobThread$$runPrimaryJobs(JobThread.scala:143)
	at org.nlogo.job.JobThread$$anonfun$run$1.apply$mcV$sp(JobThread.scala:78)
	at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
	at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
	at scala.util.control.Exception$Catch.apply(Exception.scala:88)
	at org.nlogo.util.Exceptions$.handling(Exceptions.scala:41)
	at org.nlogo.job.JobThread.run(JobThread.scala:75)
Run #4, RUNTIME ERROR: Illegal number format
error while object 2 running READ-FROM-STRING
  called by (command task from: procedure -INITIAL-GROUP-IDS-27)
  called by procedure -INITIAL-GROUP-IDS-27
  called by procedure THE-MODEL
  called by procedure START
  called by procedure SETUP-EXCEPT
  called by procedure SETUP
  called by procedure __EVALUATOR
org.nlogo.nvm.EngineException: Illegal number format
	at org.nlogo.nvm.CommandTask.perform(Task.scala:87)
	at org.nlogo.prim.etc._foreach.perform(_foreach.scala:36)
	at org.nlogo.nvm.Context.runExclusive(Context.java:119)
	at org.nlogo.nvm.ExclusiveJob.run(ExclusiveJob.java:57)
	at org.nlogo.nvm.Context.runExclusiveJob(Context.java:162)
	at org.nlogo.prim._asm_procedurethemodel_ask_61.perform(:1)
	at org.nlogo.nvm.Context.stepConcurrent(Context.java:91)
	at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.java:82)
	at org.nlogo.job.JobThread.org$nlogo$job$JobThread$$runPrimaryJobs(JobThread.scala:143)
	at org.nlogo.job.JobThread$$anonfun$run$1.apply$mcV$sp(JobThread.scala:78)
	at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
	at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
	at scala.util.control.Exception$Catch.apply(Exception.scala:88)
	at org.nlogo.util.Exceptions$.handling(Exceptions.scala:41)
	at org.nlogo.job.JobThread.run(JobThread.scala:75)
Run #3, RUNTIME ERROR: Illegal number format
error while object 2 running READ-FROM-STRING
  called by (command task from: procedure -INITIAL-GROUP-IDS-27)
  called by procedure -INITIAL-GROUP-IDS-27
  called by procedure THE-MODEL
  called by procedure START
  called by procedure SETUP-EXCEPT
  called by procedure SETUP
  called by procedure __EVALUATOR
org.nlogo.nvm.EngineException: Illegal number format
	at org.nlogo.nvm.CommandTask.perform(Task.scala:87)
	at org.nlogo.prim.etc._foreach.perform(_foreach.scala:36)
	at org.nlogo.nvm.Context.runExclusive(Context.java:119)
	at org.nlogo.nvm.ExclusiveJob.run(ExclusiveJob.java:57)
	at org.nlogo.nvm.Context.runExclusiveJob(Context.java:162)
	at org.nlogo.prim._asm_procedurethemodel_ask_61.perform(:1)
	at org.nlogo.nvm.Context.stepConcurrent(Context.java:91)
	at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.java:82)
	at org.nlogo.job.JobThread.org$nlogo$job$JobThread$$runPrimaryJobs(JobThread.scala:143)
	at org.nlogo.job.JobThread$$anonfun$run$1.apply$mcV$sp(JobThread.scala:78)
	at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
	at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
	at scala.util.control.Exception$Catch.apply(Exception.scala:88)
	at org.nlogo.util.Exceptions$.handling(Exceptions.scala:41)
	at org.nlogo.job.JobThread.run(JobThread.scala:75)
Run #2, RUNTIME ERROR: ASK expected input to be an agent or agentset but got the number 0 instead.
error while object 22 running ASK
  called by (command task from: procedure GENE-ACTIVATION-STATISTICS)
  called by procedure GENE-ACTIVATION-STATISTICS
  called by (command task from: procedure -LOG-GENE-ACTIVATION-STATISTICS-6)
  called by procedure RUN-PROCEDURE
  called by procedure DO-EVERY-INTERNAL
  called by procedure DO-EVERY
  called by (command task from: procedure -LOG-GENE-ACTIVATION-STATISTICS-6)
  called by procedure RUN-PROCEDURE
  called by (command task from: procedure START-TICK)
  called by procedure START-TICK
  called by procedure GO-UNTIL
  called by procedure GO
  called by procedure __EVALUATOR
org.nlogo.nvm.ArgumentTypeException: ASK expected input to be an agent or agentset but got the number 0 instead.
	at org.nlogo.nvm.CommandTask.perform(Task.scala:87)
	at org.nlogo.prim.etc._foreach.perform(_foreach.scala:36)
	at org.nlogo.nvm.Context.runExclusive(Context.java:119)
	at org.nlogo.nvm.ExclusiveJob.run(ExclusiveJob.java:57)
	at org.nlogo.nvm.Context.runExclusiveJob(Context.java:162)
	at org.nlogo.prim._asm_proceduregountil_ask_27.perform(:1)
	at org.nlogo.nvm.Context.callReporterProcedure(Context.java:243)
	at org.nlogo.prim._asm_procedurego_if_0.perform(:2)
	at org.nlogo.nvm.Context.stepConcurrent(Context.java:91)
	at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.java:82)
	at org.nlogo.job.JobThread.org$nlogo$job$JobThread$$runPrimaryJobs(JobThread.scala:143)
	at org.nlogo.job.JobThread$$anonfun$run$1.apply$mcV$sp(JobThread.scala:78)
	at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
	at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
	at scala.util.control.Exception$Catch.apply(Exception.scala:88)
	at org.nlogo.util.Exceptions$.handling(Exceptions.scala:41)
	at org.nlogo.job.JobThread.run(JobThread.scala:75)
Run #1, RUNTIME ERROR: ASK expected input to be an agent or agentset but got the number 0 instead.
error while object 34 running ASK
  called by (command task from: procedure GENE-ACTIVATION-STATISTICS)
  called by procedure GENE-ACTIVATION-STATISTICS
  called by (command task from: procedure -LOG-GENE-ACTIVATION-STATISTICS-6)
  called by procedure RUN-PROCEDURE
  called by procedure DO-EVERY-INTERNAL
  called by procedure DO-EVERY
  called by (command task from: procedure -LOG-GENE-ACTIVATION-STATISTICS-6)
  called by procedure RUN-PROCEDURE
  called by (command task from: procedure START-TICK)
  called by procedure START-TICK
  called by procedure GO-UNTIL
  called by procedure GO
  called by procedure __EVALUATOR
org.nlogo.nvm.ArgumentTypeException: ASK expected input to be an agent or agentset but got the number 0 instead.
	at org.nlogo.nvm.CommandTask.perform(Task.scala:87)
	at org.nlogo.prim.etc._foreach.perform(_foreach.scala:36)
	at org.nlogo.nvm.Context.runExclusive(Context.java:119)
	at org.nlogo.nvm.ExclusiveJob.run(ExclusiveJob.java:57)
	at org.nlogo.nvm.Context.runExclusiveJob(Context.java:162)
	at org.nlogo.prim._asm_proceduregountil_ask_27.perform(:1)
	at org.nlogo.nvm.Context.callReporterProcedure(Context.java:243)
	at org.nlogo.prim._asm_procedurego_if_0.perform(:2)
	at org.nlogo.nvm.Context.stepConcurrent(Context.java:91)
	at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.java:82)
	at org.nlogo.job.JobThread.org$nlogo$job$JobThread$$runPrimaryJobs(JobThread.scala:143)
	at org.nlogo.job.JobThread$$anonfun$run$1.apply$mcV$sp(JobThread.scala:78)
	at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
	at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
	at scala.util.control.Exception$Catch.apply(Exception.scala:88)
	at org.nlogo.util.Exceptions$.handling(Exceptions.scala:41)
	at org.nlogo.job.JobThread.run(JobThread.scala:75)
Run #3, RUNTIME ERROR: ASK expected input to be an agent or agentset but got the number 0 instead.
error while object 38 running ASK
  called by (command task from: procedure GENE-ACTIVATION-STATISTICS)
  called by procedure GENE-ACTIVATION-STATISTICS
  called by (command task from: procedure -LOG-GENE-ACTIVATION-STATISTICS-6)
  called by procedure RUN-PROCEDURE
  called by procedure DO-EVERY-INTERNAL
  called by procedure DO-EVERY
  called by (command task from: procedure -LOG-GENE-ACTIVATION-STATISTICS-6)
  called by procedure RUN-PROCEDURE
  called by (command task from: procedure START-TICK)
  called by procedure START-TICK
  called by procedure GO-UNTIL
  called by procedure GO
  called by procedure __EVALUATOR

**Comment by mrerrormessage** [comment]
Thanks for reporting. Would a "fail on error" flag be an acceptable solution? If the flag was present, experiments would stop after the first reported failure. If the flag was absent, runs would continue as normal?

**Comment by ToonTalk** [comment]
The flag would work well for me.
