### ISSUE TITLE
SDM: when saving model, IllegalArgumentException in org.nlogo.sdm.gui.Wrapper.wrap

### ISSUE THREAD

**Issue by Valenq** [NetLogo/NetLogo#1186]
NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.lang.reflect.InvocationTargetException
 at java.awt.EventQueue.invokeAndWait(EventQueue.java:1086)
 at java.awt.EventQueue.invokeAndWait(EventQueue.java:1063)
 at org.nlogo.awt.EventQueue$.invokeAndWait(EventQueue.scala:19)
 at org.nlogo.swing.ModalProgressTask$Boss.run(ModalProgressTask.scala:61)
Caused by: java.lang.IllegalArgumentException
 at org.nlogo.sdm.gui.Wrapper.wrap(Wrapper.java:37)
 at org.nlogo.sdm.gui.WrappedRate.write(WrappedRate.java:25)
 at org.jhotdraw.util.StorableOutput.writeStorable(Unknown Source)
 at org.nlogo.sdm.gui.RateConnection.write(RateConnection.java:236)
 at org.jhotdraw.util.StorableOutput.writeStorable(Unknown Source)
 at org.jhotdraw.standard.CompositeFigure.write(Unknown Source)
 at org.jhotdraw.util.StorableOutput.writeStorable(Unknown Source)
 at org.nlogo.sdm.gui.GUIAggregateManager.save(GUIAggregateManager.scala:41)
 at org.nlogo.app.ModelSaver$$anonfun$save$7.apply$mcV$sp(ModelSaver.scala:62)
 at org.nlogo.app.ModelSaver.section$1(ModelSaver.scala:15)
 at org.nlogo.app.ModelSaver.save(ModelSaver.scala:60)
 at org.nlogo.app.FileMenu$Saver.run(FileMenu.java:862)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:199)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:672)
 at java.awt.EventQueue.access$400(EventQueue.java:81)
 at java.awt.EventQueue$2.run(EventQueue.java:633)
 at java.awt.EventQueue$2.run(EventQueue.java:631)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:642)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:178)
 at java.awt.Dialog$1.run(Dialog.java:1052)
 at java.awt.Dialog$3.run(Dialog.java:1104)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.awt.Dialog.show(Dialog.java:1102)
 at java.awt.Component.show(Component.java:1591)
 at java.awt.Component.setVisible(Component.java:1543)
 at java.awt.Window.setVisible(Window.java:843)
 at java.awt.Dialog.setVisible(Dialog.java:987)
 at org.nlogo.swing.ModalProgressTask$.apply(ModalProgressTask.scala:43)
 at org.nlogo.swing.ModalProgressTask.apply(ModalProgressTask.scala)
 at org.nlogo.app.FileMenu.doSave(FileMenu.java:880)
 at org.nlogo.app.FileMenu.saveAs(FileMenu.java:837)
 at org.nlogo.app.FileMenu.save(FileMenu.java:829)
 at org.nlogo.app.FileMenu.access$300(FileMenu.java:23)
 at org.nlogo.app.FileMenu$SaveAction.action(FileMenu.java:195)
 at org.nlogo.app.FileMenu$FileMenuAction.actionPerformed(FileMenu.java:95)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1995)
 at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2318)
 at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:387)
 at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:242)
 at javax.swing.AbstractButton.doClick(AbstractButton.java:357)
 at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:809)
 at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:850)
 at java.awt.Component.processMouseEvent(Component.java:6297)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3275)
 at java.awt.Component.processEvent(Component.java:6062)
 at java.awt.Container.processEvent(Container.java:2039)
 at java.awt.Component.dispatchEventImpl(Component.java:4660)
 at java.awt.Container.dispatchEventImpl(Container.java:2097)
 at java.awt.Component.dispatchEvent(Component.java:4488)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4575)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4236)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4166)
 at java.awt.Container.dispatchEventImpl(Container.java:2083)
 at java.awt.Window.dispatchEventImpl(Window.java:2489)
 at java.awt.Component.dispatchEvent(Component.java:4488)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:674)
 at java.awt.EventQueue.access$400(EventQueue.java:81)
 at java.awt.EventQueue$2.run(EventQueue.java:633)
 at java.awt.EventQueue$2.run(EventQueue.java:631)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:98)
 at java.awt.EventQueue$3.run(EventQueue.java:647)
 at java.awt.EventQueue$3.run(EventQueue.java:645)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:644)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

NetLogo 5.2.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) Server VM 1.6.0_45 (Sun Microsystems Inc.; 1.6.0_45-b06)
operating system: Windows 8 6.2 (x86 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Untitled

10:03:26.278 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:03:26.077 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:03:25.877 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:03:25.677 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:03:25.477 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:03:25.277 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:03:25.077 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:03:24.877 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:03:24.676 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:03:24.476 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.lang.reflect.InvocationTargetException
 at java.awt.EventQueue.invokeAndWait(EventQueue.java:1086)
 at java.awt.EventQueue.invokeAndWait(EventQueue.java:1063)
 at org.nlogo.awt.EventQueue$.invokeAndWait(EventQueue.scala:19)
 at org.nlogo.swing.ModalProgressTask$Boss.run(ModalProgressTask.scala:61)
Caused by: java.lang.IllegalArgumentException
 at org.nlogo.sdm.gui.Wrapper.wrap(Wrapper.java:37)
 at org.nlogo.sdm.gui.WrappedRate.write(WrappedRate.java:25)
 at org.jhotdraw.util.StorableOutput.writeStorable(Unknown Source)
 at org.nlogo.sdm.gui.RateConnection.write(RateConnection.java:236)
 at org.jhotdraw.util.StorableOutput.writeStorable(Unknown Source)
 at org.jhotdraw.standard.CompositeFigure.write(Unknown Source)
 at org.jhotdraw.util.StorableOutput.writeStorable(Unknown Source)
 at org.nlogo.sdm.gui.GUIAggregateManager.save(GUIAggregateManager.scala:41)
 at org.nlogo.app.ModelSaver$$anonfun$save$7.apply$mcV$sp(ModelSaver.scala:62)
 at org.nlogo.app.ModelSaver.section$1(ModelSaver.scala:15)
 at org.nlogo.app.ModelSaver.save(ModelSaver.scala:60)
 at org.nlogo.app.FileMenu$Saver.run(FileMenu.java:862)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:199)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:672)
 at java.awt.EventQueue.access$400(EventQueue.java:81)
 at java.awt.EventQueue$2.run(EventQueue.java:633)
 at java.awt.EventQueue$2.run(EventQueue.java:631)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:642)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:178)
 at java.awt.Dialog$1.run(Dialog.java:1052)
 at java.awt.Dialog$3.run(Dialog.java:1104)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.awt.Dialog.show(Dialog.java:1102)
 at java.awt.Component.show(Component.java:1591)
 at java.awt.Component.setVisible(Component.java:1543)
 at java.awt.Window.setVisible(Window.java:843)
 at java.awt.Dialog.setVisible(Dialog.java:987)
 at org.nlogo.swing.ModalProgressTask$.apply(ModalProgressTask.scala:43)
 at org.nlogo.swing.ModalProgressTask.apply(ModalProgressTask.scala)
 at org.nlogo.app.FileMenu.doSave(FileMenu.java:880)
 at org.nlogo.app.FileMenu.saveAs(FileMenu.java:837)
 at org.nlogo.app.FileMenu.save(FileMenu.java:829)
 at org.nlogo.app.FileMenu.access$300(FileMenu.java:23)
 at org.nlogo.app.FileMenu$SaveAction.action(FileMenu.java:195)
 at org.nlogo.app.FileMenu$FileMenuAction.actionPerformed(FileMenu.java:95)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1995)
 at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2318)
 at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:387)
 at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:242)
 at javax.swing.AbstractButton.doClick(AbstractButton.java:357)
 at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:809)
 at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:850)
 at java.awt.Component.processMouseEvent(Component.java:6297)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3275)
 at java.awt.Component.processEvent(Component.java:6062)
 at java.awt.Container.processEvent(Container.java:2039)
 at java.awt.Component.dispatchEventImpl(Component.java:4660)
 at java.awt.Container.dispatchEventImpl(Container.java:2097)
 at java.awt.Component.dispatchEvent(Component.java:4488)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4575)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4236)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4166)
 at java.awt.Container.dispatchEventImpl(Container.java:2083)
 at java.awt.Window.dispatchEventImpl(Window.java:2489)
 at java.awt.Component.dispatchEvent(Component.java:4488)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:674)
 at java.awt.EventQueue.access$400(EventQueue.java:81)
 at java.awt.EventQueue$2.run(EventQueue.java:633)
 at java.awt.EventQueue$2.run(EventQueue.java:631)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:98)
 at java.awt.EventQueue$3.run(EventQueue.java:647)
 at java.awt.EventQueue$3.run(EventQueue.java:645)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:644)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

NetLogo 5.2.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) Server VM 1.6.0_45 (Sun Microsystems Inc.; 1.6.0_45-b06)
operating system: Windows 8 6.2 (x86 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Untitled

10:03:26.278 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:03:26.077 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:03:25.877 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:03:25.677 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:03:25.477 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:03:25.277 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:03:25.077 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:03:24.877 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:03:24.676 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:03:24.476 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

**Comment by SethTisue** [comment]
is the problem reproducible in NetLogo 5.3.1?

**Comment by ERSUCC** [comment]
This issue should probably be closed, because it was caused by the old SDM saving code, which is no longer supported as of NetLogo 7. Leaving it open for now just in case it somehow applies to the new SDM saving code.

**Comment by SethTisue** [comment]
I would suggest simply closing the issue in the absence of definite information that any bug exists. If a bug is found in the new saving code, it would be a new bug, and someone could open a new ticket at the time that bug is discovered.

Literally anything in NetLogo _might_ have a bug in it.
