### ISSUE TITLE
Headless does not load extensions

### ISSUE THREAD

**Issue by non87** [NetLogo/NetLogo#1232]
I am trying to run a BehaviorSpace experiment from command line, but Netlogo is not loading extensions. 

Specifically:

I use the fire.nlogo model, add a random experiment called "experiment1"  in the GUI and copy-paste from online manual:

java -Xmx1024m -Dfile.encoding=UTF-8 -cp ~/Desktop/netlogo-5.3.1-64/app/NetLogo.jar\
  org.nlogo.headless.Main \
  --model "~/Desktop/netlogo-6.0-M6-64/app/models/Sample Models/Earth Science/Fire.nlogo" Fire.nlogo" \
  --experiment experiment1 \
  --table -

As expected, this works. 

Then I add "extensions[csv]" as first line in the model (see attachment [Fire.txt](https://github.com/NetLogo/NetLogo/files/614926/Fire.txt)) and run exact same command. This is what I get:

Exception in thread "main" Can't find extension: csv at position 11 in 
	at org.nlogo.core.ErrorSource.signalError(ErrorSource.scala:11)
	at org.nlogo.workspace.ExtensionManager.importExtension(ExtensionManager.scala:171)
	at org.nlogo.parse.StructureParser$$anonfun$parsingWithExtensions$1.apply(StructureParser.scala:70)
	at org.nlogo.parse.StructureParser$$anonfun$parsingWithExtensions$1.apply(StructureParser.scala:69)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.nlogo.parse.StructureParser$.parsingWithExtensions(StructureParser.scala:69)
	at org.nlogo.parse.StructureParser$.parseSources(StructureParser.scala:35)
	at org.nlogo.parse.FrontEndMain$class.frontEnd(FrontEnd.scala:28)
	at org.nlogo.parse.FrontEnd.frontEnd(FrontEnd.scala:16)
	at org.nlogo.compiler.CompilerMain$.compile(CompilerMain.scala:28)
	at org.nlogo.compiler.Compiler.compileProgram(Compiler.scala:54)
	at org.nlogo.headless.HeadlessModelOpener.openFromModel(HeadlessModelOpener.scala:68)
	at org.nlogo.headless.HeadlessWorkspace.openModel(HeadlessWorkspace.scala:544)
	at org.nlogo.headless.HeadlessWorkspace.openFromSource(HeadlessWorkspace.scala:540)
	at org.nlogo.headless.HeadlessWorkspace.openString(HeadlessWorkspace.scala:526)
	at org.nlogo.headless.HeadlessWorkspace.open(HeadlessWorkspace.scala:508)
	at org.nlogo.headless.Main$.org$nlogo$headless$Main$$newWorkspace$1(Main.scala:19)
	at org.nlogo.headless.Main$$anonfun$runExperiment$1.apply(Main.scala:24)
	at org.nlogo.headless.Main$$anonfun$runExperiment$1.apply(Main.scala:24)
	at org.nlogo.lab.Lab$$anonfun$2.apply(Lab.scala:33)
	at org.nlogo.lab.Lab$$anonfun$2.apply(Lab.scala:33)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.Range.foreach(Range.scala:160)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.nlogo.lab.Lab.run(Lab.scala:33)
	at org.nlogo.headless.Main$.runExperiment(Main.scala:24)
	at org.nlogo.headless.Main$$anonfun$main$1.apply(Main.scala:14)
	at org.nlogo.headless.Main$$anonfun$main$1.apply(Main.scala:14)
	at scala.Option.foreach(Option.scala:257)
	at org.nlogo.headless.Main$.main(Main.scala:14)
	at org.nlogo.headless.Main.main(Main.scala)

If I repeat the procedure with Netlogo 5.3.1-64, I obtain a different error starting with "java.lang.IllegalStateException: Can't find extension: csv/csv.jar"

Noticeably, the experiment works if I start if from GUI.

I use 
Ubuntu 16.10 
java-1.8.0-openjdk-amd64

**Comment by TheBizzle** [comment]
The location that the executable is launched from matters to NetLogo.  Are you, by any chance, running it from a shortcut to the executable or something similar?  Or are you running it from directly within the NetLogo directory?

**Comment by non87** [comment]
Following your suggestion, I have tried to work this inside the folder containing netlogo.jar and it works. Thank you. 

Should I conclude that I **need** to run the command from within that folder in order to import extensions correctly?

**Comment by TheBizzle** [comment]
More or less.  If you really prefer to launch from another place, you *can* tell whatever script you're running to `cd` into the NetLogo directory before it launches NetLogo.

**Comment by non87** [comment]
Very clear, thank you for your help.
