### ISSUE TITLE
Extensions? 

### ISSUE THREAD

**Issue by Shintaro-Miyazaki** [NetLogo/NetLogo#1239]
While loading this model here:
https://www.openabm.org/model/4871/version/5/view

NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.lang.reflect.InvocationTargetException
 at java.awt.EventQueue.invokeAndWait(EventQueue.java:1319)
 at java.awt.EventQueue.invokeAndWait(EventQueue.java:1294)
 at org.nlogo.awt.EventQueue$.invokeAndWait(EventQueue.scala:19)
 at org.nlogo.swing.ModalProgressTask$Boss.run(ModalProgressTask.scala:61)
Caused by: java.lang.NoClassDefFoundError: org/nlogo/core/Primitive
 at java.lang.Class.getDeclaredConstructors0(Native Method)
 at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
 at java.lang.Class.getConstructor0(Class.java:3075)
 at java.lang.Class.newInstance(Class.java:412)
 at org.nlogo.workspace.ExtensionManager.getClassManager(ExtensionManager.java:410)
 at org.nlogo.workspace.ExtensionManager.importExtension(ExtensionManager.java:177)
 at org.nlogo.compiler.StructureParser.parseImport(StructureParser.scala:459)
 at org.nlogo.compiler.StructureParser.parse(StructureParser.scala:196)
 at org.nlogo.compiler.CompilerMain$.compile(CompilerMain.scala:25)
 at org.nlogo.compiler.Compiler$.compileProgram(Compiler.scala:28)
 at org.nlogo.window.CompilerManager.compileProcedures(CompilerManager.java:107)
 at org.nlogo.window.CompilerManager.compileAll(CompilerManager.java:87)
 at org.nlogo.window.CompilerManager.handle(CompilerManager.java:71)
 at org.nlogo.window.Events$LoadEndEvent.beHandledBy(Events.java:449)
 at org.nlogo.window.Event.doRaise(Event.java:198)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.window.ModelLoader$Loader$$anonfun$loadHelper$1.apply(ModelLoader.scala:101)
 at org.nlogo.window.ModelLoader$Loader$$anonfun$loadHelper$1.apply(ModelLoader.scala:101)
 at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
 at scala.collection.immutable.List.foreach(List.scala:76)
 at org.nlogo.window.ModelLoader$Loader.loadHelper(ModelLoader.scala:101)
 at org.nlogo.window.ModelLoader$.load(ModelLoader.scala:16)
 at org.nlogo.window.ModelLoader.load(ModelLoader.scala)
 at org.nlogo.app.FileMenu$1.run(FileMenu.java:859)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
 at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
 at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
 at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
 at java.awt.Dialog.show(Dialog.java:1084)
 at java.awt.Component.show(Component.java:1673)
 at java.awt.Component.setVisible(Component.java:1625)
 at java.awt.Window.setVisible(Window.java:1014)
 at java.awt.Dialog.setVisible(Dialog.java:1005)
 at org.nlogo.swing.ModalProgressTask$.apply(ModalProgressTask.scala:43)
 at org.nlogo.swing.ModalProgressTask.apply(ModalProgressTask.scala)
 at org.nlogo.app.FileMenu.openFromMap(FileMenu.java:869)
 at org.nlogo.app.FileMenu.openFromSource(FileMenu.java:841)
 at org.nlogo.app.FileMenu.openFromPath(FileMenu.java:795)
 at org.nlogo.app.App$$anonfun$open$1.apply$mcV$sp(App.scala:800)
 at org.nlogo.app.App$$anonfun$open$1.apply(App.scala:800)
 at org.nlogo.app.App$$anonfun$open$1.apply(App.scala:800)
 at org.nlogo.app.App.dispatchThreadOrBust(App.scala:1018)
 at org.nlogo.app.App.open(App.scala:800)
 at org.nlogo.app.MacHandler.doOpen(MacHandler.java:104)
 at org.nlogo.app.MacHandler.ready(MacHandler.java:93)
 at org.nlogo.app.App.org$nlogo$app$App$$finishStartup(App.scala:453)
 at org.nlogo.app.App$$anonfun$mainWithAppHandler$1.apply$mcV$sp(App.scala:141)
 at org.nlogo.swing.Implicits$$anon$17.run(Implicits.scala:12)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: org.nlogo.core.Primitive
 at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
 at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
 ... 74 more

NetLogo 5.3
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_66 (Oracle Corporation; 1.8.0_66-b17)
operating system: Mac OS X 10.10.5 (x86_64 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: DiDIY-22

02:13:54.592 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
02:13:54.592 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
02:13:54.592 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
02:13:54.592 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
02:13:54.591 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
02:13:54.591 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
02:13:54.591 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
02:13:54.591 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
02:13:54.591 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
02:13:54.590 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0

**Comment by mrerrormessage** [comment]
It appears you may be using an extension compiled for NetLogo 6 in NetLogo 5. I'm guessing that the extension in question is probably the `rnd` extension. Could you try replacing your existing RND installation with the one available [here](https://github.com/NetLogo/Rnd-Extension/releases/tag/v2.0.0) and let us know if that fixes the problem?

**Comment by Shintaro-Miyazaki** [comment]
Thanks! I tried, but now I am missing the extension: https://github.com/NetLogo/Reflection-Extension 
Which has only a .java file and when I am trying to compile then I get errors..

**Comment by mrerrormessage** [comment]
The reflection extension can be downloaded [here](https://github.com/NetLogo/Reflection-Extension/releases/tag/v0.1).

**Comment by Shintaro-Miyazaki** [comment]
Thanks a lot! This is really helpful. Now I get an internal syntax problem.. Probably none of your business anymore.. `      report join rnd:weighted-n-of 2 (sort things-here with [not tool?]) [scale (-1 * length str-of ?) 0]` leads to "RND: WEIGHTHED-N-OF expected this input to be an agentset, but got a list instead"...

**Comment by mrerrormessage** [comment]
It sounds like the model may have been written using an older version of the `rnd` extension. You might try changing `weighted-n-of` to `weighted-n-of-list`. Hope that helps! I'm going to go ahead and close this bug. Thanks again for reporting!
