### ISSUE TITLE
Webcam discovery timeout

### ISSUE THREAD

**Issue by stephenguerin** [NetLogo/NetLogo#1240]
Running "Model Library/Code Examples/ExtensionsExamples/Video Camera Example" on a Macbook Air mid-2012 Mac OS X 10.12.1 I'm seeing the following error when selecting a camera. Same example runs fine on a windows 10 box and a 2015 Macbook Pro. Also, Movie Playing Example and Movie Recording Example runs fine on the mid-2012 Macbook Air.

```
NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 

java.util.concurrent.TimeoutException: Webcams discovery timeout (500 ms) has been exceeded
 at com.github.sarxos.webcam.WebcamDiscoveryService.getWebcams(WebcamDiscoveryService.java:128)
 at com.github.sarxos.webcam.Webcam.getWebcams(Webcam.java:874)
 at org.nlogo.extensions.vid.Camera$.$anonfun$cameraNames$1(Camera.scala:40)
 at org.nlogo.extensions.vid.Camera$.withContextClassLoader(Camera.scala:33)
 at org.nlogo.extensions.vid.Camera$.cameraNames(Camera.scala:40)
 at org.nlogo.extensions.vid.CameraSelect.perform(CameraSelect.scala:10)
 at org.nlogo.prim._extern.perform(_extern.java:36)
 at org.nlogo.nvm.Context.runExclusive(Context.java:128)
 at org.nlogo.nvm.ExclusiveJob.run(ExclusiveJob.java:58)
 at org.nlogo.nvm.Context.runExclusiveJob(Context.java:175)
 at org.nlogo.prim._asm_buttonselectcamera_carefully_0.perform(:1)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:99)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.java:84)
 at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
 at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
 at scala.util.control.Exception$Catch.apply(Exception.scala:224)
 at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:66)

NetLogo 6.0-BETA2
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_112 (Oracle Corporation; 1.8.0_112-b16)
operating system: Mac OS X 10.12.1 (x86_64 processor)
Scala version 2.12.0
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Video Camera Example

07:44:52.189 AddJobEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
07:44:52.115 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
07:44:52.085 InputBoxLoseFocusEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
07:44:51.711 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
07:44:51.507 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
07:44:51.102 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
07:44:50.901 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
07:44:50.632 AfterLoadEvent (org.nlogo.window.ReconfigureWorkspaceUI$Loader (java.lang.Object)) AWT-EventQueue-0
07:44:50.628 AddJobEvent (org.nlogo.window.MonitorWidget) AWT-EventQueue-0
07:44:50.627 RemoveJobEvent (org.nlogo.window.MonitorWidget) AWT-EventQueue-0

```

**Comment by mrerrormessage** [comment]
Thanks for reporting this problem. 

First of all, this exception should definitely be caught and reported to the user.

Secondly, I could extend the timeout length, but a half-second is already quite a long time. Out of curiosity, are you able to use the camera on this computer in programs like Skype or Google Hangouts?

**Comment by stephenguerin** [comment]
This was resolved with this pull request: https://github.com/NetLogo/vid/commit/a653e57e309edf2786f502d2c56c4af514a4a9b5
