### ISSUE TITLE
NetLogo is unable to supply you with more details about this error

### ISSUE THREAD

**Issue by hwalbert** [NetLogo/NetLogo#1252]
NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

org.nlogo.api.ValueConstraint$Violation: Value must be one of: ["RandomNetwork" "SmallWorldNetwork" "ScaleFreeNetwork"]
 at org.nlogo.agent.ChooserConstraint.assertConstraint(ChooserConstraint.scala:31)
 at org.nlogo.agent.Observer.assertVariableConstraint(Observer.java:112)
 at org.nlogo.agent.Observer.setObserverVariable(Observer.java:119)
 at org.nlogo.agent.World.setObserverVariableByName(World.java:1349)
 at org.nlogo.lab.Worker$Runner$$anonfun$setVariables$1$4.apply(Worker.scala:128)
 at org.nlogo.lab.Worker$Runner$$anonfun$setVariables$1$4.apply(Worker.scala:122)
 at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
 at scala.collection.immutable.List.foreach(List.scala:76)
 at org.nlogo.lab.Worker$Runner.setVariables$1(Worker.scala:122)
 at org.nlogo.lab.Worker$Runner.callHelper(Worker.scala:167)
 at org.nlogo.lab.Worker$Runner.call(Worker.scala:91)
 at org.nlogo.lab.Worker$Runner.call(Worker.scala:74)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)

NetLogo 3D 5.3.1
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_74 (Oracle Corporation; 1.8.0_74-b02)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.9.2
JOGL: 2.3.2
OpenGL graphics: Intel(R) HD Graphics 4000
OpenGL version: 4.0.0 - Build 10.18.10.4358
OpenGL vendor: Intel
model: 3d_Ideological_Agents_v1_w.experiments

06:52:17.558 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
06:52:17.558 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
06:52:17.558 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
06:52:17.557 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
06:52:17.557 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
06:52:16.771 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
06:52:16.771 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
06:52:16.771 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
06:52:16.770 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
06:52:16.770 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread

**Comment by mrerrormessage** [comment]
Would it be possible for you to attach the model to this ticket? Or if the model can't be shared publicly, can you email it to bugs@ccl.northwestern.edu ?

**Comment by hwalbert** [comment]
I believe it was an unusual error from when I was running experiments in behavior space.  I believe it was different error thrown that would have been thrown if I were just running the model once outside of behavior space.  Once I address a global variable name issue the problem didn't appear again. Thank you.

**Comment by mrerrormessage** [comment]
Glad you found a solution!
