### ISSUE TITLE
Matlab extension not compatible with NetLogo 6

### ISSUE THREAD

**Issue by nmuggleton** [NetLogo/NetLogo#1305]
Issue with matlab extension: https://github.com/NetLogo/NetLogo/wiki/Extensions
===
NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 

java.lang.NoClassDefFoundError: org/nlogo/api/Primitive
 at java.lang.Class.getDeclaredConstructors0(Native Method)
 at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
 at java.lang.Class.getConstructor0(Class.java:3075)
 at java.lang.Class.newInstance(Class.java:412)
 at org.nlogo.workspace.JarLoader.extensionClassManager(JarLoader.scala:48)
 at org.nlogo.workspace.ExtensionManager.$anonfun$importExtension$8(ExtensionManager.scala:167)
 at scala.Option.getOrElse(Option.scala:121)
 at org.nlogo.workspace.ExtensionManager.importExtension(ExtensionManager.scala:165)
 at org.nlogo.parse.StructureParser$.$anonfun$parsingWithExtensions$1(StructureParser.scala:71)
 at org.nlogo.parse.StructureParser$.$anonfun$parsingWithExtensions$1$adapted(StructureParser.scala:69)
 at scala.collection.immutable.List.foreach(List.scala:378)
 at org.nlogo.parse.StructureParser$.parsingWithExtensions(StructureParser.scala:69)
 at org.nlogo.parse.StructureParser$.parseSources(StructureParser.scala:35)
 at org.nlogo.parse.NetLogoParser.basicParse(NetLogoParser.scala:17)
 at org.nlogo.parse.NetLogoParser.basicParse$(NetLogoParser.scala:15)
 at org.nlogo.parse.FrontEnd$.basicParse(FrontEnd.scala:10)
 at org.nlogo.parse.FrontEndMain.frontEnd(FrontEnd.scala:27)
 at org.nlogo.parse.FrontEndMain.frontEnd$(FrontEnd.scala:25)
 at org.nlogo.parse.FrontEnd$.frontEnd(FrontEnd.scala:10)
 at org.nlogo.compile.CompilerMain$.compile(CompilerMain.scala:38)
 at org.nlogo.compile.Compiler.compileProgram(Compiler.scala:52)
 at org.nlogo.window.CompilerManager.compileProcedures(CompilerManager.scala:203)
 at org.nlogo.window.CompilerManager.compileAll(CompilerManager.scala:174)
 at org.nlogo.window.CompilerManager.handle(CompilerManager.scala:66)
 at org.nlogo.window.Events$LoadEndEvent.beHandledBy(Events.java:462)
 at org.nlogo.window.Event.doRaise(Event.java:198)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.window.ReconfigureWorkspaceUI$Loader.$anonfun$loadHelper$2(ReconfigureWorkspaceUI.scala:37)
 at org.nlogo.window.ReconfigureWorkspaceUI$Loader.$anonfun$loadHelper$2$adapted(ReconfigureWorkspaceUI.scala:37)
 at scala.collection.immutable.List.foreach(List.scala:378)
 at org.nlogo.window.ReconfigureWorkspaceUI$Loader.loadHelper(ReconfigureWorkspaceUI.scala:37)
 at org.nlogo.window.ReconfigureWorkspaceUI$.apply(ReconfigureWorkspaceUI.scala:19)
 at org.nlogo.app.FileManager.org$nlogo$app$FileManager$$runLoad(FileManager.scala:286)
 at org.nlogo.app.FileManager$$anon$3.run(FileManager.scala:347)
 at org.nlogo.swing.ModalProgressTask$.$anonfun$onUIThread$1(ModalProgressTask.scala:29)
 at org.nlogo.swing.ModalProgressTask$.$anonfun$onUIThread$1$adapted(ModalProgressTask.scala:27)
 at org.nlogo.swing.ModalProgressTask$.$anonfun$display$1(ModalProgressTask.scala:21)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
 at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
 at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
 at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
 at java.awt.Dialog.show(Dialog.java:1084)
 at java.awt.Component.show(Component.java:1671)
 at java.awt.Component.setVisible(Component.java:1623)
 at java.awt.Window.setVisible(Window.java:1014)
 at java.awt.Dialog.setVisible(Dialog.java:1005)
 at org.nlogo.swing.ModalProgressTask$.display(ModalProgressTask.scala:23)
 at org.nlogo.swing.ModalProgressTask$.onUIThread(ModalProgressTask.scala:27)
 at org.nlogo.app.FileManager.openFromModel(FileManager.scala:351)
 at org.nlogo.app.FileManager.$anonfun$openFromURI$1(FileManager.scala:282)
 at org.nlogo.app.FileManager.$anonfun$openFromURI$1$adapted(FileManager.scala:282)
 at scala.Option.foreach(Option.scala:257)
 at org.nlogo.app.FileManager.openFromURI(FileManager.scala:282)
 at org.nlogo.app.FileManager.openFromPath(FileManager.scala:278)
 at org.nlogo.app.OpenRecentFileAction.open(RecentFilesMenu.scala:67)
 at org.nlogo.app.OpenRecentFileAction.actionPerformed(RecentFilesMenu.scala:61)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
 at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
 at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
 at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
 at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
 at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:125)
 at java.awt.MenuItem.processActionEvent(MenuItem.java:669)
 at java.awt.MenuItem.processEvent(MenuItem.java:628)
 at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351)
 at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:761)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.awt.EventQueue$4.run(EventQueue.java:729)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: org.nlogo.api.Primitive
 at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
 at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
 ... 96 more

NetLogo 6.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_112 (Oracle Corporation; 1.8.0_112-b16)
operating system: Mac OS X 10.12.2 (x86_64 processor)
Scala version 2.12.1
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Segregation_edit

09:38:40.866 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
09:38:40.865 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
09:38:40.865 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
09:38:40.858 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:38:40.648 RemoveAllJobsEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
09:38:40.598 LoadEndEvent (org.nlogo.window.ReconfigureWorkspaceUI$Loader (java.lang.Object)) AWT-EventQueue-0
09:38:40.597 WidgetAddedEvent (org.nlogo.window.MonitorWidget) AWT-EventQueue-0
09:38:40.597 CompileMoreSourceEvent (org.nlogo.window.MonitorWidget) AWT-EventQueue-0
09:38:40.596 WidgetAddedEvent (org.nlogo.window.MonitorWidget) AWT-EventQueue-0
09:38:40.596 CompileMoreSourceEvent (org.nlogo.window.MonitorWidget) AWT-EventQueue-0

**Comment by mrerrormessage** [comment]
Hi, thanks for reporting. The matlab extension is maintained by @mbi2gs . As of this time, the `matlab` extension hasn't been updated for NetLogo 6. You can either use NetLogo 5.3.1 or file an issue for them to upgrade the extension for NetLogo 6 ([link to their issue tracker](https://github.com/mbi2gs/netlogo-matlab-extension/issues?q=is%3Aopen+is%3Aissue)). If  @mbi2gs decides to upgrade the extension and runs into problems in NetLogo, please feel free to re-open this issue.
