### ISSUE TITLE
NullPointerException while running Model

### ISSUE THREAD

**Issue by JanVan01** [NetLogo/NetLogo#1314]
NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 

java.lang.NullPointerException
 at org.nlogo.nvm.StackTraceBuilt.computeRuntimeErrorMessage(EngineException.scala:37)
 at org.nlogo.nvm.StackTraceBuilt.computeRuntimeErrorMessage$(EngineException.scala:36)
 at org.nlogo.nvm.RuntimePrimitiveException.computeRuntimeErrorMessage(EngineException.scala:51)
 at org.nlogo.nvm.EngineException.runtimeErrorMessage$lzycompute(EngineException.scala:29)
 at org.nlogo.nvm.EngineException.runtimeErrorMessage(EngineException.scala:28)
 at org.nlogo.nvm.Context.buildRuntimeErrorMessage(Context.java:368)
 at org.nlogo.nvm.Context.buildRuntimeErrorMessage(Context.java:363)
 at org.nlogo.window.ErrorInfo.$anonfun$errorMessage$3(RuntimeErrorDialog.scala:35)
 at scala.Option.map(Option.scala:146)
 at org.nlogo.window.ErrorInfo.errorMessage(RuntimeErrorDialog.scala:34)
 at org.nlogo.window.LogoExceptionDialog.buildTexts(RuntimeErrorDialog.scala:238)
 at org.nlogo.window.LogoExceptionDialog.doShow(RuntimeErrorDialog.scala:224)
 at org.nlogo.window.RuntimeErrorDialog$.$anonfun$show$1(RuntimeErrorDialog.scala:102)
 at org.nlogo.window.RuntimeErrorDialog$.$anonfun$show$1$adapted(RuntimeErrorDialog.scala:102)
 at scala.Option.foreach(Option.scala:257)
 at org.nlogo.window.RuntimeErrorDialog$.show(RuntimeErrorDialog.scala:102)
 at org.nlogo.window.GUIWorkspace$12.run(GUIWorkspace.java:1059)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

NetLogo 6.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_112 (Oracle Corporation; 1.8.0_112-b16)
operating system: Mac OS X 10.11.6 (x86_64 processor)
Scala version 2.12.1
JOGL: 2.3.2
OpenGL graphics: Intel Iris OpenGL Engine
OpenGL version: 2.1 INTEL-10.14.73
OpenGL vendor: Intel Inc.
model: herd_behaviour

06:13:12.287 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
06:13:12.287 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
06:13:12.281 RuntimeErrorEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
06:13:12.180 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
06:13:12.180 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
06:13:12.180 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
06:13:12.180 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
06:13:12.180 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
06:13:12.180 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
06:13:12.180 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0

**Comment by JanVan01** [comment]
I have found the reason for the crash. Apparently it crashes when calculating the acos of a number bigger than 1 or smaller than -1.

Minimal example:
```
to go
  print acos number
end

to-report number
  report 1.00001
end
```

**Comment by mrerrormessage** [comment]
This has the same underlying cause as #1277 and will be fixed in the next release of NetLogo. Thanks for reporting!
