### ISSUE TITLE
Unexpected Error 

### ISSUE THREAD

**Issue by sectuumsempra** [NetLogo/NetLogo#1323]
Hi everyone,
while I was running my simulation an unexpected error occurred, and I can't find out why! Everything seems to work fine, but after 180 ticks (always the same number) the simulation stops and this message appears:

java.lang.NullPointerException
 at org.nlogo.nvm.StackTraceBuilt.computeRuntimeErrorMessage(EngineException.scala:37)
 at org.nlogo.nvm.StackTraceBuilt.computeRuntimeErrorMessage$(EngineException.scala:36)
 at org.nlogo.nvm.RuntimePrimitiveException.computeRuntimeErrorMessage(EngineException.scala:51)
 at org.nlogo.nvm.EngineException.runtimeErrorMessage$lzycompute(EngineException.scala:29)
 at org.nlogo.nvm.EngineException.runtimeErrorMessage(EngineException.scala:28)
 at org.nlogo.nvm.Context.buildRuntimeErrorMessage(Context.java:368)
 at org.nlogo.nvm.Context.buildRuntimeErrorMessage(Context.java:363)
 at org.nlogo.window.ErrorInfo.$anonfun$errorMessage$3(RuntimeErrorDialog.scala:35)
 at scala.Option.map(Option.scala:146)
 at org.nlogo.window.ErrorInfo.errorMessage(RuntimeErrorDialog.scala:34)
 at org.nlogo.window.LogoExceptionDialog.buildTexts(RuntimeErrorDialog.scala:238)
 at org.nlogo.window.LogoExceptionDialog.doShow(RuntimeErrorDialog.scala:224)
 at org.nlogo.window.RuntimeErrorDialog$.$anonfun$show$1(RuntimeErrorDialog.scala:102)
 at org.nlogo.window.RuntimeErrorDialog$.$anonfun$show$1$adapted(RuntimeErrorDialog.scala:102)
 at scala.Option.foreach(Option.scala:257)
 at org.nlogo.window.RuntimeErrorDialog$.show(RuntimeErrorDialog.scala:102)
 at org.nlogo.window.GUIWorkspace$12.run(GUIWorkspace.java:1059)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

NetLogo 6.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_112 (Oracle Corporation; 1.8.0_112-b15)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.1
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: modellodefinitivo

05:20:56.383 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
05:20:56.379 RuntimeErrorEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
05:20:56.361 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
05:20:56.309 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:20:56.309 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:20:56.309 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:20:56.309 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:20:56.309 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:20:56.309 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:20:56.309 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0

Thank you for your help!

**Comment by mrerrormessage** [comment]
I'm fairly certain this is yet another manifestation of #1277 . If you're performing numeric computations, they are probably getting too large around tick 180, causing a number-too-large exception which then causes this. We've fixed #1277 and the fix will be included in the next NetLogo release.
