### ISSUE TITLE
i can't set up the netlogo-matlab extension

### ISSUE THREAD

**Issue by Lugo82** [NetLogo/NetLogo#1362]
java.lang.NoClassDefFoundError: org/nlogo/api/Primitive
 at java.lang.Class.getDeclaredConstructors0(Native Method)
 at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
 at java.lang.Class.getConstructor0(Class.java:3075)
 at java.lang.Class.newInstance(Class.java:412)
 at org.nlogo.workspace.JarLoader.extensionClassManager(JarLoader.scala:48)
 at org.nlogo.workspace.ExtensionManager.$anonfun$importExtension$8(ExtensionManager.scala:167)
 at scala.Option.getOrElse(Option.scala:121)
 at org.nlogo.workspace.ExtensionManager.importExtension(ExtensionManager.scala:165)
 at org.nlogo.parse.StructureParser$.$anonfun$parsingWithExtensions$1(StructureParser.scala:71)
 at org.nlogo.parse.StructureParser$.$anonfun$parsingWithExtensions$1$adapted(StructureParser.scala:69)
 at scala.collection.immutable.List.foreach(List.scala:378)
 at org.nlogo.parse.StructureParser$.parsingWithExtensions(StructureParser.scala:69)
 at org.nlogo.parse.StructureParser$.parseSources(StructureParser.scala:35)
 at org.nlogo.parse.NetLogoParser.basicParse(NetLogoParser.scala:17)
 at org.nlogo.parse.NetLogoParser.basicParse$(NetLogoParser.scala:15)
 at org.nlogo.parse.FrontEnd$.basicParse(FrontEnd.scala:10)
 at org.nlogo.parse.FrontEndMain.frontEnd(FrontEnd.scala:27)
 at org.nlogo.parse.FrontEndMain.frontEnd$(FrontEnd.scala:25)
 at org.nlogo.parse.FrontEnd$.frontEnd(FrontEnd.scala:10)
 at org.nlogo.compile.CompilerMain$.compile(CompilerMain.scala:38)
 at org.nlogo.compile.Compiler.compileProgram(Compiler.scala:52)
 at org.nlogo.window.CompilerManager.compileProcedures(CompilerManager.scala:203)
 at org.nlogo.window.CompilerManager.compileAll(CompilerManager.scala:174)
 at org.nlogo.window.CompilerManager.handle(CompilerManager.scala:138)
 at org.nlogo.window.Events$CompileAllEvent.beHandledBy(Events.java:185)
 at org.nlogo.window.Event.doRaise(Event.java:198)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.app.codetab.CodeTab.compile(CodeTab.scala:134)
 at org.nlogo.app.codetab.CodeTab$CompileAction$.actionPerformed(CodeTab.scala:170)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
 at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
 at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
 at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
 at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
 at java.awt.Component.processMouseEvent(Component.java:6533)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
 at java.awt.Component.processEvent(Component.java:6298)
 at java.awt.Container.processEvent(Container.java:2236)
 at java.awt.Component.dispatchEventImpl(Component.java:4889)
 at java.awt.Container.dispatchEventImpl(Container.java:2294)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
 at java.awt.Container.dispatchEventImpl(Container.java:2280)
 at java.awt.Window.dispatchEventImpl(Window.java:2746)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.awt.EventQueue$4.run(EventQueue.java:729)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: org.nlogo.api.Primitive
 at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
 at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
 ... 65 more

NetLogo 6.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_112 (Oracle Corporation; 1.8.0_112-b15)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.1
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Untitled

08:32:55.966 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
08:32:55.764 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
08:32:55.563 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
08:32:55.362 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
08:32:55.162 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
08:32:54.958 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
08:32:54.758 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
08:32:54.557 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
08:32:54.438 RemoveAllJobsEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
08:32:54.438 CompileAllEvent (org.nlogo.app.codetab.MainCodeTab) AWT-EventQueue-0

**Comment by mrerrormessage** [comment]
The matlab extension is maintained by @mbi2gs and is *not* a bundled NetLogo extension. It looks like the MatLab extension lists itself as being compatible with NetLogo 5.3.1, but not NetLogo 6. You can download NetLogo 5.3.1 [here](https://ccl.northwestern.edu/netlogo/5.3.1/).
