### ISSUE TITLE
String ".5*" in code tab crashes netLogo

### ISSUE THREAD

**Issue by jirkaslavotinek** [NetLogo/NetLogo#1370]
Here is log:

java.security.PrivilegedActionException: java.security.PrivilegedActionException: java.text.ParseException: Unparseable number: ".5*"
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.security.PrivilegedActionException: java.text.ParseException: Unparseable number: ".5*"
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.awt.EventQueue$4.run(EventQueue.java:729)
 ... 9 more
Caused by: java.text.ParseException: Unparseable number: ".5*"
 at java.text.NumberFormat.parse(NumberFormat.java:385)
 at org.nlogo.core.NumberParser$.parse(NumberParser.scala:58)
 at org.nlogo.lex.TokenLexer.tokenizeLiteral(TokenLexer.scala:128)
 at org.nlogo.lex.TokenLexer.$anonfun$numericLiteral$5(TokenLexer.scala:100)
 at org.nlogo.lex.CharacterIteratorInput.assembleToken(CharacterIteratorInput.scala:34)
 at org.nlogo.lex.TokenLexer.$anonfun$apply$1(TokenLexer.scala:34)
 at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
 at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
 at scala.collection.immutable.List.foldLeft(List.scala:86)
 at org.nlogo.lex.TokenLexer.apply(TokenLexer.scala:31)
 at org.nlogo.lex.Tokenizer$TokenLexIterator.next(Tokenizer.scala:68)
 at org.nlogo.lex.Tokenizer$TokenLexIterator.next(Tokenizer.scala:60)
 at scala.collection.Iterator$$anon$10.next(Iterator.scala:448)
 at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:501)
 at org.nlogo.ide.NetLogoTokenMaker.getTokenList(NetLogoTokenMaker.scala:111)
 at org.nlogo.ide.NetLogoTokenMaker.getTokenList$(NetLogoTokenMaker.scala:93)
 at org.nlogo.ide.NetLogoTwoDTokenMaker.getTokenList(NetLogoTokenMaker.scala:122)
 at org.fife.ui.rsyntaxtextarea.TokenMakerBase.getLastTokenTypeOnLine(TokenMakerBase.java:225)
 at org.fife.ui.rsyntaxtextarea.RSyntaxDocument.updateLastTokensBelow(RSyntaxDocument.java:608)
 at org.fife.ui.rsyntaxtextarea.RSyntaxDocument.fireInsertUpdate(RSyntaxDocument.java:182)
 at javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:748)
 at javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:707)
 at javax.swing.text.PlainDocument.insertString(PlainDocument.java:130)
 at javax.swing.text.AbstractDocument.replace(AbstractDocument.java:669)
 at javax.swing.text.JTextComponent.replaceSelection(JTextComponent.java:1328)
 at org.fife.ui.rtextarea.RTextArea.handleReplaceSelection(RTextArea.java:870)
 at org.fife.ui.rtextarea.RTextArea.replaceSelection(RTextArea.java:1235)
 at org.nlogo.editor.AdvancedEditorArea.replaceSelection(AdvancedEditorArea.scala:60)
 at javax.swing.text.DefaultEditorKit$DefaultKeyTypedAction.actionPerformed(DefaultEditorKit.java:884)
 at org.fife.ui.rtextarea.RTextAreaEditorKit$DefaultKeyTypedAction.actionPerformedImpl(RTextAreaEditorKit.java:862)
 at org.fife.ui.rtextarea.RecordableTextAction.actionPerformed(RecordableTextAction.java:106)
 at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)
 at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
 at javax.swing.JComponent.processKeyBindings(JComponent.java:2929)
 at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
 at java.awt.Component.processEvent(Component.java:6310)
 at java.awt.Container.processEvent(Container.java:2236)
 at java.awt.Component.dispatchEventImpl(Component.java:4889)
 at java.awt.Container.dispatchEventImpl(Container.java:2294)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
 at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
 at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
 at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
 at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
 at java.awt.Component.dispatchEventImpl(Component.java:4760)
 at java.awt.Container.dispatchEventImpl(Container.java:2294)
 at java.awt.Window.dispatchEventImpl(Window.java:2746)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 ... 14 more

NetLogo 6.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_112 (Oracle Corporation; 1.8.0_112-b15)
operating system: Windows 7 6.1 (amd64 processor)
Scala version 2.12.1
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Untitled

01:45:38.835 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
01:45:38.635 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
01:45:38.435 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
01:45:38.367 DirtyEvent (org.nlogo.app.codetab.MainCodeTab) AWT-EventQueue-0
01:45:38.366 DirtyEvent (org.nlogo.app.codetab.MainCodeTab) AWT-EventQueue-0
01:45:38.235 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
01:45:38.033 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
01:45:38.027 DirtyEvent (org.nlogo.app.codetab.MainCodeTab) AWT-EventQueue-0
01:45:37.969 DirtyEvent (org.nlogo.app.codetab.MainCodeTab) AWT-EventQueue-0
01:45:37.807 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

**Comment by mrerrormessage** [comment]
Thanks for reporting. I'm unable to replicate this problem - do you have a particular model that you see it happen in? Does it happen when the model is started or is already running?

**Comment by mrerrormessage** [comment]
Thanks for reporting. I'm unable to replicate this problem - do you have a particular model that you see it happen in? (You can just paste some of the surrounding code). Does it happen when the model is started or is already running? Also, are what are your computers localization/internationalization settings?

**Comment by jirkaslavotinek** [comment]
Simple case: Create new model, Go to Code, write .5* and then Internal error shows up immediately. I was using NetLogo 6.0 and tried with 6.0.1 but the problem persist. OS localization is English (might be Czech for something)

**Comment by mrerrormessage** [comment]
Thanks! I've managed to reproduce the problem by changing my locale out of US-English.

**Comment by mrerrormessage** [comment]
Technical details:

* Reproducible in NetLogo 6.0 when run with `-Duser.country=FR -Duser.region=FR -Duser.language=fr`
* Number Format uses `DecimalFormat`, should probably get a specific format for US-en from [`NumberFormat.getNumberInstance`](https://docs.oracle.com/javase/8/docs/api/java/text/NumberFormat.html#getNumberInstance-java.util.Locale-) and customize as appropriate (see DecimalFormat documentation for example).
