### ISSUE TITLE
BehaviorSpace run does not stop on an error.

### ISSUE THREAD

**Issue by cstaelin** [NetLogo/NetLogo#1386]
I've started running BehaviorSpace headless for the first time in a long while, and for the first time with NetLogo 6.0 (in this case 6.0.1).  In the process I've found a documentation error and what I think is a bug.  The documentation error is simple, 
`"java -Xmx1024m -Dfile.encoding=UTF-8 -cp NetLogo.jar \"`
shoud be
`"java -Xmx1024m -Dfile.encoding=UTF-8 -cp NetLogo-6.0.1.jar \"`
now that the jar file carries the version number. It might also be helpful for the documentation to point to the app directory where the jar file is found.

The bug is puzzling.  When I run the model with one given set of parameters interactively, I get an extension exception error at step 37 of a planned 100 and the run stops with the expected exception message, which I can then "Dismiss".  (The extension is my own, and it throws a NetLogo extension exception from the Java code.)  But, when I run the same set of parameters through BehaviorSpace in headless mode, I get the same exception at the same step, but then the model simply continues running for steps 37 though 100, generating a runtime NetLogo error at each step (which makes sense given the implications of the initial extension exception). I have the model write output to a file at every step, and that output stops at step 36, as I would expect. But if I also specify the table option, the table file shows 100 steps, with the last 62 giving identical results, which is what leads me to believe that BehaviorSpace is indeed looping through steps 38 - 100.

To further test this, I ran this set of parameters in an BehaviorSpace experiment interactively. In this case, I don't see the initial extension exception, but only the subsequent runtime error at step 37 and, when I dismiss it the model seemingly stops - I don't get further runtime errors. If I go to the command line before dismissing the runtime error message ahd `show ticks`, I get 37. If I do so after dismissing the message, I get 37 as well. My output file stops at step 36, but again the table file still has 100 steps listed, as it did when I ran headless. It seems that my extension exception is not really stopping execution (as it does when running interactively), nor is the runtime error, but why that should be different in BehaviorSpace, I don't know.

I've copied the exception and runtime error below in case they are useful.

Charles

**The original exception:**
Run #1, RUNTIME ERROR: Extension exception: Simplex exceeded 20000 iterations, the maximum number specified.
error while firm 3300 running NUMANAL:SIMPLEX
  called by procedure SIMPLEX (C:\Users\cstaelin\Google Drive\New Model\NewModel36\solution-setups.nls)
  called by procedure FIRM-FIND-PRICES
  called by procedure FIRM-CHECK-TO-ENTER-MARKETS
  called by procedure GO
  called by procedure __EVALUATOR
org.nlogo.nvm.WrappedExtensionException: Extension exception: Simplex exceeded 20000 iterations, the maximum number specified.
	at org.nlogo.prim._externreport.report(_externreport.java:35)
	at org.nlogo.prim._asm_proceduresimplexcuserscstaelingoogledrivenewmodelnewmodel36solutionsetupsnls_report_12.perform()
	at org.nlogo.nvm.Context.callReporterProcedure(Context.java:258)
	at org.nlogo.prim._asm_proceduresolutiontablesetupcuserscstaelingoogledrivenewmodelnewmodel36solutionsetups$a495f448c7ccfcba30609915509ca865$_callreport_3.report(:1)
	at org.nlogo.nvm.AnonymousReporter.report(AnonymousProcedure.scala:102)
	at org.nlogo.nvm.AnonymousReporter.report(AnonymousProcedure.scala:93)
	at org.nlogo.prim.etc._runresult.report(_runresult.scala:43)
	at org.nlogo.prim._asm_procedurefirmfindprices_setprocedurevariable_19.perform()
	at org.nlogo.nvm.Context.callReporterProcedure(Context.java:258)
	at org.nlogo.prim._asm_procedurefirmchecktoentermarkets_setprocedurevariable_22.perform(:2)
	at org.nlogo.nvm.Context.runExclusive(Context.java:135)
	at org.nlogo.nvm.ExclusiveJob.run(ExclusiveJob.scala:39)
	at org.nlogo.nvm.Context.runExclusiveJob(Context.java:181)
	at org.nlogo.prim._asm_procedurego_ask_16.perform(:1)
	at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
	at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
	at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
	at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
	at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
	at org.nlogo.job.JobThread.run(JobThread.scala:66)
Caused by: org.nlogo.api.ExtensionException: Simplex exceeded 20000 iterations, the maximum number specified.
	at org.nlogo.extensions.numanal.Simplex.performSimplex(Simplex.java:305)
	at org.nlogo.extensions.numanal.Simplex.access$000(Simplex.java:26)
	at org.nlogo.extensions.numanal.Simplex$SimplexSolve.report(Simplex.java:208)
	at org.nlogo.prim._externreport.report(_externreport.java:31)
	... 21 more
	
**The subsequent runtime errors, repeated 32 times:**
Run #1, RUNTIME ERROR: OF expected input to be a link agentset or link but got NOBODY instead.
org.nlogo.nvm.ArgumentTypeException: OF expected input to be a link agentset or link but got NOBODY instead.
	at org.nlogo.nvm.AnonymousCommand.perform(AnonymousProcedure.scala:150)
	at org.nlogo.nvm.AnonymousCommand.perform(AnonymousProcedure.scala:133)
	at org.nlogo.prim.etc._foreach.perform(_foreach.scala:35)
	at org.nlogo.nvm.Context.runExclusive(Context.java:135)
	at org.nlogo.nvm.ExclusiveJob.run(ExclusiveJob.scala:39)
	at org.nlogo.nvm.Context.runExclusiveJob(Context.java:181)
	at org.nlogo.prim._asm_procedurego_ask_8.perform(:1)
	at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
	at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
	at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
	at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
	at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
	at org.nlogo.job.JobThread.run(JobThread.scala:66)
Run #1, RUNTIME ERROR: OF expected input to be a link agentset or link but got NOBODY instead.
org.nlogo.nvm.ArgumentTypeException: OF expected input to be a link agentset or link but got NOBODY instead.
	at org.nlogo.nvm.AnonymousCommand.perform(AnonymousProcedure.scala:150)
	at org.nlogo.nvm.AnonymousCommand.perform(AnonymousProcedure.scala:133)
	at org.nlogo.prim.etc._foreach.perform(_foreach.scala:35)
	at org.nlogo.nvm.Context.runExclusive(Context.java:135)
	at org.nlogo.nvm.ExclusiveJob.run(ExclusiveJob.scala:39)
	at org.nlogo.nvm.Context.runExclusiveJob(Context.java:181)
	at org.nlogo.prim._asm_procedurego_ask_8.perform(:1)
	at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
	at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
	at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
	at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
	at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
	at org.nlogo.job.JobThread.run(JobThread.scala:66)

**Comment by mrerrormessage** [comment]
Thanks for reporting! The documentation issue definitely needs to get resolved and we will see to it that that happens.

The error issue is actually a bit more complex. I tested the following model:

```NetLogo
to setup
  clear-all
  reset-ticks
end

to go
  print "going"
  error "error"
  print ticks
end
```

In a simple Behaviorspace experiment which ran `go` 5 times (in the GUI) and I saw "going" printed in the command center 5 times (it never prints the number of ticks, but does display the error alert window). This seems to have been the behavior for a long time. It is reflected in the headless run as well, except it also shows errors which happen in background threads. Many of our users want Behaviorspace runs to continue in the presence of errors (for instance, they have a long run and don't want to be bothered if some of their runs return errors if most complete successfully).

Based on the fact that you have two different types of exceptions, I think your case may be slightly different and may point to a deeper problem. Could you send a copy of your model to bugs@ccl.northwestern.edu (referencing this issue) so I can evaluate it further? Alternatively, if the model is public, post a link here and I'll download it to have a look.

**Comment by cstaelin** [comment]
I sent a test model and its output to "bugs".  As I say there, the issue for me is not that the other BehaviorSpace runs continue - that seems as it should be, but that the run that exhibits an error continues rather than terminating with the error - or at least so it seems.
Thanks,
Charles

**Comment by mrerrormessage** [comment]
We believe the solution here is to add a preference to behaviorspace which allows users to control the behavior when an error is encountered. Hopefully this will be suitable for users like yourself as well as users who want to keep running even with an error.

**Comment by cstaelin** [comment]
That sounds like a good solution.  I am a bit worried that a user with a
long series of BehaviorSpace runs my not notice that a particular run
encountered an error and interpret the results of that run following the
error as valid, particularly if BS was running headless.  But, with the
option you suggest, the user could at least avoid that by setting the
option appropriately.  Have you decided which behavior would be the default?

Thanks,
Charles


-------------------------------
Charles P. Staelin
Professor of Economics
Smith College
Northampton, MA 01063

**Comment by daimpi** [comment]
It would be cool if there was a BehaviorSpace reporter which you could add to the list of reporters in your experiment. The output could be a simple 0/1, signifying whether an error occurred during a particular run of the experiment. This would allow you to detect which runs are invalid in case a problem occurs, without requiring to abort the whole experiment :).

**Comment by cstaelin** [comment]
I think that I've discovered a more serious issue with errors in BehaviorSpace. By way of background, in my own model I write to my own .csv file at the end of each step. I've not been getting errors in runs recently, but today I did and I checked both my own .csv file and BS's table file.  I discovered that my file for the errant run ended with the step just before the error while the table file continued writing results for the errant run up to the nominal end of the run. So I went back to the test model I sent earlier and added a file-print to the go procedure after the point where an error is generated on one of the six runs, the 4th. Sure enough, when I ran the experiment my Run 4 data

 stopped at the step before the error was generated, step 3, and the table file continued listing Run 4 results on to step 10, the intended end of the run. It seemed like when an error was encountered, BS stopped the run itself, but not the table file. To test this out further, I created a turtle in the code both before and after the point at which an error is generated, put `count turtles` as a reporter in the table file, and had the table file record each step. In those runs without an error, the count goes up by two at each step, as we would expect. However, in the run with an error, run 4, the count goes up by two each step before the error is generated, but then goes up by one for each of the remaining steps. It seems as if for each step after the error is generated, BS is running only that part of the code in the go procedure that comes before the point where the error was generated and then skips over the rest. The second `create-turtles` and write to my data file never occur. Surely this is not intended behavior?!

I've attached the revised test model and the two data files it produces as a zip here and sent them to "bugs" in their original forms. 

Do let me know if I've not been clear.

[BSTest.zip](https://github.com/NetLogo/NetLogo/files/980620/BSTest.zip)

Charles

**Comment by mrerrormessage** [comment]
Thanks for the thorough report. I've reviewed the model you attached and it displays the behavior you have described. Although this behavior is consistent between NetLogo 5.3.1, 6.0, and 6.0.1, I agree it is strange that we fail to even note that there was an error when it was raised explicitly by the user with the `error` primitive. I'll discuss this with the development team and see whether we can come up with some solution which makes the problem clear to the user without introducing noise and confusion.

**Comment by cstaelin** [comment]
Robert,

I wonder if the solution might be two-fold.  1) mention in the
documentation that this can be a problem to be watchful for; and 2) provide
an option to specify an error file.  When running headless, one can capture
stderr and pipe it to a file.  That is how I know something is going on
with my models when they encounter an error.  An option when running
interactively that allows the user to specify an error file along with the
table and/or spreadsheet file would provide a heads up to the user when one
of their runs encounters an error.  As an option, it could be ignored by
most users, but be available to those who want/need it.

For what it's worth,
Charles


-------------------------------
Charles P. Staelin
Professor of Economics
Smith College
Northampton, MA 01063

**Comment by cstaelin** [comment]
I wonder if any more thought has been given to this issue - that is the ability for a runtime error in an individual BS run to stop that run (and only that run).  I just encountered a situation where one of 35 runs generated the same runtime math error over 300 thousand times - creating a stderr file over a gigabyte in size.  NetLogo's own error primitive also will not lead a run to abort.

Can anyone think of a workaround for the moment?

Thanks,
Charles

**Comment by danielvartan** [comment]
I think this is a critical issue for BehaviorSpace.

Not stopping the model when an error occurs can create misleading results. When used for research, this can be very detrimental.

I created a reproducible example for this. You can find it at: https://github.com/danielvartan/test/tree/netlogo-1

Here is the [test model](https://github.com/danielvartan/test/blob/netlogo-1/nlogox/test.nlogox) code:

```NetLogo
patches-own [value]

to setup
  clear-all
  reset-ticks
end

to go
  user-message "Test"

  error "Test"
  
  ask patches [
    set pcolor random 140
    set value 999
  ]
end
```

## How to Reproduce

1. Clone the repository (branch: `netlogo-1`) indicated above.
2. Open a terminal and go to the project's root.
3. In a terminal, run the following experiment:

> I'm assuming you have the NetLogo binary in your `PATH` environment variable.

```bash
NetLogo --headless --model './nlogox/test.nlogox' --setup-file './xml/test.xml' --table './test.csv'
```

4. Check the contents of [`test.csv`](https://github.com/danielvartan/test/blob/netlogo-1/data/table.csv).

## Expected Behavior

While running the model headless with a BehaviorSpace experiment, NetLogo should stop and produce an error and not produce any output.

At the moment, although the results in `test.csv` show the patch values as `0`, it does not stop the run and produce an error, leading to inaccurate conclusions.

## System

NetLogo 7.0.3 (December 1, 2025)
Extension API version: 7.0
OpenJDK 64-Bit Server VM 17.0.2 (Oracle Corporation; 17.0.2+8-86)
Operating system: Linux 6.18.2-arch2-1 (amd64 processor)
Scala 3.7.0
Java heap: used = 74 MB, free = 198 MB, max = 15896 MB

JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)

**Comment by TheBizzle** [comment]
[A relevant thread on the NetLogo Forum.](https://forum.netlogo.org/t/dealing-with-errors-in-behaviorspace-experiments/754)

I'm not able to find the initially-mentioned documentation error anywhere in our current docs, so I'm just going to re-target this ticket for the "let the user choose how they want to handle runtime errors" functionality.

**Comment by ERSUCC** [comment]
Fixed by PR #2565.
