### ISSUE TITLE
Netlogo SourceTagger error

### ISSUE THREAD

**Issue by shanghua-tuebingen** [NetLogo/NetLogo#1393]
When i convert the code in Netlogo from 5.2 to 6.0, it gives me this error

java.util.NoSuchElementException
 at scala.collection.LinearSeqOptimized.last(LinearSeqOptimized.scala:146)
 at scala.collection.LinearSeqOptimized.last$(LinearSeqOptimized.scala:145)
 at scala.collection.immutable.List.last(List.scala:86)
 at org.nlogo.compile.middle.SourceTagger.visitCommandBlock(SourceTagger.scala:58)
 at org.nlogo.compile.api.CommandBlock.accept(AstNode.scala:125)
 at org.nlogo.compile.api.DefaultAstVisitor.$anonfun$visitStatement$1(AstVisitor.scala:31)
 at org.nlogo.compile.api.DefaultAstVisitor.$anonfun$visitStatement$1$adapted(AstVisitor.scala:31)
 at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
 at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
 at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
 at org.nlogo.compile.api.DefaultAstVisitor.visitStatement(AstVisitor.scala:31)
 at org.nlogo.compile.middle.SourceTagger.super$visitStatement(SourceTagger.scala:28)
 at org.nlogo.compile.middle.SourceTagger.$anonfun$visitStatement$1(SourceTagger.scala:28)
 at org.nlogo.compile.middle.SourceTagger.captureInternalSources(SourceTagger.scala:21)
 at org.nlogo.compile.middle.SourceTagger.visitStatement(SourceTagger.scala:28)
 at org.nlogo.compile.api.Statement.accept(AstNode.scala:98)
 at org.nlogo.compile.api.DefaultAstVisitor.$anonfun$visitStatements$1(AstVisitor.scala:32)
 at org.nlogo.compile.api.DefaultAstVisitor.$anonfun$visitStatements$1$adapted(AstVisitor.scala:32)
 at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
 at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
 at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
 at org.nlogo.compile.api.DefaultAstVisitor.visitStatements(AstVisitor.scala:32)
 at org.nlogo.compile.api.Statements.accept(AstNode.scala:74)
 at org.nlogo.compile.api.DefaultAstVisitor.visitProcedureDefinition(AstVisitor.scala:27)
 at org.nlogo.compile.api.ProcedureDefinition.accept(AstNode.scala:50)
 at org.nlogo.compile.middle.MiddleEnd$.$anonfun$middleEnd$3(MiddleEnd.scala:39)
 at org.nlogo.compile.middle.MiddleEnd$.$anonfun$middleEnd$3$adapted(MiddleEnd.scala:38)
 at scala.collection.immutable.List.foreach(List.scala:378)
 at org.nlogo.compile.middle.MiddleEnd$.middleEnd(MiddleEnd.scala:38)
 at org.nlogo.compile.CompilerMain$.compile(CompilerMain.scala:46)
 at org.nlogo.compile.Compiler.compileProgram(Compiler.scala:52)
 at org.nlogo.window.CompilerManager.compileProcedures(CompilerManager.scala:203)
 at org.nlogo.window.CompilerManager.compileAll(CompilerManager.scala:174)
 at org.nlogo.window.CompilerManager.handle(CompilerManager.scala:138)
 at org.nlogo.window.Events$CompileAllEvent.beHandledBy(Events.java:185)
 at org.nlogo.window.Event.doRaise(Event.java:198)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.app.codetab.CodeTab.compile(CodeTab.scala:134)
 at org.nlogo.app.codetab.CodeTab$CompileAction$.actionPerformed(CodeTab.scala:170)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
 at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
 at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
 at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
 at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
 at java.awt.Component.processMouseEvent(Component.java:6533)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
 at java.awt.Component.processEvent(Component.java:6298)
 at java.awt.Container.processEvent(Container.java:2236)
 at java.awt.Component.dispatchEventImpl(Component.java:4889)
 at java.awt.Container.dispatchEventImpl(Container.java:2294)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
 at java.awt.Container.dispatchEventImpl(Container.java:2280)
 at java.awt.Window.dispatchEventImpl(Window.java:2746)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.awt.EventQueue$4.run(EventQueue.java:729)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

NetLogo 6.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_112 (Oracle Corporation; 1.8.0_112-b15)
operating system: Windows 7 6.1 (amd64 processor)
Scala version 2.12.1
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: veg_model_0305

09:30:59.192 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
09:30:59.192 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
09:30:59.192 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
09:30:59.192 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
09:30:59.192 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
09:30:59.192 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
09:30:59.192 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
09:30:59.192 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
09:30:59.192 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
09:30:59.192 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0

Anyone knows how to fix this?
Thanks

**Comment by SethTisue** [comment]
does the problem occur in NetLogo 6.0.1 as well?

**Comment by shanghua-tuebingen** [comment]
I do not know, i only used 6.0

**Comment by mrerrormessage** [comment]
This was most likely fixed in #1435. When the next version of NetLogo is released (6.0.2), please let us know if it does not fix this error.
