### ISSUE TITLE
Internal error while running a model of netlogo 5.3.1 in 6.0

### ISSUE THREAD

**Issue by alishahzad93** [NetLogo/NetLogo#1395]
java.lang.AssertionError: assertion failed
 at scala.Predef$.assert(Predef.scala:156)
 at org.nlogo.app.TemporaryCodeTab.load(TemporaryCodeTab.scala:62)
 at org.nlogo.app.TemporaryCodeTab.<init>(TemporaryCodeTab.scala:27)
 at org.nlogo.app.Tabs.addNewTab(Tabs.scala:136)
 at org.nlogo.app.Tabs.openTemporaryFile(Tabs.scala:120)
 at org.nlogo.app.Tabs.handle(Tabs.scala:100)
 at org.nlogo.window.Events$CompiledEvent.beHandledBy(Events.java:212)
 at org.nlogo.window.Event.doRaise(Event.java:198)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.window.CompilerManager.compileProcedures(CompilerManager.java:149)
 at org.nlogo.window.CompilerManager.compileAll(CompilerManager.java:86)
 at org.nlogo.window.CompilerManager.handle(CompilerManager.java:312)
 at org.nlogo.window.Events$CompileAllEvent.beHandledBy(Events.java:174)
 at org.nlogo.window.Event.doRaise(Event.java:198)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.app.CodeTab$CompileAction.actionPerformed(CodeTab.scala:62)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
 at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
 at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
 at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
 at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
 at java.awt.Component.processMouseEvent(Component.java:6533)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
 at java.awt.Component.processEvent(Component.java:6298)
 at java.awt.Container.processEvent(Container.java:2236)
 at java.awt.Component.dispatchEventImpl(Component.java:4889)
 at java.awt.Container.dispatchEventImpl(Container.java:2294)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
 at java.awt.Container.dispatchEventImpl(Container.java:2280)
 at java.awt.Window.dispatchEventImpl(Window.java:2746)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.awt.EventQueue$4.run(EventQueue.java:729)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

NetLogo 6.0-M6
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) Client VM 1.8.0_92 (Oracle Corporation; 1.8.0_92-b14)
operating system: Windows 7 6.1 (x86 processor)
Scala version 2.11.8
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: drug_model

02:01:28.915 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
02:01:28.915 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
02:01:28.915 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
02:01:28.915 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
02:01:28.915 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
02:01:28.915 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
02:01:28.915 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
02:01:28.915 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
02:01:28.915 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
02:01:28.915 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0

**Comment by mrerrormessage** [comment]
Can you please send a copy of the model which produced this error? If you would prefer not to share it publicly, it can be sent to bugs@ccl.northwestern.edu

**Comment by mrerrormessage** [comment]
I just noticed this was NetLogo 6.0-M6. Please upgrade to NetLogo 6.0 or 6.0.1, available for download on [the NetLogo Website](ccl.northwestern.edu/netlogo). If you see the same error, please re-open this. Otherwise, I'm assuming this issue has been resolved in a more recent version (given that the file involved was totally rewritten).
