### ISSUE TITLE
netlogo-headless using controlling-api 

### ISSUE THREAD

**Issue by martin-riedl** [NetLogo/NetLogo#1398]
Trying to integrate NetLogo Headless in an Scala Application 
```scala
import org.nlogo.headless.HeadlessWorkspace
object Example2 {
  def main(args:Array[String]) {
    val workspace = HeadlessWorkspace.newInstance
  }
}
```
compiles well using the following build file
```
scalaVersion := "2.12.1"
lazy val root = Project("root", file(".")) dependsOn(nl)
lazy val nl = ProjectRef(file("../NetLogo/"),"headless")
```
but eventually fails with the following errer when running 
```
[error] (run-main-0) java.lang.ExceptionInInitializerError
java.lang.ExceptionInInitializerError
        at org.nlogo.core.NetLogoCore$.<init>(Dialect.scala:22)
        at org.nlogo.core.NetLogoCore$.<clinit>(Dialect.scala)
        at org.nlogo.core.Program$.empty(Program.scala:8)
        at org.nlogo.core.Program.empty(Program.scala)
        at org.nlogo.agent.World.newProgram(World.java:1130)
        at org.nlogo.agent.World.<init>(World.java:1115)
        at org.nlogo.headless.HeadlessWorkspace$.newInstance(HeadlessWorkspace.scala:39)
        at org.nlogo.headless.HeadlessWorkspace$.newInstance(HeadlessWorkspace.scala:33)
        at Example2$.main(Main.scala:4)
        at Example2.main(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
Caused by: java.lang.NullPointerException
        at scala.io.Source$.fromURL(Source.scala:141)
        at org.nlogo.core.Resource$.get(Resource.scala:8)
        at org.nlogo.core.Resource$.lines(Resource.scala:11)
        at org.nlogo.core.TokenMapper.entries(TokenMapper.scala:23)
        at org.nlogo.core.TokenMapper.<init>(TokenMapper.scala:28)
        at org.nlogo.core.DefaultTokenMapper$.<init>(TokenMapper.scala:6)
        at org.nlogo.core.DefaultTokenMapper$.<clinit>(TokenMapper.scala)
        at org.nlogo.core.NetLogoCore$.<init>(Dialect.scala:22)
        at org.nlogo.core.NetLogoCore$.<clinit>(Dialect.scala)
        at org.nlogo.core.Program$.empty(Program.scala:8)
        at org.nlogo.core.Program.empty(Program.scala)
        at org.nlogo.agent.World.newProgram(World.java:1130)
        at org.nlogo.agent.World.<init>(World.java:1115)
        at org.nlogo.headless.HeadlessWorkspace$.newInstance(HeadlessWorkspace.scala:39)
        at org.nlogo.headless.HeadlessWorkspace$.newInstance(HeadlessWorkspace.scala:33)
        at Example2$.main(Main.scala:4)
        at Example2.main(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
```
I'd be happy to get to know what the issue is and why in general there is a call to *fromURL()*?

**Comment by mrerrormessage** [comment]
The issue is that NetLogo depends on a file called "system/tokens.txt" being on the classpath at the time it is run. This file contains a mapping between given text strings ("foreach", for instance) and the runtime class used to provide syntax information about the `foreach` NetLogo primitive (`org.nlogo.core.prim.etc._foreach`). This file doesn't live in the "headless" project in the NetLogo repository, but in one of the dependent projects. I'm a bit surprised that sbt isn't integrating it with headless, since it certainly works in the main NetLogo build.

Unless your needs are extremely specialized, I would recommend depending on the published NetLogo jars instead of using an sbt project ref. This can be done with the following sbt configuration:

```scala
resolvers += Resolver.bintrayRepo("content/netlogo", "NetLogo-JVM")
 libraryDependencies ++= Seq(
  "org.nlogo" % "netlogo" % "6.0.1" intransitive,
  "org.picocontainer" % "picocontainer" % "2.13.6",
  "org.ow2.asm" % "asm-all" % "5.0.3")
```

Note that the above dependencies are for a minimal set of features. If you use more advanced features and run into problems, you may need to add dependencies on one or more of [these libraries used by NetLogo](https://github.com/NetLogo/NetLogo/blob/hexy/build.sbt#L129-L143).

**Comment by martin-riedl** [comment]
Thanks a lot for your immediate feedback. Your feedback helped to get it running. 

For model parsing and execution of e.g. of the *fire.nlogo* example, I also had to add transitive dependencies 
```
libraryDependencies += "org.scala-lang.modules" % "scala-parser-combinators_2.12" % "1.0.6"
libraryDependencies += "org.parboiled" %% "parboiled" % "2.1.4"
```
Thenafter, the example could be performed.
