### ISSUE TITLE
Internal error Netlogo 6.0.1

### ISSUE THREAD

**Issue by SimonB74** [NetLogo/NetLogo#1417]
While updating a model from 5.3 to 6.0.1 the following occurred.  The model was the same before and after the error occurred.  

java.util.NoSuchElementException
 at scala.collection.LinearSeqOptimized.last(LinearSeqOptimized.scala:146)
 at scala.collection.LinearSeqOptimized.last$(LinearSeqOptimized.scala:145)
 at scala.collection.immutable.List.last(List.scala:86)
 at org.nlogo.compile.middle.SourceTagger.visitCommandBlock(SourceTagger.scala:58)
 at org.nlogo.compile.api.CommandBlock.accept(AstNode.scala:125)
 at org.nlogo.compile.api.DefaultAstVisitor.$anonfun$visitReporterApp$1(AstVisitor.scala:29)
 at org.nlogo.compile.api.DefaultAstVisitor.$anonfun$visitReporterApp$1$adapted(AstVisitor.scala:29)
 at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
 at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
 at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
 at org.nlogo.compile.api.DefaultAstVisitor.visitReporterApp(AstVisitor.scala:29)
 at org.nlogo.compile.middle.SourceTagger.super$visitReporterApp(SourceTagger.scala:39)
 at org.nlogo.compile.middle.SourceTagger.$anonfun$visitReporterApp$1(SourceTagger.scala:39)
 at org.nlogo.compile.middle.SourceTagger.captureInternalSources(SourceTagger.scala:21)
 at org.nlogo.compile.middle.SourceTagger.visitReporterApp(SourceTagger.scala:39)
 at org.nlogo.compile.api.ReporterApp.accept(AstNode.scala:199)
 at org.nlogo.compile.api.DefaultAstVisitor.$anonfun$visitStatement$1(AstVisitor.scala:31)
 at org.nlogo.compile.api.DefaultAstVisitor.$anonfun$visitStatement$1$adapted(AstVisitor.scala:31)
 at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
 at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
 at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
 at org.nlogo.compile.api.DefaultAstVisitor.visitStatement(AstVisitor.scala:31)
 at org.nlogo.compile.middle.SourceTagger.super$visitStatement(SourceTagger.scala:28)
 at org.nlogo.compile.middle.SourceTagger.$anonfun$visitStatement$1(SourceTagger.scala:28)
 at org.nlogo.compile.middle.SourceTagger.captureInternalSources(SourceTagger.scala:21)
 at org.nlogo.compile.middle.SourceTagger.visitStatement(SourceTagger.scala:28)
 at org.nlogo.compile.api.Statement.accept(AstNode.scala:98)
 at org.nlogo.compile.api.DefaultAstVisitor.$anonfun$visitStatements$1(AstVisitor.scala:32)
 at org.nlogo.compile.api.DefaultAstVisitor.$anonfun$visitStatements$1$adapted(AstVisitor.scala:32)
 at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
 at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
 at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
 at org.nlogo.compile.api.DefaultAstVisitor.visitStatements(AstVisitor.scala:32)
 at org.nlogo.compile.api.Statements.accept(AstNode.scala:74)
 at org.nlogo.compile.api.DefaultAstVisitor.visitProcedureDefinition(AstVisitor.scala:27)
 at org.nlogo.compile.api.ProcedureDefinition.accept(AstNode.scala:50)
 at org.nlogo.compile.middle.MiddleEnd$.$anonfun$middleEnd$3(MiddleEnd.scala:39)
 at org.nlogo.compile.middle.MiddleEnd$.$anonfun$middleEnd$3$adapted(MiddleEnd.scala:38)
 at scala.collection.immutable.List.foreach(List.scala:378)
 at org.nlogo.compile.middle.MiddleEnd$.middleEnd(MiddleEnd.scala:38)
 at org.nlogo.compile.CompilerMain$.compile(CompilerMain.scala:51)
 at org.nlogo.compile.Compiler.compileProgram(Compiler.scala:52)
 at org.nlogo.window.CompilerManager.compileProcedures(CompilerManager.scala:204)
 at org.nlogo.window.CompilerManager.compileAll(CompilerManager.scala:175)
 at org.nlogo.window.CompilerManager.handle(CompilerManager.scala:139)
 at org.nlogo.window.Events$CompileAllEvent.beHandledBy(Events.java:185)
 at org.nlogo.window.Event.doRaise(Event.java:198)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.app.codetab.CodeTab.compile(CodeTab.scala:147)
 at org.nlogo.app.codetab.CodeTab$CompileAction$.actionPerformed(CodeTab.scala:183)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
 at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
 at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
 at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
 at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
 at java.awt.Component.processMouseEvent(Component.java:6533)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
 at java.awt.Component.processEvent(Component.java:6298)
 at java.awt.Container.processEvent(Container.java:2236)
 at java.awt.Component.dispatchEventImpl(Component.java:4889)
 at java.awt.Container.dispatchEventImpl(Container.java:2294)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
 at java.awt.Container.dispatchEventImpl(Container.java:2280)
 at java.awt.Window.dispatchEventImpl(Window.java:2746)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.awt.EventQueue$4.run(EventQueue.java:729)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

NetLogo 6.0.1
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_121 (Oracle Corporation; 1.8.0_121-b13)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.1
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: GIS Network v13.0 (Model)

04:40:26.989 RemoveAllJobsEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
04:40:26.989 CompileAllEvent (org.nlogo.app.codetab.MainCodeTab) AWT-EventQueue-0
04:40:15.049 RemoveAllJobsEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
04:40:15.049 CompileAllEvent (org.nlogo.app.codetab.MainCodeTab) AWT-EventQueue-0
04:40:14.474 DirtyEvent (org.nlogo.app.codetab.MainCodeTab) AWT-EventQueue-0
04:40:14.474 DirtyEvent (org.nlogo.app.codetab.MainCodeTab) AWT-EventQueue-0
04:40:13.827 DirtyEvent (org.nlogo.app.codetab.MainCodeTab) AWT-EventQueue-0
04:40:13.827 DirtyEvent (org.nlogo.app.codetab.MainCodeTab) AWT-EventQueue-0
04:40:12.135 DirtyEvent (org.nlogo.app.codetab.MainCodeTab) AWT-EventQueue-0
04:40:12.135 DirtyEvent (org.nlogo.app.codetab.MainCodeTab) AWT-EventQueue-0

**Comment by mrerrormessage** [comment]
Could you post a copy of the model or email it to [mailto:bugs@ccl.northwestern.edu](our bugs email address)? It's easiest to find and fix a bug like this when we have a model which can generate the error reliably.

**Comment by mrerrormessage** [comment]
fixed in #1435
