### ISSUE TITLE
Bug: BehaviorSpace errors when running SDM experiments in parallel

### ISSUE THREAD

**Issue by justa9** [NetLogo/NetLogo#1423]
Hello.

Since I have not found if this is possible, I would suggest that running SDM via BehaviorSpace would be a useful feature.

Thank you.

**Comment by mrerrormessage** [comment]
Hi @justa9 ! Thanks for reporting. While investigating this issue, I've determined that it *is* possible to run SDM models through BehaviorSpace, but with the (rather severe) limitation that only 1 run can be done in parallel (which is a bug).

To run an SDM experiment in behaviorspace with only a single run done in parallel, open up the "Exponential Growth" library model and create a new behaviorspace experiment. Change the reporters from `count turtles` to `stock` and set a time limit with some number other than 0 (I used 10). Run the experiment, setting "Simultaneous runs in parallel" to 1. Click OK and you will see that the data table appears at the selected location with valid data.

The other side of this is, in fact, a bug. When setting up this experiment if Simultaneous runs in parallel is greater than 1, I get the following exception:

java.lang.ClassCastException: org.nlogo.sdm.gui.AggregateDrawing cannot be cast to org.nlogo.sdm.Model
 at scala.Option.foreach(Option.scala:257)
 at org.nlogo.sdm.AggregateManagerLite.load(AggregateManagerLite.scala:14)
 at org.nlogo.headless.HeadlessModelOpener.openFromModel(HeadlessModelOpener.scala:45)
 at org.nlogo.headless.HeadlessWorkspace.openModel(HeadlessWorkspace.scala:532)
 at org.nlogo.app.App$$anon$2.openCurrentModelIn(App.scala:175)
 at org.nlogo.lab.gui.Supervisor.$anonfun$start$1(Supervisor.scala:95)
 at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:156)
 at org.nlogo.lab.gui.Supervisor.start(Supervisor.scala:93)
 at org.nlogo.lab.gui.ManagerDialog.run(ManagerDialog.scala:100)
 at org.nlogo.lab.gui.ManagerDialog.$anonfun$runAction$1(ManagerDialog.scala:30)
 at org.nlogo.lab.gui.ManagerDialog$$anon$3.actionPerformed(ManagerDialog.scala:24)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
 at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
 at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
 at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
 at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
 at java.awt.Component.processMouseEvent(Component.java:6533)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
 at java.awt.Component.processEvent(Component.java:6298)
 at java.awt.Container.processEvent(Container.java:2236)
 at java.awt.Component.dispatchEventImpl(Component.java:4889)
 at java.awt.Container.dispatchEventImpl(Container.java:2294)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
 at java.awt.Container.dispatchEventImpl(Container.java:2280)
 at java.awt.Window.dispatchEventImpl(Window.java:2746)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.awt.EventQueue$4.run(EventQueue.java:729)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

NetLogo 6.0.1
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_121 (Oracle Corporation; 1.8.0_121-b13)
operating system: Mac OS X 10.12.5 (x86_64 processor)
Scala version 2.12.1
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Exponential Growth

02:09:18.442 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
02:09:18.442 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:09:18.147 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
02:09:18.147 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:09:17.942 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
02:09:17.942 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:09:17.741 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
02:09:17.741 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:09:17.541 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
02:09:17.541 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

**Comment by SethTisue** [comment]
yet another consequence of #105, I guess

**Comment by justa9** [comment]
@mrerrormessage Thank you very much for the clarifying answer. I can confirm that the experiment runs if one follows your instructions.

**Comment by SESmodeller** [comment]
Since I am having the same issue, can you circumvent this by running NetLogo headless? Never tried it before but would if it is promising.

**Comment by mrerrormessage** [comment]
@SESmodeller , what a great idea! You should be able to get around this by running headlessly. `netlogo-headless.sh` is included with the Linux version of NetLogo. We don't distribute a headless script with Mac OS, but you can write one using [the linux script](https://github.com/NetLogo/NetLogo/blob/hexy/dist/configuration/shared/linux/netlogo-headless.sh.mustache) as inspiration. Simply replace "{{{classpathJars}}}" with a ':'-separated list of all the jars included with the mac version (they're found in "/Applications/NetLogo 6.0.1/Java/").

**Comment by mrerrormessage** [comment]
Another consequence of the underlying problem causing this bug is that the preview commands editor errors when trying to edit preview commands for a system dynamics model.

**Comment by mrerrormessage** [comment]
Resolved in 6.0.3
