### ISSUE TITLE
Runtime error when trying to run a turtle anonymous reporter from a link command block

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/NetLogo#1437]
Running:
```
to test
  clear-all
  crt 2
  let f [ -> patch-here ]
  ask turtles [
    create-link-with one-of other turtles [
      show runresult f
    ]
  ]
end
```

Results in:

```
scala.MatchError: - (of class java.lang.Character)
 at org.nlogo.nvm.AnonymousProcedure.$anonfun$checkAgentClass$1(AnonymousProcedure.scala:33)
 at org.nlogo.nvm.AnonymousProcedure.$anonfun$checkAgentClass$1$adapted(AnonymousProcedure.scala:33)
 at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
 at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
 at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
 at scala.collection.immutable.StringOps.foreach(StringOps.scala:29)
 at scala.collection.TraversableLike.map(TraversableLike.scala:234)
 at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
 at scala.collection.immutable.StringOps.map(StringOps.scala:29)
 at org.nlogo.nvm.AnonymousProcedure.checkAgentClass(AnonymousProcedure.scala:33)
 at org.nlogo.nvm.AnonymousProcedure.checkAgentClass$(AnonymousProcedure.scala:26)
 at org.nlogo.nvm.AnonymousReporter.checkAgentClass(AnonymousProcedure.scala:74)
 at org.nlogo.nvm.AnonymousReporter.report(AnonymousProcedure.scala:96)
 at org.nlogo.nvm.AnonymousReporter.report(AnonymousProcedure.scala:93)
 at org.nlogo.prim.etc._runresult.report(_runresult.scala:43)
 at org.nlogo.prim.etc._show.perform(_show.scala:13)
 at org.nlogo.nvm.Context.runExclusive(Context.java:135)
 at org.nlogo.nvm.ExclusiveJob.run(ExclusiveJob.scala:39)
 at org.nlogo.nvm.Context.runExclusiveJob(Context.java:181)
 at org.nlogo.prim.etc.LinkCreationCommand.perform(linkcreation.scala:34)
 at org.nlogo.prim.etc.LinkCreationCommand.perform$(linkcreation.scala:25)
 at org.nlogo.prim.etc._createlinkwith.perform(linkcreation.scala:124)
 at org.nlogo.nvm.Context.runExclusive(Context.java:135)
 at org.nlogo.nvm.ExclusiveJob.run(ExclusiveJob.scala:39)
 at org.nlogo.nvm.Context.runExclusiveJob(Context.java:181)
 at org.nlogo.prim._asm_proceduretest_ask_3.perform(:1)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
 at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
 at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
 at scala.util.control.Exception$Catch.apply(Exception.scala:224)
 at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:66)

NetLogo 6.0.1
main: org.nlogo.app.AppFrame
thread: JobThread
Java HotSpot(TM) 64-Bit Server VM 1.8.0_121 (Oracle Corporation; 1.8.0_121-b13)
operating system: Linux 4.4.0-83-generic (amd64 processor)
Scala version 2.12.1
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Untitled

05:03:16.709 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
05:03:16.702 RuntimeErrorEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
05:03:16.701 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
05:03:16.701 TickStateChangeEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
05:03:16.701 OutputEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
05:03:16.697 AddJobEvent (org.nlogo.app.common.CommandLine) AWT-EventQueue-0
05:03:16.697 OutputEvent (org.nlogo.app.common.CommandLine) AWT-EventQueue-0
05:03:16.697 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
05:03:16.693 CompileMoreSourceEvent (org.nlogo.app.common.CommandLine) AWT-EventQueue-0
05:03:16.501 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
```

NetLogo is right to complain, but a proper error message is probably needed.

**Comment by nicolaspayette** [comment]
At the suggestion of @mrerrormessage, I tried it in the `hexy` branch (as opposed to 6.0.1), and we get a proper message over there. That was most likely a duplicate of #1389. In any case, it is now fixed.
