### ISSUE TITLE
Exporting world

### ISSUE THREAD

**Issue by Rbhui** [NetLogo/NetLogo#1486]
Hi,

While exporting world, I am getting the following error. Please suggest what I should do.
Thank you,
Rita

error (NullPointerException)
 while observer running EXPORT-WORLD
  called by Command Center

NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.lang.NullPointerException
 at org.nlogo.workspace.AbstractWorkspaceTraits$Exporting$$anonfun$exportPlotsToCSV$1.apply(AbstractWorkspaceScala.scala:120)
 at org.nlogo.workspace.AbstractWorkspaceTraits$Exporting$$anonfun$exportPlotsToCSV$1.apply(AbstractWorkspaceScala.scala:120)
 at scala.Option.map(Option.scala:133)
 at org.nlogo.workspace.AbstractWorkspaceTraits$Exporting$class.exportPlotsToCSV(AbstractWorkspaceScala.scala:120)
 at org.nlogo.workspace.AbstractWorkspaceScala.exportPlotsToCSV(AbstractWorkspaceScala.scala:19)
 at org.nlogo.workspace.AbstractWorkspaceTraits$Exporting$$anon$1.export(AbstractWorkspaceScala.scala:103)
 at org.nlogo.agent.AbstractExporter.export(AbstractExporter.scala:39)
 at org.nlogo.workspace.AbstractWorkspaceTraits$Exporting$class.exportWorld(AbstractWorkspaceScala.scala:105)
 at org.nlogo.workspace.AbstractWorkspaceScala.exportWorld(AbstractWorkspaceScala.scala:19)
 at org.nlogo.prim.etc._exportworld$1.run(_exportworld.java:27)
 at org.nlogo.window.ThreadUtils$$anonfun$waitFor$2.apply$mcV$sp(ThreadUtils.scala:29)
 at org.nlogo.window.ThreadUtils$$anon$3.run(ThreadUtils.scala:24)
 at org.nlogo.window.ThreadUtils$$anon$3.run(ThreadUtils.scala:23)
 at org.nlogo.window.ThreadUtils$$anon$2.run(ThreadUtils.scala:49)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

NetLogo 3D 5.3.1
main: org.nlogo.app.AppFrame
thread: JobThread
Java HotSpot(TM) 64-Bit Server VM 1.8.0_74 (Oracle Corporation; 1.8.0_74-b02)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.9.2
JOGL: 2.3.2
OpenGL graphics: AMD FirePro W4100 (FireGL V) Graphics Adapter
OpenGL version: 4.5.13397 Compatibility Profile Context FireGL 15.200.1045.0
OpenGL vendor: ATI Technologies Inc.
model: LTM2_2017_Aug25

11:43:12.753 RuntimeErrorEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:43:12.753 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
11:43:12.737 ExportWorldEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:42:31.025 AddJobEvent (org.nlogo.app.CommandLine) AWT-EventQueue-0
11:42:31.025 OutputEvent (org.nlogo.app.CommandLine) AWT-EventQueue-0
11:42:31.025 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
11:42:31.025 CompileMoreSourceEvent (org.nlogo.app.CommandLine) AWT-EventQueue-0
11:42:30.994 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:42:30.994 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:42:30.994 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0

**Comment by mrerrormessage** [comment]
To investigate this more thoroughly, can you please see whether this error also occurs in NetLogo 3D 6.0.2 (available from ccl.northwestern.edu/netlogo)?

It would also be helpful if you could provide a copy of your model. You can post a link to it here or if you would prefer not to share it publicly, please email bugs@ccl.northwestern.edu with a copy of the model attached and reference this issue in your email.
