### ISSUE TITLE
Netlogo error report while R-extension

### ISSUE THREAD

**Issue by seocody** [NetLogo/NetLogo#1508]
NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.lang.NoClassDefFoundError: org/rosuda/REngine/REngine
 at org.nlogo.extension.r.Entry.runOnce(Entry.java:154)
 at org.nlogo.workspace.ExtensionManager.importExtension(ExtensionManager.java:198)
 at org.nlogo.compiler.StructureParser.parseImport(StructureParser.scala:459)
 at org.nlogo.compiler.StructureParser.parse(StructureParser.scala:196)
 at org.nlogo.compiler.CompilerMain$.compile(CompilerMain.scala:25)
 at org.nlogo.compiler.Compiler$.compileProgram(Compiler.scala:28)
 at org.nlogo.window.CompilerManager.compileProcedures(CompilerManager.java:107)
 at org.nlogo.window.CompilerManager.compileAll(CompilerManager.java:87)
 at org.nlogo.window.CompilerManager.handle(CompilerManager.java:309)
 at org.nlogo.window.Events$CompileAllEvent.beHandledBy(Events.java:175)
 at org.nlogo.window.Event.doRaise(Event.java:198)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.app.ProceduresTab.recompile(ProceduresTab.scala:124)
 at org.nlogo.app.ProceduresTab.handle(ProceduresTab.scala:104)
 at org.nlogo.app.Events$SwitchedTabsEvent.beHandledBy(Events.java:42)
 at org.nlogo.window.Event.doRaise(Event.java:198)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.app.Tabs.stateChanged(Tabs.scala:45)
 at javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:416)
 at javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:270)
 at javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:132)
 at javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:67)
 at javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:616)
 at javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:591)
 at javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(BasicTabbedPaneUI.java:3647)
 at java.awt.Component.processMouseEvent(Component.java:6532)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
 at java.awt.Component.processEvent(Component.java:6300)
 at java.awt.Container.processEvent(Container.java:2236)
 at java.awt.Component.dispatchEventImpl(Component.java:4891)
 at java.awt.Container.dispatchEventImpl(Container.java:2294)
 at java.awt.Component.dispatchEvent(Component.java:4713)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4522)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
 at java.awt.Container.dispatchEventImpl(Container.java:2280)
 at java.awt.Window.dispatchEventImpl(Window.java:2750)
 at java.awt.Component.dispatchEvent(Component.java:4713)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.awt.EventQueue$4.run(EventQueue.java:729)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: org.rosuda.REngine.REngine
 at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
 at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
 ... 56 more

NetLogo 5.3.1
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_74 (Oracle Corporation; 1.8.0_74-b02)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Untitled

04:40:13.515 RemoveAllJobsEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
04:40:13.515 CompileAllEvent (org.nlogo.app.MainProceduresTab) AWT-EventQueue-0
04:40:13.515 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
04:40:13.446 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:40:13.241 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:40:13.039 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:40:12.837 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:40:12.636 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:40:12.434 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:40:12.232 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

**Comment by mrerrormessage** [comment]
Please try upgrading to NetLogo 6.0.2, which bundles the R extension. Documentation for the R extension under NetLogo 6.0.2 can be found [here](http://ccl.northwestern.edu/netlogo/docs/r.html). If this issue persists in NetLogo 6.0.2, please reopen (I'm closing for now).
