### ISSUE TITLE
Internal Error NetLogo v6.0.1

### ISSUE THREAD

**Issue by Zalsa** [NetLogo/NetLogo#1510]
**Hi,
I am facing a problem when a try to run my model.
When I check 'Mirror plots on clients' box in HubNet Control Center and add a new client, appears me this problem:**

java.util.NoSuchElementException: None.get
 at scala.None$.get(Option.scala:349)
 at scala.None$.get(Option.scala:347)
 at org.nlogo.hubnet.client.ClientPanel.$anonfun$updatePlot$1(ClientPanel.scala:73)
 at scala.collection.immutable.List.foreach(List.scala:378)
 at org.nlogo.hubnet.client.ClientPanel.updatePlot(ClientPanel.scala:70)
 at org.nlogo.hubnet.client.ClientPanel.$anonfun$handlePlotUpdate$1(ClientPanel.scala:59)
 at org.nlogo.hubnet.client.ClientPanel.$anonfun$handlePlotUpdate$1$adapted(ClientPanel.scala:56)
 at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
 at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
 at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:193)
 at org.nlogo.hubnet.client.ClientPanel.handlePlotUpdate(ClientPanel.scala:56)
 at org.nlogo.hubnet.client.ClientPanel.handleProtocolMessage(ClientPanel.scala:266)
 at org.nlogo.hubnet.client.ClientPanel.receiveData(ClientPanel.scala:420)
 at org.nlogo.hubnet.client.ClientPanel.processEvent(ClientPanel.scala:386)
 at java.awt.Component.dispatchEventImpl(Component.java:4889)
 at java.awt.Container.dispatchEventImpl(Container.java:2294)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.awt.EventQueue$4.run(EventQueue.java:729)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

NetLogo 6.0.1
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_121 (Oracle Corporation; 1.8.0_121-b13)
operating system: Windows 8.1 6.3 (amd64 processor)
Scala version 2.12.1
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Oligopolios (PRUEBAAAA) v6.1

01:10:28.409 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:10:28.409 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:10:28.408 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:10:28.408 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:10:28.407 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:10:28.407 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:10:28.407 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
01:10:28.406 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:10:28.406 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
01:10:28.379 AddSliderConstraintEvent (org.nlogo.window.SliderWidget) AWT-EventQueue-0

**Also if I don´t check that box and try to run my model again, appears me this error. I suppose that both errors are related.**

java.util.NoSuchElementException: None.get
 at scala.None$.get(Option.scala:349)
 at scala.None$.get(Option.scala:347)
 at org.nlogo.hubnet.client.ClientPanel.handlePlotControlMessage(ClientPanel.scala:172)
 at org.nlogo.hubnet.client.ClientPanel.handleProtocolMessage(ClientPanel.scala:265)
 at org.nlogo.hubnet.client.ClientPanel.receiveData(ClientPanel.scala:420)
 at org.nlogo.hubnet.client.ClientPanel.processEvent(ClientPanel.scala:386)
 at java.awt.Component.dispatchEventImpl(Component.java:4889)
 at java.awt.Container.dispatchEventImpl(Container.java:2294)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.awt.EventQueue$4.run(EventQueue.java:729)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

NetLogo 6.0.1
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_121 (Oracle Corporation; 1.8.0_121-b13)
operating system: Windows 8.1 6.3 (amd64 processor)
Scala version 2.12.1
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Modelo competencia en precios

01:51:14.384 AddJobEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
01:51:14.358 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
01:51:14.358 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:51:14.358 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:51:14.358 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:51:14.358 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:51:14.358 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:51:14.358 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:51:14.358 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:51:14.358 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

**Thank you in advance**

**Comment by mrerrormessage** [comment]
Could you post a link to one or both of these models? If you would prefer to keep them private, you can also email them to bugs@ccl.northwestern.edu . If you email, please reference this issue in your email.

**Comment by Zalsa** [comment]
Ok, I will send you my model by email. Thanks!
