### ISSUE TITLE
Can´t run Behavior Space in NetLogo -> Help plz! 

### ISSUE THREAD

**Issue by kamisasvw** [NetLogo/NetLogo#1511]
When pressed RUN, this error appears:

Expected command. at position 33 in 
 at org.nlogo.core.Fail$.exception(Fail.scala:27)
 at org.nlogo.core.Fail$.exception(Fail.scala:25)
 at org.nlogo.core.Fail$.exception(Fail.scala:23)
 at org.nlogo.parse.ExpressionParser$.parseStatement(ExpressionParser.scala:75)
 at org.nlogo.parse.ExpressionParser$.$anonfun$apply$1(ExpressionParser.scala:30)
 at org.nlogo.parse.ExpressionParser$.parseStatements(ExpressionParser.scala:42)
 at org.nlogo.parse.ExpressionParser$.apply(ExpressionParser.scala:30)
 at org.nlogo.parse.NetLogoParser.parseProcedure(NetLogoParser.scala:45)
 at org.nlogo.parse.NetLogoParser.parseProcedure$(NetLogoParser.scala:29)
 at org.nlogo.parse.FrontEnd$.parseProcedure(FrontEnd.scala:10)
 at org.nlogo.parse.NetLogoParser.$anonfun$basicParse$1(NetLogoParser.scala:25)
 at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
 at scala.collection.Iterator.foreach(Iterator.scala:929)
 at scala.collection.Iterator.foreach$(Iterator.scala:929)
 at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
 at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:210)
 at scala.collection.TraversableLike.map(TraversableLike.scala:234)
 at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
 at scala.collection.AbstractTraversable.map(Traversable.scala:104)
 at org.nlogo.parse.NetLogoParser.basicParse(NetLogoParser.scala:25)
 at org.nlogo.parse.NetLogoParser.basicParse$(NetLogoParser.scala:15)
 at org.nlogo.parse.FrontEnd$.basicParse(FrontEnd.scala:10)
 at org.nlogo.parse.FrontEndMain.frontEnd(FrontEnd.scala:26)
 at org.nlogo.parse.FrontEndMain.frontEnd$(FrontEnd.scala:25)
 at org.nlogo.parse.FrontEnd$.frontEnd(FrontEnd.scala:10)
 at org.nlogo.compile.CompilerMain$.compile(CompilerMain.scala:42)
 at org.nlogo.compile.Compiler.compileMoreCode(Compiler.scala:78)
 at org.nlogo.compile.Compiler.compileMoreCode(Compiler.scala:91)
 at org.nlogo.workspace.Evaluator.invokeCompiler(Evaluator.scala:158)
 at org.nlogo.workspace.Evaluator.makeCommandThunk(Evaluator.scala:110)
 at org.nlogo.workspace.Evaluating.makeCommandThunk(Evaluating.scala:25)
 at org.nlogo.workspace.Evaluating.makeCommandThunk$(Evaluating.scala:23)
 at org.nlogo.workspace.AbstractWorkspaceScala.makeCommandThunk(AbstractWorkspaceScala.scala:24)
 at org.nlogo.plot.PlotManager.compile$1(PlotManager.scala:86)
 at org.nlogo.plot.PlotManager.$anonfun$compilePlot$4(PlotManager.scala:101)
 at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:739)
 at scala.collection.immutable.List.foreach(List.scala:389)
 at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:738)
 at org.nlogo.plot.PlotManager.compilePlot(PlotManager.scala:100)
 at org.nlogo.plot.PlotManager.$anonfun$compileAllPlots$1(PlotManager.scala:81)
 at scala.collection.immutable.List.flatMap(List.scala:335)
 at org.nlogo.plot.PlotManager.compileAllPlots(PlotManager.scala:81)
 at org.nlogo.headless.HeadlessModelOpener.finish(HeadlessModelOpener.scala:89)
 at org.nlogo.headless.HeadlessModelOpener.openFromModel(HeadlessModelOpener.scala:73)
 at org.nlogo.headless.HeadlessWorkspace.openModel(HeadlessWorkspace.scala:528)
 at org.nlogo.app.App$$anon$2.openCurrentModelIn(App.scala:172)
 at org.nlogo.lab.gui.Supervisor.$anonfun$start$1(Supervisor.scala:95)
 at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:156)
 at org.nlogo.lab.gui.Supervisor.start(Supervisor.scala:93)
 at org.nlogo.lab.gui.ManagerDialog.run(ManagerDialog.scala:100)
 at org.nlogo.lab.gui.ManagerDialog.$anonfun$runAction$1(ManagerDialog.scala:30)
 at org.nlogo.lab.gui.ManagerDialog$$anon$3.actionPerformed(ManagerDialog.scala:24)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
 at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
 at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
 at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
 at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
 at java.awt.Component.processMouseEvent(Component.java:6533)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
 at java.awt.Component.processEvent(Component.java:6298)
 at java.awt.Container.processEvent(Container.java:2236)
 at java.awt.Component.dispatchEventImpl(Component.java:4889)
 at java.awt.Container.dispatchEventImpl(Container.java:2294)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
 at java.awt.Container.dispatchEventImpl(Container.java:2280)
 at java.awt.Window.dispatchEventImpl(Window.java:2746)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.awt.EventQueue$4.run(EventQueue.java:729)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

NetLogo 6.0.2
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_141 (Oracle Corporation; 1.8.0_141-b15)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: 1trab_nova_versao_comentado_v5

12:59:16.740 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
12:59:16.740 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
12:59:16.740 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
12:59:16.740 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
12:59:16.740 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
12:59:16.740 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
12:59:16.740 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
12:59:16.740 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
12:59:16.740 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
12:59:16.740 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

**Comment by SethTisue** [comment]
#1087, #425  (should one of the two be closed, too?)
