### ISSUE TITLE
opening code gives an error

### ISSUE THREAD

**Issue by alonsela2015** [NetLogo/NetLogo#1514]
when opening a model, I receive this err.

java.lang.NoSuchMethodError: org.nlogo.core.Syntax$.commandSyntax(Lscala/collection/immutable/List;Lscala/Option;Lscala/Option;Ljava/lang/String;Lscala/Option;Z)Lorg/nlogo/core/Syntax;
 at nicolaspayette.dist.PlotPoints.getSyntax(DistExtension.scala:108)
 at org.nlogo.parse.ExtensionPrimitiveHandler.wrap(NameHandlers.scala:79)
 at org.nlogo.parse.ExtensionPrimitiveHandler.apply(NameHandlers.scala:73)
 at org.nlogo.parse.ExtensionPrimitiveHandler.apply(NameHandlers.scala:56)
 at org.nlogo.parse.Namer.$anonfun$processOne$1(Namer.scala:64)
 at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
 at scala.collection.immutable.List.foreach(List.scala:378)
 at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
 at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
 at scala.collection.immutable.List.flatMap(List.scala:341)
 at org.nlogo.parse.Namer.processOne(Namer.scala:64)
 at org.nlogo.parse.Namer.transform(Namer.scala:49)
 at org.nlogo.parse.Namer.transform(Namer.scala:21)
 at org.nlogo.parse.SimpleTransformIterator.next(TransformableTokenStream.scala:20)
 at org.nlogo.parse.SimpleTransformIterator.next(TransformableTokenStream.scala:13)
 at scala.collection.Iterator$$anon$1.next(Iterator.scala:1081)
 at org.nlogo.parse.ExpressionParser$.collect$1(ExpressionParser.scala:536)
 at org.nlogo.parse.ExpressionParser$.delayBlock(ExpressionParser.scala:548)
 at org.nlogo.parse.ExpressionParser$.parseExpressionInternal(ExpressionParser.scala:367)
 at org.nlogo.parse.ExpressionParser$.parseArgExpression(ExpressionParser.scala:231)
 at org.nlogo.parse.ExpressionParser$.$anonfun$parseArguments$1(ExpressionParser.scala:167)
 at org.nlogo.parse.ExpressionParser$.$anonfun$parseArguments$1$adapted(ExpressionParser.scala:166)
 at scala.collection.immutable.Range.foreach(Range.scala:156)
 at org.nlogo.parse.ExpressionParser$.parseArguments(ExpressionParser.scala:166)
 at org.nlogo.parse.ExpressionParser$.parsePotentiallyVariadicArgumentList(ExpressionParser.scala:89)
 at org.nlogo.parse.ExpressionParser$.parseStatement(ExpressionParser.scala:70)
 at org.nlogo.parse.ExpressionParser$.$anonfun$apply$1(ExpressionParser.scala:31)
 at org.nlogo.parse.ExpressionParser$.parseStatements(ExpressionParser.scala:43)
 at org.nlogo.parse.ExpressionParser$.apply(ExpressionParser.scala:31)
 at org.nlogo.parse.NetLogoParser.parseProcedure(NetLogoParser.scala:45)
 at org.nlogo.parse.NetLogoParser.parseProcedure$(NetLogoParser.scala:29)
 at org.nlogo.parse.FrontEnd$.parseProcedure(FrontEnd.scala:10)
 at org.nlogo.parse.NetLogoParser.$anonfun$basicParse$1(NetLogoParser.scala:25)
 at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
 at scala.collection.Iterator.foreach(Iterator.scala:929)
 at scala.collection.Iterator.foreach$(Iterator.scala:929)
 at scala.collection.AbstractIterator.foreach(Iterator.scala:1406)
 at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:210)
 at scala.collection.TraversableLike.map(TraversableLike.scala:234)
 at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
 at scala.collection.AbstractTraversable.map(Traversable.scala:104)
 at org.nlogo.parse.NetLogoParser.basicParse(NetLogoParser.scala:25)
 at org.nlogo.parse.NetLogoParser.basicParse$(NetLogoParser.scala:15)
 at org.nlogo.parse.FrontEnd$.basicParse(FrontEnd.scala:10)
 at org.nlogo.parse.FrontEndMain.frontEnd(FrontEnd.scala:27)
 at org.nlogo.parse.FrontEndMain.frontEnd$(FrontEnd.scala:25)
 at org.nlogo.parse.FrontEnd$.frontEnd(FrontEnd.scala:10)
 at org.nlogo.compile.CompilerMain$.compile(CompilerMain.scala:43)
 at org.nlogo.compile.Compiler.compileProgram(Compiler.scala:52)
 at org.nlogo.window.CompilerManager.compileProcedures(CompilerManager.scala:204)
 at org.nlogo.window.CompilerManager.compileAll(CompilerManager.scala:175)
 at org.nlogo.window.CompilerManager.handle(CompilerManager.scala:139)
 at org.nlogo.window.Events$CompileAllEvent.beHandledBy(Events.java:185)
 at org.nlogo.window.Event.doRaise(Event.java:198)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.app.codetab.CodeTab.compile(CodeTab.scala:147)
 at org.nlogo.app.codetab.CodeTab$CompileAction$.actionPerformed(CodeTab.scala:183)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
 at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
 at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
 at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
 at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
 at java.awt.Component.processMouseEvent(Component.java:6533)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
 at java.awt.Component.processEvent(Component.java:6298)
 at java.awt.Container.processEvent(Container.java:2236)
 at java.awt.Component.dispatchEventImpl(Component.java:4889)
 at java.awt.Container.dispatchEventImpl(Container.java:2294)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
 at java.awt.Container.dispatchEventImpl(Container.java:2280)
 at java.awt.Window.dispatchEventImpl(Window.java:2746)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.awt.EventQueue$4.run(EventQueue.java:729)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

NetLogo 6.0.1
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_121 (Oracle Corporation; 1.8.0_121-b13)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.1
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: .percolation3.10.17_countPatch.tmp

12:45:58.568 RemoveAllJobsEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
12:45:58.568 CompileAllEvent (org.nlogo.app.codetab.MainCodeTab) AWT-EventQueue-0
12:43:07.114 DirtyEvent (org.nlogo.app.codetab.MainCodeTab) AWT-EventQueue-0
12:43:07.114 DirtyEvent (org.nlogo.app.codetab.MainCodeTab) AWT-EventQueue-0
12:43:07.114 DirtyEvent (org.nlogo.app.codetab.MainCodeTab) AWT-EventQueue-0
12:43:07.114 DirtyEvent (org.nlogo.app.codetab.MainCodeTab) AWT-EventQueue-0
12:43:07.112 DirtyEvent (org.nlogo.app.codetab.MainCodeTab) AWT-EventQueue-0
12:43:07.112 DirtyEvent (org.nlogo.app.codetab.MainCodeTab) AWT-EventQueue-0
12:43:05.643 DirtyEvent (org.nlogo.app.codetab.MainCodeTab) AWT-EventQueue-0
12:43:05.643 DirtyEvent (org.nlogo.app.codetab.MainCodeTab) AWT-EventQueue-0

**Comment by SethTisue** [comment]
attn @nicolaspayette

**Comment by SethTisue** [comment]
it looks like you're trying to use a NetLogo 5 extension on NetLogo 6. did a warning dialog appear?

**Comment by nicolaspayette** [comment]
Last version of the extension that I published was compiled against 6.0-BETA1. Things have changed since then, so that might very well be the reason. I'm going to close the present issue, but I have opened an issue on the extension's repo (https://github.com/nicolaspayette/DistExtension/issues/1). @alonsela2015, you can track it over there. And thanks for reporting!
