### ISSUE TITLE
Internal Error: NetLogo unable to supply more details...

### ISSUE THREAD

**Issue by clothedinsun** [NetLogo/NetLogo#1518]
Any suggestions as to what the problem is with the below would be greatly appreciated.

java.lang.NoClassDefFoundError: org/nlogo/app/InterfaceToolBar$$anonfun$2
 at org.nlogo.app.InterfaceToolBar.handle(InterfaceToolBar.scala:73)
 at org.nlogo.window.Events$EditWidgetEvent.beHandledBy(Events.java:240)
 at org.nlogo.window.Event.doRaise(Event.java:198)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.window.ViewUpdatePanel$SettingsButton$1.actionPerformed(ViewUpdatePanel.java:113)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1995)
 at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2318)
 at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:387)
 at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:242)
 at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:236)
 at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:272)
 at java.awt.Component.processMouseEvent(Component.java:6297)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3275)
 at java.awt.Component.processEvent(Component.java:6062)
 at java.awt.Container.processEvent(Container.java:2039)
 at java.awt.Component.dispatchEventImpl(Component.java:4660)
 at java.awt.Container.dispatchEventImpl(Container.java:2097)
 at java.awt.Component.dispatchEvent(Component.java:4488)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4575)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4236)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4166)
 at java.awt.Container.dispatchEventImpl(Container.java:2083)
 at java.awt.Window.dispatchEventImpl(Window.java:2489)
 at java.awt.Component.dispatchEvent(Component.java:4488)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:674)
 at java.awt.EventQueue.access$400(EventQueue.java:81)
 at java.awt.EventQueue$2.run(EventQueue.java:633)
 at java.awt.EventQueue$2.run(EventQueue.java:631)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:98)
 at java.awt.EventQueue$3.run(EventQueue.java:647)
 at java.awt.EventQueue$3.run(EventQueue.java:645)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:644)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

NetLogo 5.2.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) Server VM 1.6.0_45 (Sun Microsystems Inc.; 1.6.0_45-b06)
operating system: Windows 7 6.1 (x86 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: JASSS_ENHANCE.flood_Oxford

12:47:31.591 EditWidgetEvent (org.nlogo.window.ViewUpdatePanel$SettingsButton (javax.swing.JButton)) AWT-EventQueue-0
12:47:31.511 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
12:47:31.511 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
12:47:31.511 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
12:47:31.511 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
12:47:31.511 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
12:47:31.511 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
12:47:31.511 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
12:47:31.511 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
12:47:31.511 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0

**Comment by mrerrormessage** [comment]
Hello,

I'm not certain what the problem above is being caused by, but here are a few suggestions:

- NetLogo 5.2.0 is an older unsupported version of NetLogo.  Unless you're using a large number of extensions compiled for NetLogo 5, we recommend upgrading to [NetLogo 6.0.2](http://ccl.northwestern.edu/netlogo/6.0.2/). If you can't upgrade all the way to 6.0.2, upgrading to [NetLogo 5.3.1](https://ccl.northwestern.edu/netlogo/5.3.1/) will offer several bugfixes and enhancements over 6.0.2.
- In rare circumstances, errors like this are caused by models which use a large amount of memory. The NetLogo User Manual [includes instructions](http://ccl.northwestern.edu/netlogo/docs/faq.html#howbig) (valid for NetLogo 5.3.1 and 6.0.2) on how to adjust the amount of memory available to NetLogo. 

I'll leave this issue open for the next week or two; please post if you are still encountering this issue after upgrading to 5.3.1 or 6.0.2.

**Comment by SethTisue** [comment]
> NetLogo 5.3.1 will offer several bugfixes and enhancements over 6.0.2

over 5.2.0
