### ISSUE TITLE
NetLogo batch run fails on Windows Cluster

### ISSUE THREAD

**Issue by gunnardressler** [NetLogo/NetLogo#1527]
I've been using NetLogo for several years and have used it often to run large behavior space simulations on a Windows Compute Cluster, using the command line call, i.e. something like

netlogo-headless.bat --threads 12 --model simple_model.nlogo --experiment experiment_1 --table table_experiment_1.csv

This has worked well with NetLogo 5, but since NetLogo 6 I'm always getting a strange error when I try to run a simulation:

`Exception in thread "main" java.lang.IllegalArgumentException: URI has an authority component
	at java.io.File.<init>(File.java:423)
	at scala.io.Source$.fromURI(Source.scala:121)
	at org.nlogo.fileformat.AbstractNLogoFormat.$anonfun$sections$1(NLogoFormat.scala:37)
	at scala.util.Try$.apply(Try.scala:209)
	at org.nlogo.fileformat.AbstractNLogoFormat.sections(NLogoFormat.scala:36)
	at org.nlogo.fileformat.AbstractNLogoFormat.sections$(NLogoFormat.scala:34)
	at org.nlogo.fileformat.NLogoFormat.sections(NLogoFormat.scala:16)
	at org.nlogo.api.ModelFormat.load(ModelFormat.scala:53)
	at org.nlogo.api.ModelFormat.load$(ModelFormat.scala:51)
	at org.nlogo.fileformat.NLogoFormat.load(NLogoFormat.scala:16)
	at org.nlogo.api.FormatterPair.load(ModelLoader.scala:26)
	at org.nlogo.api.ModelLoader.readModel(ModelLoader.scala:60)
	at org.nlogo.api.ModelLoader.readModel$(ModelLoader.scala:57)
	at org.nlogo.api.ConfigurableModelLoader.readModel(ModelLoader.scala:90)
	at org.nlogo.headless.HeadlessWorkspace.open(HeadlessWorkspace.scala:491)
	at org.nlogo.headless.Main$.newWorkspace$1(Main.scala:18)
	at org.nlogo.headless.Main$.runExperiment(Main.scala:21)
	at org.nlogo.headless.Main$.$anonfun$main$1(Main.scala:12)
	at org.nlogo.headless.Main$.$anonfun$main$1$adapted(Main.scala:12)
	at scala.Option.foreach(Option.scala:257)
	at org.nlogo.headless.Main$.main(Main.scala:12)
	at org.nlogo.headless.Main.main(Main.scala)
`

I have no idea if this error is caused by NetLogo or by the Java Runtime. 

After it failed with my real model, I also tried it with a very simple dummy model and behavior space experiment, but the error prevails, so I'm pretty sure it's not specific to the model. However, what I did notice is that the error does not occur when I run the model locally from the command line, using the same command line call - only on the Windows HPC Cluster. 

I'm running NetLogo 6.0.2, but had the same error also with versions 6.0 and 6.0.1. I've attached the minimum model that I tried to run (I renamed it from .nlogo to .txt, as .nlogo files are not allowed as attachments), as well as a system information summary of the cluster. We are using Microsoft HPC Pack 2012 R2 as cluster manager. 

Thanks for any help or advide on this!

[simple_model.txt](https://github.com/NetLogo/NetLogo/files/1539273/simple_model.txt)

[ClusterSystemInformation.txt](https://github.com/NetLogo/NetLogo/files/1539262/ClusterSystemInformation.txt)

**Comment by daimpi** [comment]
Might this have something to do with using a UNC path? Here is someone talking about a similar error message (for a different program) which doesn't occur on a local machine: https://stackoverflow.com/questions/2366270/what-does-uri-has-an-authority-component-mean
see also this answer: https://stackoverflow.com/a/30725096/7010420

**Comment by mrerrormessage** [comment]
Thanks for letting us know about this. I'm going to try to do a bit more research and figure out exactly what's going wrong here, but let me give you some information that I think will be helpful:

* This is not related to the particular model, it's happening because NetLogo "can't find" the model to load.
* Your argument usage seems pretty much correct, with the possible exception of the model path (discussed below).
* You don't list the Java version that you're using, but I assume it's a relatively recent version of Java 8. If you're using Java 9, please let me know as that's another *possible* (although unlikely) source of error. If you're using Java 7 or older, you should upgrade to Java 8 and see if that fixes the problem.
* Is the file here loaded from a network share? Some googling indicates that this error sometimes occurs when that is the case.

I believe you may be able to fix this problem by providing an absolute path (`C:\Path\To\simple_model.nlogo`) as opposed to a relative path (`simple_model.nlogo`). Please let me know whether that resolves this problem for you.

**Comment by gunnardressler** [comment]
Thank you for your comments so far. 

Yes, I'm trying to load the model from a network share, and I can't avoid doing this as the compute cluster is distributed over several nodes and resource allocation is handled by the cluster manager, so I cannot use a local path to load the model. I've used the exact same setup with NetLogo 5.2/5.3 which never caused an error. 

However, as I said above, the error does not occur when I use the same batch call in a local terminal window, also using a relative path - so I guess you are right that the problem lies with the network path. 

The cluster runs Java 8, this is the exact version info:
`Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)`

**Comment by daimpi** [comment]
maybe this is related to #722 ?
