### ISSUE TITLE
Internal Error.

### ISSUE THREAD

**Issue by Achaean** [NetLogo/NetLogo#1568]
Going Help -> About and clicking the web link, returns this error (on Debian Jessie x64 KDE):

```
java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
 at java.awt.Desktop.checkActionSupport(Desktop.java:225)
 at java.awt.Desktop.browse(Desktop.java:381)
 at org.nlogo.swing.BrowserLauncher$.$anonfun$openURI$1(BrowserLauncher.scala:26)
 at org.nlogo.swing.BrowserLauncher$.$anonfun$openURI$1$adapted(BrowserLauncher.scala:26)
 at scala.Option.map(Option.scala:146)
 at org.nlogo.swing.BrowserLauncher$.openURI(BrowserLauncher.scala:26)
 at org.nlogo.app.AboutWindow$$anon$4$$anon$8.mouseClicked(AboutWindow.scala:57)
 at java.awt.Component.processMouseEvent(Component.java:6536)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
 at java.awt.Component.processEvent(Component.java:6298)
 at java.awt.Container.processEvent(Container.java:2236)
 at java.awt.Component.dispatchEventImpl(Component.java:4889)
 at java.awt.Container.dispatchEventImpl(Container.java:2294)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4534)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
 at java.awt.Container.dispatchEventImpl(Container.java:2280)
 at java.awt.Window.dispatchEventImpl(Window.java:2746)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.awt.EventQueue$4.run(EventQueue.java:729)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

NetLogo 6.0.2
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_141 (Oracle Corporation; 1.8.0_141-b15)
operating system: Linux 3.16.0-5-amd64 (amd64 processor)
Scala version 2.12.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Untitled

04:41:57.570 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:41:57.369 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:41:57.168 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:41:56.967 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:41:56.767 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:41:56.566 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:41:56.366 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:41:56.165 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:41:55.964 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:41:55.763 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

```

**Comment by mrerrormessage** [comment]
Thanks for reporting! I'm updating the title to reflect what the expected fix is. This would be a great first issue for someone. The fix is changing [this `catch`-block](https://github.com/NetLogo/NetLogo/blob/hexy/netlogo-gui/src/main/swing/BrowserLauncher.scala#L29) to properly handle `UnsupportedOperationException`.

**Comment by amro-ashmeik** [comment]
@mrerrormessage Hi, I'd like to implement this fix! What message should be displayed in the dialogue box when the exception is caught?

**Comment by mrerrormessage** [comment]
@amro-ashmeik , the error displayed should match the text of the exception for `browserNotFound`. Feel free to move that text out into a separate `val` which is used in `browserNotFound` and when catching the exception. Thanks!
