### ISSUE TITLE
Error: “Can't find extension: stats” (Netlogo 5.3.1 + stats extension 1.4.0 )

### ISSUE THREAD

**Issue by Noris2H** [NetLogo/NetLogo#1631]
I am new to Netlogo and trying to run a model with Netlogo ver 5.3.1 and stats extension 1.4.0. But Netlogo won't recognise the extension and keeps saying "can't find extension: stats" (detailed error msg below). Other people seem to run the model without any problem with the same settings.

Netlogo programme folder is in Application folder on my mac. I have put stats folder in extension folder under Netlogo folder. I've tried installing it several times on my mac and on another mac to no avail. Any advice would be very much appreciated. Thank you.

========
NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.lang.NullPointerException
 at sun.java2d.pipe.AlphaColorPipe.renderPathTile(AlphaColorPipe.java:55)
 at sun.java2d.pipe.AAShapePipe.renderTiles(AAShapePipe.java:201)
 at sun.java2d.pipe.AAShapePipe.fillParallelogram(AAShapePipe.java:102)
 at sun.java2d.pipe.PixelToParallelogramConverter.fillRectangle(PixelToParallelogramConverter.java:322)
 at sun.java2d.pipe.PixelToParallelogramConverter.fillRect(PixelToParallelogramConverter.java:115)
 at sun.java2d.pipe.ValidatePipe.fillRect(ValidatePipe.java:76)
 at sun.java2d.SunGraphics2D.fillRect(SunGraphics2D.java:2423)
 at ch.randelshofer.quaqua.border.ImageBevelBorder.paintBorder(ImageBevelBorder.java:236)
 at ch.randelshofer.quaqua.panther.QuaquaPantherScrollTabbedPaneUI.paintContentBorder(QuaquaPantherScrollTabbedPaneUI.java:491)
 at ch.randelshofer.quaqua.panther.QuaquaPantherScrollTabbedPaneUI.paint(QuaquaPantherScrollTabbedPaneUI.java:416)
 at ch.randelshofer.quaqua.panther.QuaquaPantherTabbedPaneUI.paint(QuaquaPantherTabbedPaneUI.java:132)
 at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
 at javax.swing.JComponent.paintComponent(JComponent.java:780)
 at javax.swing.JComponent.paint(JComponent.java:1056)
 at javax.swing.JComponent.paintChildren(JComponent.java:889)
 at javax.swing.JComponent.paint(JComponent.java:1065)
 at javax.swing.JComponent.paintChildren(JComponent.java:889)
 at javax.swing.JComponent.paint(JComponent.java:1065)
 at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
 at javax.swing.JComponent.paintChildren(JComponent.java:889)
 at javax.swing.JComponent.paintToOffscreen(JComponent.java:5217)
 at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
 at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
 at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
 at javax.swing.JComponent.paint(JComponent.java:1042)
 at java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
 at sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:79)
 at sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:116)
 at java.awt.Container.paint(Container.java:1975)
 at java.awt.Window.paint(Window.java:3912)
 at javax.swing.RepaintManager$4.run(RepaintManager.java:842)
 at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
 at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
 at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
 at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
 at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
 at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
 at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
 at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
 at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
 at java.awt.Dialog.show(Dialog.java:1084)
 at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:869)
 at javax.swing.JOptionPane.showConfirmDialog(JOptionPane.java:795)
 at javax.swing.JOptionPane.showConfirmDialog(JOptionPane.java:757)
 at javax.swing.JOptionPane.showConfirmDialog(JOptionPane.java:718)
 at org.nlogo.app.ExtensionAssistant.confirmOpen(ExtensionAssistant.scala:26)
 at org.nlogo.app.ExtensionAssistant.handle(ExtensionAssistant.scala:21)
 at org.nlogo.window.Events$CompiledEvent.beHandledBy(Events.java:213)
 at org.nlogo.window.Event.doRaise(Event.java:198)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.window.CompilerManager.compileProcedures(CompilerManager.java:136)
 at org.nlogo.window.CompilerManager.compileAll(CompilerManager.java:87)
 at org.nlogo.window.CompilerManager.handle(CompilerManager.java:309)
 at org.nlogo.window.Events$CompileAllEvent.beHandledBy(Events.java:175)
 at org.nlogo.window.Event.doRaise(Event.java:198)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.app.ProceduresTab$CompileAction.actionPerformed(ProceduresTab.scala:60)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
 at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
 at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
 at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
 at ch.randelshofer.quaqua.QuaquaButtonListener.mouseReleased(QuaquaButtonListener.java:112)
 at java.awt.Component.processMouseEvent(Component.java:6535)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
 at java.awt.Component.processEvent(Component.java:6300)
 at java.awt.Container.processEvent(Container.java:2236)
 at java.awt.Component.dispatchEventImpl(Component.java:4891)
 at java.awt.Container.dispatchEventImpl(Container.java:2294)
 at java.awt.Component.dispatchEvent(Component.java:4713)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
 at java.awt.Container.dispatchEventImpl(Container.java:2280)
 at java.awt.Window.dispatchEventImpl(Window.java:2750)
 at java.awt.Component.dispatchEvent(Component.java:4713)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.awt.EventQueue$4.run(EventQueue.java:729)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

NetLogo 5.3.1
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_74 (Oracle Corporation; 1.8.0_74-b02)
operating system: Mac OS X 10.12.6 (x86_64 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: EpistemicNetworkV031-4-separates-init-rel

06:13:51.341 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
06:13:51.341 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
06:13:51.341 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
06:13:51.341 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
06:13:51.341 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
06:13:51.341 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
06:13:51.341 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
06:13:51.341 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
06:13:51.341 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
06:13:51.341 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0

**Comment by LaCuneta** [comment]
Sorry you encountered this issue.  Stats 1.4.0 should work with NetLogo 5.3.1, as you said.  A few questions:

- Can you confirm the path of the stats folder is `/Applications/NetLogo 5.3.1/extensions/stats`, and that you see the `stats.jar` file in that folder (along with some other files)?  Also, check that the `StatsExtension-v1.4.0.pdf` is there, just to confirm you got the right version.
- Can you confirm NetLogo 5.3.1 works for you otherwise with a different model or with the included sample stats model (/Applications/NetLogo 5.3.1/extensions/stats/StatsExample.nlogo`)?

**Comment by Noris2H** [comment]
Thanks. I've just doublechecked and can confirm all (screen grabs attached). Could it be something to do with the environment variables? 

![screen shot 2018-05-24 at 15 51 54](https://user-images.githubusercontent.com/39538573/40493622-016aabac-5f6b-11e8-8ebd-790b03ea1c91.png)
![screen shot 2018-05-24 at 15 52 22](https://user-images.githubusercontent.com/39538573/40493623-0187d1be-5f6b-11e8-9b9a-8ef1cd6fc300.png)

**Comment by LaCuneta** [comment]
Unfortunately I haven't been able to think of or dig up anything else that might be causing this.  Are you able to download NetLogo 6.0.3 and update the model to run using it and Stats 2.0.0?  For most models opening them in 6.0.3 is enough to auto-convert, but you can checkout our [transition guide](https://ccl.northwestern.edu/netlogo/docs/transition.html) for more information.

**Comment by Noris2H** [comment]
Actually I've just discovered by checking all folder info across in detail that, unlike the rest, the stats folder had "hide extension" ticked under name and extension of folder info. I don't know how and why but the issue is resolved. Thank you so much for your help!

**Comment by LaCuneta** [comment]
Glad you got it fixed!
