### ISSUE TITLE
Internal error - NetLogo is unable to supply you with more details about this error.

### ISSUE THREAD

**Issue by nwijermans** [NetLogo/NetLogo#1681]
Hi!

I got an internal error when running a BehaviourSpace experiment:  "NetLogo is unable to supply you with more details about this error”. See below for the content of the error window.

The strange thing is that everything works fine when I run things from the interface, but as soon as I do the exact same thing in BehaviourSpace is throws an error. It seems to occur even before the setup function is called, and irrespective of making output files or having to log anything. 

I would greatly appreciate some help to understand and fix this!

Best wishes, Nanda

#####Error report ######

Expected a literal value. at position 45 in 
 at org.nlogo.core.Fail$.exception(Fail.scala:27)
 at org.nlogo.core.Fail$.exception(Fail.scala:25)
 at org.nlogo.core.Fail$.exception(Fail.scala:23)
 at org.nlogo.parse.LiteralParser.readLiteralPrefix(LiteralParser.scala:83)
 at org.nlogo.parse.LiteralParser.parseLiteralList(LiteralParser.scala:99)
 at org.nlogo.parse.ExpressionParser$.parseDelayedBlock(ExpressionParser.scala:627)
 at org.nlogo.parse.ExpressionParser$.resolveType(ExpressionParser.scala:273)
 at org.nlogo.parse.ExpressionParser$.resolveTypes(ExpressionParser.scala:127)
 at org.nlogo.parse.ExpressionParser$.parsePotentiallyVariadicArgumentList(ExpressionParser.scala:90)
 at org.nlogo.parse.ExpressionParser$.parseExpressionInternal(ExpressionParser.scala:418)
 at org.nlogo.parse.ExpressionParser$.parseArgExpression(ExpressionParser.scala:230)
 at org.nlogo.parse.ExpressionParser$.$anonfun$parseArguments$1(ExpressionParser.scala:166)
 at org.nlogo.parse.ExpressionParser$.$anonfun$parseArguments$1$adapted(ExpressionParser.scala:165)
 at scala.collection.immutable.Range.foreach(Range.scala:156)
 at org.nlogo.parse.ExpressionParser$.parseArguments(ExpressionParser.scala:165)
 at org.nlogo.parse.ExpressionParser$.parsePotentiallyVariadicArgumentList(ExpressionParser.scala:88)
 at org.nlogo.parse.ExpressionParser$.parseStatement(ExpressionParser.scala:69)
 at org.nlogo.parse.ExpressionParser$.$anonfun$apply$1(ExpressionParser.scala:30)
 at org.nlogo.parse.ExpressionParser$.parseStatements(ExpressionParser.scala:42)
 at org.nlogo.parse.ExpressionParser$.apply(ExpressionParser.scala:30)
 at org.nlogo.parse.NetLogoParser.parseProcedure(NetLogoParser.scala:45)
 at org.nlogo.parse.NetLogoParser.parseProcedure$(NetLogoParser.scala:29)
 at org.nlogo.parse.FrontEnd$.parseProcedure(FrontEnd.scala:10)
 at org.nlogo.parse.NetLogoParser.$anonfun$basicParse$1(NetLogoParser.scala:25)
 at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
 at scala.collection.Iterator.foreach(Iterator.scala:929)
 at scala.collection.Iterator.foreach$(Iterator.scala:929)
 at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
 at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:210)
 at scala.collection.TraversableLike.map(TraversableLike.scala:234)
 at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
 at scala.collection.AbstractTraversable.map(Traversable.scala:104)
 at org.nlogo.parse.NetLogoParser.basicParse(NetLogoParser.scala:25)
 at org.nlogo.parse.NetLogoParser.basicParse$(NetLogoParser.scala:15)
 at org.nlogo.parse.FrontEnd$.basicParse(FrontEnd.scala:10)
 at org.nlogo.parse.FrontEndMain.frontEnd(FrontEnd.scala:26)
 at org.nlogo.parse.FrontEndMain.frontEnd$(FrontEnd.scala:25)
 at org.nlogo.parse.FrontEnd$.frontEnd(FrontEnd.scala:10)
 at org.nlogo.compile.CompilerMain$.compile(CompilerMain.scala:42)
 at org.nlogo.compile.Compiler.compileMoreCode(Compiler.scala:78)
 at org.nlogo.compile.Compiler.compileMoreCode(Compiler.scala:91)
 at org.nlogo.workspace.Evaluator.invokeCompiler(Evaluator.scala:158)
 at org.nlogo.workspace.Evaluator.makeCommandThunk(Evaluator.scala:110)
 at org.nlogo.workspace.Evaluating.makeCommandThunk(Evaluating.scala:25)
 at org.nlogo.workspace.Evaluating.makeCommandThunk$(Evaluating.scala:23)
 at org.nlogo.workspace.AbstractWorkspaceScala.makeCommandThunk(AbstractWorkspaceScala.scala:24)
 at org.nlogo.plot.PlotManager.compile$1(PlotManager.scala:86)
 at org.nlogo.plot.PlotManager.$anonfun$compilePlot$4(PlotManager.scala:102)
 at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:739)
 at scala.collection.immutable.List.foreach(List.scala:389)
 at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:738)
 at org.nlogo.plot.PlotManager.compilePlot(PlotManager.scala:100)
 at org.nlogo.plot.PlotManager.$anonfun$compileAllPlots$1(PlotManager.scala:81)
 at scala.collection.immutable.List.flatMap(List.scala:335)
 at org.nlogo.plot.PlotManager.compileAllPlots(PlotManager.scala:81)
 at org.nlogo.headless.HeadlessModelOpener.finish(HeadlessModelOpener.scala:89)
 at org.nlogo.headless.HeadlessModelOpener.openFromModel(HeadlessModelOpener.scala:73)
 at org.nlogo.headless.HeadlessWorkspace.openModel(HeadlessWorkspace.scala:535)
 at org.nlogo.app.App$$anon$2.openCurrentModelIn(App.scala:134)
 at org.nlogo.lab.gui.Supervisor.$anonfun$start$1(Supervisor.scala:98)
 at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:156)
 at org.nlogo.lab.gui.Supervisor.start(Supervisor.scala:96)
 at org.nlogo.lab.gui.ManagerDialog.run(ManagerDialog.scala:100)
 at org.nlogo.lab.gui.ManagerDialog.$anonfun$runAction$1(ManagerDialog.scala:30)
 at org.nlogo.lab.gui.ManagerDialog$$anon$3.actionPerformed(ManagerDialog.scala:24)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
 at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
 at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
 at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
 at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
 at java.awt.Component.processMouseEvent(Component.java:6533)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
 at java.awt.Component.processEvent(Component.java:6298)
 at java.awt.Container.processEvent(Container.java:2237)
 at java.awt.Component.dispatchEventImpl(Component.java:4889)
 at java.awt.Container.dispatchEventImpl(Container.java:2295)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
 at java.awt.Container.dispatchEventImpl(Container.java:2281)
 at java.awt.Window.dispatchEventImpl(Window.java:2746)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.awt.EventQueue$4.run(EventQueue.java:729)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

NetLogo 6.0.4
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_152 (Oracle Corporation; 1.8.0_152-b16)
operating system: Mac OS X 10.14 (x86_64 processor)
Scala version 2.12.4
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: PhizaFish

09:58:04.140 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
09:58:04.140 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
09:58:04.140 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
09:58:04.140 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
09:58:04.140 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
09:58:04.140 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
09:58:04.140 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
09:58:04.140 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
09:58:04.140 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
09:58:04.140 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0

**Comment by LaCuneta** [comment]
@nwijermans Thank you for reporting this issue, we appreciate it!  

As Seth pointed out, this is most likely an occasional error in the plot code of your model that causes no problems when running in the interface, but causes this exception when run in BehaviorSpace.  If you can't track down the problem plot code in your model, you can post it here and I'll see if I can find the source of the error.  If you don't want to post your model publicly, you can email it to bugs@ccl.northwestern.edu instead and we'll keep it private.

**Comment by LaCuneta** [comment]
Closing as a duplicate, please let us know if you aren't able to get the model running in BehaviorSpace.

**Comment by nwijermans** [comment]
@LaCuneta and @SethTisue thanks for pointing this out. Your hint of a not-functioning plot immediately gave me the right feedback to solve it. It works now. Thanks for being my human compiler and your swift replies!
