### ISSUE TITLE
Unknown error, not able to open Netlogo

### ISSUE THREAD

**Issue by Joua007** [NetLogo/NetLogo#1685]
No idea what is going on, but I need Netlogo for school and I'm getting this.

java.lang.reflect.InvocationTargetException
 at java.awt.EventQueue.invokeAndWait(Unknown Source)
 at java.awt.EventQueue.invokeAndWait(Unknown Source)
 at org.nlogo.awt.EventQueue$.invokeAndWait(EventQueue.scala:19)
 at org.nlogo.app.App$.mainWithAppHandler(App.scala:162)
 at org.nlogo.app.App$.main(App.scala:68)
 at org.nlogo.app.App.main(App.scala)
Caused by: java.lang.RuntimeException: Unclosed '
 at javax.swing.text.html.CSSParser.readTill(Unknown Source)
 at javax.swing.text.html.CSSParser.nextToken(Unknown Source)
 at javax.swing.text.html.CSSParser.parseTillClosed(Unknown Source)
 at javax.swing.text.html.CSSParser.parseIdentifiers(Unknown Source)
 at javax.swing.text.html.CSSParser.parseDeclaration(Unknown Source)
 at javax.swing.text.html.CSSParser.parseDeclarationBlock(Unknown Source)
 at javax.swing.text.html.CSSParser.parseRuleSet(Unknown Source)
 at javax.swing.text.html.CSSParser.getNextStatement(Unknown Source)
 at javax.swing.text.html.CSSParser.parse(Unknown Source)
 at javax.swing.text.html.StyleSheet$CssParser.parse(Unknown Source)
 at javax.swing.text.html.StyleSheet.addRule(Unknown Source)
 at javax.swing.text.html.HTMLDocument$HTMLReader.addCSSRules(Unknown Source)
 at javax.swing.text.html.HTMLDocument$HTMLReader$HeadAction.end(Unknown Source)
 at javax.swing.text.html.HTMLDocument$HTMLReader.handleEndTag(Unknown Source)
 at javax.swing.text.html.parser.DocumentParser.handleEndTag(Unknown Source)
 at javax.swing.text.html.parser.Parser.parse(Unknown Source)
 at javax.swing.text.html.parser.DocumentParser.parse(Unknown Source)
 at javax.swing.text.html.parser.ParserDelegator.parse(Unknown Source)
 at javax.swing.text.html.HTMLEditorKit.read(Unknown Source)
 at javax.swing.JEditorPane.setText(Unknown Source)
 at org.nlogo.app.infotab.InfoTab.updateEditorPane(InfoTab.scala:136)
 at org.nlogo.app.infotab.InfoTab.org$nlogo$app$infotab$InfoTab$$updateEditorPane(InfoTab.scala:129)
 at org.nlogo.app.infotab.InfoTab.resetView(InfoTab.scala:148)
 at org.nlogo.app.infotab.InfoTab.handle(InfoTab.scala:153)
 at org.nlogo.window.Events$LoadModelEvent.beHandledBy(Events.java:478)
 at org.nlogo.window.Event.doRaise(Event.java:198)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.window.ReconfigureWorkspaceUI$Loader.$anonfun$loadHelper$5(ReconfigureWorkspaceUI.scala:40)
 at org.nlogo.window.ReconfigureWorkspaceUI$Loader.$anonfun$loadHelper$5$adapted(ReconfigureWorkspaceUI.scala:40)
 at scala.collection.immutable.List.foreach(List.scala:389)
 at org.nlogo.window.ReconfigureWorkspaceUI$Loader.loadHelper(ReconfigureWorkspaceUI.scala:40)
 at org.nlogo.window.ReconfigureWorkspaceUI$.apply(ReconfigureWorkspaceUI.scala:19)
 at org.nlogo.app.FileManager.org$nlogo$app$FileManager$$runLoad(FileManager.scala:302)
 at org.nlogo.app.FileManager.openFromModel(FileManager.scala:359)
 at org.nlogo.app.FileManager.newModel(FileManager.scala:322)
 at org.nlogo.app.App.loadDefaultModel(App.scala:561)
 at org.nlogo.app.App.org$nlogo$app$App$$finishStartup(App.scala:443)
 at org.nlogo.app.App$.$anonfun$mainWithAppHandler$1(App.scala:162)
 at java.awt.event.InvocationEvent.dispatch(Unknown Source)
 at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
 at java.awt.EventQueue.access$500(Unknown Source)
 at java.awt.EventQueue$3.run(Unknown Source)
 at java.awt.EventQueue$3.run(Unknown Source)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.awt.EventQueue.dispatchEvent(Unknown Source)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
 at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
 at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
 at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
 at java.awt.EventDispatchThread.run(Unknown Source)

NetLogo 6.0.4
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_181 (Oracle Corporation; 1.8.0_181-b13)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.4
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Untitled

10:20:59.806 DirtyEvent (org.nlogo.app.infotab.InfoTab) AWT-EventQueue-0
10:20:59.806 LoadModelEvent (org.nlogo.window.ReconfigureWorkspaceUI$Loader (java.lang.Object)) AWT-EventQueue-0
10:20:59.668 LoadBeginEvent (org.nlogo.window.ReconfigureWorkspaceUI$Loader (java.lang.Object)) AWT-EventQueue-0
10:20:59.593 BeforeLoadEvent (org.nlogo.window.ReconfigureWorkspaceUI$Loader (java.lang.Object)) AWT-EventQueue-0
10:20:59.303 IndenterChangedEvent (org.nlogo.app.codetab.MainCodeTab) AWT-EventQueue-0
10:20:59.157 WidgetAddedEvent (org.nlogo.app.common.CommandLine) AWT-EventQueue-0
10:20:59.126 WidgetAddedEvent (org.nlogo.window.ViewWidget) AWT-EventQueue-0
10:20:58.868 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0

**Comment by LaCuneta** [comment]
@Joua007 Thanks for reporting this issue, sorry you ran into it.  One thing that sticks out to me is that is not the Java version that comes bundled with NetLogo 6.0.4.  Did you download it from the CCL website ( http://ccl.northwestern.edu/netlogo/ )?  Are you running NetLogo with any special scripts or other custom setup?  Any other information you can provide would be helpful.  Thanks!

**Comment by LaCuneta** [comment]
I'm closing this for now, but if it's still a problem feel free to leave a comment with more information as per the previous comment and we'll look back into it.
