### ISSUE TITLE
Improve error message for lists that grow too large

### ISSUE THREAD

**Issue by efyoungud** [NetLogo/NetLogo#1686]
The error comes up when I'm running the 'go' procedure, and ends with a highlight of 'ask' in a procedure that asks a breed of agents to call several other procedures. My code is https://github.com/efyoungud/stationfire/blob/master/socevac.nlogo if it's a matter of my having done something incompatible.

java.lang.IllegalArgumentException
 at scala.collection.immutable.VectorPointer.gotoFreshPosWritable0(Vector.scala:1102)
 at scala.collection.immutable.VectorPointer.gotoFreshPosWritable0$(Vector.scala:1043)
 at scala.collection.immutable.Vector.gotoFreshPosWritable0(Vector.scala:64)
 at scala.collection.immutable.VectorPointer.gotoFreshPosWritable1(Vector.scala:1110)
 at scala.collection.immutable.VectorPointer.gotoFreshPosWritable1$(Vector.scala:1108)
 at scala.collection.immutable.Vector.gotoFreshPosWritable1(Vector.scala:64)
 at scala.collection.immutable.Vector.gotoFreshPosWritable(Vector.scala:260)
 at scala.collection.immutable.Vector.appendFront(Vector.scala:318)
 at scala.collection.immutable.Vector.$plus$colon(Vector.scala:139)
 at org.nlogo.core.LogoList.fput(LogoList.scala:49)
 at org.nlogo.prim._asm_procedureaxprojectsstationnightclubprojectsimulationpathsnls_setprocedurevariable_51.perform(:2)
 at org.nlogo.nvm.Context.callReporterProcedure(Context.java:254)
 at org.nlogo.prim._asm_proceduresetpathxprojectsstationnightclubprojectsimulationpathsnls_setbreedvariable_0.perform(:2)
 at org.nlogo.nvm.Context.runExclusive(Context.java:133)
 at org.nlogo.nvm.ExclusiveJob.run(ExclusiveJob.scala:39)
 at org.nlogo.nvm.Context.runExclusiveJob(Context.java:177)
 at org.nlogo.prim._asm_procedurego_ask_7.perform(:1)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
 at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
 at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
 at scala.util.control.Exception$Catch.apply(Exception.scala:224)
 at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:66)

NetLogo 6.0.4
main: org.nlogo.app.AppFrame
thread: JobThread
Java HotSpot(TM) 64-Bit Server VM 1.8.0_172 (Oracle Corporation; 1.8.0_172-b11)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.4
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: socevac

02:29:09.271 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
02:29:09.268 RuntimeErrorEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:29:09.268 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
02:29:09.268 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
02:29:09.268 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
02:29:09.268 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
02:29:09.268 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
02:29:09.268 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
02:29:09.267 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
02:29:09.267 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

**Comment by LaCuneta** [comment]
@efyoungud Thanks for reporting this issue, we appreciate it.

I took a look at your model and it ran without error for me for the first few ticks, anyway.  Do you know about how many ticks it has to go through before you see the error?  Or are there other steps you know of that cause the error to happen every time?

From the exception message and looking at your model, I think the exception is getting thrown in `paths.nls` in the `A*` reporter; the line `set rep fput current rep`.  It might be whatever value is in the `current` variable that is causing the exception.

It definitely should not be causing an exception in this way, so we'll continue trying to track it down.

**Comment by efyoungud** [comment]
Usually it takes about 30-35 ticks to error, which means that it is
somewhere in the 'move' command, so paths.nls as the root of the problem
makes sense. Would it be possible that the problem is caused by no viable
paths being found?

**Comment by LaCuneta** [comment]
@efyoungud I'm still running tests, but I'm pretty sure I tracked the issue down.  This exception would get thrown when a list has many, many, many items in it, 2^32 or so (in the billions), and then you try to `fput` one more item past the limit.  If your code has an infinite `while` loop in it, maybe caused by no viable path being there as you said, it could generate a list this large.  

One way to troubleshoot this would be to add a counter to your `while` loop and create an `error` if it gets to a value you wouldn't expect, say over 1000 or so.  Then it'd be a matter of determining what values led to that situation.  So you could do this in your code:

    while [current != #Start]
    [
      set current [father] of current
      set rep fput current rep
      if length rep > 1000 [ error (word "The path seems way too big: " rep) ]
    ]

**Comment by LaCuneta** [comment]
Updating the title to better reflect the issue.  When you try to append or prepend with a Scala Vector that is already at the [size limit](https://docs.scala-lang.org/overviews/collections/concrete-immutable-collection-classes.html#vectors), it throws the `IllegalArgumentException` exception.  We should replace that with a friendlier, normal NetLogo runtime error message.

**Comment by SethTisue** [comment]
Scala 2.13 replaces the implementation of `Vector`; this behavior might change when you upgrade

**Comment by ERSUCC** [comment]
The same illogical error message was still present in NetLogo 7 with Scala 3, so I made the requested improvement.
