### ISSUE TITLE
Java issue

### ISSUE THREAD

**Issue by wilkehe** [NetLogo/NetLogo#1689]
NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.awt.IllegalComponentStateException: component must be showing on the screen to determine its location
 at java.awt.Component.getLocationOnScreen_NoTreeLock(Unknown Source)
 at java.awt.Component.getLocationOnScreen(Unknown Source)
 at javax.swing.text.JTextComponent$InputMethodRequestsHandler.getTextLocation(Unknown Source)
 at sun.awt.im.InputMethodContext.getTextLocation(Unknown Source)
 at sun.awt.windows.WInputMethod$1.run(Unknown Source)
 at java.awt.event.InvocationEvent.dispatch(Unknown Source)
 at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
 at java.awt.EventQueue.access$500(Unknown Source)
 at java.awt.EventQueue$3.run(Unknown Source)
 at java.awt.EventQueue$3.run(Unknown Source)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.awt.EventQueue$4.run(Unknown Source)
 at java.awt.EventQueue$4.run(Unknown Source)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.awt.EventQueue.dispatchEvent(Unknown Source)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
 at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
 at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
 at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
 at java.awt.EventDispatchThread.run(Unknown Source)

NetLogo 5.3.1
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) Client VM 1.8.0_131 (Oracle Corporation; 1.8.0_131-b11)
operating system: Windows 7 6.1 (x86 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: MicsimKombi59_NEWBASELINE_oneButton

10:20:09.826 AddSliderConstraintEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
10:20:09.826 AddSliderConstraintEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
10:20:09.826 AddSliderConstraintEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
10:20:09.826 AddSliderConstraintEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
10:20:09.825 AddSliderConstraintEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
10:20:09.825 AddSliderConstraintEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
10:20:09.825 AddSliderConstraintEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
10:20:09.825 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
10:20:09.825 AddSliderConstraintEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
10:20:09.825 AddSliderConstraintEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0

**Comment by charlesres** [comment]
@wilkehe Thanks for reporting this issue. I see the model you are running is MicsimKombi59_NEWBASELINE_oneButton. Could you include a link to the model's source code?

**Comment by wilkehe** [comment]
@charlesres:
I am sorry, I am not sure where to find it. I tried to install the following example:
https://www.comses.net/codebases/5146/releases/1.5.0/

**Comment by charlesres** [comment]
@wilkehe:
I am still running tests on 1.5.0, but I should mention that NetLogo 5.3.1 is no longer supported. If the problem is intermittent and happens with widget changes, then I would try to avoid anything that would crash the model. But if the model doesn't start or function properly, I would suggest updating the model to work with NetLogo 6.0.4 since it should have the latest fixes.

Transition guide : https://ccl.northwestern.edu/netlogo/docs/transition.html
