### ISSUE TITLE
Behavior Space simultaneous runs error

### ISSUE THREAD

**Issue by Duganja** [NetLogo/NetLogo#1701]
I'm running Netlogo 5.1.0 in Windows 10, and I'm having run time errors using the simultaneous runs feature in behavior space. 

Behavior space works when running only one at a time, but two or more causes errors. "clear-all" is used as the first set up command. The errors are variations of "LAST expected input to be a string or list but got the number 0 instead." This error has varied a bit, but it is generally finding 0 when looking for a variable. 

I appreciate any help on the issue. I couldn't find much help on Google. 

full errors: 
1.
LAST expected input to be a string or list but got the number 0 instead.
error while car -1 running LAST
  called by procedure GO
  called by procedure __EVALUATOR

org.nlogo.nvm.ArgumentTypeException: LAST expected input to be a string or list but got the number 0 instead.
 at org.nlogo.nvm.EngineException.fillInStackTrace(EngineException.java:81)
 at java.lang.Throwable.<init>(Throwable.java:218)
 at java.lang.Exception.<init>(Exception.java:59)
 at org.nlogo.api.LogoException.<init>(LogoException.scala:15)
 at org.nlogo.nvm.EngineException.<init>(EngineException.java:20)
 at org.nlogo.nvm.ArgumentTypeException.<init>(ArgumentTypeException.java:22)
 at org.nlogo.prim.etc._last.report(_last.java:39)
 at org.nlogo.prim._setbreedvariable.perform(_setbreedvariable.java:34)
 at org.nlogo.nvm.Context.runExclusive(Context.java:119)
 at org.nlogo.nvm.ExclusiveJob.run(ExclusiveJob.java:57)
 at org.nlogo.nvm.Context.runExclusiveJob(Context.java:162)
 at org.nlogo.prim._hatch.perform(_hatch.java:60)
 at org.nlogo.nvm.Context.runExclusive(Context.java:119)
 at org.nlogo.nvm.ExclusiveJob.run(ExclusiveJob.java:57)
 at org.nlogo.nvm.Context.runExclusiveJob(Context.java:162)
 at org.nlogo.prim._asm_procedurego_ask_105.perform(:1)
 at org.nlogo.nvm.Context.runExclusive(Context.java:119)
 at org.nlogo.nvm.ExclusiveJob.run(ExclusiveJob.java:57)
 at org.nlogo.nvm.Context.runExclusiveJob(Context.java:162)
 at org.nlogo.prim._asm_procedurego_ask_103.perform(:1)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:91)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.java:82)
 at org.nlogo.job.JobThread.org$nlogo$job$JobThread$$runPrimaryJobs(JobThread.scala:143)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply$mcV$sp(JobThread.scala:78)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at scala.util.control.Exception$Catch.apply(Exception.scala:88)
 at org.nlogo.util.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:75)

NetLogo 5.1.0
main: org.nlogo.app.AppFrame
thread: JobThread
Java HotSpot(TM) Server VM 1.6.0_45 (Sun Microsystems Inc.; 1.6.0_45-b06)
operating system: Windows 8 6.2 (x86 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Evacuation Model

04:02:38.579 RuntimeErrorEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:02:38.573 RuntimeErrorEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:02:38.565 RuntimeErrorEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:02:38.565 OutputEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:02:38.556 RuntimeErrorEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:02:38.547 RuntimeErrorEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:02:38.531 RuntimeErrorEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:02:38.530 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
04:02:38.530 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
04:02:38.530 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread

2.

**Comment by charlesres** [comment]
Hi, @Duganja. Thanks for reporting the issue and providing some details. For NetLogo 5.1.0, we no longer support that version and would recommend upgrading to the latest NetLogo release. As for your issue with Last, the first thing that comes to mind is it might be an issue with initialization or values being rewritten over time. If you could provide the source code for the Evacuation Model, that would help with reproducing the issue. 
Also, if you have any general questions, feel free to submit to the NetLogo user-group.
https://groups.google.com/forum/#!forum/netlogo-users
