### ISSUE TITLE
Unknown error  

### ISSUE THREAD

**Issue by deadletterb** [NetLogo/NetLogo#1709]
NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 

java.lang.reflect.InvocationTargetException
 at java.awt.EventQueue.invokeAndWait(EventQueue.java:1349)
 at java.awt.EventQueue.invokeAndWait(EventQueue.java:1324)
 at org.nlogo.awt.EventQueue$.invokeAndWait(EventQueue.scala:19)
 at org.nlogo.awt.EventQueue.invokeAndWait(EventQueue.scala)
 at org.nlogo.window.ViewManager.incrementalUpdateFromJobThread(ViewManager.java:62)
 at org.nlogo.window.GUIWorkspace.updateDisplay(GUIWorkspace.java:624)
 at org.nlogo.window.GUIWorkspace.ownerFinished(GUIWorkspace.java:826)
 at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:119)
 at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
 at scala.util.control.Exception$Catch.apply(Exception.scala:224)
 at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:66)
Caused by: com.jogamp.opengl.GLException: Caught NullPointerException: null on thread AWT-EventQueue-0
 at com.jogamp.opengl.GLException.newGLException(GLException.java:76)
 at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1327)
 at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
 at com.jogamp.opengl.awt.GLCanvas$12.run(GLCanvas.java:1438)
 at com.jogamp.opengl.Threading.invoke(Threading.java:223)
 at com.jogamp.opengl.awt.GLCanvas.display(GLCanvas.java:505)
 at org.nlogo.gl.view.View.display(View.scala:80)
 at org.nlogo.gl.view.ViewManager.incrementalUpdateFromEventThread(ViewManager.scala:145)
 at org.nlogo.window.ViewManager.incrementalUpdateFromEventThread(ViewManager.java:48)
 at org.nlogo.window.ViewManager$1.run(ViewManager.java:56)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
 at org.nlogo.gl.render.LinkRenderer.renderLink(LinkRenderer.scala:127)
 at org.nlogo.gl.render.LinkRenderer.renderWrappedLink(LinkRenderer.scala:54)
 at org.nlogo.gl.render.LinkRenderer.$anonfun$renderLinks$2(LinkRenderer.scala:31)
 at org.nlogo.gl.render.LinkRenderer.$anonfun$renderLinks$2$adapted(LinkRenderer.scala:29)
 at scala.collection.immutable.List.foreach(List.scala:389)
 at org.nlogo.gl.render.LinkRenderer.renderLinks(LinkRenderer.scala:29)
 at org.nlogo.gl.render.Renderer.render(Renderer.java:450)
 at org.nlogo.gl.render.Renderer.display(Renderer.java:260)
 at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
 at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
 at com.jogamp.opengl.awt.GLCanvas$11.run(GLCanvas.java:1424)
 at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
 ... 22 more

NetLogo 3D 6.0.4
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_172 (Oracle Corporation; 1.8.0_172-b11)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.4
JOGL: 2.3.2
OpenGL graphics: AMD Radeon HD 6900 Series
OpenGL version: 4.5.13399 Compatibility Profile Context 15.200.1062.1004
OpenGL vendor: ATI Technologies Inc.
model: display (1)

02:01:07.600 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
02:01:07.569 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
02:01:07.569 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
02:01:07.569 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
02:01:07.569 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
02:01:07.569 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
02:01:07.569 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
02:01:07.569 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
02:01:07.569 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
02:01:07.569 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0

**Comment by charlesres** [comment]
Hi @deadletterb. Thanks for submitting a report. My initial thought is that AWT thread is referencing an OpenGL value that isn't initialized to NetLogo. For reproducing the issue, could you provide a copy of your model? You can post a link to it here or if you would prefer not to share it publicly, please email bugs@ccl.northwestern.edu with a copy of the model attached and reference this issue in your email.

**Comment by LaCuneta** [comment]
I'm closing this for now, but if it's still a problem feel free to leave a comment with more information as per the previous comment and we'll look back into it.
