### ISSUE TITLE
Error with the time extension of NetLogo 6.0.4

### ISSUE THREAD

**Issue by kanead** [NetLogo/NetLogo#1737]
Hi all,

When I run the _DiscreteEventScheduling_ example model that comes with the time extension, NetLogo gives me an unknown error. Some of the other example models work e.g. _TimeExample_ which leads me to believe it's related to the schedule functions associated with the extension. Hope you can help clarify what's going wrong here. 

java.lang.NoSuchMethodError: org.nlogo.nvm.AnonymousCommand.procedure()Lorg/nlogo/nvm/Procedure;
 at time.datatypes.LogoEvent.dump(LogoEvent.java:72)
 at time.datatypes.LogoSchedule.dump(LogoSchedule.java:215)
 at time.primitives.DiscreteEventSchedulerPrimitives$ShowSchedule.report(DiscreteEventSchedulerPrimitives.java:157)
 at org.nlogo.prim._externreport.report(_externreport.java:31)
 at org.nlogo.prim.etc._print.perform(_print.scala:12)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
 at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
 at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
 at scala.util.control.Exception$Catch.apply(Exception.scala:224)
 at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:66)

NetLogo 6.0.4
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_172 (Oracle Corporation; 1.8.0_172-b11)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.4
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: DiscreteEventScheduling

06:05:05.307 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
06:05:05.307 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
06:05:05.307 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
06:05:05.307 TickStateChangeEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
06:05:05.293 TickStateChangeEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
06:05:05.285 OutputEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
06:05:05.268 AddJobEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
06:05:05.151 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
06:05:05.150 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
06:05:05.150 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

**Comment by charlesres** [comment]
Hi @kanead. Thank you for submitting a report. With the time extension, there are two extensions that are, currently, available. Are you referring to [Colin Sheppard's GitHub project](https://github.com/colinsheppard/time) or the forked [NetLogo/Time-Extension](https://github.com/NetLogo/Time-Extension) project? With each NetLogo release, from 6.0 -> 6.0.4, there have been some minor updates that have affected the main time extension (Sheppard).

**Comment by kanead** [comment]
Hi, thanks for your response. It's the Colin Sheppard version that causing the issues for me.

**Comment by charlesres** [comment]
Thanks, @kanead. As of 2018, the latest updates are on the NetLogo fork of the [Time-Extension](https://github.com/NetLogo/Time-Extension). With the fork, there have been some updates to match NetLogo 6.0.4's expectations, but the [release](https://github.com/NetLogo/Time-Extension/releases/tag/v2.0.0-beta) might have some bugs. The DiscreteEventScheduling model should be a working example with the release and can be tested with this [version](https://github.com/NetLogo/Time-Extension/blob/master/time.jar). Feel free to give a try and let us know if any issues or conflicts come up.

**Comment by ERSUCC** [comment]
The time extension is now bundled and maintained, so incompatibilities like these are highly unlikely to occur. I think this issue is no longer relevant.
