### ISSUE TITLE
'Collect Data' issues on mac os

### ISSUE THREAD

**Issue by baekkkkimchi** [NetLogo/NetLogo#1752]
java.lang.NoClassDefFoundError: org/apache/commons/csv/CSVFormat
 at org.nlogo.extensions.csv.CSVExtension.csvFormat(CSVExtension.scala:22)
 at org.nlogo.extensions.csv.CSVExtension$ToLine.report(CSVExtension.scala:82)
 at org.nlogo.extensions.csv.CSVExtension$ToLine.report(CSVExtension.scala:76)
 at org.nlogo.prim._externreport.report(_externreport.java:31)
 at org.nlogo.prim.file._fileprint.perform(primitives.scala:125)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
 at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
 at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
 at scala.util.control.Exception$Catch.apply(Exception.scala:228)
 at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:66)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.csv.CSVFormat
 at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
 at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:817)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
 ... 13 more

NetLogo 6.1.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_202 (Oracle Corporation; 1.8.0_202-b08)
operating system: Mac OS X 10.14.5 (x86_64 processor)
Scala version 2.12.8
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Sampling

06:03:48.859 AddJobEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
06:03:48.854 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
06:03:48.850 InputBoxLoseFocusEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
06:03:48.807 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
06:03:48.807 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
06:03:48.807 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
06:03:48.807 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
06:03:48.807 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
06:03:48.807 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
06:03:48.807 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0

**Comment by LaCuneta** [comment]
@baekkkkimchi Thanks for reporting this error, sorry you ran into it!

It looks to me like you were trying to use the CSV extensions's `csv:to-row` primitive in a model, correct?  I tested that out on NetLogo 6.1 on my macOS machine, and it did work as expected.  Would you be able to post your model so we can see if anything else in there would be causing this?

I'd also like to see if the extension was installed correctly.

- Are you running NetLogo from a folder on your machine after downloading it, or is it installed in some other way?  This sort of error could occur when trying to run NetLogo off of a network folder, for instance.
- If you're using the version bundled with NetLogo, can you open the Terminal app and run the command `ls "/Applications/NetLogo 6.1.0/extensions/.bundled/csv"` (that's lower-case L, lower-case S, `ls`)?  You may have to change the `/Applications/` part of the folder path to wherever you are running the NetLogo app from if you didn't install it in `Applications`.

Or if you installed the CSV extension manually in some other way instead of using the one bundled with NetLogo, let me know as that might be related.

Thanks again for reporting this, and for helping us to track it down.

**Comment by LaCuneta** [comment]
I'm closing this for now, but if it's still a problem feel free to leave a comment with more information as per the previous comment and we'll look back into it.
