### ISSUE TITLE
Exceptions when editing code of a model using breeded links

### ISSUE THREAD

**Issue by LaCuneta** [NetLogo/NetLogo#1758]
Reported by a user.  If you have a model that has breeded links, and you create some of those links in your world, then you start editing code in the code tab and make a mistake with a syntax error or other compile-time error, you'll see an exception as below.

```
NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 


java.lang.IllegalStateException: neither of the breeds exist, that's bad
 at org.nlogo.agent.LinkManagement.$anonfun$compareLinkBreeds$1(LinkManagement.scala:119)
 at scala.Option.getOrElse(Option.scala:121)
 at org.nlogo.agent.LinkManagement.compareLinkBreeds(LinkManagement.scala:119)
 at org.nlogo.agent.LinkManagement.compareLinkBreeds$(LinkManagement.scala:112)
 at org.nlogo.agent.World.compareLinkBreeds(World.scala:109)
 at org.nlogo.agent.Link.compareTo(Link.java:696)
 at org.nlogo.agent.Link.compareTo(Link.java:20)
 at java.util.TreeMap.getEntry(TreeMap.java:352)
 at java.util.TreeMap.remove(TreeMap.java:603)
 at org.nlogo.agent.TreeAgentSet.remove(TreeAgentSet.scala:58)
 at org.nlogo.agent.Link.die(Link.java:121)
 at org.nlogo.agent.LinkManagerImpl.$anonfun$cleanupTurtle$1(LinkManager.scala:148)
 at org.nlogo.agent.LinkManagerImpl.$anonfun$cleanupTurtle$1$adapted(LinkManager.scala:148)
 at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
 at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
 at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
 at org.nlogo.agent.LinkManagerImpl.cleanupTurtle(LinkManager.scala:148)
 at org.nlogo.agent.Turtle.die(Turtle.java:156)
 at org.nlogo.agent.Realloc$.$anonfun$realloc$9(Realloc.scala:43)
 at org.nlogo.agent.Realloc$.$anonfun$realloc$9$adapted(Realloc.scala:43)
 at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
 at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
 at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
 at org.nlogo.agent.Realloc$.realloc(Realloc.scala:43)
 at org.nlogo.agent.CompilationManagement.realloc(CompilationManagement.scala:70)
 at org.nlogo.agent.CompilationManagement.realloc$(CompilationManagement.scala:69)
 at org.nlogo.agent.World2D.realloc(World.scala:138)
 at org.nlogo.window.CompilerManager.compileAll(CompilerManager.scala:174)
 at org.nlogo.window.CompilerManager.handle(CompilerManager.scala:137)
 at org.nlogo.window.Events$CompileAllEvent.beHandledBy(Events.java:185)
 at org.nlogo.window.Event.doRaise(Event.java:198)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.app.codetab.CodeTab.compile(CodeTab.scala:158)
 at org.nlogo.app.codetab.CodeTab$CompileAction$.actionPerformed(CodeTab.scala:193)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
 at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
 at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
 at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
 at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
 at java.awt.Component.processMouseEvent(Component.java:6539)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
 at java.awt.Component.processEvent(Component.java:6304)
 at java.awt.Container.processEvent(Container.java:2239)
 at java.awt.Component.dispatchEventImpl(Component.java:4889)
 at java.awt.Container.dispatchEventImpl(Container.java:2297)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
 at java.awt.Container.dispatchEventImpl(Container.java:2283)
 at java.awt.Window.dispatchEventImpl(Window.java:2746)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
 at java.awt.EventQueue$4.run(EventQueue.java:733)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

NetLogo 6.0.4
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_202 (Oracle Corporation; 1.8.0_202-b08)
operating system: Mac OS X 10.14.5 (x86_64 processor)
Scala version 2.12.4
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Team 6.1.0 no file

09:28:15.271 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
09:28:15.271 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
09:28:15.270 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
09:28:15.270 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
09:28:15.270 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:28:14.930 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
09:28:14.865 RemoveAllJobsEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
09:28:14.865 CompileAllEvent (org.nlogo.app.codetab.MainCodeTab) AWT-EventQueue-0
09:28:14.799 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
09:28:14.798 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
```

**Comment by LaCuneta** [comment]
This is a regression in 6.1.0.  I tracked the issue down to the changes we made to avoid having slider values reset to 0 when opening a model that was saved with an unresolved compile-time error.  

I've got a fix running through tests now, and hopefully it'll be merged soon.

Unfortunately the only workaround for the problem I've come up with isn't great: If you're using breeded links in your model, any time you want to start editing code in the code tab, you should first switch to the Command Center and run `clear-all` or `clear-links` in order to leave the world empty.  This can be made mildly easier with hot-keys - so you can use Command-Shift-C (if you're on the interface tab) or Command-1 (if you are on the info or code tabs) to jump to the command center to run the `clear-all` command, then Command-3 to jump to the code tab to do your edits.
