### ISSUE TITLE
Commands taking patch variable names can throw unhelpful exceptions

### ISSUE THREAD

**Issue by LaCuneta** [NetLogo/NetLogo#1760]
The `diffuse`, `downhill`, and `uphill` commands and their `*4` variants can throw unhelpful exceptions when they are given a `turtles-own` variable name.

If your model has `turtles-own [ apples ]` and you do `diffuse apples 0.5` you'll get an exception like the one below.

The desired behavior would be to have a compile-time error when you try to use a `turtles-own` variable name with one of the affected primitives if that's possible.  If not, the next best behavior would be to give a much more clear runtime error message about the problem when the situation is encountered, instead of the unhelpful `ArrayIndexOutOfBoundsException`.

Confirmed on 6.0.4 and 6.1.0 on macOS.  

```
NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 


java.lang.ArrayIndexOutOfBoundsException: 13
 at org.nlogo.agent.Patch.getPatchVariable(Patch.java:297)
 at org.nlogo.agent.Topology.getPatchScratch(Topology.scala:176)
 at org.nlogo.agent.Topology.diffuse(Topology.scala:71)
 at org.nlogo.agent.World2D.diffuse(World.scala:202)
 at org.nlogo.prim.etc._diffuse.perform(_diffuse.scala:37)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
 at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
 at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
 at scala.util.control.Exception$Catch.apply(Exception.scala:228)
 at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:66)

NetLogo 6.1.0
main: org.nlogo.app.AppFrame
thread: JobThread
Java HotSpot(TM) 64-Bit Server VM 1.8.0_202 (Oracle Corporation; 1.8.0_202-b08)
operating system: Mac OS X 10.14.5 (x86_64 processor)
Scala version 2.12.8
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Untitled

02:28:14.678 RuntimeErrorEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:28:14.674 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:28:14.667 AddJobEvent (org.nlogo.app.common.CommandLine) AWT-EventQueue-0
02:28:14.667 OutputEvent (org.nlogo.app.common.CommandLine) AWT-EventQueue-0
02:28:14.667 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
02:28:14.652 CompileMoreSourceEvent (org.nlogo.app.common.CommandLine) AWT-EventQueue-0
02:28:14.540 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:28:14.339 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:28:14.137 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:28:13.933 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
```

**Comment by ERSUCC** [comment]
A related issue is that adding a slider widget and then using its global variable name in the `diffuse` primitive throws the error "You can't change a patch's coordinates", rather than "Expected a patch variable".

EDIT: Seems like the underlying problem here is that in the observer context, there is no type checking of agent variables, it just assumes you know what you're doing and directly gets the variable by index. Here is a concrete example that demonstrates this:

```
ask patch 0 0 [ set pcolor white ]
diffuse heading 0.5
```

In this example, you will see that the central patch diffuses its `pcolor` to the neighboring patches. This is because `heading` is the third turtle variable, and `pcolor` is the third patch variable, so it ends up working. This explains the error I mentioned above as well, because when I created a slider in a blank model, its global variable was the first global variable, and the first patch variable is `pxcor`. Hence the error about not being able to change the coordinates.
