### ISSUE TITLE
Classloader issue in dispose method of the headless workspace

### ISSUE THREAD

**Issue by romainreuillon** [NetLogo/NetLogo#1766]
In OpenMOLE (an osgi application) some of our user are using the *nw* extension for there netlogo model. The extension works properly with the HeadlessWorkspace, but the dispose methods throw a ClassNotDefException:

```
Caused by: java.lang.NoClassDefFoundError: org/openide/util/Lookup
	at org.nlogo.extensions.nw.gephi.GephiUtils$.$anonfun$shutdownStupidExtraThreads$1(GephiUtils.scala:33)
	at org.nlogo.extensions.nw.gephi.GephiUtils$.withClassLoaderContext(GephiUtils.scala:16)
	at org.nlogo.extensions.nw.gephi.GephiUtils$.$anonfun$withNWLoaderContext$1(GephiUtils.scala:10)
	at org.nlogo.extensions.nw.gephi.GephiUtils$.shutdownStupidExtraThreads(GephiUtils.scala:33)
	at org.nlogo.extensions.nw.NetworkExtension.unload(NetworkExtension.scala:41)
	at org.nlogo.workspace.ExtensionManager$JarContainer.unload(ExtensionManager.scala:91)
	at org.nlogo.workspace.ExtensionManager.$anonfun$reset$1(ExtensionManager.scala:287)
	at org.nlogo.workspace.ExtensionManager.$anonfun$reset$1$adapted(ExtensionManager.scala:286)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:213)
	at org.nlogo.workspace.ExtensionManager.reset(ExtensionManager.scala:286)
	at org.nlogo.workspace.AbstractWorkspace.dispose(AbstractWorkspace.java:85)
	at org.nlogo.workspace.AbstractWorkspaceScala.org$nlogo$workspace$Components$$super$dispose(AbstractWorkspaceScala.scala:26)
	at org.nlogo.workspace.Components.dispose(Components.scala:59)
	at org.nlogo.workspace.Components.dispose$(Components.scala:58)
	at org.nlogo.workspace.AbstractWorkspaceScala.dispose(AbstractWorkspaceScala.scala:26)
	at org.openmole.plugin.tool.netlogo6.NetLogo6.dispose(NetLogo6.java:88)
	at org.openmole.plugin.task.netlogo.NetLogoTask$.destroyInstance$1(NetLogoTask.scala:132)
	at org.openmole.plugin.task.netlogo.NetLogoTask$.$anonfun$createPool$2(NetLogoTask.scala:137)
	at org.openmole.plugin.task.netlogo.NetLogoTask$.$anonfun$createPool$2$adapted(NetLogoTask.scala:137)
	at org.openmole.tool.cache.WithNewInstance.apply(Pool.scala:61)
	at org.openmole.plugin.task.netlogo.NetLogoTask.$anonfun$process$1(NetLogoTask.scala:328)
	at org.openmole.core.expansion.FromContext.apply(FromContext.scala:243)
	at org.openmole.core.expansion.FromContext.from(FromContext.scala:244)
	at org.openmole.core.workflow.tools.InputOutputCheck$.$anonfun$perform$1(InputOutputCheck.scala:123)
	... 18 more
Caused by: java.lang.ClassNotFoundException: org.openide.util.Lookup
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:817)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 45 more
```

Note that this class is present in the gephi jar and that the netlogo version used in openmole is 6.1.0.

Any idea of what's happening here. Since the extension works properly during the model execution, I would guess that it might be a classloader issue in the dispose method.

Cheers,
Romain

**Comment by romainreuillon** [comment]
I fixed the issue in the NW extension, see: https://github.com/NetLogo/NW-Extension/issues/194

 but I guess that it could be solved in a generic manner in the netlogo extension manager. The manager should first call the unload method(s) and then get rid of the jars.
