### ISSUE TITLE
Camera is not working in MacOS 10.15.5

### ISSUE THREAD

**Issue by lofyer** [NetLogo/NetLogo#1842]
NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 

java.lang.ExceptionInInitializerError
 at org.nlogo.extensions.vid.VidExtension$.$anonfun$camera$1(VidExtension.scala:13)
 at org.nlogo.extensions.vid.VidExtension$.guiOrHeadless(VidExtension.scala:9)
 at org.nlogo.extensions.vid.VidExtension$.camera$lzycompute(VidExtension.scala:13)
 at org.nlogo.extensions.vid.VidExtension$.camera(VidExtension.scala:13)
 at org.nlogo.extensions.vid.VidExtension.<init>(VidExtension.scala:21)
 at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
 at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
 at java.lang.Class.newInstance(Class.java:442)
 at org.nlogo.workspace.JarLoader.extensionClassManager(JarLoader.scala:48)
 at org.nlogo.workspace.ExtensionManager.$anonfun$importExtension$8(ExtensionManager.scala:159)
 at scala.Option.getOrElse(Option.scala:138)
 at org.nlogo.workspace.ExtensionManager.importExtension(ExtensionManager.scala:157)
 at org.nlogo.parse.StructureParser$.$anonfun$parsingWithExtensions$1(StructureParser.scala:74)
 at org.nlogo.parse.StructureParser$.$anonfun$parsingWithExtensions$1$adapted(StructureParser.scala:68)
 at scala.collection.immutable.List.foreach(List.scala:392)
 at org.nlogo.parse.StructureParser$.parsingWithExtensions(StructureParser.scala:68)
 at org.nlogo.parse.StructureParser$.parseSources(StructureParser.scala:33)
 at org.nlogo.parse.NetLogoParser.basicParse(NetLogoParser.scala:17)
 at org.nlogo.parse.NetLogoParser.basicParse$(NetLogoParser.scala:15)
 at org.nlogo.parse.FrontEnd$.basicParse(FrontEnd.scala:10)
 at org.nlogo.parse.FrontEndMain.frontEnd(FrontEnd.scala:26)
 at org.nlogo.parse.FrontEndMain.frontEnd$(FrontEnd.scala:25)
 at org.nlogo.parse.FrontEnd$.frontEnd(FrontEnd.scala:10)
 at org.nlogo.compile.CompilerMain$.compile(CompilerMain.scala:43)
 at org.nlogo.compile.Compiler.compileProgram(Compiler.scala:54)
 at org.nlogo.window.CompilerManager.compileProcedures(CompilerManager.scala:209)
 at org.nlogo.window.CompilerManager.compileAll(CompilerManager.scala:173)
 at org.nlogo.window.CompilerManager.handle(CompilerManager.scala:64)
 at org.nlogo.window.Events$LoadEndEvent.beHandledBy(Events.java:462)
 at org.nlogo.window.Event.doRaise(Event.java:198)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.window.ReconfigureWorkspaceUI$Loader.$anonfun$loadHelper$5(ReconfigureWorkspaceUI.scala:41)
 at org.nlogo.window.ReconfigureWorkspaceUI$Loader.$anonfun$loadHelper$5$adapted(ReconfigureWorkspaceUI.scala:41)
 at scala.collection.immutable.List.foreach(List.scala:392)
 at org.nlogo.window.ReconfigureWorkspaceUI$Loader.loadHelper(ReconfigureWorkspaceUI.scala:41)
 at org.nlogo.window.ReconfigureWorkspaceUI$.apply(ReconfigureWorkspaceUI.scala:19)
 at org.nlogo.app.FileManager.org$nlogo$app$FileManager$$runLoad(FileManager.scala:303)
 at org.nlogo.app.FileManager$$anon$2.run(FileManager.scala:365)
 at org.nlogo.swing.ModalProgressTask$.$anonfun$onUIThread$1(ModalProgressTask.scala:26)
 at org.nlogo.swing.ModalProgressTask$.$anonfun$onUIThread$1$adapted(ModalProgressTask.scala:24)
 at org.nlogo.swing.ModalProgressTask$.$anonfun$display$1(ModalProgressTask.scala:18)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
 at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
 at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
 at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
 at java.awt.Dialog.show(Dialog.java:1084)
 at java.awt.Component.show(Component.java:1671)
 at java.awt.Component.setVisible(Component.java:1623)
 at java.awt.Window.setVisible(Window.java:1014)
 at java.awt.Dialog.setVisible(Dialog.java:1005)
 at org.nlogo.swing.ModalProgressTask$.display(ModalProgressTask.scala:20)
 at org.nlogo.swing.ModalProgressTask$.onUIThread(ModalProgressTask.scala:24)
 at org.nlogo.app.FileManager.openFromModel(FileManager.scala:369)
 at org.nlogo.app.FileManager.$anonfun$openFromURI$1(FileManager.scala:280)
 at org.nlogo.app.FileManager.$anonfun$openFromURI$1$adapted(FileManager.scala:280)
 at scala.Option.foreach(Option.scala:274)
 at org.nlogo.app.FileManager.openFromURI(FileManager.scala:280)
 at org.nlogo.app.FileManager$ModelsLibraryAction.$anonfun$action$1(FileManager.scala:87)
 at org.nlogo.app.FileManager$ModelsLibraryAction.$anonfun$action$1$adapted(FileManager.scala:87)
 at scala.Option.foreach(Option.scala:274)
 at org.nlogo.app.tools.ModelsLibraryDialog$.finishOpen(ModelsLibraryDialog.scala:65)
 at org.nlogo.app.tools.ModelsLibraryDialog$.open(ModelsLibraryDialog.scala:57)
 at org.nlogo.app.FileManager$ModelsLibraryAction.action(FileManager.scala:87)
 at org.nlogo.app.common.ExceptionCatchingAction.actionPerformed(Actions.scala:113)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
 at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
 at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
 at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
 at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
 at javax.swing.AbstractButton.doClick(AbstractButton.java:356)
 at javax.swing.plaf.basic.BasicMenuItemUI$Actions.actionPerformed(BasicMenuItemUI.java:811)
 at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1668)
 at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
 at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:699)
 at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706)
 at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706)
 at javax.swing.JMenuBar.processKeyBinding(JMenuBar.java:677)
 at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:307)
 at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:293)
 at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2974)
 at javax.swing.JComponent.processKeyBindings(JComponent.java:2966)
 at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
 at java.awt.Component.processEvent(Component.java:6316)
 at java.awt.Container.processEvent(Container.java:2239)
 at java.awt.Component.dispatchEventImpl(Component.java:4889)
 at java.awt.Container.dispatchEventImpl(Container.java:2297)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
 at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:835)
 at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1103)
 at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:974)
 at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:800)
 at java.awt.Component.dispatchEventImpl(Component.java:4760)
 at java.awt.Container.dispatchEventImpl(Container.java:2297)
 at java.awt.Window.dispatchEventImpl(Window.java:2746)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
 at java.awt.EventQueue$4.run(EventQueue.java:733)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.github.sarxos.webcam.WebcamException: java.util.concurrent.ExecutionException: com.github.sarxos.webcam.WebcamException: Cannot execute task
 at com.github.sarxos.webcam.WebcamDiscoveryService.getWebcams(WebcamDiscoveryService.java:124)
 at com.github.sarxos.webcam.Webcam.getWebcams(Webcam.java:874)
 at org.nlogo.extensions.vid.Camera$.$anonfun$cameraNames$1(Camera.scala:35)
 at org.nlogo.extensions.vid.Camera$.withContextClassLoader(Camera.scala:27)
 at org.nlogo.extensions.vid.Camera$.<init>(Camera.scala:35)
 at org.nlogo.extensions.vid.Camera$.<clinit>(Camera.scala)
 ... 128 more
Caused by: java.util.concurrent.ExecutionException: com.github.sarxos.webcam.WebcamException: Cannot execute task
 at java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.util.concurrent.FutureTask.get(FutureTask.java:192)
 at com.github.sarxos.webcam.WebcamDiscoveryService.getWebcams(WebcamDiscoveryService.java:116)
 ... 133 more
Caused by: com.github.sarxos.webcam.WebcamException: Cannot execute task
 at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.process(WebcamProcessor.java:72)
 at com.github.sarxos.webcam.WebcamProcessor.process(WebcamProcessor.java:140)
 at com.github.sarxos.webcam.WebcamTask.process(WebcamTask.java:46)
 at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$GetDevicesTask.getDevices(WebcamDefaultDriver.java:79)
 at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver.getDevices(WebcamDefaultDriver.java:124)
 at com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:36)
 at com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:26)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsatisfiedLinkError: com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber.getVideoDevices()Lorg/bridj/Pointer;
 at com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber.getVideoDevices(Native Method)
 at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$GetDevicesTask.handle(WebcamDefaultDriver.java:93)
 at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.run(WebcamProcessor.java:81)
 ... 3 more

NetLogo 6.1.1
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_202 (Oracle Corporation; 1.8.0_202-b08)
operating system: Mac OS X 10.15.5 (x86_64 processor)
Scala version 2.12.8
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Movie Playing Example

10:49:12.883 RemoveAllJobsEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
10:49:12.879 LoadEndEvent (org.nlogo.window.ReconfigureWorkspaceUI$Loader (java.lang.Object)) AWT-EventQueue-0
10:49:12.879 WidgetAddedEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
10:49:12.879 WidgetAddedEvent (org.nlogo.window.MonitorWidget) AWT-EventQueue-0
10:49:12.878 CompileMoreSourceEvent (org.nlogo.window.MonitorWidget) AWT-EventQueue-0
10:49:12.878 WidgetAddedEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
10:49:12.878 CompileMoreSourceEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
10:49:12.878 RemoveJobEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
10:49:12.878 WidgetAddedEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
10:49:12.878 CompileMoreSourceEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0

**Comment by brandesNW** [comment]
Thanks for letting us know about this issue. 
Your problem is very similar to a report included in the issue

https://github.com/NetLogo/vid/issues/20

We have not been able to reproduce that issue, and have determined that a separate (but probably connected) issue in the vid extension occurs on MacOS, but not linux.
The problem seems to be related to an external package com.github.sarxos.webcam used by the extension.

We would appreciate it if you could send us a model that reliably produces the error on your system. This would facilitate our ability to get help from the producer of the external package.

**Comment by lofyer** [comment]
Model:
Code Examples/Extension Examples/vid/*.logo
All these three models occur the error.

**Comment by LaCuneta** [comment]
I linked to this to a tracking issue in the Vid Extension repo.  Updates will be provided there, and feel free to add any comments there, too.

**Comment by LaCuneta** [comment]
@lofyer We recently released an updated version of the Vid extension that should hopefully address this issue.  You can use [the extensions manager](https://ccl.northwestern.edu/netlogo/docs/extension-manager.html) from within NetLogo to update to it.  

Also, please make sure NetLogo has permissions to use the camera on your system.  You can open System Preferences, Security & Privacy, then the Privacy Tab, select Camera in the list, and allow NetLogo to use the camera.  You will need to quit and re-open NetLogo for the change to take effect.  See this link for more details:  https://support.apple.com/en-euro/guide/mac-help/mchlf6d108da/mac

If you still have trouble with it, feel free to open a new issue in [the Vid repository](https://github.com/NetLogo/Vid-Extension/issues).  Thanks.

**Comment by lofyer** [comment]
Thanks, it works!

But Netlogo did not request Camera permission, I have to add it to the permission list manually with following commands.
OS: MacOS 12.3.1

sudo csrutil disable # in recover os

sudo sqlite3 ~/Library/Application\ Support/com.apple.TCC/TCC.db "INSERT or REPLACE INTO access VALUES('kTCCServiceCamera','org.nlogo.NetLogo3D',0,2,4,1,NULL,NULL,NULL,'UNUSED',NULL,0,1637381304);

sudo sqlite3 ~/Library/Application\ Support/com.apple.TCC/TCC.db "INSERT or REPLACE INTO access VALUES('kTCCServiceCamera','org.nlogo.NetLogo3D',0,2,4,1,NULL,NULL,NULL,'UNUSED',NULL,0,1637381304);

**Comment by lofyer** [comment]
> @lofyer We recently released an updated version of the Vid extension that should hopefully address this issue. You can use [the extensions manager](https://ccl.northwestern.edu/netlogo/docs/extension-manager.html) from within NetLogo to update to it.
> 
> Also, please make sure NetLogo has permissions to use the camera on your system. You can open System Preferences, Security & Privacy, then the Privacy Tab, select Camera in the list, and allow NetLogo to use the camera. You will need to quit and re-open NetLogo for the change to take effect. See this link for more details: https://support.apple.com/en-euro/guide/mac-help/mchlf6d108da/mac
> 
> If you still have trouble with it, feel free to open a new issue in [the Vid repository](https://github.com/NetLogo/Vid-Extension/issues). Thanks.


Thanks, it works!

But Netlogo did not request Camera permission, I have to add it to the permission list manually with following commands.
OS: MacOS 12.3.1

```
sudo csrutil disable # in recover os

sudo sqlite3 ~/Library/Application\ Support/com.apple.TCC/TCC.db "INSERT or REPLACE INTO access VALUES('kTCCServiceCamera','org.nlogo.NetLogo3D',0,2,4,1,NULL,NULL,NULL,'UNUSED',NULL,0,1637381304);

sudo sqlite3 ~/Library/Application\ Support/com.apple.TCC/TCC.db "INSERT or REPLACE INTO access VALUES('kTCCServiceCamera','org.nlogo.NetLogo3D',0,2,4,1,NULL,NULL,NULL,'UNUSED',NULL,0,1637381304);
```

**Comment by LaCuneta** [comment]
@lofyer You are still using NetLogo 6.1, correct?  I think we may have started including camera permissions in the app manifest as of 6.2.0+

**Comment by lofyer** [comment]
> @lofyer You are still using NetLogo 6.1, correct? I think we may have started including camera permissions in the app manifest as of 6.2.0+

No, I'm using 6.2.2
