### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by zahraahussein** [NetLogo/NetLogo#1843]
copy of my code:
`extensions [csv]

turtles-own [var  rank ]
to setup
  clear-all
  file-close-all ; Close any files open from last run
  reset-ticks
end
to read-turtles-from-csv
  file-close-all ; close all open files

  if not file-exists? "turtles.csv" [
    user-message "No file 'turtles.csv' exists! Try pressing WRITE-TURTLES-TO-CSV."
    stop
  ]

  file-open "turtles.csv" ; open the file with the turtle data

  ; We'll read all the data in a single loop
  while [ not file-at-end? ] [
    ; here the CSV extension grabs a single line and puts the read data in a list
    let data csv:from-row file-read-line
    create-turtles 1 [
      set var item 0 data

    ]
    ; now we can use that list to create a turtle with the saved properties
  ; if file-at-end? [stop]
    let rank-list sort-on [ var ] turtles
  let ranks n-values length rank-list [ ? ]
  (foreach rank-list ranks [ ask ?1 [ set rank ?2 ] ])
    csv:to-file "turtles1.csv" rank-list

  ]

  file-close ; make sure to close the file
end`
error
error (MatchError)
 while observer running CSV:TO-FILE
  called by procedure READ-TURTLES-FROM-CSV
  called by Button 'read-turtles-from-csv'

NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

scala.MatchError: turtle 0 (of class org.nlogo.agent.Turtle3D)
 at org.nlogo.extensions.csv.CSVExtension$ToFile$$anonfun$perform$1$$anonfun$apply$2.apply(CSVExtension.scala:88)
 at org.nlogo.extensions.csv.CSVExtension$ToFile$$anonfun$perform$1$$anonfun$apply$2.apply(CSVExtension.scala:88)
 at scala.collection.Iterator$class.foreach(Iterator.scala:772)
 at scala.collection.immutable.VectorIterator.foreach(Vector.scala:648)
 at org.nlogo.extensions.csv.CSVExtension$ToFile$$anonfun$perform$1.apply(CSVExtension.scala:88)
 at org.nlogo.extensions.csv.CSVExtension$ToFile$$anonfun$perform$1.apply(CSVExtension.scala:87)
 at org.nlogo.extensions.csv.CSVExtension.using(CSVExtension.scala:110)
 at org.nlogo.extensions.csv.CSVExtension$ToFile.perform(CSVExtension.scala:87)
 at org.nlogo.prim._extern.perform(_extern.java:54)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:91)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.java:82)
 at org.nlogo.job.JobThread.org$nlogo$job$JobThread$$runPrimaryJobs(JobThread.scala:143)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply$mcV$sp(JobThread.scala:78)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at scala.util.control.Exception$Catch.apply(Exception.scala:88)
 at org.nlogo.util.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:75)

NetLogo 3D 5.3.1
main: org.nlogo.app.AppFrame
thread: JobThread
Java HotSpot(TM) Client VM 1.8.0_74 (Oracle Corporation; 1.8.0_74-b02)
operating system: Windows 10 10.0 (x86 processor)
Scala version 2.9.2
JOGL: 2.3.2
OpenGL graphics: Intel(R) HD Graphics 3000
OpenGL version: 3.1.0 - Build 9.17.10.4459
OpenGL vendor: Intel
model: rank

10:26:50.032 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
10:26:50.026 RuntimeErrorEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:26:49.953 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:26:49.759 AddJobEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
10:26:49.730 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:26:49.625 InputBoxLoseFocusEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
10:26:49.530 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:26:49.329 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:26:49.129 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:26:48.929 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

**Comment by SethTisue** [comment]
is the problem reproducible in current NetLogo (6.1.x)?

**Comment by zahraahussein** [comment]
this error in  NetLogo 6.1
Extension exception: Couldn't create file: C:\Users\zahraa\Desktop\turtles1.csv
error while observer running CSV:TO-FILE
  called by procedure READ-TURTLES-FROM-CSV
  called by Button 'read-turtles-from-csv'

org.nlogo.nvm.WrappedExtensionException: Extension exception: Couldn't create file: C:\Users\zahraa\Desktop\turtles1.csv
 at org.nlogo.prim._extern.perform(_extern.java:40)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
 at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
 at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
 at scala.util.control.Exception$Catch.apply(Exception.scala:228)
 at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:66)
Caused by: org.nlogo.api.ExtensionException: Couldn't create file: C:\Users\zahraa\Desktop\turtles1.csv
 at org.nlogo.extensions.csv.CSVExtension$ToFile.perform(CSVExtension.scala:105)
 at org.nlogo.prim._extern.perform(_extern.java:36)
 ... 8 more
Caused by: java.io.FileNotFoundException: C:\Users\zahraa\Desktop\turtles1.csv (The process cannot access the file because it is being used by another process)
 at java.io.FileOutputStream.open0(Native Method)
 at java.io.FileOutputStream.open(FileOutputStream.java:270)
 at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
 at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
 at java.io.PrintWriter.<init>(PrintWriter.java:263)
 at org.nlogo.extensions.csv.CSVExtension$ToFile.perform(CSVExtension.scala:99)
 ... 9 more

NetLogo 6.1.1
main: org.nlogo.app.AppFrame
thread: JobThread
Java HotSpot(TM) Client VM 1.8.0_202 (Oracle Corporation; 1.8.0_202-b08)
operating system: Windows 10 10.0 (x86 processor)
Scala version 2.12.8
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: rank

05:02:50.410 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
05:02:50.407 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
05:02:50.375 RuntimeErrorEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
05:02:50.361 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
05:02:49.795 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
05:02:46.999 AddJobEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
05:02:46.899 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
05:02:46.870 InputBoxLoseFocusEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
05:02:46.698 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
05:02:46.498 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

**Comment by SethTisue** [comment]
```
Caused by: java.io.FileNotFoundException: C:\Users\zahraa\Desktop\turtles1.csv (The process cannot access the file because it is being used by another process)
```

but this is a different problem than your original report

**Comment by zahraahussein** [comment]
I tried on two version
And in the two I have a different problem

**Comment by SethTisue** [comment]
the `java.io.FileNotFoundException` seems to be not a bug in NetLogo, but an actual problem with not being able to have the same file open in two different applications. close the other application, or use a different filename

at that point, either your problem will be solved, or you'll be back to getting the `scala.MatchError`. only if you can reproduce the `scala.MatchError` in 6.1.1 is there something actionable for us here

**Comment by brandesNW** [comment]
I think the program needs to be debugged, and there is likely no NetLogo issue.

Here are a few corrected problems: (** denotes changed code)

  file-open "turtles.csv" ; open the file with the turtle data
  
  ; We'll read all the data in a single loop
  while [ not file-at-end? ] [
    ; here the CSV extension grabs a single line and puts the read data in a list
    let data csv:from-row file-read-line
    create-turtles 1 [
      set var item 0 data
    ]
  ]
  
  file-close ; make sure to close the file ** this was being done later
  
  ; now we can use that list to create a turtle with the saved properties

  let rank-list sort-on [ var ] turtles
  let ranks (range 1 (length rank-list + 1)) ;  ** got compilation error
  
  (foreach rank-list ranks 
    [[ t r ] -> ask t [ set rank r]])  ; ** current syntax of anonymous functions

  ;csv:to-file "turtles1.csv" rank-list.  ;** 

; rank-list is a list of turtles not a list of the lists that should be written to the file
