### ISSUE TITLE
Misleading message when attempt to open a "recent file" that does not exist

### ISSUE THREAD

**Issue by brandesNW** [NetLogo/NetLogo#1862]
**To reproduce:**

1. Open a model in NetLogo.
2. Close the model.
3. Delete, rename or move the model.
4. Attempt to open the model in the File->Recent Files drop-down menu.

A box with the following error messages opens
**NetLogo can't open the model**
**path-to-model**
**:**

**Unable to open model with current format:**
**path-to-model**
**.**

A more appropriate message would be
**Model File path-to-model not found.**
or 
**Model File path-to-model does not exist.**

There is no problem with the model format.

**Comment by Add-mac** [comment]
Hey @LaCuneta

Below is what I have done.

add@add-air NetLogo 6.2.0 %  ./netlogo-headless.sh --model "/Applications/NetLogo 6.2.0/app/models/Curricular Models/BEAGLE Evolution/Red Queen.nlogo" --experiment "Final Counts" --table -

Exception in thread "main" java.lang.Exception: Unable to open model with current format: /Applications/NetLogo 6.2.0/app/models/Curricular Models/BEAGLE Evolution/Red Queen.nlogo
	at org.nlogo.api.ModelLoader.readModel(ModelLoader.scala:65)
	at org.nlogo.api.ModelLoader.readModel$(ModelLoader.scala:60)
	at org.nlogo.api.ConfigurableModelLoader.readModel(ModelLoader.scala:106)
	at org.nlogo.headless.HeadlessWorkspace.open(HeadlessWorkspace.scala:502)
	at org.nlogo.headless.Main$.newWorkspace$1(Main.scala:18)
	at org.nlogo.headless.Main$.runExperiment(Main.scala:21)
	at org.nlogo.headless.Main$.$anonfun$main$1(Main.scala:12)
	at org.nlogo.headless.Main$.$anonfun$main$1$adapted(Main.scala:12)
	at scala.Option.foreach(Option.scala:407)
	at org.nlogo.headless.Main$.main(Main.scala:12)
	at org.nlogo.headless.Main.main(Main.scala)

**Comment by Add-mac** [comment]
Hey @LaCuneta 

It works with the following directory in Mac. Thanks for your help!

add@add-air NetLogo 6.2.0 %  ./netlogo-headless.sh --model "/Applications/NetLogo 6.2.0/models/Curricular Models/BEAGLE Evolution/Red Queen.nlogo"

**Comment by LaCuneta** [comment]
I ran the steps to reproduce this in NetLogo 6.1.1 and the same misleading error message appeared as in 6.2.0.  I ran them in NetLogo 6.0.4 and the error message was a much more normal "No such file" one.  So looks like this was a regression in NetLogo 6.1.0 or 6.1.1.
