### ISSUE TITLE
Python Basic Example: Internal Error

### ISSUE THREAD

**Issue by cynthia-w** [NetLogo/NetLogo#1863]
After pressing "setup", I get the following error:

NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 

java.lang.IllegalStateException
 at scala.util.matching.Regex$MatchIterator.ensure(Regex.scala:850)
 at scala.util.matching.Regex$MatchIterator.groupCount(Regex.scala:869)
 at org.nlogo.extensions.py.PythonBinary$.$anonfun$fromFile$2(PythonExtension.scala:150)
 at scala.Option.flatMap(Option.scala:188)
 at org.nlogo.extensions.py.PythonBinary$.fromFile(PythonExtension.scala:148)
 at org.nlogo.extensions.py.PythonSubprocess$.$anonfun$pythons$3(PythonExtension.scala:253)
 at scala.collection.immutable.Stream.flatMap(Stream.scala:489)
 at org.nlogo.extensions.py.PythonSubprocess$.pythons(PythonExtension.scala:253)
 at org.nlogo.extensions.py.PythonSubprocess$.$anonfun$python3$4(PythonExtension.scala:246)
 at scala.Option.orElse(Option.scala:306)
 at org.nlogo.extensions.py.PythonSubprocess$.python3(PythonExtension.scala:246)
 at org.nlogo.extensions.py.PythonSubprocess$.anyPython(PythonExtension.scala:248)
 at org.nlogo.extensions.py.PythonExtension.$anonfun$load$5(PythonExtension.scala:512)
 at org.nlogo.extensions.py.FindPython.report(PythonExtension.scala:590)
 at org.nlogo.extensions.py.FindPython.report(PythonExtension.scala:585)
 at org.nlogo.prim._externreport.report(_externreport.java:31)
 at org.nlogo.nvm.Argument.unsafeGet(Argument.scala:33)
 at org.nlogo.nvm.Argument.getString(Argument.scala:111)
 at org.nlogo.extensions.py.SetupPython$.$anonfun$perform$1(PythonExtension.scala:549)
 at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
 at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
 at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
 at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
 at scala.collection.TraversableLike.map(TraversableLike.scala:237)
 at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
 at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
 at org.nlogo.extensions.py.SetupPython$.perform(PythonExtension.scala:549)
 at org.nlogo.prim._extern.perform(_extern.java:36)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
 at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
 at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
 at scala.util.control.Exception$Catch.apply(Exception.scala:228)
 at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:66)

NetLogo 6.1.1
main: org.nlogo.app.AppFrame
thread: JobThread
Java HotSpot(TM) 64-Bit Server VM 1.8.0_202 (Oracle Corporation; 1.8.0_202-b08)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.8
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Python Basic Example

09:22:25.076 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
09:22:25.060 RuntimeErrorEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:22:25.060 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
09:22:25.060 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
09:22:25.060 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
09:22:25.060 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
09:22:25.060 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:22:24.871 AddJobEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
09:22:24.856 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
09:22:24.856 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0

**Comment by brandesNW** [comment]
This problem is reproducable on a Windows system, but not my Mac system.


As a workaround to this problem, the user can set the location of the python executable  permanently by using the configuration menu under the Python toolbar menu that appears when you use a model that uses the Python extension.

For more details see the documentation section [Configuring Python] (https://ccl.northwestern.edu/netlogo/docs/py.html#configuring) for help.

To determine the location of the python installation in a Windows system, open a cmd window and type ‘where python’ (without quotes) 
where python

In my case the result was
C:\ProgramData\Anaconda3\python.exe
which I entered in the. Configuration window for python3

Note: typing C:\ProgramData\Anaconda3\python.exe in the cmd window puts you into the python environment, and will show you whether you are using python2 or python3. Use “quit()” to exit.

Note: for linux or Mac users you can determine the location of the executable by using ‘which python’
