### ISSUE TITLE
Reporting a bug

### ISSUE THREAD

**Issue by ddanesh2** [NetLogo/NetLogo#1887]
java.lang.ArrayIndexOutOfBoundsException: 13
 at org.nlogo.agent.Turtle.realloc(Turtle.java:213)
 at org.nlogo.agent.Turtle.realloc(Turtle.java:183)
 at org.nlogo.agent.Realloc$.realloc(Realloc.scala:41)
 at org.nlogo.agent.CompilationManagement.realloc(CompilationManagement.scala:70)
 at org.nlogo.agent.CompilationManagement.realloc$(CompilationManagement.scala:69)
 at org.nlogo.agent.World2D.realloc(World.scala:138)
 at org.nlogo.window.CompilerManager.compileAll(CompilerManager.scala:180)
 at org.nlogo.window.CompilerManager.handle(CompilerManager.scala:137)
 at org.nlogo.window.Events$CompileAllEvent.beHandledBy(Events.java:185)
 at org.nlogo.window.Event.doRaise(Event.java:198)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.app.codetab.CodeTab.compile(CodeTab.scala:158)
 at org.nlogo.app.codetab.CodeTab$CompileAction$.actionPerformed(CodeTab.scala:193)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
 at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
 at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
 at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
 at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
 at java.awt.Component.processMouseEvent(Component.java:6539)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
 at java.awt.Component.processEvent(Component.java:6304)
 at java.awt.Container.processEvent(Container.java:2239)
 at java.awt.Component.dispatchEventImpl(Component.java:4889)
 at java.awt.Container.dispatchEventImpl(Container.java:2297)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
 at java.awt.Container.dispatchEventImpl(Container.java:2283)
 at java.awt.Window.dispatchEventImpl(Window.java:2746)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
 at java.awt.EventQueue$4.run(EventQueue.java:733)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

NetLogo 6.1.1
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_202 (Oracle Corporation; 1.8.0_202-b08)
operating system: Mac OS X 10.16 (x86_64 processor)
Scala version 2.12.8
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: ChemozoaModel

10:53:20.933 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
10:53:20.880 RemoveAllJobsEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
10:53:20.880 CompileAllEvent (org.nlogo.app.codetab.MainCodeTab) AWT-EventQueue-0
10:53:20.801 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
10:53:20.801 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
10:53:20.801 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
10:53:20.801 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
10:53:20.801 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
10:53:20.801 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
10:53:20.801 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

**Comment by brandesNW** [comment]
Hi,
Thanks for your interest in NetLogo modeling, and for including the debug information We are sorry you have encountered a problem.

In order to help you further we need more information.
The most helpful thing would be for you to share with us a model along with instructions for reproducing the bug.
(Note – to share a model as an attachment you need to either put it in a zip file, or change its extension to one that will be accepted by github, such as .txt.)

Also - NetLogo 6.2.0 was released recently, and should be a painless upgrade from NetLogo 6.1.1. Please consider trying it out.

- Aaron
--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling

**Comment by ddanesh2** [comment]
Thank you for your quick response. I have attached my code in .html, I hope that works. If I try to check my code, the bug message pops up. Any guidance would be greatly appreciated. 


Dafna Danesh
Arizona State University | College of Liberal Arts and Sciences
Biological and Biomedical Sciences, B. S.
Research Intern, Arizona Cancer Evolution Center
ddanesh2@asu.edu

**Comment by brandesNW** [comment]
Hi Dafna,
Thanks for your reply, but the attachment didn’t come through.

If the model only requires the contents of the Code Tab plus buttons calling one or more of those procedures (such as setup and go) then you can just paste
the code into your message.
If your model sets global variables using widgets such as sliders you can either move the globals into the Code tab and then include the text.

Otherwise you can copy your model file and rename it, for example from myModel.nlogo to myModel.txt

github only accepts the following file types


  *   PNG (. png)
  *   GIF (. gif)h
  *   JPEG (. jpg)
  *   Log files (. log)
  *   Microsoft Word (. docx), Powerpoint (. ...
  *   Text files (. txt)
  *   PDFs (. pdf)
  *   ZIP (. zip, .
The maximum size for files is 25MB and the maximum size for images is 10MB.

Thanks,
Aaron
--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling
