### ISSUE TITLE
NetLogo is unable to supply you with more details about this error. 

### ISSUE THREAD

**Issue by kidstoneszk** [NetLogo/NetLogo#1893]
NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 

java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
 at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
 at java.awt.image.BufferedImage.<init>(BufferedImage.java:333)
 at org.nlogo.plot.PlotPainter.setupOffscreenImage(PlotPainter.scala:26)
 at org.nlogo.window.PlotCanvas.repaintIfNeeded(PlotCanvas.java:16)
 at org.nlogo.window.PlotWidget.repaintIfNeeded(PlotWidget.scala:61)
 at org.nlogo.window.PlotWidget.handle(PlotWidget.scala:33)
 at org.nlogo.window.Events$PeriodicUpdateEvent.beHandledBy(Events.java:596)
 at org.nlogo.window.Event.doRaise(Event.java:198)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.window.GUIWorkspace$6.run(GUIWorkspace.java:650)
 at org.nlogo.window.ThreadUtils$.$anonfun$waitFor$1(ThreadUtils.scala:16)
 at org.nlogo.window.ThreadUtils$$anon$2.run(ThreadUtils.scala:24)
 at org.nlogo.window.ThreadUtils$$anon$2.run(ThreadUtils.scala:23)
 at org.nlogo.window.ThreadUtils$$anon$3.run(ThreadUtils.scala:49)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

NetLogo 6.1.1
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_202 (Oracle Corporation; 1.8.0_202-b08)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.8
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: SIMPLE-crop-model_withSpatialDiversity

11:53:31.181 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
11:53:31.181 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
11:53:31.181 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
11:53:31.181 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:53:31.181 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:53:31.181 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:53:31.180 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:53:31.180 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:53:31.180 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
11:53:31.179 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0

**Comment by brandesNW** [comment]
Thanks for your interest in NetLogo modeling, and for sending us the debug information from the error window.
We are sorry you have encountered a problem.

In order to help you further we need more information.
The most helpful thing would be for you to share with us your model along with instructions for reproducing the bug.

To share a .nlogo model file please include it in a zip file or change the extension because your reply is handled by a github program that  accepts only the following attachment formats:
PNG (.png)
GIF (.gif)
JPEG (.jpg)
Log files (.log)
Microsoft Word (.docx), Powerpoint (.pptx), and Excel (.xlsx) documents.
Text files (.txt)
PDFs (.pdf)
ZIP (.zip, .gz)

Thanks,
Aaron

--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling

**Comment by ERSUCC** [comment]
This was resolved in commit [6cd8ef6](https://github.com/NetLogo/NetLogo/commit/6cd8ef6a990ee63a7ce632156fcd904d5a0f4398).

**Comment by TheBizzle** [comment]
This was a duplicate of #900.
