### ISSUE TITLE
R extension

### ISSUE THREAD

**Issue by gydms135** [NetLogo/NetLogo#1905]
I am struggling to set up the r extension

and then, come up with this error message which recommends reporting here

java.lang.NoClassDefFoundError: org/nlogo/api/Primitive
 at java.lang.Class.getDeclaredConstructors0(Native Method)
 at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
 at java.lang.Class.getConstructor0(Class.java:3075)
 at java.lang.Class.newInstance(Class.java:412)
 at org.nlogo.workspace.JarLoader.extensionClassManager(JarLoader.scala:48)
 at org.nlogo.workspace.ExtensionManager.$anonfun$importExtension$8(ExtensionManager.scala:159)
 at scala.Option.getOrElse(Option.scala:138)
 at org.nlogo.workspace.ExtensionManager.importExtension(ExtensionManager.scala:157)
 at org.nlogo.parse.StructureParser$.$anonfun$parsingWithExtensions$1(StructureParser.scala:74)
 at org.nlogo.parse.StructureParser$.$anonfun$parsingWithExtensions$1$adapted(StructureParser.scala:68)
 at scala.collection.immutable.List.foreach(List.scala:392)
 at org.nlogo.parse.StructureParser$.parsingWithExtensions(StructureParser.scala:68)
 at org.nlogo.parse.StructureParser$.parseSources(StructureParser.scala:33)
 at org.nlogo.parse.NetLogoParser.basicParse(NetLogoParser.scala:17)
 at org.nlogo.parse.NetLogoParser.basicParse$(NetLogoParser.scala:15)
 at org.nlogo.parse.FrontEnd$.basicParse(FrontEnd.scala:10)
 at org.nlogo.parse.FrontEndMain.frontEnd(FrontEnd.scala:26)
 at org.nlogo.parse.FrontEndMain.frontEnd$(FrontEnd.scala:25)
 at org.nlogo.parse.FrontEnd$.frontEnd(FrontEnd.scala:10)
 at org.nlogo.compile.CompilerMain$.compile(CompilerMain.scala:43)
 at org.nlogo.compile.Compiler.compileProgram(Compiler.scala:54)
 at org.nlogo.window.CompilerManager.compileProcedures(CompilerManager.scala:209)
 at org.nlogo.window.CompilerManager.compileAll(CompilerManager.scala:173)
 at org.nlogo.window.CompilerManager.handle(CompilerManager.scala:137)
 at org.nlogo.window.Events$CompileAllEvent.beHandledBy(Events.java:185)
 at org.nlogo.window.Event.doRaise(Event.java:198)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.app.codetab.CodeTab.compile(CodeTab.scala:158)
 at org.nlogo.app.codetab.CodeTab$CompileAction$.actionPerformed(CodeTab.scala:193)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
 at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
 at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
 at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
 at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
 at java.awt.Component.processMouseEvent(Component.java:6539)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
 at java.awt.Component.processEvent(Component.java:6304)
 at java.awt.Container.processEvent(Container.java:2239)
 at java.awt.Component.dispatchEventImpl(Component.java:4889)
 at java.awt.Container.dispatchEventImpl(Container.java:2297)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
 at java.awt.Container.dispatchEventImpl(Container.java:2283)
 at java.awt.Window.dispatchEventImpl(Window.java:2746)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
 at java.awt.EventQueue$4.run(EventQueue.java:733)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: org.nlogo.api.Primitive
 at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
 at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:817)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
 ... 65 more

NetLogo 6.1.1
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_202 (Oracle Corporation; 1.8.0_202-b08)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.8
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Untitled

07:16:46.216 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
07:16:46.015 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
07:16:45.815 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
07:16:45.615 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
07:16:45.415 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
07:16:45.214 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
07:16:45.013 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
07:16:44.813 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
07:16:44.733 RemoveAllJobsEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
07:16:44.733 CompileAllEvent (org.nlogo.app.codetab.MainCodeTab) AWT-EventQueue-0

**Comment by brandesNW** [comment]
Hi,
We are sorry you have encountered this issue.
The R extension can be set up to work on Windows 10 environments. Setup includes editing an “Environment Variable.”
To make the process easier for us to help you debug, I recommend downloading and installing NetLogo 6.2.0<http://ccl.northwestern.edu/netlogo/download.shtml>, which was recently released.

Next please read over the instructions<https://ccl.northwestern.edu/netlogo/docs/r.html#installing> for installing R and configuring it with the extension. I will indicate one issue I ran into and how I got around it.
Pay particular attention to the Windows-specific installation steps<https://ccl.northwestern.edu/netlogo/docs/r.html#windows-specific-installation-steps>
These are some of the specific steps I went through during installation. (I work primarily on a Mac and made a new installation of R on a Windows 10 machine.)

I downloaded R 4.0.4 for Windows<https://cran.r-project.org/bin/windows/base/>  and ran the installer with default options plus installing a desktop icon.
I opened R by double clicking the desktop icon.
I typed
install.packages("rJava")
For installation of the packages I accepted the default local location, and chose a mirror site for downloading
Next
install.packages("JavaGD") # Optional
install.packages("CommonJavaJars") # Optional
I collected the necessary system information
R.home(component = "home")
[1] "C:/PROGRA~1/R/R-40~1.4"

system.file("jri", package = "rJava")
[1] "C:/Users/MyName/Documents/R/win-library/4.0/rJava/jri"


I tried the Microsoft Visual C++ 2013 redistributable download<https://www.microsoft.com/en-us/download/details.aspx?id=40784>

Choosing the file vcredist_x64.exe
The files had already been installed, so the Installer referred to “modify setup” and had an option “repair.”
I therefore quit the installer, but you should proceed if you don’t have Microsoft Visual C++ 2013

Note: I have substituted “MyName” for my actual username throughout this email, and you should substitute in your username when making the changes.
The one discrepancy I ran into is that there was no file C:\Users\MyName\AppData\Roaming\NetLogo\6.2\r\user.properties
The directory existed but was empty.

You can download the user.properties file I have attached to C:\Users\MyName\AppData\Roaming\NetLogo\6.2\r

You should then edit the following lines to reflect your name and R installation. (You might be able to edit directly in NotePad because I already did the step of opening and saving with WordPad.)
r.home=C:/PROGRA~1/R/R-40~1.4
jri.home.paths=C:/Users/MyName/Documents/R/win-library/4.0/rJava/jri
r.lib.paths=C:/Users/MyName/Documents/R/win-library/4.0

After that you need to  edit your system environment variable Path
Use the New button to add the line (adapted if necessary)
C:\Program Files\R\R-4.0.4\bin\x64\

You will need to log in and out of Windows, or do a restart for the environment variable change to take effect.

Most NetLogo extensions are usable out of the box. Unfortunately multiple steps are needed to configure the R extension in Windows.

Please let us know if this works, or send us more specific information if you need more help.

Aaron

--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling

**Comment by brandesNW** [comment]
This was resolved to the user's satisfaction.
