### ISSUE TITLE
Transient language test failure in 3D

### ISSUE THREAD

**Issue by LaCuneta** [NetLogo/NetLogo#1919]
I saw [this failure in Jenkins](https://netlogobuild.northwestern.edu/job/NetLogo/job/hexy/359/console):

```
[info] - Tilt::TiltDownOne_3D *** FAILED ***
[info]   NormalMode: not equals(): reporter "[roll] of turtle 0" Expected "[0]", but got "[8.537736462515939E-7]" (AbstractTestLanguage.scala:74)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   ...
[info]   at org.nlogo.headless.AbstractTestLanguage.$anonfun$testReporter$1(AbstractTestLanguage.scala:74)
[info]   at org.scalatest.Assertions.withClue(Assertions.scala:1221)
[info]   at org.scalatest.Assertions.withClue$(Assertions.scala:1208)
[info]   at org.nlogo.headless.TestLanguage$LegacyLanguageTest$Tester$1.withClue(TestLanguage.scala:48)
[info]   at org.nlogo.headless.AbstractTestLanguage.testReporter(AbstractTestLanguage.scala:74)
[info]   at org.nlogo.headless.AbstractTestLanguage.testReporter$(AbstractTestLanguage.scala:61)
[info]   at org.nlogo.headless.TestLanguage$LegacyLanguageTest$Tester$1.testReporter(TestLanguage.scala:48)
[info]   ...
```

And here is that test:

```
TiltDownOne_3D
  O> crt 1
  [roll] of turtle 0 => 0
  [pitch] of turtle 0 => 0
  T> tilt-down 1
  [roll] of turtle 0 => 0
  [pitch] of turtle 0 => 359
  T> tilt-down 1
  [roll] of turtle 0 => 0
  [pitch] of turtle 0 => 358
```

There were no related changes in the commit that it failed during, and subsequent local runs and re-runs on Jenkins passed.

**Comment by ERSUCC** [comment]
This was resolved in commit [7b422d2](https://github.com/NetLogo/NetLogo/commit/7b422d2e5caae390190604db322497ff684c8fc1).
