### ISSUE TITLE
Reporting bug using eXtraWidgets extensions

### ISSUE THREAD

**Issue by gpetrini** [NetLogo/NetLogo#1930]
Hi every one!
I am really new on NetLogo and tried to use eXtraWidgets extensions following the example code in the documentation:

```
extensions [ xw ]

to startup
  xw:clear-all
  xw:create-tab "t1"
  xw:create-slider "population"
end
```

But I got the following error message:
```
Java.security.PrivilegedActionException: uk.ac.surrey.xw.api.XWException: Tab t1 does not exist.
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: uk.ac.surrey.xw.api.XWException: Tab t1 does not exist.
 at uk.ac.surrey.xw.api.ComponentWidget.setTab(ComponentWidget.scala:56)
 at uk.ac.surrey.xw.api.ComponentWidget.setTab$(ComponentWidget.scala:54)
 at uk.ac.surrey.xw.button.Button.setTab(Button.scala:38)
 at uk.ac.surrey.xw.api.ComponentWidgetKind.$anonfun$tabProperty$1(ComponentWidget.scala:14)
 at uk.ac.surrey.xw.api.ComponentWidgetKind.$anonfun$tabProperty$1$adapted(ComponentWidget.scala:14)
 at uk.ac.surrey.xw.api.Property.$anonfun$set$1(Property.scala:39)
 at uk.ac.surrey.xw.api.Property.$anonfun$set$1$adapted(Property.scala:39)
 at scala.Option.foreach(Option.scala:407)
 at uk.ac.surrey.xw.api.Property.set(Property.scala:39)
 at uk.ac.surrey.xw.api.ExtraWidget.$anonfun$setProperty$1(ExtraWidget.scala:29)
 at uk.ac.surrey.xw.api.ExtraWidget.$anonfun$setProperty$1$adapted(ExtraWidget.scala:28)
 at scala.Option.foreach(Option.scala:407)
 at uk.ac.surrey.xw.api.ExtraWidget.setProperty(ExtraWidget.scala:28)
 at uk.ac.surrey.xw.api.ExtraWidget.setProperty$(ExtraWidget.scala:25)
 at uk.ac.surrey.xw.button.Button.setProperty(Button.scala:38)
 at uk.ac.surrey.xw.api.ExtraWidget.$anonfun$init$3(ExtraWidget.scala:23)
 at uk.ac.surrey.xw.api.ExtraWidget.$anonfun$init$3$adapted(ExtraWidget.scala:23)
 at scala.collection.Iterator.foreach(Iterator.scala:943)
 at scala.collection.Iterator.foreach$(Iterator.scala:943)
 at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
 at scala.collection.IterableLike.foreach(IterableLike.scala:74)
 at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
 at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
 at uk.ac.surrey.xw.api.ExtraWidget.init(ExtraWidget.scala:23)
 at uk.ac.surrey.xw.api.ExtraWidget.init$(ExtraWidget.scala:18)
 at uk.ac.surrey.xw.button.Button.init(Button.scala:38)
 at uk.ac.surrey.xw.gui.GUI.$anonfun$addWidget$3(GUI.scala:69)
 at uk.ac.surrey.xw.gui.GUI.$anonfun$addWidget$3$adapted(GUI.scala:67)
 at scala.util.Either$RightProjection.foreach(Either.scala:652)
 at uk.ac.surrey.xw.gui.GUI.$anonfun$addWidget$2(GUI.scala:67)
 at uk.ac.surrey.xw.gui.GUI.$anonfun$addWidget$2$adapted(GUI.scala:65)
 at scala.util.Either$RightProjection.foreach(Either.scala:652)
 at uk.ac.surrey.xw.gui.GUI.addWidget(GUI.scala:65)
 at uk.ac.surrey.xw.gui.GUI.$anonfun$notify$1(GUI.scala:47)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
 at uk.ac.surrey.xw.api.package$$anon$1.run(package.scala:33)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 ... 9 more

NetLogo 6.2.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
OpenJDK 64-Bit Server VM 1.8.0_275 (BellSoft; 1.8.0_275-b01)
operating system: Linux 5.10.0-7-amd64 (amd64 processor)
Scala version 2.12.12
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: teste

05:22:03.009 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
05:22:03.009 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
05:22:02.916 AfterLoadEvent (org.nlogo.window.ReconfigureWorkspaceUI$Loader (java.lang.Object)) AWT-EventQueue-0
05:22:02.916 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
05:22:02.915 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
05:22:02.659 RemoveAllJobsEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
05:22:02.623 LoadEndEvent (org.nlogo.window.ReconfigureWorkspaceUI$Loader (java.lang.Object)) AWT-EventQueue-0
05:22:02.623 ResizeViewEvent (org.nlogo.window.ViewWidget) AWT-EventQueue-0
05:22:02.622 ResizeViewEvent (org.nlogo.window.ViewWidget) AWT-EventQueue-0
05:22:02.622 LoadWidgetsEvent (org.nlogo.window.ReconfigureWorkspaceUI$Loader (java.lang.Object)) AWT-EventQueue-0
```

I tried to install the extension both on =NetLogo 6.2.0/app/extentions/= and =~/.netlogo/extensions/= directories and same result.

There is another way to implement widgets in the code tab?

Thank you in advance

**Comment by brandesNW** [comment]
Hi Gabriel,
We are sorry you ran into this problem.
The eXtraWidgets is currently not compatible with NetLogo 6.2.0.
The author of the extension is planning to update it.

We recommend using NetLogo 6.2.0 because it has features and bug fixes not in earlier versions.

To explore eXtraWidgets you could go to our Download Page<https://ccl.northwestern.edu/netlogo/download.shtml> and select NetLogo 6.1.1.
Once it is installed you can work on either version of NetLogo.

Let us know if you have any other questions.

Aaron


--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling


From: Gabriel Petrini da Silveira ***@***.***>
Reply-To: NetLogo/NetLogo ***@***.***>
Date: Wednesday, June 23, 2021 at 4:28 PM
To: NetLogo/NetLogo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [NetLogo/NetLogo] Reporting bug using eXtraWidgets extensions (#1930)


Hi every one!
I am really new on NetLogo and tried to use eXtraWidgets extensions following the example code in the documentation:

extensions [ xw ]



to startup

  xw:clear-all

  xw:create-tab "t1"

  xw:create-slider "population"

end

But I got the following error message:

Java.security.PrivilegedActionException: uk.ac.surrey.xw.api.XWException: Tab t1 does not exist.

 at java.security.AccessController.doPrivileged(Native Method)

 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)

 at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)

 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)

 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)

 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)

 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)

 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)

 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Caused by: uk.ac.surrey.xw.api.XWException: Tab t1 does not exist.

 at uk.ac.surrey.xw.api.ComponentWidget.setTab(ComponentWidget.scala:56)

 at uk.ac.surrey.xw.api.ComponentWidget.setTab$(ComponentWidget.scala:54)

 at uk.ac.surrey.xw.button.Button.setTab(Button.scala:38)

 at uk.ac.surrey.xw.api.ComponentWidgetKind.$anonfun$tabProperty$1(ComponentWidget.scala:14)

 at uk.ac.surrey.xw.api.ComponentWidgetKind.$anonfun$tabProperty$1$adapted(ComponentWidget.scala:14)

 at uk.ac.surrey.xw.api.Property.$anonfun$set$1(Property.scala:39)

 at uk.ac.surrey.xw.api.Property.$anonfun$set$1$adapted(Property.scala:39)

 at scala.Option.foreach(Option.scala:407)

 at uk.ac.surrey.xw.api.Property.set(Property.scala:39)

 at uk.ac.surrey.xw.api.ExtraWidget.$anonfun$setProperty$1(ExtraWidget.scala:29)

 at uk.ac.surrey.xw.api.ExtraWidget.$anonfun$setProperty$1$adapted(ExtraWidget.scala:28)

 at scala.Option.foreach(Option.scala:407)

 at uk.ac.surrey.xw.api.ExtraWidget.setProperty(ExtraWidget.scala:28)

 at uk.ac.surrey.xw.api.ExtraWidget.setProperty$(ExtraWidget.scala:25)

 at uk.ac.surrey.xw.button.Button.setProperty(Button.scala:38)

 at uk.ac.surrey.xw.api.ExtraWidget.$anonfun$init$3(ExtraWidget.scala:23)

 at uk.ac.surrey.xw.api.ExtraWidget.$anonfun$init$3$adapted(ExtraWidget.scala:23)

 at scala.collection.Iterator.foreach(Iterator.scala:943)

 at scala.collection.Iterator.foreach$(Iterator.scala:943)

 at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)

 at scala.collection.IterableLike.foreach(IterableLike.scala:74)

 at scala.collection.IterableLike.foreach$(IterableLike.scala:73)

 at scala.collection.AbstractIterable.foreach(Iterable.scala:56)

 at uk.ac.surrey.xw.api.ExtraWidget.init(ExtraWidget.scala:23)

 at uk.ac.surrey.xw.api.ExtraWidget.init$(ExtraWidget.scala:18)

 at uk.ac.surrey.xw.button.Button.init(Button.scala:38)

 at uk.ac.surrey.xw.gui.GUI.$anonfun$addWidget$3(GUI.scala:69)

 at uk.ac.surrey.xw.gui.GUI.$anonfun$addWidget$3$adapted(GUI.scala:67)

 at scala.util.Either$RightProjection.foreach(Either.scala:652)

 at uk.ac.surrey.xw.gui.GUI.$anonfun$addWidget$2(GUI.scala:67)

 at uk.ac.surrey.xw.gui.GUI.$anonfun$addWidget$2$adapted(GUI.scala:65)

 at scala.util.Either$RightProjection.foreach(Either.scala:652)

 at uk.ac.surrey.xw.gui.GUI.addWidget(GUI.scala:65)

 at uk.ac.surrey.xw.gui.GUI.$anonfun$notify$1(GUI.scala:47)

 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)

 at uk.ac.surrey.xw.api.package$$anon$1.run(package.scala:33)

 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)

 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)

 at java.awt.EventQueue.access$500(EventQueue.java:97)

 at java.awt.EventQueue$3.run(EventQueue.java:709)

 at java.awt.EventQueue$3.run(EventQueue.java:703)

 ... 9 more



NetLogo 6.2.0

main: org.nlogo.app.AppFrame

thread: AWT-EventQueue-0

OpenJDK 64-Bit Server VM 1.8.0_275 (BellSoft; 1.8.0_275-b01)

operating system: Linux 5.10.0-7-amd64 (amd64 processor)

Scala version 2.12.12

JOGL: (3D View not initialized)

OpenGL Graphics: (3D View not initialized)

model: teste



05:22:03.009 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

05:22:03.009 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0

05:22:02.916 AfterLoadEvent (org.nlogo.window.ReconfigureWorkspaceUI$Loader (java.lang.Object)) AWT-EventQueue-0

05:22:02.916 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0

05:22:02.915 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0

05:22:02.659 RemoveAllJobsEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0

05:22:02.623 LoadEndEvent (org.nlogo.window.ReconfigureWorkspaceUI$Loader (java.lang.Object)) AWT-EventQueue-0

05:22:02.623 ResizeViewEvent (org.nlogo.window.ViewWidget) AWT-EventQueue-0

05:22:02.622 ResizeViewEvent (org.nlogo.window.ViewWidget) AWT-EventQueue-0

05:22:02.622 LoadWidgetsEvent (org.nlogo.window.ReconfigureWorkspaceUI$Loader (java.lang.Object)) AWT-EventQueue-0

I tried to install the extension both on =NetLogo 6.2.0/app/extentions/= and =~/.netlogo/extensions/= directories and same result.

There is another way to implement widgets in the code tab?

Thank you in advance
