### ISSUE TITLE
Uninstall of in-use extension causes exception

### ISSUE THREAD

**Issue by LaCuneta** [NetLogo/NetLogo#1965]
If you install an extension through the extension manager, then load a model that uses it, then try to uninstall that same extension, you'll get the below exception.  After this happens the extension manager can be opened, but no extensions can be installed, updated, or uninstalled (the buttons don't even appear).  This behavior persists until NetLogo is closed and re-opened, after which it functions normally again.

Ideally we'd check which extensions were loaded and not even allow the attempt at uninstall with a message about why.  Second best would just be catching the exception and displaying a more meaningful error message to the user.

```
NetLogo is unable to supply you with more details about this error.  Please report the problem
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.


java.security.PrivilegedActionException: java.nio.file.FileSystemException: C:\Users\home\AppData\Roaming\NetLogo\6.2\extensions\import-a\import-a.jar: The process cannot access the file because it is being used by another process.

 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.nio.file.FileSystemException: C:\Users\home\AppData\Roaming\NetLogo\6.2\extensions\import-a\import-a.jar: The process cannot access the file because it is being used by another process.

 at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
 at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
 at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
 at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
 at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
 at java.nio.file.Files.delete(Files.java:1126)
 at org.nlogo.api.ExtensionInstaller$$anon$1.delete(ExtensionInstaller.scala:52)
 at org.nlogo.api.ExtensionInstaller$$anon$1.visitFile(ExtensionInstaller.scala:48)
 at org.nlogo.api.ExtensionInstaller$$anon$1.visitFile(ExtensionInstaller.scala:46)
 at java.nio.file.Files.walkFileTree(Files.java:2670)
 at java.nio.file.Files.walkFileTree(Files.java:2742)
 at org.nlogo.api.ExtensionInstaller.uninstall(ExtensionInstaller.scala:46)
 at org.nlogo.api.LibraryManager.uninstallExtension(LibraryManager.scala:97)
 at org.nlogo.app.tools.LibrariesTab.$anonfun$uninstall$1(LibrariesTab.scala:62)
 at org.nlogo.app.tools.LibrariesTab.$anonfun$uninstall$1$adapted(LibrariesTab.scala:62)
 at org.nlogo.app.tools.LibrariesTab$Worker.doInBackground(LibrariesTab.scala:407)
 at org.nlogo.app.tools.LibrariesTab$Worker.doInBackground(LibrariesTab.scala:401)
 at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at javax.swing.SwingWorker.run(SwingWorker.java:334)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)

NetLogo 6.2.1
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
OpenJDK 64-Bit Server VM 1.8.0_275 (BellSoft; 1.8.0_275-b01)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.12
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Calorimetry

08:51:47.318 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
08:51:47.318 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
08:51:47.318 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
08:51:47.318 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
08:51:47.318 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
08:51:47.318 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
08:51:47.318 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
08:51:47.113 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
08:51:47.113 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
08:51:47.113 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
```

**Comment by ERSUCC** [comment]
Disallowing uninstalls while the extension is loaded is not a good solution, because dynamic libraries erroneously remain loaded after the extension is unloaded. As the user, it would be pretty weird to go to uninstall an extension after removing it from the model only to be told that it's still loaded. So the ideal fix here is to unload an extension and its dynamic libraries when the user clicks the uninstall button.

**Comment by TheBizzle** [comment]
Potential solution (or a step in the direction of a solution):

* Installing through the ExtMan saves extensions to directory `A`
* When loading an extension, if it resolved to a location within `A`, copy it to temporary directory `B` and load it from there
* Uninstalling through the ExtMan deletes the files from `A` and removes it from the ExtMan's registry of installed extensions
* `B` gets cleared on each launch of the application

(Possible degenerate case of copying the files: `vid` which is about 100MB in size.)

**Comment by ERSUCC** [comment]
@TheBizzle I experimented with a variety of alternate solutions, but unfortunately none of them worked. No matter how hard we try to release the resources associated with an extension, we can't control what goes on in that extension's code or the code of its dependencies. So the only completely foolproof way of preventing dangling file handles from affecting the Extension Manager is to create a copy of the jar, as you suggested.

Luckily, I don't think this will present any major issues, because at least on my system, copying `vid` to another location happens practically in an instant. Actually loading the necessary resources for the extension can take up to a few seconds, so I doubt anyone will notice the addition of a few milliseconds of copying.
