### ISSUE TITLE
Empty link monitor throws exception when number typed in as end value

### ISSUE THREAD

**Issue by LaCuneta** [NetLogo/NetLogo#1999]
If you open NetLogo with a new model, do **Tools** > **Link Monitor** to get the empty link monitor window, then type `1` into the `end1` box, you will get an exception like the one below.

In the empty turtle monitor you can type a `who` number to get a turtle.  In the empty patch monitor you can type a `pxcor` or `pycor` to get a patch.  I think it'd be desirable to let users enter numbers for `end1` and `end2` as turtle `who` numbers.  At the very least, no internal exception should occur if a user enters a number into the box, and preferably no error would occur at all.  Interestingly, if you type `turtle 1` into the `end1` box the value disappears and nothing happens (no error).  Also interestingly, typing an invalid `pxcor` like a string in the patch monitor gets swallowed without an error, but typing an invalid `pcolor` like a string causes a runtime error (not an internal exception).

The error happens at least as far back as NetLogo 6.0.4.

```
NetLogo is unable to supply you with more details about this error.  Please report the problem
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.


java.lang.ClassCastException: org.nlogo.core.Nobody$ cannot be cast to org.nlogo.agent.Turtle
 at org.nlogo.agent.AgentManagement.$anonfun$getOrCreateDummyLink$1(AgentManagement.scala:100)
 at scala.Option.getOrElse(Option.scala:189)
 at org.nlogo.agent.AgentManagement.getOrCreateDummyLink(AgentManagement.scala:100)
 at org.nlogo.agent.AgentManagement.getOrCreateDummyLink$(AgentManagement.scala:92)
 at org.nlogo.agent.World.getOrCreateDummyLink(World.scala:107)
 at org.nlogo.app.tools.AgentVarEditor.doAgentSwitch(AgentMonitorEditor.scala:358)
 at org.nlogo.app.tools.AgentVarEditor.action(AgentMonitorEditor.scala:326)
 at org.nlogo.app.tools.AgentVarEditor.keyPressed(AgentMonitorEditor.scala:236)
 at java.awt.Component.processKeyEvent(Component.java:6497)
 at javax.swing.JComponent.processKeyEvent(JComponent.java:2832)
 at java.awt.Component.processEvent(Component.java:6316)
 at java.awt.Container.processEvent(Container.java:2239)
 at java.awt.Component.dispatchEventImpl(Component.java:4889)
 at java.awt.Container.dispatchEventImpl(Container.java:2297)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
 at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:834)
 at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1102)
 at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:973)
 at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:799)
 at java.awt.Component.dispatchEventImpl(Component.java:4760)
 at java.awt.Container.dispatchEventImpl(Container.java:2297)
 at java.awt.Window.dispatchEventImpl(Window.java:2746)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
 at java.awt.EventQueue$4.run(EventQueue.java:733)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

NetLogo 6.2.2
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
OpenJDK 64-Bit Server VM 1.8.0_275 (BellSoft; 1.8.0_275-b01)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.15
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Untitled

02:25:28.617 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:25:28.403 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:25:28.200 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:25:27.984 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:25:27.779 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:25:27.472 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:25:27.268 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:25:27.066 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:25:26.864 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:25:26.661 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
```

**Comment by LaCuneta** [comment]
@brandesNW I don't know if the link monitor has ever really worked when opened through the menu.  I tested in NetLogo 5.3.1 and there typing a number in one of the link ends has it transform to `(turtle #)` with the other field `<null>` without throwing an error.  But replacing the `<null>` with a second turtle number that should correspond to a valid link doesn't seem to do anything.

I think the minimum behavior should be to allow a user to type turtle numbers into the fields, as you can with patch `pxcor` or `pycor` values.  It can pick a link from any that are valid for the given turtle number, and allow the user to type in a different turtle number for the other end if they desire afterwards.   Perhaps a better user experience would be to have it list the possible links for the given turtle for selection, but that's more complicated.
