### ISSUE TITLE
error opening 5.3.3 3D model in 6.2.2

### ISSUE THREAD

**Issue by maclennan** [NetLogo/NetLogo#2005]
NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 

java.lang.ExceptionInInitializerError
 at org.nlogo.extensions.vid.VidExtension$.$anonfun$camera$1(VidExtension.scala:13)
 at org.nlogo.extensions.vid.VidExtension$.guiOrHeadless(VidExtension.scala:9)
 at org.nlogo.extensions.vid.VidExtension$.camera$lzycompute(VidExtension.scala:13)
 at org.nlogo.extensions.vid.VidExtension$.camera(VidExtension.scala:13)
 at org.nlogo.extensions.vid.VidExtension.<init>(VidExtension.scala:21)
 at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
 at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
 at java.lang.Class.newInstance(Class.java:442)
 at org.nlogo.workspace.JarLoader.extensionClassManager(JarLoader.scala:48)
 at org.nlogo.workspace.ExtensionManager.$anonfun$importExtension$8(ExtensionManager.scala:159)
 at scala.Option.getOrElse(Option.scala:189)
 at org.nlogo.workspace.ExtensionManager.importExtension(ExtensionManager.scala:157)
 at org.nlogo.parse.StructureParser$.$anonfun$parsingWithExtensions$1(StructureParser.scala:74)
 at org.nlogo.parse.StructureParser$.$anonfun$parsingWithExtensions$1$adapted(StructureParser.scala:68)
 at scala.collection.immutable.List.foreach(List.scala:431)
 at org.nlogo.parse.StructureParser$.parsingWithExtensions(StructureParser.scala:68)
 at org.nlogo.parse.StructureParser$.parseSources(StructureParser.scala:33)
 at org.nlogo.parse.NetLogoParser.basicParse(NetLogoParser.scala:17)
 at org.nlogo.parse.NetLogoParser.basicParse$(NetLogoParser.scala:15)
 at org.nlogo.parse.AstRewriter.basicParse(AstRewriter.scala:20)
 at org.nlogo.parse.AstRewriter.rewrite(AstRewriter.scala:147)
 at org.nlogo.parse.AstRewriter.replaceCommand(AstRewriter.scala:34)
 at org.nlogo.fileformat.AutoConversionList$.$anonfun$conversions$6(AutoConversionList.scala:43)
 at org.nlogo.fileformat.ModelConverter.$anonfun$apply$9(ModelConverter.scala:125)
 at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
 at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
 at scala.collection.immutable.List.foldLeft(List.scala:91)
 at org.nlogo.fileformat.ModelConverter.$anonfun$apply$8(ModelConverter.scala:121)
 at scala.util.Try$.apply(Try.scala:213)
 at org.nlogo.fileformat.ModelConverter.convertedCodeTab$lzycompute$1(ModelConverter.scala:121)
 at org.nlogo.fileformat.ModelConverter.convertedCodeTab$1(ModelConverter.scala:119)
 at org.nlogo.fileformat.ModelConverter.applyConversion$1(ModelConverter.scala:167)
 at org.nlogo.fileformat.ModelConverter.runConversion$1(ModelConverter.scala:111)
 at org.nlogo.fileformat.ModelConverter.$anonfun$apply$20(ModelConverter.scala:172)
 at org.nlogo.fileformat.SuccessfulConversion.mergeResult(ConversionResult.scala:31)
 at org.nlogo.fileformat.ModelConverter.$anonfun$apply$19(ModelConverter.scala:172)
 at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
 at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
 at scala.collection.immutable.List.foldLeft(List.scala:91)
 at org.nlogo.fileformat.ModelConverter.apply(ModelConverter.scala:170)
 at org.nlogo.fileformat.ModelConverter.apply(ModelConverter.scala:46)
 at org.nlogo.fileformat.ChainConverter.$anonfun$apply$2(ChainConverter.scala:12)
 at org.nlogo.fileformat.SuccessfulConversion.mergeResult(ConversionResult.scala:31)
 at org.nlogo.fileformat.ChainConverter.$anonfun$apply$1(ChainConverter.scala:12)
 at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
 at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
 at scala.collection.immutable.List.foldLeft(List.scala:91)
 at org.nlogo.fileformat.ChainConverter.apply(ChainConverter.scala:11)
 at org.nlogo.fileformat.ChainConverter.apply(ChainConverter.scala:9)
 at org.nlogo.workspace.OpenModel.runOpenModelProcess(OpenModel.scala:57)
 at org.nlogo.workspace.OpenModel.runOpenModelProcess$(OpenModel.scala:34)
 at org.nlogo.workspace.OpenModelFromURI$.runOpenModelProcess(OpenModel.scala:83)
 at org.nlogo.workspace.OpenModelFromURI$.apply(OpenModel.scala:93)
 at org.nlogo.app.FileManager.$anonfun$openModelURI$1(FileManager.scala:284)
 at org.nlogo.app.FileManager.$anonfun$loadModel$2(FileManager.scala:312)
 at org.nlogo.swing.ModalProgressTask$Worker.run(ModalProgressTask.scala:66)
Caused by: com.github.sarxos.webcam.WebcamException: java.util.concurrent.ExecutionException: com.github.sarxos.webcam.WebcamException: Cannot execute task
 at com.github.sarxos.webcam.WebcamDiscoveryService.getWebcams(WebcamDiscoveryService.java:124)
 at com.github.sarxos.webcam.Webcam.getWebcams(Webcam.java:893)
 at org.nlogo.extensions.vid.Camera$.$anonfun$cameraNames$1(Camera.scala:35)
 at org.nlogo.extensions.vid.Camera$.withContextClassLoader(Camera.scala:27)
 at org.nlogo.extensions.vid.Camera$.<init>(Camera.scala:35)
 at org.nlogo.extensions.vid.Camera$.<clinit>(Camera.scala)
 ... 58 more
Caused by: java.util.concurrent.ExecutionException: com.github.sarxos.webcam.WebcamException: Cannot execute task
 at java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.util.concurrent.FutureTask.get(FutureTask.java:192)
 at com.github.sarxos.webcam.WebcamDiscoveryService.getWebcams(WebcamDiscoveryService.java:116)
 ... 63 more
Caused by: com.github.sarxos.webcam.WebcamException: Cannot execute task
 at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.process(WebcamProcessor.java:72)
 at com.github.sarxos.webcam.WebcamProcessor.process(WebcamProcessor.java:140)
 at com.github.sarxos.webcam.WebcamTask.process(WebcamTask.java:46)
 at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$GetDevicesTask.getDevices(WebcamDefaultDriver.java:79)
 at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver.getDevices(WebcamDefaultDriver.java:124)
 at com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:36)
 at com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:26)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsatisfiedLinkError: com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber.getVideoDevices()Lorg/bridj/Pointer;
 at com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber.getVideoDevices(Native Method)
 at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$GetDevicesTask.handle(WebcamDefaultDriver.java:93)
 at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.run(WebcamProcessor.java:81)
 ... 3 more

NetLogo 3D 6.2.2
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
OpenJDK 64-Bit Server VM 1.8.0_275 (BellSoft; 1.8.0_275-b01)
operating system: Mac OS X 10.16 (x86_64 processor)
Scala version 2.12.15
JOGL: 2.4.0-rc-20210111
OpenGL graphics: Intel HD Graphics 5000 OpenGL Engine
OpenGL version: 2.1 INTEL-16.5.7
OpenGL vendor: Intel Inc.
model: Directed Flocking HD 3D movie big HR6

05:52:58.779 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:52:58.779 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:52:58.779 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:52:58.779 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:52:58.779 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:52:58.779 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:52:58.779 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:52:58.779 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:52:58.779 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:52:58.779 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0

**Comment by LaCuneta** [comment]
I linked to this to a tracking issue in the Vid Extension repo.  Updates will be provided there, and feel free to add any comments there, too.

**Comment by LaCuneta** [comment]
@maclennan We recently released an updated version of the Vid extension that should hopefully address this issue.  You can use [the extensions manager](https://ccl.northwestern.edu/netlogo/docs/extension-manager.html) from within NetLogo to update to it.  

Also, please make sure NetLogo has permissions to use the camera on your system.  You can open System Preferences, Security & Privacy, then the Privacy Tab, select Camera in the list, and allow NetLogo to use the camera.  You will need to quit and re-open NetLogo for the change to take effect.  See this link for more details:  https://support.apple.com/en-euro/guide/mac-help/mchlf6d108da/mac

If you still have trouble with it, feel free to open a new issue in [the Vid repository](https://github.com/NetLogo/Vid-Extension/issues).  Thanks.
