### ISSUE TITLE
NullPointerException when opening extensions manager with model in home directory loaded

### ISSUE THREAD

**Issue by LaCuneta** [NetLogo/NetLogo#2009]
This one is pretty weird.  If I open a model that is saved in the root of my home directory, then try to open the extensions manager via Tools > Extensions... I get an exception as the below.  If I save the same model in a subdirectory of my home directory and try again there is no error.  I verified this issue on 6.2.2 in Windows and macOS.

The code that is failing is trying to pull the list of all extensions installed in the model directory or the extensions directory - the ones that would override the managed extensions.  

```
NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 


java.lang.NullPointerException
 at scala.collection.mutable.ArrayOps$ofRef$.length$extension(ArrayOps.scala:204)
 at scala.collection.mutable.ArrayOps$ofRef.length(ArrayOps.scala:204)
 at scala.collection.IndexedSeqOptimized.segmentLength(IndexedSeqOptimized.scala:196)
 at scala.collection.IndexedSeqOptimized.segmentLength$(IndexedSeqOptimized.scala:195)
 at scala.collection.mutable.ArrayOps$ofRef.segmentLength(ArrayOps.scala:198)
 at scala.collection.GenSeqLike.prefixLength(GenSeqLike.scala:98)
 at scala.collection.GenSeqLike.prefixLength$(GenSeqLike.scala:98)
 at scala.collection.mutable.ArrayOps$ofRef.prefixLength(ArrayOps.scala:198)
 at scala.collection.IndexedSeqOptimized.find(IndexedSeqOptimized.scala:53)
 at scala.collection.IndexedSeqOptimized.find$(IndexedSeqOptimized.scala:52)
 at scala.collection.mutable.ArrayOps$ofRef.find(ArrayOps.scala:198)
 at org.nlogo.workspace.AbstractWorkspaceTraits$Extensions.$anonfun$getExtensionPathMappings$4(AbstractWorkspaceScala.scala:328)
 at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
 at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
 at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
 at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
 at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
 at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
 at scala.collection.mutable.ArrayOps$ofRef.flatMap(ArrayOps.scala:198)
 at org.nlogo.workspace.AbstractWorkspaceTraits$Extensions.$anonfun$getExtensionPathMappings$2(AbstractWorkspaceScala.scala:327)
 at org.nlogo.workspace.AbstractWorkspaceTraits$Extensions.$anonfun$getExtensionPathMappings$2$adapted(AbstractWorkspaceScala.scala:326)
 at scala.collection.immutable.List.flatMap(List.scala:366)
 at org.nlogo.workspace.AbstractWorkspaceTraits$Extensions.getExtensionPathMappings(AbstractWorkspaceScala.scala:326)
 at org.nlogo.workspace.AbstractWorkspaceTraits$Extensions.getExtensionPathMappings$(AbstractWorkspaceScala.scala:325)
 at org.nlogo.workspace.AbstractWorkspaceScala.getExtensionPathMappings(AbstractWorkspaceScala.scala:26)
 at org.nlogo.app.App.$anonfun$openLibrariesDialog$3(App.scala:648)
 at org.nlogo.app.tools.LibrariesDialog.setVisible(LibrariesDialog.scala:101)
 at org.nlogo.app.ShowDialogAction.actionPerformed(ToolActions.scala:27)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
 at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
 at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
 at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
 at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
 at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
 at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
 at java.awt.Component.processMouseEvent(Component.java:6539)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
 at java.awt.Component.processEvent(Component.java:6304)
 at java.awt.Container.processEvent(Container.java:2239)
 at java.awt.Component.dispatchEventImpl(Component.java:4889)
 at java.awt.Container.dispatchEventImpl(Container.java:2297)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
 at java.awt.Container.dispatchEventImpl(Container.java:2283)
 at java.awt.Window.dispatchEventImpl(Window.java:2746)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
 at java.awt.EventQueue$4.run(EventQueue.java:733)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

NetLogo 6.2.2
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
OpenJDK 64-Bit Server VM 1.8.0_275 (BellSoft; 1.8.0_275-b01)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.15
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Slime

01:08:53.440 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:08:53.440 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:08:53.440 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:08:53.440 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:08:53.439 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:08:53.439 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
01:08:53.238 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:08:53.237 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:08:53.237 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:08:53.237 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
```

**Comment by LaCuneta** [comment]
This is [fixed here](https://github.com/NetLogo/NetLogo/commit/673d1dcc1b18d78b6bbf4b484df04bfe85a6028d)
