### ISSUE TITLE
bitstring

### ISSUE THREAD

**Issue by jiafangdi-guang** [NetLogo/NetLogo#2014]
NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.lang.reflect.InvocationTargetException
 at java.awt.EventQueue.invokeAndWait(EventQueue.java:1321)
 at java.awt.EventQueue.invokeAndWait(EventQueue.java:1296)
 at org.nlogo.awt.EventQueue$.invokeAndWait(EventQueue.scala:19)
 at org.nlogo.swing.ModalProgressTask$Boss.run(ModalProgressTask.scala:61)
Caused by: java.lang.RuntimeException: invalid escape sequence in "Small world settings\t\t\t"
 at scala.sys.package$.error(package.scala:27)
 at org.nlogo.api.ModelReader$.loop$1(ModelReader.scala:87)
 at org.nlogo.api.ModelReader$.restoreLines(ModelReader.scala:91)
 at org.nlogo.widget.NoteWidget.load(NoteWidget.scala:98)
 at org.nlogo.widget.NoteWidget.load(NoteWidget.scala:9)
 at org.nlogo.app.InterfacePanel.loadWidget(InterfacePanel.java:291)
 at org.nlogo.app.InterfacePanel.loadWidget(InterfacePanel.java:231)
 at org.nlogo.app.WidgetPanel.loadWidgets(WidgetPanel.java:716)
 at org.nlogo.app.InterfacePanel.handle(InterfacePanel.java:375)
 at org.nlogo.window.Events$LoadSectionEvent.beHandledBy(Events.java:471)
 at org.nlogo.window.Event.doRaise(Event.java:198)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.window.ModelLoader$Loader$$anonfun$loadHelper$1.apply(ModelLoader.scala:101)
 at org.nlogo.window.ModelLoader$Loader$$anonfun$loadHelper$1.apply(ModelLoader.scala:101)
 at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
 at scala.collection.immutable.List.foreach(List.scala:76)
 at org.nlogo.window.ModelLoader$Loader.loadHelper(ModelLoader.scala:101)
 at org.nlogo.window.ModelLoader$.load(ModelLoader.scala:16)
 at org.nlogo.window.ModelLoader.load(ModelLoader.scala)
 at org.nlogo.app.FileMenu$1.run(FileMenu.java:859)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
 at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
 at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
 at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
 at java.awt.Dialog.show(Dialog.java:1084)
 at java.awt.Component.show(Component.java:1673)
 at java.awt.Component.setVisible(Component.java:1625)
 at java.awt.Window.setVisible(Window.java:1014)
 at java.awt.Dialog.setVisible(Dialog.java:1005)
 at org.nlogo.swing.ModalProgressTask$.apply(ModalProgressTask.scala:43)
 at org.nlogo.swing.ModalProgressTask.apply(ModalProgressTask.scala)
 at org.nlogo.app.FileMenu.openFromMap(FileMenu.java:869)
 at org.nlogo.app.FileMenu.openFromSource(FileMenu.java:841)
 at org.nlogo.app.FileMenu.openFromPath(FileMenu.java:795)
 at org.nlogo.app.FileMenu$OpenAction.action(FileMenu.java:151)
 at org.nlogo.app.FileMenu$FileMenuAction.actionPerformed(FileMenu.java:96)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
 at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
 at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
 at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
 at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
 at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
 at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
 at java.awt.Component.processMouseEvent(Component.java:6535)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
 at java.awt.Component.processEvent(Component.java:6300)
 at java.awt.Container.processEvent(Container.java:2236)
 at java.awt.Component.dispatchEventImpl(Component.java:4891)
 at java.awt.Container.dispatchEventImpl(Container.java:2294)
 at java.awt.Component.dispatchEvent(Component.java:4713)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
 at java.awt.Container.dispatchEventImpl(Container.java:2280)
 at java.awt.Window.dispatchEventImpl(Window.java:2750)
 at java.awt.Component.dispatchEvent(Component.java:4713)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.awt.EventQueue$4.run(EventQueue.java:729)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

NetLogo 5.3.1
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_74 (Oracle Corporation; 1.8.0_74-b02)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Participatory_Disinformation

10:54:59.186 WidgetAddedEvent (org.nlogo.widget.NoteWidget) AWT-EventQueue-0
10:54:59.184 WidgetAddedEvent (org.nlogo.widget.NoteWidget) AWT-EventQueue-0
10:54:59.183 WidgetAddedEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
10:54:59.182 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
10:54:59.181 WidgetAddedEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
10:54:59.181 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
10:54:59.181 AddBooleanConstraintEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
10:54:59.181 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
10:54:59.179 WidgetAddedEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
10:54:59.179 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0

**Comment by barbacbd** [comment]
@jiafangdi-guang can you provide more information here? This is quite vague and looking at your backtrace it is quite hard to determine what exactly was going on. Based on the order at the bottom it looks like an error happened on a load of a model not during widget adding during model creation.

**Comment by ERSUCC** [comment]
This appears to have been fixed in commit [9e32be0](https://github.com/NetLogo/NetLogo/commit/9e32be023b8cf68bf7814317dc97208a5bec1c9b).
