### ISSUE TITLE
Error exporting output of run in behavior space of system dynamics model

### ISSUE THREAD

**Issue by RollingCompass** [NetLogo/NetLogo#2020]
The model runs without issue within NetLogo but running an experiment through the behavior space tab produces the following error:

`NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 

Nothing named SYSTEM-DYNAMICS-SETUP has been defined. at position 16 in 
 at org.nlogo.core.Fail$.exception(Fail.scala:27)
 at org.nlogo.core.Fail$.exception(Fail.scala:25)
 at org.nlogo.core.Fail$.exception(Fail.scala:23)
 at org.nlogo.parse.ExpressionParser$.parseStatement(ExpressionParser.scala:74)
 at org.nlogo.parse.ExpressionParser$.$anonfun$apply$1(ExpressionParser.scala:30)
 at org.nlogo.parse.ExpressionParser$.parseStatements(ExpressionParser.scala:42)
 at org.nlogo.parse.ExpressionParser$.apply(ExpressionParser.scala:30)
 at org.nlogo.parse.NetLogoParser.parseProcedure(NetLogoParser.scala:45)
 at org.nlogo.parse.NetLogoParser.parseProcedure$(NetLogoParser.scala:29)
 at org.nlogo.parse.FrontEnd$.parseProcedure(FrontEnd.scala:10)
 at org.nlogo.parse.NetLogoParser.$anonfun$basicParse$1(NetLogoParser.scala:25)
 at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:285)
 at scala.collection.Iterator.foreach(Iterator.scala:943)
 at scala.collection.Iterator.foreach$(Iterator.scala:943)
 at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
 at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:213)
 at scala.collection.TraversableLike.map(TraversableLike.scala:285)
 at scala.collection.TraversableLike.map$(TraversableLike.scala:278)
 at scala.collection.AbstractTraversable.map(Traversable.scala:108)
 at org.nlogo.parse.NetLogoParser.basicParse(NetLogoParser.scala:25)
 at org.nlogo.parse.NetLogoParser.basicParse$(NetLogoParser.scala:15)
 at org.nlogo.parse.FrontEnd$.basicParse(FrontEnd.scala:10)
 at org.nlogo.parse.FrontEndMain.frontEnd(FrontEnd.scala:26)
 at org.nlogo.parse.FrontEndMain.frontEnd$(FrontEnd.scala:25)
 at org.nlogo.parse.FrontEnd$.frontEnd(FrontEnd.scala:10)
 at org.nlogo.compile.CompilerMain$.compile(CompilerMain.scala:47)
 at org.nlogo.compile.Compiler.compileProgram(Compiler.scala:54)
 at org.nlogo.headless.HeadlessModelOpener.openFromModel(HeadlessModelOpener.scala:50)
 at org.nlogo.headless.HeadlessWorkspace.openModel(HeadlessWorkspace.scala:550)
 at org.nlogo.api.Workspace.openModel(Workspace.scala:66)
 at org.nlogo.app.App$$anon$1.openCurrentModelIn(App.scala:133)
 at org.nlogo.lab.gui.Supervisor.$anonfun$start$1(Supervisor.scala:119)
 at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
 at org.nlogo.lab.gui.Supervisor.start(Supervisor.scala:117)
 at org.nlogo.lab.gui.ManagerDialog.run(ManagerDialog.scala:103)
 at org.nlogo.lab.gui.ManagerDialog.$anonfun$runAction$1(ManagerDialog.scala:30)
 at org.nlogo.lab.gui.ManagerDialog$$anon$1.actionPerformed(ManagerDialog.scala:24)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
 at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
 at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
 at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
 at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
 at java.awt.Component.processMouseEvent(Component.java:6539)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
 at java.awt.Component.processEvent(Component.java:6304)
 at java.awt.Container.processEvent(Container.java:2239)
 at java.awt.Component.dispatchEventImpl(Component.java:4889)
 at java.awt.Container.dispatchEventImpl(Container.java:2297)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
 at java.awt.Container.dispatchEventImpl(Container.java:2283)
 at java.awt.Window.dispatchEventImpl(Window.java:2746)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
 at java.awt.EventQueue$4.run(EventQueue.java:733)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

NetLogo 6.2.1
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
OpenJDK 64-Bit Server VM 1.8.0_275 (BellSoft; 1.8.0_275-b01)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.12
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Untitled

11:53:14.934 WidgetAddedEvent (org.nlogo.window.PlotWidget) AWT-EventQueue-0
11:53:14.898 AddSliderConstraintEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:53:14.898 AddSliderConstraintEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:53:14.894 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
11:53:14.877 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
11:53:14.850 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
11:53:14.672 RemoveAllJobsEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
11:53:14.671 CompileAllEvent (org.nlogo.lab.gui.LabManager) AWT-EventQueue-0
11:51:40.591 WidgetAddedEvent (org.nlogo.window.PlotWidget) AWT-EventQueue-0
11:51:40.577 AddSliderConstraintEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
`

**Comment by LaCuneta** [comment]
@RollingCompass Thanks for reporting this.  I tried running a small systems dynamics model through BehaviorSpace and it worked okay for me.  Are you able to send a copy of you model along?  To attach it to GitHub you'll have to rename it to `.txt` from `.nlogo` or compress it as a zip file, as those are the only options GitHub supports.  If you prefer to keep your model private you can email it to bugs@ccl.northwestern.edu and we will not share it outside our group.
