### ISSUE TITLE
Loading native libraries on M1 Mac fails

### ISSUE THREAD

**Issue by jstovold** [NetLogo/NetLogo#2031]
NetLogo appears to be looking specifically for x86_64 files rather than arm64 files when loading native libraries in an extension

Full error report: 

java.lang.UnsatisfiedLinkError: Native library libdemo0.dylib (/native/x86_64-darwin/libdemo0.dylib) cannot be found on the classpath.
 at org.nlogo.extensions.cdm.Library$.loadPackaged$1(Library.scala:5)
 at org.nlogo.extensions.cdm.Library$.load$1(Library.scala:5)
 at org.nlogo.extensions.cdm.Library$.<init>(Library.scala:5)
 at org.nlogo.extensions.cdm.Library$.<clinit>(Library.scala)
 at org.nlogo.extensions.cdm.IntegerList.report(CDMNetLogoExtension.scala:26)
 at org.nlogo.prim._externreport.report(_externreport.java:31)
 at org.nlogo.prim.etc._show.perform(_show.scala:12)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
 at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
 at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
 at scala.util.control.Exception$Catch.apply(Exception.scala:228)
 at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:66)

NetLogo 6.2.2
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
OpenJDK 64-Bit Server VM 1.8.0_275 (BellSoft; 1.8.0_275-b01)
operating system: Mac OS X 10.16 (x86_64 processor)
Scala version 2.12.15
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Test

02:29:13.935 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:29:13.933 AddJobEvent (org.nlogo.app.common.CommandLine) AWT-EventQueue-0
02:29:13.932 OutputEvent (org.nlogo.app.common.CommandLine) AWT-EventQueue-0
02:29:13.931 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
02:29:13.819 CompileMoreSourceEvent (org.nlogo.app.common.CommandLine) AWT-EventQueue-0
02:29:13.590 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:29:13.385 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:29:13.169 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:29:12.967 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:29:12.762 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

**Comment by jstovold** [comment]
Note that the actual error thrown here is about the classpath not being set correctly, which is easy enough to fix, but the problem remains even after that, giving the following error instead: 

NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 


java.lang.UnsatisfiedLinkError: /private/var/folders/4m/qvjc8h8d6ng7j1vz8h2trb3r0000gn/T/jni-1321728577071093171/libdemo0.dylib: dlopen(/private/var/folders/4m/qvjc8h8d6ng7j1vz8h2trb3r0000gn/T/jni-1321728577071093171/libdemo0.dylib, 0x0001): tried: '/private/var/folders/4m/qvjc8h8d6ng7j1vz8h2trb3r0000gn/T/jni-1321728577071093171/libdemo0.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
 at java.lang.ClassLoader$NativeLibrary.load(Native Method)
 at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
 at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
 at java.lang.Runtime.load0(Runtime.java:810)
 at java.lang.System.load(System.java:1088)
 at org.nlogo.extensions.cdm.Library$.loadPackaged$1(Library.scala:5)
 at org.nlogo.extensions.cdm.Library$.load$1(Library.scala:5)
 at org.nlogo.extensions.cdm.Library$.<init>(Library.scala:5)
 at org.nlogo.extensions.cdm.Library$.<clinit>(Library.scala)
 at org.nlogo.extensions.cdm.IntegerList.report(CDMNetLogoExtension.scala:26)
 at org.nlogo.prim._externreport.report(_externreport.java:31)
 at org.nlogo.prim.etc._show.perform(_show.scala:12)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
 at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
 at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
 at scala.util.control.Exception$Catch.apply(Exception.scala:228)
 at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:66)

NetLogo 6.2.2
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
OpenJDK 64-Bit Server VM 1.8.0_275 (BellSoft; 1.8.0_275-b01)
operating system: Mac OS X 10.16 (x86_64 processor)
Scala version 2.12.15
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Test

11:00:46.068 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:00:46.043 AddJobEvent (org.nlogo.app.common.CommandLine) AWT-EventQueue-0
11:00:46.040 OutputEvent (org.nlogo.app.common.CommandLine) AWT-EventQueue-0
11:00:46.037 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
11:00:45.904 CompileMoreSourceEvent (org.nlogo.app.common.CommandLine) AWT-EventQueue-0
11:00:45.734 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:00:45.527 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:00:45.325 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:00:45.115 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:00:44.909 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

**Comment by jstovold** [comment]
For further info: NetLogo *can* run native code on an M1 mac, just not M1-targeted code. If I build a shared library on an Intel mac and then copy the dylib from the Intel mac on to the M1 mac, NetLogo can run it (one assumes Rosetta does the heavy lifting there), but it won't work with any M1-compiled code.

**Comment by ERSUCC** [comment]
This is probably fixed now that we are providing separate binaries for Apple Silicon. @jstovold I would be interested to know if the problem persists in the upcoming beta release of NetLogo 7.
