### ISSUE TITLE
Extension built using Scala v2.13.8 throws fatal error at runtime

### ISSUE THREAD

**Issue by jstovold** [NetLogo/NetLogo#2032]
Writing an extension that is built using old version of Scala (v2.12.15) works fine, but newer version (v2.13.8) fails at runtime with the following error. The code used to produce the bug is just the sample Scala extension code from the NetLogo documentation (with minor updates for newly-deprecated syntax in v2.13). 

java.lang.NoSuchMethodError: scala.runtime.ScalaRunTime$.wrapIntArray([I)Lscala/collection/immutable/ArraySeq;
 at org.nlogo.extensions.samplescala.IntegerList$.getSyntax(SampleScalaExtension.scala:16)
 at org.nlogo.parse.ExtensionPrimitiveHandler.wrap(NameHandlers.scala:80)
 at org.nlogo.parse.ExtensionPrimitiveHandler.apply(NameHandlers.scala:72)
 at org.nlogo.parse.ExtensionPrimitiveHandler.apply(NameHandlers.scala:55)
 at org.nlogo.parse.Namer$.makeToken$1(Namer.scala:91)
 at org.nlogo.parse.Namer$.$anonfun$basicNamer$4(Namer.scala:102)
 at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
 at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
 at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
 at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
 at scala.collection.Iterator.toStream(Iterator.scala:1417)
 at scala.collection.Iterator.toStream$(Iterator.scala:1416)
 at scala.collection.AbstractIterator.toStream(Iterator.scala:1431)
 at scala.collection.Iterator.$anonfun$toStream$1(Iterator.scala:1417)
 at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1173)
 at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1163)
 at scala.collection.immutable.Stream.length(Stream.scala:312)
 at scala.collection.SeqLike.size(SeqLike.scala:108)
 at scala.collection.SeqLike.size$(SeqLike.scala:108)
 at scala.collection.AbstractSeq.size(Seq.scala:45)
 at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:341)
 at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:339)
 at scala.collection.AbstractTraversable.toArray(Traversable.scala:108)
 at org.nlogo.compile.Compiler.tokenizeForColorization(Compiler.scala:198)
 at org.nlogo.workspace.Compiling.tokenizeForColorization(Compiling.scala:42)
 at org.nlogo.workspace.Compiling.tokenizeForColorization$(Compiling.scala:41)
 at org.nlogo.workspace.AbstractWorkspaceScala.tokenizeForColorization(AbstractWorkspaceScala.scala:26)
 at org.nlogo.window.EditorColorizer.tokenizeForColorization(EditorColorizer.scala:76)
 at org.nlogo.window.EditorColorizer.getCharacterTokenTypes(EditorColorizer.scala:57)
 at org.nlogo.editor.BracketMatcher.caretUpdate(BracketMatcher.java:75)
 at javax.swing.text.JTextComponent.fireCaretUpdate(JTextComponent.java:397)
 at javax.swing.text.JTextComponent$MutableCaretEvent.fire(JTextComponent.java:4394)
 at javax.swing.text.JTextComponent$MutableCaretEvent.stateChanged(JTextComponent.java:4416)
 at javax.swing.text.DefaultCaret.fireStateChanged(DefaultCaret.java:802)
 at javax.swing.text.DefaultCaret.changeCaretPosition(DefaultCaret.java:1274)
 at javax.swing.text.DefaultCaret.handleSetDot(DefaultCaret.java:1173)
 at javax.swing.text.DefaultCaret.setDot(DefaultCaret.java:1154)
 at javax.swing.text.DefaultCaret.setDot(DefaultCaret.java:1051)
 at javax.swing.text.JTextComponent.setCaretPosition(JTextComponent.java:1631)
 at org.nlogo.editor.FocusTraversalListener.focusGained(FocusTraversal.scala:33)
 at java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:220)
 at java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:219)
 at java.awt.Component.processFocusEvent(Component.java:6428)
 at java.awt.Component.processEvent(Component.java:6295)
 at java.awt.Container.processEvent(Container.java:2239)
 at java.awt.Component.dispatchEventImpl(Component.java:4889)
 at java.awt.Container.dispatchEventImpl(Container.java:2297)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
 at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1014)
 at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:638)
 at java.awt.Component.dispatchEventImpl(Component.java:4760)
 at java.awt.Container.dispatchEventImpl(Container.java:2297)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
 at java.awt.EventQueue$4.run(EventQueue.java:733)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

NetLogo 6.2.2
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
OpenJDK 64-Bit Server VM 1.8.0_275 (BellSoft; 1.8.0_275-b01)
operating system: Mac OS X 10.16 (x86_64 processor)
Scala version 2.12.15
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Test

02:40:34.141 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
02:40:33.944 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:40:33.740 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:40:33.538 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:40:33.332 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:40:33.123 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:40:32.912 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
02:40:32.912 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:40:32.911 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
02:40:32.906 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0

**Comment by SethTisue** [comment]
You have to use the same Scala major version (Scala 2 version numbers are epoch.major.minor) NetLogo uses.

Hopefully NetLogo will move to Scala 2.13 before too much longer. The ticket on that is https://github.com/NetLogo/NetLogo/issues/1823

**Comment by ERSUCC** [comment]
This is not a NetLogo issue, this is user error, or maybe the fault of Scala for not providing better cross-version compatibility.
