### ISSUE TITLE
Java Error

### ISSUE THREAD

**Issue by GNelson12** [NetLogo/NetLogo#2038]
Has anyone experienced the error below?  I recently switched to version 6.22 and get this message.  I updated to the most recent version of Java and am using Windows 10.  Netlogo version 6.1.1 still works correctly.

java.lang.ExceptionInInitializerError
 at org.nlogo.extensions.vid.VidExtension$.$anonfun$camera$1(VidExtension.scala:13)
 at org.nlogo.extensions.vid.VidExtension$.guiOrHeadless(VidExtension.scala:9)
 at org.nlogo.extensions.vid.VidExtension$.camera$lzycompute(VidExtension.scala:13)
 at org.nlogo.extensions.vid.VidExtension$.camera(VidExtension.scala:13)
 at org.nlogo.extensions.vid.VidExtension.<init>(VidExtension.scala:21)
 at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
 at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
 at java.lang.Class.newInstance(Class.java:442)
 at org.nlogo.workspace.JarLoader.extensionClassManager(JarLoader.scala:48)
 at org.nlogo.workspace.ExtensionManager.$anonfun$importExtension$8(ExtensionManager.scala:159)
 at scala.Option.getOrElse(Option.scala:189)
 at org.nlogo.workspace.ExtensionManager.importExtension(ExtensionManager.scala:157)
 at org.nlogo.parse.StructureParser$.$anonfun$parsingWithExtensions$1(StructureParser.scala:74)
 at org.nlogo.parse.StructureParser$.$anonfun$parsingWithExtensions$1$adapted(StructureParser.scala:68)
 at scala.collection.immutable.List.foreach(List.scala:431)
 at org.nlogo.parse.StructureParser$.parsingWithExtensions(StructureParser.scala:68)
 at org.nlogo.parse.StructureParser$.parseSources(StructureParser.scala:33)
 at org.nlogo.parse.NetLogoParser.basicParse(NetLogoParser.scala:17)
 at org.nlogo.parse.NetLogoParser.basicParse$(NetLogoParser.scala:15)
 at org.nlogo.parse.FrontEnd$.basicParse(FrontEnd.scala:10)
 at org.nlogo.parse.FrontEndMain.frontEnd(FrontEnd.scala:26)
 at org.nlogo.parse.FrontEndMain.frontEnd$(FrontEnd.scala:25)
 at org.nlogo.parse.FrontEnd$.frontEnd(FrontEnd.scala:10)
 at org.nlogo.compile.CompilerMain$.compile(CompilerMain.scala:47)
 at org.nlogo.compile.Compiler.compileProgram(Compiler.scala:54)
 at org.nlogo.window.CompilerManager.compileProcedures(CompilerManager.scala:209)
 at org.nlogo.window.CompilerManager.compileAll(CompilerManager.scala:173)
 at org.nlogo.window.CompilerManager.handle(CompilerManager.scala:137)
 at org.nlogo.window.Events$CompileAllEvent.beHandledBy(Events.java:185)
 at org.nlogo.window.Event.doRaise(Event.java:206)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.app.codetab.CodeTab.compile(CodeTab.scala:163)
 at org.nlogo.app.codetab.CodeTab.handle(CodeTab.scala:144)
 at org.nlogo.app.common.Events$SwitchedTabsEvent.beHandledBy(Events.java:41)
 at org.nlogo.window.Event.doRaise(Event.java:206)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.app.Tabs$$anon$1.windowGainedFocus(Tabs.scala:106)
 at java.awt.Window.processWindowFocusEvent(Window.java:2101)
 at java.awt.Window.processEvent(Window.java:2017)
 at java.awt.Component.dispatchEventImpl(Component.java:4889)
 at java.awt.Container.dispatchEventImpl(Container.java:2297)
 at java.awt.Window.dispatchEventImpl(Window.java:2746)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
 at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1023)
 at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:477)
 at java.awt.Component.dispatchEventImpl(Component.java:4760)
 at java.awt.Container.dispatchEventImpl(Container.java:2297)
 at java.awt.Window.dispatchEventImpl(Window.java:2746)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
 at java.awt.EventQueue$4.run(EventQueue.java:733)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
 at java.awt.SequencedEvent.dispatch(SequencedEvent.java:156)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
 at java.awt.EventQueue$4.run(EventQueue.java:733)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.github.sarxos.webcam.WebcamException: java.util.concurrent.ExecutionException: com.github.sarxos.webcam.WebcamException: Cannot execute task
 at com.github.sarxos.webcam.WebcamDiscoveryService.getWebcams(WebcamDiscoveryService.java:124)
 at com.github.sarxos.webcam.Webcam.getWebcams(Webcam.java:893)
 at org.nlogo.extensions.vid.Camera$.$anonfun$cameraNames$1(Camera.scala:35)
 at org.nlogo.extensions.vid.Camera$.withContextClassLoader(Camera.scala:27)
 at org.nlogo.extensions.vid.Camera$.<init>(Camera.scala:35)
 at org.nlogo.extensions.vid.Camera$.<clinit>(Camera.scala)
 ... 83 more
Caused by: java.util.concurrent.ExecutionException: com.github.sarxos.webcam.WebcamException: Cannot execute task
 at java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.util.concurrent.FutureTask.get(FutureTask.java:192)
 at com.github.sarxos.webcam.WebcamDiscoveryService.getWebcams(WebcamDiscoveryService.java:116)
 ... 88 more
Caused by: com.github.sarxos.webcam.WebcamException: Cannot execute task
 at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.process(WebcamProcessor.java:72)
 at com.github.sarxos.webcam.WebcamProcessor.process(WebcamProcessor.java:140)
 at com.github.sarxos.webcam.WebcamTask.process(WebcamTask.java:46)
 at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$WebcamNewGrabberTask.newGrabber(WebcamDefaultDriver.java:45)
 at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver.getDevices(WebcamDefaultDriver.java:117)
 at com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:36)
 at com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:26)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Failed to allocate new instance of type class com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber
 at org.bridj.cpp.CPPRuntime.newCPPInstance(CPPRuntime.java:806)
 at org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(CPPRuntime.java:1016)
 at org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(CPPRuntime.java:898)
 at org.bridj.CRuntime$CTypeInfo.initialize(CRuntime.java:271)
 at org.bridj.BridJ.initialize(BridJ.java:1117)
 at org.bridj.NativeObject.<init>(NativeObject.java:50)
 at org.bridj.StructObject.<init>(StructObject.java:46)
 at org.bridj.cpp.CPPObject.<init>(CPPObject.java:55)
 at com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber.<init>(OpenIMAJGrabber.java:62)
 at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$WebcamNewGrabberTask.handle(WebcamDefaultDriver.java:55)
 at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.run(WebcamProcessor.java:81)
 ... 3 more
Caused by: java.lang.RuntimeException: Library 'OpenIMAJGrabber' was not loaded successfully from file 'C:\Users\Gary\AppData\Local\Temp\BridJExtractedLibraries6980303494182341334\OpenIMAJGrabber.dll'
 at org.bridj.BridJ.getNativeLibrary(BridJ.java:1061)
 at org.bridj.BridJ.getNativeLibrary(BridJ.java:1038)
 at org.bridj.BridJ.getNativeLibrary(BridJ.java:607)
 at org.bridj.cpp.CPPRuntime.newCPPInstance(CPPRuntime.java:765)
 ... 13 more

NetLogo 6.2.2
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
OpenJDK 64-Bit Server VM 1.8.0_275 (BellSoft; 1.8.0_275-b01)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.15
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Shawsheen_River_Model_05162022

10:47:18.833 RemoveAllJobsEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
10:47:18.833 CompileAllEvent (org.nlogo.app.codetab.MainCodeTab) AWT-EventQueue-0
10:47:18.833 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
10:47:18.192 RemoveAllJobsEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
10:47:18.130 LoadEndEvent (org.nlogo.window.ReconfigureWorkspaceUI$Loader (java.lang.Object)) AWT-EventQueue-0
10:47:18.130 WidgetAddedEvent (org.nlogo.widget.NoteWidget) AWT-EventQueue-0
10:47:18.130 WidgetAddedEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
10:47:18.130 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
10:47:18.130 WidgetAddedEvent (org.nlogo.window.PlotWidget) AWT-EventQueue-0
10:47:18.114 WidgetAddedEvent (org.nlogo.window.PlotWidget) AWT-EventQueue-0""

**Comment by brandesNW** [comment]
Hi,
We are sorry you have run into this issue.

As noted by Seth Tisue the stack trace is like that of another known issue.
The cause for that one is  use Vid on a system without a properly installed Microsoft Visual C++ 2010 library.
So this could have to do with your computer setup. Note that NetLogo comes with its own Java environment, so your Java installation shouldn’t matter.

Another possibility is that the issue has an element that is model dependent.

I am able to run the Code Examples -> Extension Examples -> vid -> Video Camera Example model on my Windows computer, which has the following configuration.
NetLogo 6.2.2 (November 19, 2021)
Extension API version: 6.1
OpenJDK 64-Bit Server VM 1.8.0_275 (BellSoft; 1.8.0_275-b01)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.15
Java heap: used = 20 MB, free = 244 MB, max = 910 MB
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
I suggest you first see if you can run this model. If it runs, can you please share your model with us, so I can see if it runs on my system. Note: github does not accept .nlogo files as input? Please either zip up the file, or change its extension to .txt.

If that model does not run, your installed Microsoft Visual C++ 2010 library may be the problem.
Aaron

--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling


From: GNelson12 ***@***.***>
Reply-To: NetLogo/NetLogo ***@***.***>
Date: Tuesday, June 21, 2022 at 12:41 PM
To: NetLogo/NetLogo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [NetLogo/NetLogo] Java Error (Issue #2038)


Has anyone experienced the error below? I recently switched to version 6.22 and get this message. I updated to the most recent version of Java and am using Windows 10. Netlogo version 6.1.1 still works correctly.

java.lang.ExceptionInInitializerError
at org.nlogo.extensions.vid.VidExtension$.$anonfun$camera$1(VidExtension.scala:13)
at org.nlogo.extensions.vid.VidExtension$.guiOrHeadless(VidExtension.scala:9)
at org.nlogo.extensions.vid.VidExtension$.camera$lzycompute(VidExtension.scala:13)
at org.nlogo.extensions.vid.VidExtension$.camera(VidExtension.scala:13)
at org.nlogo.extensions.vid.VidExtension.(VidExtension.scala:21)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at java.lang.Class.newInstance(Class.java:442)
at org.nlogo.workspace.JarLoader.extensionClassManager(JarLoader.scala:48)
at org.nlogo.workspace.ExtensionManager.$anonfun$importExtension$8(ExtensionManager.scala:159)
at scala.Option.getOrElse(Option.scala:189)
at org.nlogo.workspace.ExtensionManager.importExtension(ExtensionManager.scala:157)
at org.nlogo.parse.StructureParser$.$anonfun$parsingWithExtensions$1(StructureParser.scala:74)
at org.nlogo.parse.StructureParser$.$anonfun$parsingWithExtensions$1$adapted(StructureParser.scala:68)
at scala.collection.immutable.List.foreach(List.scala:431)
at org.nlogo.parse.StructureParser$.parsingWithExtensions(StructureParser.scala:68)
at org.nlogo.parse.StructureParser$.parseSources(StructureParser.scala:33)
at org.nlogo.parse.NetLogoParser.basicParse(NetLogoParser.scala:17)
at org.nlogo.parse.NetLogoParser.basicParse$(NetLogoParser.scala:15)
at org.nlogo.parse.FrontEnd$.basicParse(FrontEnd.scala:10)
at org.nlogo.parse.FrontEndMain.frontEnd(FrontEnd.scala:26)
at org.nlogo.parse.FrontEndMain.frontEnd$(FrontEnd.scala:25)
at org.nlogo.parse.FrontEnd$.frontEnd(FrontEnd.scala:10)
at org.nlogo.compile.CompilerMain$.compile(CompilerMain.scala:47)
at org.nlogo.compile.Compiler.compileProgram(Compiler.scala:54)
at org.nlogo.window.CompilerManager.compileProcedures(CompilerManager.scala:209)
at org.nlogo.window.CompilerManager.compileAll(CompilerManager.scala:173)
at org.nlogo.window.CompilerManager.handle(CompilerManager.scala:137)
at org.nlogo.window.Events$CompileAllEvent.beHandledBy(Events.java:185)
at org.nlogo.window.Event.doRaise(Event.java:206)
at org.nlogo.window.Event.raise(Event.java:122)
at org.nlogo.app.codetab.CodeTab.compile(CodeTab.scala:163)
at org.nlogo.app.codetab.CodeTab.handle(CodeTab.scala:144)
at org.nlogo.app.common.Events$SwitchedTabsEvent.beHandledBy(Events.java:41)
at org.nlogo.window.Event.doRaise(Event.java:206)
at org.nlogo.window.Event.raise(Event.java:122)
at org.nlogo.app.Tabs$$anon$1.windowGainedFocus(Tabs.scala:106)
at java.awt.Window.processWindowFocusEvent(Window.java:2101)
at java.awt.Window.processEvent(Window.java:2017)
at java.awt.Component.dispatchEventImpl(Component.java:4889)
at java.awt.Container.dispatchEventImpl(Container.java:2297)
at java.awt.Window.dispatchEventImpl(Window.java:2746)
at java.awt.Component.dispatchEvent(Component.java:4711)
at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1023)
at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:477)
at java.awt.Component.dispatchEventImpl(Component.java:4760)
at java.awt.Container.dispatchEventImpl(Container.java:2297)
at java.awt.Window.dispatchEventImpl(Window.java:2746)
at java.awt.Component.dispatchEvent(Component.java:4711)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.awt.EventQueue$3.run(EventQueue.java:703)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
at java.awt.EventQueue$4.run(EventQueue.java:733)
at java.awt.EventQueue$4.run(EventQueue.java:731)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
at java.awt.SequencedEvent.dispatch(SequencedEvent.java:156)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.awt.EventQueue$3.run(EventQueue.java:703)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
at java.awt.EventQueue$4.run(EventQueue.java:733)
at java.awt.EventQueue$4.run(EventQueue.java:731)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.github.sarxos.webcam.WebcamException: java.util.concurrent.ExecutionException: com.github.sarxos.webcam.WebcamException: Cannot execute task
at com.github.sarxos.webcam.WebcamDiscoveryService.getWebcams(WebcamDiscoveryService.java:124)
at com.github.sarxos.webcam.Webcam.getWebcams(Webcam.java:893)
at org.nlogo.extensions.vid.Camera$.$anonfun$cameraNames$1(Camera.scala:35)
at org.nlogo.extensions.vid.Camera$.withContextClassLoader(Camera.scala:27)
at org.nlogo.extensions.vid.Camera$.(Camera.scala:35)
at org.nlogo.extensions.vid.Camera$.(Camera.scala)
... 83 more
Caused by: java.util.concurrent.ExecutionException: com.github.sarxos.webcam.WebcamException: Cannot execute task
at java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.util.concurrent.FutureTask.get(FutureTask.java:192)
at com.github.sarxos.webcam.WebcamDiscoveryService.getWebcams(WebcamDiscoveryService.java:116)
... 88 more
Caused by: com.github.sarxos.webcam.WebcamException: Cannot execute task
at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.process(WebcamProcessor.java:72)
at com.github.sarxos.webcam.WebcamProcessor.process(WebcamProcessor.java:140)
at com.github.sarxos.webcam.WebcamTask.process(WebcamTask.java:46)
at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$WebcamNewGrabberTask.newGrabber(WebcamDefaultDriver.java:45)
at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver.getDevices(WebcamDefaultDriver.java:117)
at com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:36)
at com.github.sarxos.webcam.WebcamDiscoveryService$WebcamsDiscovery.call(WebcamDiscoveryService.java:26)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Failed to allocate new instance of type class com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber
at org.bridj.cpp.CPPRuntime.newCPPInstance(CPPRuntime.java:806)
at org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(CPPRuntime.java:1016)
at org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(CPPRuntime.java:898)
at org.bridj.CRuntime$CTypeInfo.initialize(CRuntime.java:271)
at org.bridj.BridJ.initialize(BridJ.java:1117)
at org.bridj.NativeObject.(NativeObject.java:50)
at org.bridj.StructObject.(StructObject.java:46)
at org.bridj.cpp.CPPObject.(CPPObject.java:55)
at com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber.(OpenIMAJGrabber.java:62)
at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$WebcamNewGrabberTask.handle(WebcamDefaultDriver.java:55)
at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.run(WebcamProcessor.java:81)
... 3 more
Caused by: java.lang.RuntimeException: Library 'OpenIMAJGrabber' was not loaded successfully from file 'C:\Users\Gary\AppData\Local\Temp\BridJExtractedLibraries6980303494182341334\OpenIMAJGrabber.dll'
at org.bridj.BridJ.getNativeLibrary(BridJ.java:1061)
at org.bridj.BridJ.getNativeLibrary(BridJ.java:1038)
at org.bridj.BridJ.getNativeLibrary(BridJ.java:607)
at org.bridj.cpp.CPPRuntime.newCPPInstance(CPPRuntime.java:765)
... 13 more

NetLogo 6.2.2
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
OpenJDK 64-Bit Server VM 1.8.0_275 (BellSoft; 1.8.0_275-b01)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.15
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Shawsheen_River_Model_05162022

10:47:18.833 RemoveAllJobsEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
10:47:18.833 CompileAllEvent (org.nlogo.app.codetab.MainCodeTab) AWT-EventQueue-0
10:47:18.833 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
10:47:18.192 RemoveAllJobsEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
10:47:18.130 LoadEndEvent (org.nlogo.window.ReconfigureWorkspaceUI$Loader (java.lang.Object)) AWT-EventQueue-0
10:47:18.130 WidgetAddedEvent (org.nlogo.widget.NoteWidget) AWT-EventQueue-0
10:47:18.130 WidgetAddedEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
10:47:18.130 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
10:47:18.130 WidgetAddedEvent (org.nlogo.window.PlotWidget) AWT-EventQueue-0
10:47:18.114 WidgetAddedEvent (org.nlogo.window.PlotWidget) AWT-EventQueue-0""

**Comment by GNelson12** [comment]
Thanks. I’ll give it a try.

**Comment by GNelson12** [comment]
That seemed to work! Thanks!

**Comment by brandesNW** [comment]
Hi Gary,
Thanks for the update.
To help us respond to other users can you clarify the steps you took?
For example did you reinstall the Microsoft Visual C++ 2010 library?
Thanks,
Aaron

--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling


From: GNelson12 ***@***.***>
Reply-To: NetLogo/NetLogo ***@***.***>
Date: Monday, June 27, 2022 at 2:35 PM
To: NetLogo/NetLogo ***@***.***>
Cc: Aaron Andre Brandes ***@***.***>, Comment ***@***.***>
Subject: Re: [NetLogo/NetLogo] Java Error (Issue #2038)

That seemed to work! Thanks!

**Comment by GNelson12** [comment]
I went Microsoft and downloaded the Microsoft Visual C++ 2010 library and re-installed it on my computer.
Thanks for your help.

**Comment by brandesNW** [comment]
Thanks Gary,
That is very helpful.
Aaron

--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling


From: GNelson12 ***@***.***>
Reply-To: NetLogo/NetLogo ***@***.***>
Date: Tuesday, June 28, 2022 at 7:20 AM
To: NetLogo/NetLogo ***@***.***>
Cc: Aaron Andre Brandes ***@***.***>, Comment ***@***.***>
Subject: Re: [NetLogo/NetLogo] Java Error (Issue #2038)


I went Microsoft and downloaded the Microsoft Visual C++ 2010 library and re-installed it on my computer.
Thanks for your help.

**Comment by brandesNW** [comment]
This issue was resolved by downloading the Microsoft Visual C++ 2010 library from Microsoft and re-installing it on the computer.
