### ISSUE TITLE
Error Code

### ISSUE THREAD

**Issue by lmmfk6** [NetLogo/NetLogo#2039]
I received this error code today while trying to run an in-radius command: 

java.lang.ArrayIndexOutOfBoundsException: 10
 at org.nlogo.agent.Patch.getPatchVariable(Patch.java:297)
 at org.nlogo.prim._asm_procedurefirmmovement_uphill_22.perform(:1)
 at org.nlogo.nvm.Context.runExclusive(Context.java:133)
 at org.nlogo.nvm.ExclusiveJob.run(ExclusiveJob.scala:39)
 at org.nlogo.nvm.Context.runExclusiveJob(Context.java:177)
 at org.nlogo.prim._asm_procedurefirmmovement_ask_0.perform(:1)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
 at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
 at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
 at scala.util.control.Exception$Catch.apply(Exception.scala:228)
 at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:66)

NetLogo 6.2.2
main: org.nlogo.app.AppFrame
thread: JobThread
OpenJDK 64-Bit Server VM 1.8.0_275 (BellSoft; 1.8.0_275-b01)
operating system: Mac OS X 10.16 (x86_64 processor)
Scala version 2.12.15
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Integrated Model_v2

03:33:55.021 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
03:33:54.941 RuntimeErrorEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
03:33:54.931 AddJobEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
03:33:54.848 InputBoxLoseFocusEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
03:33:54.775 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
03:33:54.775 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
03:33:54.775 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
03:33:54.775 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
03:33:54.774 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
03:33:54.774 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

Here is my code it is calling: 
`
to firm-movement
  ask turtles
  [
   let potential-destinations patches in-radius search-radius with [not any? turtles-here]
   set potential-destinations (patch-set potential-destinations patch-here)
   ;let new-match one-of potential-destinations

    let ND max [required-pa] of potential-destinations
    let LD [required-pa] of patch-here
    let AT (produced-pa)
    let current-unit-available [units-available] of patch-here

  ifelse AT = LD
    [
      set funds funds + (profit * current-unit-available)
    ]
    [
    ifelse ND = AT [
      move-to one-of potential-destinations with [required-pa = AT]
      set funds funds - 150
     ]
     [
      uphill required-pa
      set funds funds - 100
     ]
      ]
    ]
end`

**Comment by brandesNW** [comment]
Hi,
We are sorry you have encountered this problem.
The error suggests a problem with patch variables.

I need more information than the code you shared. It would be helpful if you could share your model, and the steps needed to create the error. Note: github does not accept .nlogo files as input. Please either zip up the file, or change its extension to .txt.
Thanks,
Aaron

--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling


From: lmmfk6 ***@***.***>
Reply-To: NetLogo/NetLogo ***@***.***>
Date: Wednesday, June 22, 2022 at 4:38 PM
To: NetLogo/NetLogo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [NetLogo/NetLogo] Error Code (Issue #2039)


I received this error code today while trying to run an in-radius command:

java.lang.ArrayIndexOutOfBoundsException: 10
at org.nlogo.agent.Patch.getPatchVariable(Patch.java:297)
at org.nlogo.prim._asm_procedurefirmmovement_uphill_22.perform(:1)
at org.nlogo.nvm.Context.runExclusive(Context.java:133)
at org.nlogo.nvm.ExclusiveJob.run(ExclusiveJob.scala:39)
at org.nlogo.nvm.Context.runExclusiveJob(Context.java:177)
at org.nlogo.prim._asm_procedurefirmmovement_ask_0.perform(:1)
at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
at scala.util.control.Exception$Catch.apply(Exception.scala:228)
at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
at org.nlogo.job.JobThread.run(JobThread.scala:66)

NetLogo 6.2.2
main: org.nlogo.app.AppFrame
thread: JobThread
OpenJDK 64-Bit Server VM 1.8.0_275 (BellSoft; 1.8.0_275-b01)
operating system: Mac OS X 10.16 (x86_64 processor)
Scala version 2.12.15
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Integrated Model_v2

03:33:55.021 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
03:33:54.941 RuntimeErrorEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
03:33:54.931 AddJobEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
03:33:54.848 InputBoxLoseFocusEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
03:33:54.775 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
03:33:54.775 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
03:33:54.775 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
03:33:54.775 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
03:33:54.774 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
03:33:54.774 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

Here is my code it is calling:
`
to firm-movement
ask turtles
[
let potential-destinations patches in-radius search-radius with [not any? turtles-here]
set potential-destinations (patch-set potential-destinations patch-here)
;let new-match one-of potential-destinations

let ND max [required-pa] of potential-destinations

let LD [required-pa] of patch-here

let AT (produced-pa)

let current-unit-available [units-available] of patch-here

ifelse AT = LD
[
set funds funds + (profit * current-unit-available)
]
[
ifelse ND = AT [
move-to one-of potential-destinations with [required-pa = AT]
set funds funds - 150
]
[
uphill required-pa
set funds funds - 100
]
]
]
end`

**Comment by brandesNW** [comment]
I wrote the above reply months ago. It was sent out by Github at 2:55 a.m.. The same thing happened with 2 messages a couple of days ago. If anyone has an idea of what might be causing this, or how I can deal with it please reply.

**Comment by lunalovegood87** [comment]
i have the same problem,  i think this problem have not a solution. i decided to format my computer.

**Comment by ERSUCC** [comment]
Closing this issue as a duplicate of #1760.
