### ISSUE TITLE
Netlogo 6.3Beta: Unable to determine GraphicsConfiguration : JOGL 2.4 on Java 17 & Windows 11

### ISSUE THREAD

**Issue by stephenguerin** [NetLogo/NetLogo#2048]
"Switch to 3D View" throws a com.jogamp.opengl.GLException on Netlogo 6.3beta.  Just opening new model and switching view.

"Switch to 3D View" works fine in Netlogo 6.2.2.

Surfing around it looks like it's a JOGL / JAVA 17 issue
  #https://github.com/jzy3d/jogl/issues/4
 
My test was on a Windows11 Lenovo IdeaPad (LENOVO_MT_82A6_BU_idea_FM_IdeaPad Slim 7 14ITL05
). Haven't explored other installs/devices - but assume its the Java 17 issue.

full message:
NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 

com.jogamp.opengl.GLException: Unable to determine GraphicsConfiguration: WindowsWGLGraphicsConfiguration[DefaultGraphicsScreen[WindowsGraphicsDevice[type .windows, connection decon, unitID 0, handle 0x0, owner false, NullToolkitLock[obj 0xd26cc1a]], idx 0], pfdID 39, ARB-Choosen true,
 requested GLCaps[rgba 8/8/8/1, opaque, accum-rgba 0/0/0/0, dp/st/ms 16/1/4, sample-ext default, dbl, mono  , hw, GLProfile[GL2/GL4bc.hw], on-scr[.]],
 chosen    GLCaps[wgl vid 39 arb: rgba 8/8/8/8, opaque, accum-rgba 16/16/16/16, dp/st/ms 24/8/4, sample-ext default, dbl, mono  , hw, GLProfile[GL2/GL4bc.hw], on-scr[.]]]
 at jogamp.opengl.windows.wgl.awt.WindowsAWTWGLGraphicsConfigurationFactory.chooseGraphicsConfigurationImpl(WindowsAWTWGLGraphicsConfigurationFactory.java:182)
 at com.jogamp.nativewindow.GraphicsConfigurationFactory.chooseGraphicsConfiguration(GraphicsConfigurationFactory.java:424)
 at com.jogamp.opengl.awt.GLCanvas.chooseGraphicsConfiguration(GLCanvas.java:1513)
 at com.jogamp.opengl.awt.GLCanvas.addNotify(GLCanvas.java:609)
 at java.desktop/java.awt.Container.addNotify(Unknown Source)
 at java.desktop/java.awt.Window.addNotify(Unknown Source)
 at java.desktop/java.awt.Frame.addNotify(Unknown Source)
 at java.desktop/java.awt.Window.show(Unknown Source)
 at java.desktop/java.awt.Component.show(Unknown Source)
 at java.desktop/java.awt.Component.setVisible(Unknown Source)
 at java.desktop/java.awt.Window.setVisible(Unknown Source)
 at org.nlogo.gl.view.ViewManager.init(ViewManager.scala:67)
 at org.nlogo.gl.view.ViewManager.open(ViewManager.scala:42)
 at org.nlogo.window.WorkspaceActions$Open3DViewAction.performAction(WorkspaceActions.scala:60)
 at org.nlogo.window.WorkspaceActions$GUIWorkspaceAction.actionPerformed(WorkspaceActions.scala:36)
 at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
 at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
 at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
 at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
 at java.desktop/javax.swing.AbstractButton.doClick(Unknown Source)
 at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
 at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
 at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
 at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
 at java.desktop/java.awt.Component.processEvent(Unknown Source)
 at java.desktop/java.awt.Container.processEvent(Unknown Source)
 at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
 at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
 at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
 at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
 at java.base/java.security.AccessController.doPrivileged(Unknown Source)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
 at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
 at java.base/java.security.AccessController.doPrivileged(Unknown Source)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

NetLogo 6.3.0-beta1
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
OpenJDK 64-Bit Server VM 17.0.3 (BellSoft; 17.0.3+7-LTS)
operating system: Windows 11 10.0 (amd64 processor)
Scala version 2.12.16
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Untitled

02:14:24.775 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:14:24.563 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:14:24.348 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:14:24.145 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:14:23.940 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:14:23.727 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:14:23.522 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:14:23.308 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:14:23.095 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:14:22.886 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

**Comment by LaCuneta** [comment]
Thank you so much for testing out the beta and sending your feedback!  We did already find this issue and [got it resolved](https://github.com/NetLogo/NetLogo/commit/4a20150bc30a23695deb81a77281fd4d4bfa7378) so it won't affect the final release.  The problem was we weren't correctly passing in the necessary flags to get our JOGL library running with our updated build process.
