### ISSUE TITLE
Behaviorspace Experiment Internal Error

### ISSUE THREAD

**Issue by Friend-of-Ollie** [NetLogo/NetLogo#2067]
Hello, my colleague is trying to run a NetLogo Behaviorspace experiment based on models we use in our lab, but she's new to NetLogo and programming in general so I'm lending a hand. My NetLogo knowledege is decent but I still struggle to decode error messages. We've run into a strange issue where running the same experiment on 2 different machines results in 1 producing this error, while the other is fine.

I'm trying to trace back the issue but I'm struggling to understand the message, is position 49 the line where the issue is originating? I also cannot figure out what's wrong as the global variable in question. "SPREAD-TC" is used several times in the code, but never in an ifelse (" at scala.Option.getOrElse(Option.scala:189)" below).

My money is on this being a code problem rather than a NetLogo bug, but any pointers as to what's going on and/or where to investigate would be appriciated.

```
Nothing named SPREAD-TC has been defined. at position 49 in
 at org.nlogo.core.Fail$.exception(Fail.scala:27)
 at org.nlogo.core.Fail$.exception(Fail.scala:25)
 at org.nlogo.core.Fail$.exception(Fail.scala:23)
 at org.nlogo.parse.ExpressionParser$.$anonfun$parseExpressionInternal$4(ExpressionParser.scala:391)
 at scala.Option.getOrElse(Option.scala:189)
 at org.nlogo.parse.ExpressionParser$.parseExpressionInternal(ExpressionParser.scala:391)
 at org.nlogo.parse.ExpressionParser$.parseExpression(ExpressionParser.scala:302)
 at org.nlogo.parse.ExpressionParser$.$anonfun$parseExpressionInternal$1(ExpressionParser.scala:358)
 at org.nlogo.parse.ExpressionParser$.parseParenthesized(ExpressionParser.scala:317)
 at org.nlogo.parse.ExpressionParser$.parseExpressionInternal(ExpressionParser.scala:363)
 at org.nlogo.parse.ExpressionParser$.parseArgExpression(ExpressionParser.scala:230)
 at org.nlogo.parse.ExpressionParser$.$anonfun$parseArguments$1(ExpressionParser.scala:166)
 at org.nlogo.parse.ExpressionParser$.$anonfun$parseArguments$1$adapted(ExpressionParser.scala:165)
 at scala.collection.immutable.Range.foreach(Range.scala:158)
 at org.nlogo.parse.ExpressionParser$.parseArguments(ExpressionParser.scala:165)
 at org.nlogo.parse.ExpressionParser$.parsePotentiallyVariadicArgumentList(ExpressionParser.scala:88)
 at org.nlogo.parse.ExpressionParser$.parseStatement(ExpressionParser.scala:69)
 at org.nlogo.parse.ExpressionParser$.$anonfun$apply$1(ExpressionParser.scala:30)
 at org.nlogo.parse.ExpressionParser$.parseStatements(ExpressionParser.scala:42)
 at org.nlogo.parse.ExpressionParser$.apply(ExpressionParser.scala:30)
 at org.nlogo.parse.NetLogoParser.parseProcedure(NetLogoParser.scala:45)
 at org.nlogo.parse.NetLogoParser.parseProcedure$(NetLogoParser.scala:29)
 at org.nlogo.parse.FrontEnd$.parseProcedure(FrontEnd.scala:10)
 at org.nlogo.parse.NetLogoParser.$anonfun$basicParse$1(NetLogoParser.scala:25)
 at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
 at scala.collection.Iterator.foreach(Iterator.scala:943)
 at scala.collection.Iterator.foreach$(Iterator.scala:943)
 at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
 at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:214)
 at scala.collection.TraversableLike.map(TraversableLike.scala:286)
 at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
 at scala.collection.AbstractTraversable.map(Traversable.scala:108)
 at org.nlogo.parse.NetLogoParser.basicParse(NetLogoParser.scala:25)
 at org.nlogo.parse.NetLogoParser.basicParse$(NetLogoParser.scala:15)
 at org.nlogo.parse.FrontEnd$.basicParse(FrontEnd.scala:10)
 at org.nlogo.parse.FrontEndMain.frontEnd(FrontEnd.scala:26)
 at org.nlogo.parse.FrontEndMain.frontEnd$(FrontEnd.scala:25)
 at org.nlogo.parse.FrontEnd$.frontEnd(FrontEnd.scala:10)
 at org.nlogo.compile.CompilerMain$.compile(CompilerMain.scala:47)
 at org.nlogo.compile.Compiler.compileMoreCode(Compiler.scala:85)
 at org.nlogo.compile.Compiler.compileMoreCode(Compiler.scala:100)
 at org.nlogo.workspace.Evaluator.invokeCompiler(Evaluator.scala:159)
 at org.nlogo.workspace.Evaluator.compileReporter(Evaluator.scala:38)
 at org.nlogo.workspace.Evaluating.compileReporter(Evaluating.scala:57)
 at org.nlogo.workspace.Evaluating.compileReporter$(Evaluating.scala:56)
 at org.nlogo.workspace.AbstractWorkspaceScala.compileReporter(AbstractWorkspaceScala.scala:26)
 at org.nlogo.lab.Worker$Procedures.$anonfun$metricProcedures$1(Worker.scala:72)
 at scala.collection.immutable.List.map(List.scala:293)
 at org.nlogo.lab.Worker$Procedures.<init>(Worker.scala:72)
 at org.nlogo.lab.Worker$Runner.callHelper(Worker.scala:101)
 at org.nlogo.lab.Worker$Runner.call(Worker.scala:91)
 at org.nlogo.lab.Worker$Runner.call(Worker.scala:74)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)

NetLogo 6.2.2
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
OpenJDK 64-Bit Server VM 1.8.0_275 (BellSoft; 1.8.0_275-b01)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.15
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: toy_model_20221117

03:06:04.520 AddChooserConstraintEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
03:06:04.520 AddSliderConstraintEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
03:06:04.520 AddChooserConstraintEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
03:06:04.520 AddBooleanConstraintEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
03:06:04.520 AddSliderConstraintEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
03:06:04.520 AddChooserConstraintEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
03:06:04.520 AddSliderConstraintEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
03:06:04.520 AddSliderConstraintEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
03:06:04.520 AddChooserConstraintEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
03:06:04.520 AddSliderConstraintEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
```

**Comment by LaCuneta** [comment]
Thanks for your interest in NetLogo!  And yeah, that error message is hard to understand.  The problem is in the model code as you suspect, more specifically in one of the metrics in the BehaviorSpace experiment setup.  It's running code using `foreach` on a list, and somewhere in the anonymous procedure given to that primitive it's trying to get a `spread-tc` variable, but that variable does not exist as expected.  Here are some likely causes:

- Maybe a name changed in the global variables of the model?  
- Maybe the code was copied from another location where that variable was a local `let` variable?  
- Maybe the code is expecting to be in agent context and that is an agent variable, but `foreach` on lists doesn't set agent context so you'd have to do something like `foreach ts [ t -> [spread-tc] of t ]`.  That's just a guess at what it'd look like since I don't know without seeing the code.

As for why you'd have different errors across different machines I'm not sure, but I'd suspect the model is somehow not actually the same, at least in the BehaviorSpace experiment setup.

I hope that helps.  If you want to discuss further a good place to ask questions about writing models is [the NetLogo users group](https://groups.google.com/g/netlogo-users).
