### ISSUE TITLE
Internal Error happens while trying to open the extension

### ISSUE THREAD

**Issue by blankingblack** [NetLogo/NetLogo#2083]
NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 

java.lang.NullPointerException: Cannot read the array length because "$this" is null
 at scala.collection.mutable.ArrayOps$ofRef$.length$extension(ArrayOps.scala:204)
 at scala.collection.mutable.ArrayOps$ofRef.length(ArrayOps.scala:204)
 at scala.collection.IndexedSeqOptimized.segmentLength(IndexedSeqOptimized.scala:196)
 at scala.collection.IndexedSeqOptimized.segmentLength$(IndexedSeqOptimized.scala:195)
 at scala.collection.mutable.ArrayOps$ofRef.segmentLength(ArrayOps.scala:198)
 at scala.collection.GenSeqLike.prefixLength(GenSeqLike.scala:98)
 at scala.collection.GenSeqLike.prefixLength$(GenSeqLike.scala:98)
 at scala.collection.mutable.ArrayOps$ofRef.prefixLength(ArrayOps.scala:198)
 at scala.collection.IndexedSeqOptimized.find(IndexedSeqOptimized.scala:53)
 at scala.collection.IndexedSeqOptimized.find$(IndexedSeqOptimized.scala:52)
 at scala.collection.mutable.ArrayOps$ofRef.find(ArrayOps.scala:198)
 at org.nlogo.workspace.AbstractWorkspaceTraits$Extensions.$anonfun$getExtensionPathMappings$4(AbstractWorkspaceScala.scala:328)
 at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
 at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
 at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
 at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
 at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
 at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
 at scala.collection.mutable.ArrayOps$ofRef.flatMap(ArrayOps.scala:198)
 at org.nlogo.workspace.AbstractWorkspaceTraits$Extensions.$anonfun$getExtensionPathMappings$2(AbstractWorkspaceScala.scala:327)
 at org.nlogo.workspace.AbstractWorkspaceTraits$Extensions.$anonfun$getExtensionPathMappings$2$adapted(AbstractWorkspaceScala.scala:326)
 at scala.collection.immutable.List.flatMap(List.scala:366)
 at org.nlogo.workspace.AbstractWorkspaceTraits$Extensions.getExtensionPathMappings(AbstractWorkspaceScala.scala:326)
 at org.nlogo.workspace.AbstractWorkspaceTraits$Extensions.getExtensionPathMappings$(AbstractWorkspaceScala.scala:325)
 at org.nlogo.workspace.AbstractWorkspaceScala.getExtensionPathMappings(AbstractWorkspaceScala.scala:26)
 at org.nlogo.app.App.$anonfun$openLibrariesDialog$3(App.scala:634)
 at org.nlogo.app.tools.LibrariesDialog.setVisible(LibrariesDialog.scala:101)
 at org.nlogo.app.ShowDialogAction.actionPerformed(ToolActions.scala:27)
 at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
 at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
 at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
 at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
 at java.desktop/javax.swing.AbstractButton.doClick(Unknown Source)
 at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
 at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
 at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
 at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
 at java.desktop/java.awt.Component.processEvent(Unknown Source)
 at java.desktop/java.awt.Container.processEvent(Unknown Source)
 at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
 at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
 at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
 at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
 at java.base/java.security.AccessController.doPrivileged(Unknown Source)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
 at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
 at java.base/java.security.AccessController.doPrivileged(Unknown Source)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

NetLogo 6.3.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
OpenJDK 64-Bit Server VM 17.0.3 (BellSoft; 17.0.3+7-LTS)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.16
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: 1

03:33:16.315 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
03:33:16.115 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
03:33:15.915 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
03:33:15.714 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
03:33:15.514 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
03:33:15.313 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
03:33:15.113 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
03:33:14.912 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
03:33:14.712 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
03:33:14.511 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

**Comment by brandesNW** [comment]
Hi,
We are sorry you have encountered this problem.

Which extension are you using?
Please make sure you have the most recent version of the extension.
You can do this by clicking on the NetLogo Tools->Extension menu item and either clicking the Update All button or finding the extension using the scroll down menu on the left and updating it if it has a red icon.
If the extension was not installed, click the install button (That should not happen because you should get a error message “Can’t find extension: extension-name” when you try to run the program)
Let us know if that fixes your problem.

Otherwise we would like you to send us the model, or if it is complex, a simplified version that reproduces the problem.
If you can make a version without sliders, choosers, switches and inputs, sending the contents of the Code tab would be fine.
Otherwise please put your model in a zip file, or change the extension to .txt in order to work around a GitHub limitation.


  *   Aaron

--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling


From: blankingblack ***@***.***>
Date: Friday, February 17, 2023 at 2:50 AM
To: NetLogo/NetLogo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [NetLogo/NetLogo] Internal Error happens while trying to open the extension (Issue #2083)

NetLogo is unable to supply you with more details about this error. Please report the problem
at https://github.com/NetLogo/NetLogo/issues<https://urldefense.com/v3/__https:/github.com/NetLogo/NetLogo/issues__;!!Dq0X2DkFhyF93HkjWTBQKhk!QLmnMSKLBhzXJwXrwM2v5VGrzoNCaz6MbtD7I5tpz6IiYbd_dG4RD3WhfKPPpNl62i50p6a4LSPGiLf0GfJYWei0qUZSeTPwSA$>, or to ***@***.******@***.***>, and paste the
contents of this window into your report.

java.lang.NullPointerException: Cannot read the array length because "$this" is null
at scala.collection.mutable.ArrayOps$ofRef$.length$extension(ArrayOps.scala:204)
at scala.collection.mutable.ArrayOps$ofRef.length(ArrayOps.scala:204)
at scala.collection.IndexedSeqOptimized.segmentLength(IndexedSeqOptimized.scala:196)
at scala.collection.IndexedSeqOptimized.segmentLength$(IndexedSeqOptimized.scala:195)
at scala.collection.mutable.ArrayOps$ofRef.segmentLength(ArrayOps.scala:198)
at scala.collection.GenSeqLike.prefixLength(GenSeqLike.scala:98)
at scala.collection.GenSeqLike.prefixLength$(GenSeqLike.scala:98)
at scala.collection.mutable.ArrayOps$ofRef.prefixLength(ArrayOps.scala:198)
at scala.collection.IndexedSeqOptimized.find(IndexedSeqOptimized.scala:53)
at scala.collection.IndexedSeqOptimized.find$(IndexedSeqOptimized.scala:52)
at scala.collection.mutable.ArrayOps$ofRef.find(ArrayOps.scala:198)
at org.nlogo.workspace.AbstractWorkspaceTraits$Extensions.$anonfun$getExtensionPathMappings$4(AbstractWorkspaceScala.scala:328)
at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
at scala.collection.mutable.ArrayOps$ofRef.flatMap(ArrayOps.scala:198)
at org.nlogo.workspace.AbstractWorkspaceTraits$Extensions.$anonfun$getExtensionPathMappings$2(AbstractWorkspaceScala.scala:327)
at org.nlogo.workspace.AbstractWorkspaceTraits$Extensions.$anonfun$getExtensionPathMappings$2$adapted(AbstractWorkspaceScala.scala:326)
at scala.collection.immutable.List.flatMap(List.scala:366)
at org.nlogo.workspace.AbstractWorkspaceTraits$Extensions.getExtensionPathMappings(AbstractWorkspaceScala.scala:326)
at org.nlogo.workspace.AbstractWorkspaceTraits$Extensions.getExtensionPathMappings$(AbstractWorkspaceScala.scala:325)
at org.nlogo.workspace.AbstractWorkspaceScala.getExtensionPathMappings(AbstractWorkspaceScala.scala:26)
at org.nlogo.app.App.$anonfun$openLibrariesDialog$3(App.scala:634)
at org.nlogo.app.tools.LibrariesDialog.setVisible(LibrariesDialog.scala:101)
at org.nlogo.app.ShowDialogAction.actionPerformed(ToolActions.scala:27)
at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
at java.desktop/javax.swing.AbstractButton.doClick(Unknown Source)
at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
at java.desktop/java.awt.Component.processEvent(Unknown Source)
at java.desktop/java.awt.Container.processEvent(Unknown Source)
at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
at java.base/java.security.AccessController.doPrivileged(Unknown Source)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
at java.base/java.security.AccessController.doPrivileged(Unknown Source)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

NetLogo 6.3.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
OpenJDK 64-Bit Server VM 17.0.3 (BellSoft; 17.0.3+7-LTS)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.16
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: 1

03:33:16.315 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
03:33:16.115 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
03:33:15.915 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
03:33:15.714 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
03:33:15.514 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
03:33:15.313 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
03:33:15.113 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
03:33:14.912 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
03:33:14.712 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
03:33:14.511 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

**Comment by ERSUCC** [comment]
This appears to have been resolved in commit [673d1dc](https://github.com/NetLogo/NetLogo/commit/673d1dcc1b18d78b6bbf4b484df04bfe85a6028d).
