### ISSUE TITLE
Internal Error report

### ISSUE THREAD

**Issue by yidakra** [NetLogo/NetLogo#2086]
NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 

Nothing named SATURATED? has been defined. at position 73 in 
 at org.nlogo.core.Fail$.exception(Fail.scala:27)
 at org.nlogo.core.Fail$.exception(Fail.scala:25)
 at org.nlogo.core.Fail$.exception(Fail.scala:23)
 at org.nlogo.parse.ExpressionParser$.$anonfun$parseExpressionInternal$4(ExpressionParser.scala:391)
 at scala.Option.getOrElse(Option.scala:189)
 at org.nlogo.parse.ExpressionParser$.parseExpressionInternal(ExpressionParser.scala:391)
 at org.nlogo.parse.ExpressionParser$.parseArgExpression(ExpressionParser.scala:230)
 at org.nlogo.parse.ExpressionParser$.$anonfun$parseArguments$1(ExpressionParser.scala:166)
 at org.nlogo.parse.ExpressionParser$.$anonfun$parseArguments$1$adapted(ExpressionParser.scala:165)
 at scala.collection.immutable.Range.foreach(Range.scala:158)
 at org.nlogo.parse.ExpressionParser$.parseArguments(ExpressionParser.scala:165)
 at org.nlogo.parse.ExpressionParser$.parsePotentiallyVariadicArgumentList(ExpressionParser.scala:88)
 at org.nlogo.parse.ExpressionParser$.parseExpressionInternal(ExpressionParser.scala:418)
 at org.nlogo.parse.ExpressionParser$.parseExpression(ExpressionParser.scala:302)
 at org.nlogo.parse.ExpressionParser$.reporterApp$1(ExpressionParser.scala:568)
 at org.nlogo.parse.ExpressionParser$.parseDelayedBlock(ExpressionParser.scala:611)
 at org.nlogo.parse.ExpressionParser$.resolveType(ExpressionParser.scala:273)
 at org.nlogo.parse.ExpressionParser$.resolveTypes(ExpressionParser.scala:127)
 at org.nlogo.parse.ExpressionParser$.parseMore(ExpressionParser.scala:508)
 at org.nlogo.parse.ExpressionParser$.parseExpressionInternal(ExpressionParser.scala:427)
 at org.nlogo.parse.ExpressionParser$.parseArgExpression(ExpressionParser.scala:230)
 at org.nlogo.parse.ExpressionParser$.$anonfun$parseArguments$1(ExpressionParser.scala:166)
 at org.nlogo.parse.ExpressionParser$.$anonfun$parseArguments$1$adapted(ExpressionParser.scala:165)
 at scala.collection.immutable.Range.foreach(Range.scala:158)
 at org.nlogo.parse.ExpressionParser$.parseArguments(ExpressionParser.scala:165)
 at org.nlogo.parse.ExpressionParser$.parsePotentiallyVariadicArgumentList(ExpressionParser.scala:88)
 at org.nlogo.parse.ExpressionParser$.parseExpressionInternal(ExpressionParser.scala:418)
 at org.nlogo.parse.ExpressionParser$.parseExpression(ExpressionParser.scala:302)
 at org.nlogo.parse.ExpressionParser$.$anonfun$parseExpressionInternal$1(ExpressionParser.scala:358)
 at org.nlogo.parse.ExpressionParser$.parseParenthesized(ExpressionParser.scala:317)
 at org.nlogo.parse.ExpressionParser$.parseExpressionInternal(ExpressionParser.scala:363)
 at org.nlogo.parse.ExpressionParser$.parseArgExpression(ExpressionParser.scala:230)
 at org.nlogo.parse.ExpressionParser$.$anonfun$parseArguments$1(ExpressionParser.scala:166)
 at org.nlogo.parse.ExpressionParser$.$anonfun$parseArguments$1$adapted(ExpressionParser.scala:165)
 at scala.collection.immutable.Range.foreach(Range.scala:158)
 at org.nlogo.parse.ExpressionParser$.parseArguments(ExpressionParser.scala:165)
 at org.nlogo.parse.ExpressionParser$.parsePotentiallyVariadicArgumentList(ExpressionParser.scala:88)
 at org.nlogo.parse.ExpressionParser$.parseStatement(ExpressionParser.scala:69)
 at org.nlogo.parse.ExpressionParser$.$anonfun$apply$1(ExpressionParser.scala:30)
 at org.nlogo.parse.ExpressionParser$.parseStatements(ExpressionParser.scala:42)
 at org.nlogo.parse.ExpressionParser$.apply(ExpressionParser.scala:30)
 at org.nlogo.parse.NetLogoParser.parseProcedure(NetLogoParser.scala:45)
 at org.nlogo.parse.NetLogoParser.parseProcedure$(NetLogoParser.scala:29)
 at org.nlogo.parse.FrontEnd$.parseProcedure(FrontEnd.scala:10)
 at org.nlogo.parse.NetLogoParser.$anonfun$basicParse$1(NetLogoParser.scala:25)
 at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
 at scala.collection.Iterator.foreach(Iterator.scala:943)
 at scala.collection.Iterator.foreach$(Iterator.scala:943)
 at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
 at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:214)
 at scala.collection.TraversableLike.map(TraversableLike.scala:286)
 at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
 at scala.collection.AbstractTraversable.map(Traversable.scala:108)
 at org.nlogo.parse.NetLogoParser.basicParse(NetLogoParser.scala:25)
 at org.nlogo.parse.NetLogoParser.basicParse$(NetLogoParser.scala:15)
 at org.nlogo.parse.FrontEnd$.basicParse(FrontEnd.scala:10)
 at org.nlogo.parse.FrontEndMain.frontEnd(FrontEnd.scala:26)
 at org.nlogo.parse.FrontEndMain.frontEnd$(FrontEnd.scala:25)
 at org.nlogo.parse.FrontEnd$.frontEnd(FrontEnd.scala:10)
 at org.nlogo.compile.CompilerMain$.compile(CompilerMain.scala:47)
 at org.nlogo.compile.Compiler.compileMoreCode(Compiler.scala:85)
 at org.nlogo.compile.Compiler.compileMoreCode(Compiler.scala:100)
 at org.nlogo.workspace.Evaluator.invokeCompiler(Evaluator.scala:159)
 at org.nlogo.workspace.Evaluator.compileReporter(Evaluator.scala:38)
 at org.nlogo.workspace.Evaluating.compileReporter(Evaluating.scala:57)
 at org.nlogo.workspace.Evaluating.compileReporter$(Evaluating.scala:56)
 at org.nlogo.workspace.AbstractWorkspaceScala.compileReporter(AbstractWorkspaceScala.scala:26)
 at org.nlogo.lab.Worker$Procedures.$anonfun$metricProcedures$1(Worker.scala:72)
 at scala.collection.immutable.List.map(List.scala:293)
 at org.nlogo.lab.Worker$Procedures.<init>(Worker.scala:72)
 at org.nlogo.lab.Worker$Runner.callHelper(Worker.scala:101)
 at org.nlogo.lab.Worker$Runner.call(Worker.scala:91)
 at org.nlogo.lab.Worker$Runner.call(Worker.scala:74)
 at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
 at java.base/java.lang.Thread.run(Unknown Source)

NetLogo 6.3.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
OpenJDK 64-Bit Server VM 17.0.3 (BellSoft; 17.0.3+7-LTS)
operating system: Linux 5.19.0-35-generic (amd64 processor)
Scala version 2.12.16
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Viral_Marketing

05:13:39.317 AddSliderConstraintEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:13:39.317 AddSliderConstraintEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:13:39.317 AddSliderConstraintEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:13:39.317 AddSliderConstraintEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:13:39.317 AddBooleanConstraintEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
05:13:39.317 AddSliderConstraintEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:13:39.317 AddSliderConstraintEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:13:39.316 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
05:13:39.266 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
05:13:39.242 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0

**Comment by brandesNW** [comment]
Hi,
It appears that you have an undefined variable named saturated?
Do you have a variable with that name in your model?
Since you did not get a compiler error there must be something unusual about the situation.

The most useful thing for us would be for you to share your model as an attachment. Because GitHub does not accept .nlogo files please either creating a zip file containing the model, or changing the extension from .nlogo to .txt

We are sorry you have encountered this issue.


  *   Aaron

--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling


From: Ark ***@***.***>
Date: Wednesday, February 22, 2023 at 11:18 AM
To: NetLogo/NetLogo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [NetLogo/NetLogo] Internal Error report (Issue #2086)

NetLogo is unable to supply you with more details about this error. Please report the problem
at https://github.com/NetLogo/NetLogo/issues<https://urldefense.com/v3/__https:/github.com/NetLogo/NetLogo/issues__;!!Dq0X2DkFhyF93HkjWTBQKhk!XGVQqCMrGLL6cPS3YngrfBynKABSFblktmY1XCjWgUZGaEuJd16MSv4zppmPwEqUqqF7NPi9n2Axh9LbrGYLdu6iXwdGP5kZFg$>, or to ***@***.******@***.***>, and paste the
contents of this window into your report.

Nothing named SATURATED? has been defined. at position 73 in
at org.nlogo.core.Fail$.exception(Fail.scala:27)
at org.nlogo.core.Fail$.exception(Fail.scala:25)
at org.nlogo.core.Fail$.exception(Fail.scala:23)
at org.nlogo.parse.ExpressionParser$.$anonfun$parseExpressionInternal$4(ExpressionParser.scala:391)
at scala.Option.getOrElse(Option.scala:189)
at org.nlogo.parse.ExpressionParser$.parseExpressionInternal(ExpressionParser.scala:391)
at org.nlogo.parse.ExpressionParser$.parseArgExpression(ExpressionParser.scala:230)
at org.nlogo.parse.ExpressionParser$.$anonfun$parseArguments$1(ExpressionParser.scala:166)
at org.nlogo.parse.ExpressionParser$.$anonfun$parseArguments$1$adapted(ExpressionParser.scala:165)
at scala.collection.immutable.Range.foreach(Range.scala:158)
at org.nlogo.parse.ExpressionParser$.parseArguments(ExpressionParser.scala:165)
at org.nlogo.parse.ExpressionParser$.parsePotentiallyVariadicArgumentList(ExpressionParser.scala:88)
at org.nlogo.parse.ExpressionParser$.parseExpressionInternal(ExpressionParser.scala:418)
at org.nlogo.parse.ExpressionParser$.parseExpression(ExpressionParser.scala:302)
at org.nlogo.parse.ExpressionParser$.reporterApp$1(ExpressionParser.scala:568)
at org.nlogo.parse.ExpressionParser$.parseDelayedBlock(ExpressionParser.scala:611)
at org.nlogo.parse.ExpressionParser$.resolveType(ExpressionParser.scala:273)
at org.nlogo.parse.ExpressionParser$.resolveTypes(ExpressionParser.scala:127)
at org.nlogo.parse.ExpressionParser$.parseMore(ExpressionParser.scala:508)
at org.nlogo.parse.ExpressionParser$.parseExpressionInternal(ExpressionParser.scala:427)
at org.nlogo.parse.ExpressionParser$.parseArgExpression(ExpressionParser.scala:230)
at org.nlogo.parse.ExpressionParser$.$anonfun$parseArguments$1(ExpressionParser.scala:166)
at org.nlogo.parse.ExpressionParser$.$anonfun$parseArguments$1$adapted(ExpressionParser.scala:165)
at scala.collection.immutable.Range.foreach(Range.scala:158)
at org.nlogo.parse.ExpressionParser$.parseArguments(ExpressionParser.scala:165)
at org.nlogo.parse.ExpressionParser$.parsePotentiallyVariadicArgumentList(ExpressionParser.scala:88)
at org.nlogo.parse.ExpressionParser$.parseExpressionInternal(ExpressionParser.scala:418)
at org.nlogo.parse.ExpressionParser$.parseExpression(ExpressionParser.scala:302)
at org.nlogo.parse.ExpressionParser$.$anonfun$parseExpressionInternal$1(ExpressionParser.scala:358)
at org.nlogo.parse.ExpressionParser$.parseParenthesized(ExpressionParser.scala:317)
at org.nlogo.parse.ExpressionParser$.parseExpressionInternal(ExpressionParser.scala:363)
at org.nlogo.parse.ExpressionParser$.parseArgExpression(ExpressionParser.scala:230)
at org.nlogo.parse.ExpressionParser$.$anonfun$parseArguments$1(ExpressionParser.scala:166)
at org.nlogo.parse.ExpressionParser$.$anonfun$parseArguments$1$adapted(ExpressionParser.scala:165)
at scala.collection.immutable.Range.foreach(Range.scala:158)
at org.nlogo.parse.ExpressionParser$.parseArguments(ExpressionParser.scala:165)
at org.nlogo.parse.ExpressionParser$.parsePotentiallyVariadicArgumentList(ExpressionParser.scala:88)
at org.nlogo.parse.ExpressionParser$.parseStatement(ExpressionParser.scala:69)
at org.nlogo.parse.ExpressionParser$.$anonfun$apply$1(ExpressionParser.scala:30)
at org.nlogo.parse.ExpressionParser$.parseStatements(ExpressionParser.scala:42)
at org.nlogo.parse.ExpressionParser$.apply(ExpressionParser.scala:30)
at org.nlogo.parse.NetLogoParser.parseProcedure(NetLogoParser.scala:45)
at org.nlogo.parse.NetLogoParser.parseProcedure$(NetLogoParser.scala:29)
at org.nlogo.parse.FrontEnd$.parseProcedure(FrontEnd.scala:10)
at org.nlogo.parse.NetLogoParser.$anonfun$basicParse$1(NetLogoParser.scala:25)
at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
at scala.collection.Iterator.foreach(Iterator.scala:943)
at scala.collection.Iterator.foreach$(Iterator.scala:943)
at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:214)
at scala.collection.TraversableLike.map(TraversableLike.scala:286)
at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
at scala.collection.AbstractTraversable.map(Traversable.scala:108)
at org.nlogo.parse.NetLogoParser.basicParse(NetLogoParser.scala:25)
at org.nlogo.parse.NetLogoParser.basicParse$(NetLogoParser.scala:15)
at org.nlogo.parse.FrontEnd$.basicParse(FrontEnd.scala:10)
at org.nlogo.parse.FrontEndMain.frontEnd(FrontEnd.scala:26)
at org.nlogo.parse.FrontEndMain.frontEnd$(FrontEnd.scala:25)
at org.nlogo.parse.FrontEnd$.frontEnd(FrontEnd.scala:10)
at org.nlogo.compile.CompilerMain$.compile(CompilerMain.scala:47)
at org.nlogo.compile.Compiler.compileMoreCode(Compiler.scala:85)
at org.nlogo.compile.Compiler.compileMoreCode(Compiler.scala:100)
at org.nlogo.workspace.Evaluator.invokeCompiler(Evaluator.scala:159)
at org.nlogo.workspace.Evaluator.compileReporter(Evaluator.scala:38)
at org.nlogo.workspace.Evaluating.compileReporter(Evaluating.scala:57)
at org.nlogo.workspace.Evaluating.compileReporter$(Evaluating.scala:56)
at org.nlogo.workspace.AbstractWorkspaceScala.compileReporter(AbstractWorkspaceScala.scala:26)
at org.nlogo.lab.Worker$Procedures.$anonfun$metricProcedures$1(Worker.scala:72)
at scala.collection.immutable.List.map(List.scala:293)
at org.nlogo.lab.Worker$Procedures.(Worker.scala:72)
at org.nlogo.lab.Worker$Runner.callHelper(Worker.scala:101)
at org.nlogo.lab.Worker$Runner.call(Worker.scala:91)
at org.nlogo.lab.Worker$Runner.call(Worker.scala:74)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)

NetLogo 6.3.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
OpenJDK 64-Bit Server VM 17.0.3 (BellSoft; 17.0.3+7-LTS)
operating system: Linux 5.19.0-35-generic (amd64 processor)
Scala version 2.12.16
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Viral_Marketing

05:13:39.317 AddSliderConstraintEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:13:39.317 AddSliderConstraintEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:13:39.317 AddSliderConstraintEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:13:39.317 AddSliderConstraintEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:13:39.317 AddBooleanConstraintEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
05:13:39.317 AddSliderConstraintEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:13:39.317 AddSliderConstraintEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:13:39.316 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
05:13:39.266 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
05:13:39.242 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0

**Comment by SethTisue** [comment]
I see `org.nlogo.lab` in the stack trace, so maybe this is just the usual problem with BehaviorSpace not properly reporting compiler errors... not sure what the canonical ticket number on that is, maybe #761? (which links to other related tickets)
