### ISSUE TITLE
Behaviorspace crashed, during a long run.

### ISSUE THREAD

**Issue by Rhagium** [NetLogo/NetLogo#2092]
This is the error message I got.

NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 

java.nio.file.InvalidPathException: Trailing char < > at index 4: from 
 at java.base/sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
 at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
 at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
 at java.base/sun.nio.fs.WindowsPath.parse(Unknown Source)
 at java.base/sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
 at java.base/java.io.File.toPath(Unknown Source)
 at org.nlogo.properties.FilePathEditor.asPath(FilePathEditor.scala:50)
 at org.nlogo.properties.FilePathEditor.get(FilePathEditor.scala:69)
 at org.nlogo.properties.EditPanel$Changed.changed(EditPanel.scala:295)
 at org.nlogo.properties.EditPanel$Changed.changed$(EditPanel.scala:294)
 at org.nlogo.properties.EditPanel$$anon$24.changed(EditPanel.scala:289)
 at org.nlogo.properties.FilePathEditor.$anonfun$new$1(FilePathEditor.scala:26)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
 at org.nlogo.swing.Implicits$.$anonfun$thunk2documentListener$1(Implicits.scala:20)
 at org.nlogo.swing.Implicits$$anon$3.insertUpdate(Implicits.scala:23)
 at java.desktop/javax.swing.text.AbstractDocument.fireInsertUpdate(Unknown Source)
 at java.desktop/javax.swing.text.AbstractDocument.handleInsertString(Unknown Source)
 at java.desktop/javax.swing.text.AbstractDocument.insertString(Unknown Source)
 at java.desktop/javax.swing.text.PlainDocument.insertString(Unknown Source)
 at java.desktop/javax.swing.text.AbstractDocument.replace(Unknown Source)
 at java.desktop/javax.swing.text.JTextComponent.replaceSelection(Unknown Source)
 at java.desktop/javax.swing.text.DefaultEditorKit$DefaultKeyTypedAction.actionPerformed(Unknown Source)
 at java.desktop/javax.swing.SwingUtilities.notifyAction(Unknown Source)
 at java.desktop/javax.swing.JComponent.processKeyBinding(Unknown Source)
 at java.desktop/javax.swing.JComponent.processKeyBindings(Unknown Source)
 at java.desktop/javax.swing.JComponent.processKeyEvent(Unknown Source)
 at java.desktop/java.awt.Component.processEvent(Unknown Source)
 at java.desktop/java.awt.Container.processEvent(Unknown Source)
 at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
 at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(Unknown Source)
 at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(Unknown Source)
 at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
 at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
 at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
 at java.base/java.security.AccessController.doPrivileged(Unknown Source)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
 at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
 at java.base/java.security.AccessController.doPrivileged(Unknown Source)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
 at java.desktop/java.awt.WaitDispatchSupport$2.run(Unknown Source)
 at java.desktop/java.awt.WaitDispatchSupport$4.run(Unknown Source)
 at java.desktop/java.awt.WaitDispatchSupport$4.run(Unknown Source)
 at java.base/java.security.AccessController.doPrivileged(Unknown Source)
 at java.desktop/java.awt.WaitDispatchSupport.enter(Unknown Source)
 at java.desktop/java.awt.Dialog.show(Unknown Source)
 at java.desktop/java.awt.Component.show(Unknown Source)
 at java.desktop/java.awt.Component.setVisible(Unknown Source)
 at java.desktop/java.awt.Window.setVisible(Unknown Source)
 at java.desktop/java.awt.Dialog.setVisible(Unknown Source)
 at org.nlogo.properties.EditDialog.$init$(EditDialog.scala:116)
 at org.nlogo.properties.EditDialogFactory$$anon$2.<init>(EditDialogFactory.scala:23)
 at org.nlogo.properties.EditDialogFactory.canceled(EditDialogFactory.scala:23)
 at org.nlogo.lab.gui.RunOptionsDialog.get(RunOptionsDialog.scala:67)
 at org.nlogo.lab.gui.Supervisor.liftedTree1$1(Supervisor.scala:81)
 at org.nlogo.lab.gui.Supervisor.start(Supervisor.scala:80)
 at org.nlogo.lab.gui.ManagerDialog.run(ManagerDialog.scala:103)
 at org.nlogo.lab.gui.ManagerDialog.$anonfun$runAction$1(ManagerDialog.scala:30)
 at org.nlogo.lab.gui.ManagerDialog$$anon$1.actionPerformed(ManagerDialog.scala:24)
 at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
 at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
 at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
 at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
 at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
 at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
 at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
 at java.desktop/java.awt.Component.processEvent(Unknown Source)
 at java.desktop/java.awt.Container.processEvent(Unknown Source)
 at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
 at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
 at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
 at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
 at java.base/java.security.AccessController.doPrivileged(Unknown Source)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
 at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
 at java.base/java.security.AccessController.doPrivileged(Unknown Source)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

NetLogo 6.3.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
OpenJDK 64-Bit Server VM 17.0.3 (BellSoft; 17.0.3+7-LTS)
operating system: Windows 11 10.0 (amd64 processor)
Scala version 2.12.16
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: 20230309 A3 SPARTA resistance Kees and Anno

10:16:59.713 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
10:16:59.713 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
10:16:59.713 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
10:16:59.713 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
10:16:59.713 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
10:16:59.713 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
10:16:59.713 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:16:59.461 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
10:16:59.461 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
10:16:59.461 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0

**Comment by brandesNW** [comment]
We are sorry you have encountered this error. Currently we are working on improving the handling of errors encountered during Behaviorspace runs.
Were you able to determine the source of your error? Does your code create its own output files, or might NetLogo have been trying to create a spreadsheet output?
If you could attach a simple model that reproduces  the problem as a zip file we would appreciate it.

**Comment by brandesNW** [comment]
One possibility is that you have a space character at the end of the output file name. If so try removing it.
