### ISSUE TITLE
nlrx issue 

### ISSUE THREAD

**Issue by ErkinaiDerkenbaeva** [NetLogo/NetLogo#2093]
Hi there, 

I am encountering an issue with running the sensitivity analysis using nlrx R package. Namely, it gives me the following error:

Exception in thread "main" Illegal number format at position 0 in 
	at org.nlogo.parse.Namer0$.apply(Namer0.scala:11)
	at org.nlogo.parse.Namer0$.apply(Namer0.scala:8)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at org.nlogo.parse.LiteralParser.getLiteralValue(LiteralParser.scala:33)
	at org.nlogo.parse.CompilerUtilities$.$anonfun$readFromString$3(CompilerUtilities.scala:22)
	at org.nlogo.parse.CompilerUtilities$.$anonfun$numberOrElse$1(CompilerUtilities.scala:37)
	at scala.util.Either$RightProjection.getOrElse(Either.scala:665)
	at org.nlogo.parse.CompilerUtilities$.numberOrElse(CompilerUtilities.scala:36)
	at org.nlogo.parse.CompilerUtilities$.readFromString(CompilerUtilities.scala:22)
	at org.nlogo.fileformat.LabLoader.$anonfun$readProtocolElement$4(LabLoader.scala:70)
	at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:935)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:934)
	at org.nlogo.fileformat.LabLoader.readEnumeratedValueSetElement$1(LabLoader.scala:66)
	at org.nlogo.fileformat.LabLoader.$anonfun$readProtocolElement$5(LabLoader.scala:77)
	at scala.collection.immutable.List.flatMap(List.scala:366)
	at org.nlogo.fileformat.LabLoader.valueSets$1(LabLoader.scala:74)
	at org.nlogo.fileformat.LabLoader.readProtocolElement(LabLoader.scala:94)
	at org.nlogo.fileformat.LabLoader.$anonfun$apply$1(LabLoader.scala:45)
	at scala.collection.immutable.List.map(List.scala:293)
	at org.nlogo.fileformat.LabLoader.apply(LabLoader.scala:45)
	at org.nlogo.fileformat.LabLoader.apply(LabLoader.scala:30)
	at org.nlogo.fileformat.LabFormat.load(NLogoLabFormat.scala:37)
	at org.nlogo.fileformat.LabFormat.load$(NLogoLabFormat.scala:35)
	at org.nlogo.fileformat.NLogoLabFormat.load(NLogoLabFormat.scala:40)
	at org.nlogo.headless.BehaviorSpaceCoordinator$.$anonfun$selectProtocol$1(BehaviorSpaceCoordinator.scala:34)
	at scala.Option.map(Option.scala:230)
	at org.nlogo.headless.BehaviorSpaceCoordinator$.selectProtocol(BehaviorSpaceCoordinator.scala:32)
	at org.nlogo.headless.Main$.runExperiment(Main.scala:26)
	at org.nlogo.headless.Main$.$anonfun$main$1(Main.scala:14)
	at org.nlogo.headless.Main$.$anonfun$main$1$adapted(Main.scala:14)
	at scala.Option.foreach(Option.scala:407)
	at org.nlogo.headless.Main$.main(Main.scala:14)
	at org.nlogo.headless.Main.main(Main.scala)

I would appreciate it if anyone could help with fixing this issue. Thank you.

**Comment by erkinaiderkenbaeva** [comment]
Hi @brandesNW, 

I greatly appreciate your comprehensive guide. 
I successfully ran the 6.3.0 sample examples without any issues. Unfortunately, my model does not work. I have tested it on macOS and encountered the same issue. 

The output of my  nlrx  script is as follows:

```r
results = run_nl_all(model, cleanup.xml = FALSE)
Exception in thread "main" Illegal number format at position 0 in 
	at org.nlogo.parse.Namer0$.apply(Namer0.scala:11)
	at org.nlogo.parse.Namer0$.apply(Namer0.scala:8)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at org.nlogo.parse.LiteralParser.getLiteralValue(LiteralParser.scala:33)
	at org.nlogo.parse.CompilerUtilities$.$anonfun$readFromString$3(CompilerUtilities.scala:22)
	at org.nlogo.parse.CompilerUtilities$.$anonfun$numberOrElse$1(CompilerUtilities.scala:37)
	at scala.util.Either$RightProjection.getOrElse(Either.scala:665)
	at org.nlogo.parse.CompilerUtilities$.numberOrElse(CompilerUtilities.scala:36)
	at org.nlogo.parse.CompilerUtilities$.readFromString(CompilerUtilities.scala:22)
	at org.nlogo.fileformat.LabLoader.$anonfun$readProtocolElement$4(LabLoader.scala:70)
	at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:935)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:934)
	at org.nlogo.fileformat.LabLoader.readEnumeratedValueSetElement$1(LabLoader.scala:66)
	at org.nlogo.fileformat.LabLoader.$anonfun$readProtocolElement$5(LabLoader.scala:77)
	at scala.collection.immutable.List.flatMap(List.scala:366)
	at org.nlogo.fileformat.LabLoader.valueSets$1(LabLoader.scala:74)
	at org.nlogo.fileformat.LabLoader.readProtocolElement(LabLoader.scala:94)
	at org.nlogo.fileformat.LabLoader.$anonfun$apply$1(LabLoader.scala:45)
	at scala.collection.immutable.List.map(List.scala:293)
	at org.nlogo.fileformat.LabLoader.apply(LabLoader.scala:45)
	at org.nlogo.fileformat.LabLoader.apply(LabLoader.scala:30)
	at org.nlogo.fileformat.LabFormat.load(NLogoLabFormat.scala:37)
	at org.nlogo.fileformat.LabFormat.load$(NLogoLabFormat.scala:35)
	at org.nlogo.fileformat.NLogoLabFormat.load(NLogoLabFormat.scala:40)
	at org.nlogo.headless.BehaviorSpaceCoordinator$.$anonfun$selectProtocol$1(BehaviorSpaceCoordinator.scala:34)
	at scala.Option.map(Option.scala:230)
	at org.nlogo.headless.BehaviorSpaceCoordinator$.selectProtocol(BehaviorSpaceCoordinator.scala:32)
	at org.nlogo.headless.Main$.runExperiment(Main.scala:26)
	at org.nlogo.headless.Main$.$anonfun$main$1(Main.scala:14)
	at org.nlogo.headless.Main$.$anonfun$main$1$adapted(Main.scala:14)
	at scala.Option.foreach(Option.scala:407)
	at org.nlogo.headless.Main$.main(Main.scala:14)
	at org.nlogo.headless.Main.main(Main.scala)
Error in (function (.x, .f, ..., .progress = FALSE)  : 
  ℹ In index: 1.
Caused by error:
ℹ In index: 1.
Caused by error in `util_gather_results()`:
! Output file is empty - simulation aborted due to a runtime error!
         Make sure that parameter value definitions of the experiment are valid and the model code is running properly!
```

Then, I did what you suggested. And, here is the result:

```bash
❯ NetLogo_Console --headless\
                  --model ~/Documents/model/BehaviorSpace_v6.0.nlog\
                  --setup-file ~/Documents/debug/nlrx_seed_902107894_row_1_2134f2d7fe0.xml\
                  --experiment experiment3\
                  --table ~/Documents/debug/debug.csv

/Applications/NetLogo 6.3.0 
❯                            

/Applications/NetLogo 6.3.0 
❯ NetLogo_Console --headless\
   --model ~/pCloud-Drive/Pastebin/Moya/NetLogo-Ams-Mark/model/BehaviorSpace_v6.0.nlogo\ 
   --setup-file ~/pCloud-Drive/Pastebin/Moya/NetLogo-Ams-Mark/debug/nlrx_seed_902107894_row_1_2134f2d7fe0.xml\
   --experiment experiment3\
   --table ~/pCloud-Drive/Pastebin/Moya/NetLogo-Ams-Mark/debug/debug.csv
Could not invoke mainWithAppHandler on org.nlogo.app.App$
null
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.nlogo.app.MacApplication.invokeMainWithAppHandlerOrFallback(MacApplication.java:76)
        at org.nlogo.app.MacApplication.launchScalaMain(MacApplication.java:66)
        at org.nlogo.app.MacApplication.main(MacApplication.java:49)
Caused by: Illegal number format at position 0 in 
        at org.nlogo.parse.Namer0$.apply(Namer0.scala:11)
        at org.nlogo.parse.Namer0$.apply(Namer0.scala:8)
        at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
        at org.nlogo.parse.LiteralParser.getLiteralValue(LiteralParser.scala:33)
        at org.nlogo.parse.CompilerUtilities$.$anonfun$readFromString$3(CompilerUtilities.scala:22)
        at org.nlogo.parse.CompilerUtilities$.$anonfun$numberOrElse$1(CompilerUtilities.scala:37)
        at scala.util.Either$RightProjection.getOrElse(Either.scala:665)
        at org.nlogo.parse.CompilerUtilities$.numberOrElse(CompilerUtilities.scala:36)
        at org.nlogo.parse.CompilerUtilities$.readFromString(CompilerUtilities.scala:22)
        at org.nlogo.fileformat.LabLoader.$anonfun$readProtocolElement$4(LabLoader.scala:70)
        at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:935)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:934)
        at org.nlogo.fileformat.LabLoader.readEnumeratedValueSetElement$1(LabLoader.scala:66)
        at org.nlogo.fileformat.LabLoader.$anonfun$readProtocolElement$5(LabLoader.scala:77)
        at scala.collection.immutable.List.flatMap(List.scala:366)
        at org.nlogo.fileformat.LabLoader.valueSets$1(LabLoader.scala:74)
        at org.nlogo.fileformat.LabLoader.readProtocolElement(LabLoader.scala:94)
        at org.nlogo.fileformat.LabLoader.$anonfun$apply$1(LabLoader.scala:45)
        at scala.collection.immutable.List.map(List.scala:293)
        at org.nlogo.fileformat.LabLoader.apply(LabLoader.scala:45)
        at org.nlogo.fileformat.LabLoader.apply(LabLoader.scala:30)
        at org.nlogo.fileformat.LabFormat.load(NLogoLabFormat.scala:37)
        at org.nlogo.fileformat.LabFormat.load$(NLogoLabFormat.scala:35)
        at org.nlogo.fileformat.NLogoLabFormat.load(NLogoLabFormat.scala:40)
        at org.nlogo.headless.BehaviorSpaceCoordinator$.$anonfun$selectProtocol$1(BehaviorSpaceCoordinator.scala:34)
        at scala.Option.map(Option.scala:230)
        at org.nlogo.headless.BehaviorSpaceCoordinator$.selectProtocol(BehaviorSpaceCoordinator.scala:32)
        at org.nlogo.headless.Main$.runExperiment(Main.scala:26)
        at org.nlogo.headless.Main$.$anonfun$main$1(Main.scala:14)
        at org.nlogo.headless.Main$.$anonfun$main$1$adapted(Main.scala:14)
        at scala.Option.foreach(Option.scala:407)
        at org.nlogo.headless.Main$.main(Main.scala:14)
        at org.nlogo.app.App$.mainWithAppHandler(App.scala:73)
        ... 7 more

/Applications/NetLogo 6.3.0 took 6s 
❯ 
```


Can we rule out any Java, NetLogo, or nlrx related issues since the example code ran successfully? Is it possible that my model is the source of the problem, even though it ran correctly in NetLogo?


### Session Info


```bash
❯ java -version
java version "16.0.2" 2021-07-20
Java(TM) SE Runtime Environment (build 16.0.2+7-67)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.2+7-67, mixed mode, sharing)
javac -version
javac 16.0.2
```

#### Example code that runs

```r
library(nlrx)

netlogopath <- file.path("/Applications/NetLogo 6.3.0/")
modelpath <- file.path(netlogopath, "models/Sample Models/Biology/Wolf Sheep Predation.nlogo")
outpath <- "example_out/"
nl <- nl(
  nlversion = "6.3.0",
  nlpath = netlogopath,
  modelpath = modelpath,
  jvmmem = 1024
)

nl@experiment <- experiment(
  expname = "wolf-sheep",
  outpath = outpath,
  repetition = 1,
  tickmetrics = "false",
  idsetup = "setup",
  idgo = "go",
  runtime = 50,
  evalticks = seq(40,50),
  metrics = c("count sheep", "count wolves", "count patches with [pcolor = green]"),
  metrics.turtles = list("turtles" = c("energy")),
  variables = list(
    "initial-number-sheep" = list(min = 50, max = 150, qfun = "qunif"),
    "initial-number-wolves" = list(min = 50, max = 150, qfun = "qunif")
  ),
  constants = list(
    "model-version" = "\"sheep-wolves-grass\"",
    "grass-regrowth-time" = 30,
    "sheep-gain-from-food" = 4,
    "wolf-gain-from-food" = 20,
    "sheep-reproduce" = 4,
    "wolf-reproduce" = 5,
    "show-energy?" = "false"
  )
)

nl@simdesign <- simdesign_lhs(
  nl = nl,
  samples = 3,
  nseed = 1,
  precision = 3
)

results <- run_nl_all(nl, cleanup.xml = FALSE, cleanup.bat = FALSE)

# Attach results to nl object:
setsim(nl, "simoutput") <- results

# Write output to outpath of experiment within nl
write_simoutput(nl)

# Do further analysis:
analyze_nl(nl)

```

**Comment by brandesNW** [comment]
Hi,
Thanks for trying out all my suggestions.
It is possible that there is a problem with your model.
One thing you should also try with NetLogo_Console is running with only one thread.
It is possible that you have a variable or initialization error that only shows up when multiple threads are used.
Also since  you are running a large model it is best to not use more threads than about half the number of CPUs. Currently the default number of threads equals the number of CPUs.
Ideally you would get an “out of memory” message if that was the problem, but exceptions and stack traces are not always as helpful as we would prefer.

Here is an example of how to set the number of  threads to 1.


NetLogo_Console --headless\

   --model ~/pCloud-Drive/Pastebin/Moya/NetLogo-Ams-Mark/model/BehaviorSpace_v6.0.nlogo\

   --setup-file ~/pCloud-Drive/Pastebin/Moya/NetLogo-Ams-Mark/debug/nlrx_seed_902107894_row_1_2134f2d7fe0.xml\

   --threads 1 \

   --experiment experiment3\

   --table ~/pCloud-Drive/Pastebin/Moya/NetLogo-Ams-Mark/debug/debug.csv

In your first NetLogo_Console example the model name ends in .nlog not .nlogo. Is that just a copying error?
Did this run, or did it give a similar error to the second example?
Also in either of the cases was a table output file created?


❯ NetLogo_Console --headless\

                  --model ~/Documents/model/BehaviorSpace_v6.0.nlog\

                  --setup-file ~/Documents/debug/nlrx_seed_902107894_row_1_2134f2d7fe0.xml\

                  --experiment experiment3\

                  --table ~/Documents/debug/debug.csv

If none of this works would it be possible for you to share your model. We can do in a non-publically available way if necessary.

- Aaron
--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling


From: Erkinai Derkenbaeva ***@***.***>
Date: Monday, March 20, 2023 at 5:31 PM
To: NetLogo/NetLogo ***@***.***>
Cc: Aaron Andre Brandes ***@***.***>, Mention ***@***.***>
Subject: Re: [NetLogo/NetLogo] nlrx issue (Issue #2093)

Hi @brandesNW<https://urldefense.com/v3/__https:/github.com/brandesNW__;!!Dq0X2DkFhyF93HkjWTBQKhk!Uta6RGVEVtRKQSGbpJDmzOSQM8EJ_Ut3vuJ9mqTvalYHpCod8TG2jSGOeetMGHEJvNo-tkqtFD3AC_rlSti8LD869fhp1rMRyQ$>,

I greatly appreciate your comprehensive guide.
I successfully ran the 6.3.0 sample examples without any issues. Unfortunately, my model does not work. I have tested it on macOS and encountered the same issue.

The output of my  nlrx  script is as follows:

results = run_nl_all(model, cleanup.xml = FALSE)

Exception in thread "main" Illegal number format at position 0 in

        at org.nlogo.parse.Namer0$.apply(Namer0.scala:11)

        at org.nlogo.parse.Namer0$.apply(Namer0.scala:8)

        at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)

        at org.nlogo.parse.LiteralParser.getLiteralValue(LiteralParser.scala:33)

        at org.nlogo.parse.CompilerUtilities$.$anonfun$readFromString$3(CompilerUtilities.scala:22)

        at org.nlogo.parse.CompilerUtilities$.$anonfun$numberOrElse$1(CompilerUtilities.scala:37)

        at scala.util.Either$RightProjection.getOrElse(Either.scala:665)

        at org.nlogo.parse.CompilerUtilities$.numberOrElse(CompilerUtilities.scala:36)

        at org.nlogo.parse.CompilerUtilities$.readFromString(CompilerUtilities.scala:22)

        at org.nlogo.fileformat.LabLoader.$anonfun$readProtocolElement$4(LabLoader.scala:70)

        at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:935)

        at scala.collection.Iterator.foreach(Iterator.scala:943)

        at scala.collection.Iterator.foreach$(Iterator.scala:943)

        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)

        at scala.collection.IterableLike.foreach(IterableLike.scala:74)

        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)

        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)

        at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:934)

        at org.nlogo.fileformat.LabLoader.readEnumeratedValueSetElement$1(LabLoader.scala:66)

        at org.nlogo.fileformat.LabLoader.$anonfun$readProtocolElement$5(LabLoader.scala:77)

        at scala.collection.immutable.List.flatMap(List.scala:366)

        at org.nlogo.fileformat.LabLoader.valueSets$1(LabLoader.scala:74)

        at org.nlogo.fileformat.LabLoader.readProtocolElement(LabLoader.scala:94)

        at org.nlogo.fileformat.LabLoader.$anonfun$apply$1(LabLoader.scala:45)

        at scala.collection.immutable.List.map(List.scala:293)

        at org.nlogo.fileformat.LabLoader.apply(LabLoader.scala:45)

        at org.nlogo.fileformat.LabLoader.apply(LabLoader.scala:30)

        at org.nlogo.fileformat.LabFormat.load(NLogoLabFormat.scala:37)

        at org.nlogo.fileformat.LabFormat.load$(NLogoLabFormat.scala:35)

        at org.nlogo.fileformat.NLogoLabFormat.load(NLogoLabFormat.scala:40)

        at org.nlogo.headless.BehaviorSpaceCoordinator$.$anonfun$selectProtocol$1(BehaviorSpaceCoordinator.scala:34)

        at scala.Option.map(Option.scala:230)

        at org.nlogo.headless.BehaviorSpaceCoordinator$.selectProtocol(BehaviorSpaceCoordinator.scala:32)

        at org.nlogo.headless.Main$.runExperiment(Main.scala:26)

        at org.nlogo.headless.Main$.$anonfun$main$1(Main.scala:14)

        at org.nlogo.headless.Main$.$anonfun$main$1$adapted(Main.scala:14)

        at scala.Option.foreach(Option.scala:407)

        at org.nlogo.headless.Main$.main(Main.scala:14)

        at org.nlogo.headless.Main.main(Main.scala)

Error in (function (.x, .f, ..., .progress = FALSE)  :

  ℹ In index: 1.

Caused by error:

ℹ In index: 1.

Caused by error in `util_gather_results()`:

! Output file is empty - simulation aborted due to a runtime error!

         Make sure that parameter value definitions of the experiment are valid and the model code is running properly!

Then, I did what you suggested. And, here is the result:

❯ NetLogo_Console --headless\

                  --model ~/Documents/model/BehaviorSpace_v6.0.nlog\

                  --setup-file ~/Documents/debug/nlrx_seed_902107894_row_1_2134f2d7fe0.xml\

                  --experiment experiment3\

                  --table ~/Documents/debug/debug.csv



/Applications/NetLogo 6.3.0

❯



/Applications/NetLogo 6.3.0

❯ NetLogo_Console --headless\

   --model ~/pCloud-Drive/Pastebin/Moya/NetLogo-Ams-Mark/model/BehaviorSpace_v6.0.nlogo\

   --setup-file ~/pCloud-Drive/Pastebin/Moya/NetLogo-Ams-Mark/debug/nlrx_seed_902107894_row_1_2134f2d7fe0.xml\

   --experiment experiment3\

   --table ~/pCloud-Drive/Pastebin/Moya/NetLogo-Ams-Mark/debug/debug.csv

Could not invoke mainWithAppHandler on org.nlogo.app.App$

null

java.lang.reflect.InvocationTargetException

        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

        at java.base/java.lang.reflect.Method.invoke(Unknown Source)

        at org.nlogo.app.MacApplication.invokeMainWithAppHandlerOrFallback(MacApplication.java:76)

        at org.nlogo.app.MacApplication.launchScalaMain(MacApplication.java:66)

        at org.nlogo.app.MacApplication.main(MacApplication.java:49)

Caused by: Illegal number format at position 0 in

        at org.nlogo.parse.Namer0$.apply(Namer0.scala:11)

        at org.nlogo.parse.Namer0$.apply(Namer0.scala:8)

        at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)

        at org.nlogo.parse.LiteralParser.getLiteralValue(LiteralParser.scala:33)

        at org.nlogo.parse.CompilerUtilities$.$anonfun$readFromString$3(CompilerUtilities.scala:22)

        at org.nlogo.parse.CompilerUtilities$.$anonfun$numberOrElse$1(CompilerUtilities.scala:37)

        at scala.util.Either$RightProjection.getOrElse(Either.scala:665)

        at org.nlogo.parse.CompilerUtilities$.numberOrElse(CompilerUtilities.scala:36)

        at org.nlogo.parse.CompilerUtilities$.readFromString(CompilerUtilities.scala:22)

        at org.nlogo.fileformat.LabLoader.$anonfun$readProtocolElement$4(LabLoader.scala:70)

        at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:935)

        at scala.collection.Iterator.foreach(Iterator.scala:943)

        at scala.collection.Iterator.foreach$(Iterator.scala:943)

        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)

        at scala.collection.IterableLike.foreach(IterableLike.scala:74)

        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)

        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)

        at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:934)

        at org.nlogo.fileformat.LabLoader.readEnumeratedValueSetElement$1(LabLoader.scala:66)

        at org.nlogo.fileformat.LabLoader.$anonfun$readProtocolElement$5(LabLoader.scala:77)

        at scala.collection.immutable.List.flatMap(List.scala:366)

        at org.nlogo.fileformat.LabLoader.valueSets$1(LabLoader.scala:74)

        at org.nlogo.fileformat.LabLoader.readProtocolElement(LabLoader.scala:94)

        at org.nlogo.fileformat.LabLoader.$anonfun$apply$1(LabLoader.scala:45)

        at scala.collection.immutable.List.map(List.scala:293)

        at org.nlogo.fileformat.LabLoader.apply(LabLoader.scala:45)

        at org.nlogo.fileformat.LabLoader.apply(LabLoader.scala:30)

        at org.nlogo.fileformat.LabFormat.load(NLogoLabFormat.scala:37)

        at org.nlogo.fileformat.LabFormat.load$(NLogoLabFormat.scala:35)

        at org.nlogo.fileformat.NLogoLabFormat.load(NLogoLabFormat.scala:40)

        at org.nlogo.headless.BehaviorSpaceCoordinator$.$anonfun$selectProtocol$1(BehaviorSpaceCoordinator.scala:34)

        at scala.Option.map(Option.scala:230)

        at org.nlogo.headless.BehaviorSpaceCoordinator$.selectProtocol(BehaviorSpaceCoordinator.scala:32)

        at org.nlogo.headless.Main$.runExperiment(Main.scala:26)

        at org.nlogo.headless.Main$.$anonfun$main$1(Main.scala:14)

        at org.nlogo.headless.Main$.$anonfun$main$1$adapted(Main.scala:14)

        at scala.Option.foreach(Option.scala:407)

        at org.nlogo.headless.Main$.main(Main.scala:14)

        at org.nlogo.app.App$.mainWithAppHandler(App.scala:73)

        ... 7 more



/Applications/NetLogo 6.3.0 took 6s

❯

Can we rule out any Java, NetLogo, or nlrx related issues since the example code ran successfully? Is it possible that my model is the source of the problem, even though it ran correctly in NetLogo?

Session Info

❯ java -version

java version "16.0.2" 2021-07-20

Java(TM) SE Runtime Environment (build 16.0.2+7-67)

Java HotSpot(TM) 64-Bit Server VM (build 16.0.2+7-67, mixed mode, sharing)

javac -version

javac 16.0.2

Example code that runs

library(nlrx)



netlogopath <- file.path("/Applications/NetLogo 6.3.0/")

modelpath <- file.path(netlogopath, "models/Sample Models/Biology/Wolf Sheep Predation.nlogo")

outpath <- "example_out/"

nl <- nl(

  nlversion = "6.3.0",

  nlpath = netlogopath,

  modelpath = modelpath,

  jvmmem = 1024

)



***@***.*** <- experiment(

  expname = "wolf-sheep",

  outpath = outpath,

  repetition = 1,

  tickmetrics = "false",

  idsetup = "setup",

  idgo = "go",

  runtime = 50,

  evalticks = seq(40,50),

  metrics = c("count sheep", "count wolves", "count patches with [pcolor = green]"),

  metrics.turtles = list("turtles" = c("energy")),

  variables = list(

    "initial-number-sheep" = list(min = 50, max = 150, qfun = "qunif"),

    "initial-number-wolves" = list(min = 50, max = 150, qfun = "qunif")

  ),

  constants = list(

    "model-version" = "\"sheep-wolves-grass\"",

    "grass-regrowth-time" = 30,

    "sheep-gain-from-food" = 4,

    "wolf-gain-from-food" = 20,

    "sheep-reproduce" = 4,

    "wolf-reproduce" = 5,

    "show-energy?" = "false"

  )

)



***@***.*** <- simdesign_lhs(

  nl = nl,

  samples = 3,

  nseed = 1,

  precision = 3

)



results <- run_nl_all(nl, cleanup.xml = FALSE, cleanup.bat = FALSE)



# Attach results to nl object:

setsim(nl, "simoutput") <- results



# Write output to outpath of experiment within nl

write_simoutput(nl)



# Do further analysis:

analyze_nl(nl)
