### ISSUE TITLE
netlogo error

### ISSUE THREAD

**Issue by SaulC018** [NetLogo/NetLogo#2103]
NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 

java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 0
 at org.nlogo.agent.Observer.getVariable(Observer.scala:16)
 at org.nlogo.prim._asm_monitornumberofsharks_count_0.report(:2)
 at org.nlogo.prim.etc._monitorprecision.report(_monitorprecision.java:16)
 at org.nlogo.prim.gui._updatemonitor.perform(_updatemonitor.scala:15)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
 at org.nlogo.job.JobThread.runSecondaryJobs(JobThread.scala:168)
 at org.nlogo.job.JobThread.maybeRunSecondaryJobs(JobThread.scala:91)
 at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:69)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
 at scala.util.control.Exception$Catch.apply(Exception.scala:228)
 at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:66)

NetLogo 6.3.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
OpenJDK 64-Bit Server VM 17.0.3 (BellSoft; 17.0.3+7-LTS)
operating system: Windows 11 10.0 (amd64 processor)
Scala version 2.12.16
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: lab10_advecosystem,nlogo

08:17:55.534 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
08:17:55.534 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
08:17:55.534 AddJobEvent (org.nlogo.window.MonitorWidget) AWT-EventQueue-0
08:17:55.534 AddJobEvent (org.nlogo.window.MonitorWidget) AWT-EventQueue-0
08:17:55.534 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
08:17:55.534 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
08:17:55.533 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
08:17:55.531 RemoveAllJobsEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
08:17:55.531 CompileAllEvent (org.nlogo.app.interfacetab.InterfacePanel) AWT-EventQueue-0
08:17:55.522 RemoveConstraintEvent (org.nlogo.app.interfacetab.InterfacePanel) AWT-EventQueue-0

**Comment by brandesNW** [comment]
Hi
We are sorry you ran into this problem.
In order to give you more help we need to be able to reproduce the problem.
If can send instructions on how to make the problem show up that would be great.
If you want include a model please put it in a zip file because GitHub does not accept .nlogo files.
If you can only reproduce it in a model you don’t want to make public let us know and we can make arrangements.

If you can’t reproduce the problem please give us as much information as you can about what lead up to the error message.

-Aaron

--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling


From: SaulC018 ***@***.***>
Date: Saturday, April 8, 2023 at 10:20 PM
To: NetLogo/NetLogo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [NetLogo/NetLogo] netlogo error (Issue #2103)

NetLogo is unable to supply you with more details about this error. Please report the problem
at https://github.com/NetLogo/NetLogo/issues<https://urldefense.com/v3/__https:/github.com/NetLogo/NetLogo/issues__;!!Dq0X2DkFhyF93HkjWTBQKhk!W6LRFo5B4bRe8qUXgI-hx0CDHEhic965eBNBHaRB4h1PVtoA34W17cKKQ-2CawkHDvV-X_GqBmMO21PlThyUApnk9gwTCl_ckA$>, or to ***@***.******@***.***>, and paste the
contents of this window into your report.

java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 0
at org.nlogo.agent.Observer.getVariable(Observer.scala:16)
at org.nlogo.prim._asm_monitornumberofsharks_count_0.report(:2)
at org.nlogo.prim.etc._monitorprecision.report(_monitorprecision.java:16)
at org.nlogo.prim.gui._updatemonitor.perform(_updatemonitor.scala:15)
at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
at org.nlogo.job.JobThread.runSecondaryJobs(JobThread.scala:168)
at org.nlogo.job.JobThread.maybeRunSecondaryJobs(JobThread.scala:91)
at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:69)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
at scala.util.control.Exception$Catch.apply(Exception.scala:228)
at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
at org.nlogo.job.JobThread.run(JobThread.scala:66)

NetLogo 6.3.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
OpenJDK 64-Bit Server VM 17.0.3 (BellSoft; 17.0.3+7-LTS)
operating system: Windows 11 10.0 (amd64 processor)
Scala version 2.12.16
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: lab10_advecosystem,nlogo

08:17:55.534 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
08:17:55.534 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
08:17:55.534 AddJobEvent (org.nlogo.window.MonitorWidget) AWT-EventQueue-0
08:17:55.534 AddJobEvent (org.nlogo.window.MonitorWidget) AWT-EventQueue-0
08:17:55.534 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
08:17:55.534 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
08:17:55.533 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
08:17:55.531 RemoveAllJobsEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
08:17:55.531 CompileAllEvent (org.nlogo.app.interfacetab.InterfacePanel) AWT-EventQueue-0
08:17:55.522 RemoveConstraintEvent (org.nlogo.app.interfacetab.InterfacePanel) AWT-EventQueue-0

**Comment by LaCuneta** [comment]
I was able to reproduce this error by creating a simple model with a monitor referencing a `number-of-sharks` reporter procedure using a global variable.  I then triggered [this exception](https://github.com/NetLogo/NetLogo/issues/2104) by editing the code to remove the global, not compiling or saving, and popping out the code tab.  I then closed the "bad" code window, re-popped it out and I can see the UI is inconsistent.  The monitor displays the prior value for the global that no longer exists.  But I cannot remember what I did to trigger the exception in this issue.  It was some further code edit, but so far I've not stumbled back onto it.  I'll update if I do get the exact steps, but it seems like the root problem is an exception leaving the UI and code in an inconsistent state.

**Comment by ERSUCC** [comment]
This is no longer reproducible as far as I can tell, but either way, the exception is now being caught as of commit [b14c30f](https://github.com/NetLogo/NetLogo/commit/b14c30f8f5983b22ff731c1c2e5edd834f05f7ee).
