### ISSUE TITLE
java.lang.IllegalStateException: cannot open system clipboard

### ISSUE THREAD

**Issue by mingyaQU** [NetLogo/NetLogo#2116]
at java.desktop/sun.awt.windows.WClipboard.openClipboard(Native Method)
 at java.desktop/sun.awt.datatransfer.SunClipboard.getClipboardFormatsOpenClose(Unknown Source)
 at java.desktop/sun.awt.datatransfer.SunClipboard.isDataFlavorAvailable(Unknown Source)
 at org.nlogo.window.TextMenuActions$WrappedPasteAction.refresh(TextMenuActions.scala:41)
 at org.nlogo.app.EditMenu$$anon$1.$anonfun$menuSelected$1(EditMenu.scala:29)
 at org.nlogo.app.EditMenu$$anon$1.$anonfun$menuSelected$1$adapted(EditMenu.scala:29)
 at scala.collection.immutable.Set$Set2.foreach(Set.scala:181)
 at org.nlogo.app.EditMenu$$anon$1.menuSelected(EditMenu.scala:29)
 at java.desktop/javax.swing.JMenu.fireMenuSelected(Unknown Source)
 at java.desktop/javax.swing.JMenu$MenuChangeListener.stateChanged(Unknown Source)
 at java.desktop/javax.swing.DefaultButtonModel.fireStateChanged(Unknown Source)
 at java.desktop/javax.swing.DefaultButtonModel.setSelected(Unknown Source)
 at java.desktop/javax.swing.JMenu.setSelected(Unknown Source)
 at java.desktop/javax.swing.JMenu.menuSelectionChanged(Unknown Source)
 at java.desktop/javax.swing.MenuSelectionManager.setSelectedPath(Unknown Source)
 at java.desktop/javax.swing.plaf.basic.BasicMenuUI$Handler.mouseEntered(Unknown Source)
 at java.desktop/javax.swing.plaf.basic.BasicMenuUI$MouseInputHandler.mouseEntered(Unknown Source)
 at java.desktop/com.sun.java.swing.plaf.windows.WindowsMenuUI$WindowsMouseInputHandler.mouseEntered(Unknown Source)
 at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
 at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
 at java.desktop/java.awt.Component.processEvent(Unknown Source)
 at java.desktop/java.awt.Container.processEvent(Unknown Source)
 at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
 at java.desktop/java.awt.LightweightDispatcher.retargetMouseEnterExit(Unknown Source)
 at java.desktop/java.awt.LightweightDispatcher.trackMouseEnterExit(Unknown Source)
 at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
 at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
 at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
 at java.base/java.security.AccessController.doPrivileged(Unknown Source)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
 at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
 at java.base/java.security.AccessController.doPrivileged(Unknown Source)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

NetLogo 6.3.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
OpenJDK 64-Bit Server VM 17.0.3 (BellSoft; 17.0.3+7-LTS)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.16
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Untitled

09:52:36.557 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:52:36.355 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:52:36.153 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:52:35.949 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:52:35.746 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)

**Comment by brandesNW** [comment]
Hi,
The system information was actually below the long stack trace.
It tells us you are using an up to date version of NetLogo, and were working in a new model.

The stack trace indicates that a mouse action that caused a menu refresh was involved.
We still need you to figure out the steps needed to reproduce the problem.
Thanks,
Aaron

--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling


From: mingyaQU ***@***.***>
Date: Thursday, June 1, 2023 at 4:00 AM
To: NetLogo/NetLogo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [NetLogo/NetLogo] java.lang.IllegalStateException: cannot open system clipboard (Issue #2116)

at java.desktop/sun.awt.windows.WClipboard.openClipboard(Native Method)
at java.desktop/sun.awt.datatransfer.SunClipboard.getClipboardFormatsOpenClose(Unknown Source)
at java.desktop/sun.awt.datatransfer.SunClipboard.isDataFlavorAvailable(Unknown Source)
at org.nlogo.window.TextMenuActions$WrappedPasteAction.refresh(TextMenuActions.scala:41)
at org.nlogo.app.EditMenu$$anon$1.$anonfun$menuSelected$1(EditMenu.scala:29)
at org.nlogo.app.EditMenu$$anon$1.$anonfun$menuSelected$1$adapted(EditMenu.scala:29)
at scala.collection.immutable.Set$Set2.foreach(Set.scala:181)
at org.nlogo.app.EditMenu$$anon$1.menuSelected(EditMenu.scala:29)
at java.desktop/javax.swing.JMenu.fireMenuSelected(Unknown Source)
at java.desktop/javax.swing.JMenu$MenuChangeListener.stateChanged(Unknown Source)
at java.desktop/javax.swing.DefaultButtonModel.fireStateChanged(Unknown Source)
at java.desktop/javax.swing.DefaultButtonModel.setSelected(Unknown Source)
at java.desktop/javax.swing.JMenu.setSelected(Unknown Source)
at java.desktop/javax.swing.JMenu.menuSelectionChanged(Unknown Source)
at java.desktop/javax.swing.MenuSelectionManager.setSelectedPath(Unknown Source)
at java.desktop/javax.swing.plaf.basic.BasicMenuUI$Handler.mouseEntered(Unknown Source)
at java.desktop/javax.swing.plaf.basic.BasicMenuUI$MouseInputHandler.mouseEntered(Unknown Source)
at java.desktop/com.sun.java.swing.plaf.windows.WindowsMenuUI$WindowsMouseInputHandler.mouseEntered(Unknown Source)
at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
at java.desktop/java.awt.Component.processEvent(Unknown Source)
at java.desktop/java.awt.Container.processEvent(Unknown Source)
at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
at java.desktop/java.awt.LightweightDispatcher.retargetMouseEnterExit(Unknown Source)
at java.desktop/java.awt.LightweightDispatcher.trackMouseEnterExit(Unknown Source)
at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
at java.base/java.security.AccessController.doPrivileged(Unknown Source)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
at java.base/java.security.AccessController.doPrivileged(Unknown Source)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

NetLogo 6.3.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
OpenJDK 64-Bit Server VM 17.0.3 (BellSoft; 17.0.3+7-LTS)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.16
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Untitled

09:52:36.557 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:52:36.355 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:52:36.153 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:52:35.949 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:52:35.746 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)
