### ISSUE TITLE
NetLogo 6.3.0 not using bundled Java 17 by default on Linux

### ISSUE THREAD

**Issue by EwoutH** [NetLogo/NetLogo#2171]
**Description:**

After updating to NetLogo 6.3.0, which now bundles Java 17, I observed that the application is not utilizing its bundled Java version by default. Instead, it seems to be attempting to use the system's default Java. A clear indication of this issue arose when trying to run the `netlogo-headless.sh` script, which produced an error suggesting that the Java executable could not be found in the expected location.

**Steps to Reproduce:**

1. Install NetLogo 6.3.0 on an Ubuntu system.
2. Run NetLogo headless (`netlogo-headless.sh --version`)

Optionally, you can point `JAVA_HOME` specifically to  `/opt/netlogo/lib/runtime`, but then it attempts to use `/opt/netlogo/lib/runtime/bin/java` which doesn't exists.

**Expected Behavior:**

The script should run successfully, displaying the version information and utilizing the bundled Java 17.

**Actual Behavior:**

Received the following error message:
```
/opt/netlogo/netlogo-headless.sh: line 35: /opt/netlogo/lib/runtime/bin/java: No such file or directory
```

**Additional Information:**

Upon further inspection, it seems that there might have been a change in the directory structure of the bundled Java, causing the `netlogo-headless.sh` script to look for the Java executable in a non-existent location. This is further suggested by the presence of three folders (`conf`, `legal`, `lib`) and a release file in the `/opt/netlogo/lib/runtime` directory.

Considering that this version of NetLogo transitioned to bundling Java 17, it's plausible that changes in the directory structure or other settings related to Java 17 are responsible for this discrepancy.

**Suggested Solution:**

I think three things should be checked:

- Is Java 17 correctly bundled?
- Is `netlogo-headless.sh` compiled correctly considering the (updated) bundled Java?
- Is the installation documentation up to date, including setting `JAVA_HOME`?

**Comment by LaCuneta** [comment]
Hey Ewout,

I use NetLogo 6.3.0 on Linux and it does use the bundled Java 17.  I think the confusion here is with the `netlogo-headless.sh` script, which is meant for situations where you do want to control which Java is used - for instance when running headlessly on a secure server which locks down allowed Java versions.  It is not meant to run the bundled Java.  The `JAVA_HOME` setting is meant for a full Java runtime install which will have those specified subfolders, so trying to point it to a bundled install will not work.

I think you want to be using either the `NetLogo` entry point or the new `NetLogo_Console` entry point with the `--headless` switch if you want to run without a GUI.  On Linux both of these are just scripts that run `bin/NetLogo`.  Once running the NetLogo GUI you can open **Help > About NetLogo 6.3** and in the **System** tab you should see which Java is running, and it should be `OpenJDK 64-Bit Server VM 17.0.3 (BellSoft; 17.0.3+7-LTS)`, which was bundled.  The [documentation for BehaviorSpace](http://ccl.northwestern.edu/netlogo/docs/behaviorspace.html#running-from-the-command-line) includes more information on running from the command line using the `NetLogo_Console` entry point.

For some background info, the `NetLogo_Console` entry point and the `--headless` switch were added in NetLogo 6.3 specifically to allow running with the bundled Java headlessly.  Previously there was no easy way to do this, and a separate JRE install run with the `netlogo-headless.sh` script was the recommended way.  That script remains for those who need it, but it's no longer the recommended way for most users.

Let me know if that makes sense, or if you see a different Java in your system information when using the `NetLogo` script.

**Comment by EwoutH** [comment]
Thanks a lot for the quick and extensive response! This clears up a lot.

My issue is actually with NetLogo working with the [EMAworkbench](https://emaworkbench.readthedocs.io/en/latest/), which uses [pyNetLogo](https://github.com/quaquel/pyNetLogo) which again uses [JPype](https://github.com/jpype-project/jpype). At this point I tried about everything but I keep getting errors like the one below (which point to [here](https://github.com/quaquel/pyNetLogo/blob/c2c910e6a5f7131b2e5ab32eb3983005d7b52430/src/pynetlogo/java/netLogoLink/NetLogoLink.java#L132)). Looking it up, it points at Java version / ASM / Classpath issues, but I can't seem to get it working.
```
java.lang.NoSuchMethodError: 'void org.objectweb.asm.MethodVisitor.visitMethodInsn(int, java.lang.String, java.lang.String, java.lang.String, boolean)'
Traceback (most recent call last):
  File "NetLogoLink.java", line 132, in netLogoLink.NetLogoLink.loadModel
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ewouth/.local/lib/python3.10/site-packages/pynetlogo/core.py", line 246, in load_model
    self.link.loadModel(path)
java.lang.java.lang.NoSuchMethodError: java.lang.NoSuchMethodError: 'void org.objectweb.asm.MethodVisitor.visitMethodInsn(int, java.lang.String, java.lang.String, java.lang.String, boolean)'
```

**Comment by LaCuneta** [comment]
Hmm, in checking [the pyNetLogo docs, they say version 0.5 supports NetLogo 6.3](https://pynetlogo.readthedocs.io/en/latest/changelog.html#version-0-5).  The `NetLogoLink` class referenced in the current code looks like it's trying to use `workspace.open()` and as far as I can see that's correct for 6.3.  Can you confirm you're using version 0.5 of `pyNetLogo`?  Past that my next best advice would be to try use pyNetLogo without the EMA workbench, maybe in a simple Linux VM or something, to see if it works correctly there, and see if you can pinpoint the incompatibility.  Maybe the pyNetLogo maintainers would have some advice, too.

**Comment by brandesNW** [comment]
Hi Ewout,
netlogo-headless.sh does not use the bundled Java 17.
The appropriate way to run NetLogo 6.3 headlessly with the bundled Java is by using theNetLogo_Console app with the --headless
Documention with examples is here: https://ccl.northwestern.edu/netlogo/docs/behaviorspace.html#how-to-use-it

The main message is that you should run NetLogo using theNetLogo_Console app with the --headless command line argument.
Because NetLogo_Console uses the Java that comes bundled with NetLogo it requires no extra software installation or configuration.

Note that in prior versions of NetLogo the directions were to use netlogo-headless.sh (or netlogo-headless.bat on Windows) along with a separate installation of Java of the system to run BehaviorSpace experiments. The netlogo-headless.sh script is still included with NetLogo and can still be used as before, which might be preferrable in server environments where the installed Java version is strictly controller. But the recommended method for on a personal computer is to use the NetLogo_Console --headless app. Because NetLogo_Console uses the Java that comes bundled with NetLogo it requires no extra software installation or configuration.

Please let us know if you find that the NetLogo GUI application or NetLogo_Console is not using Java 17.

  *   Aaron
  *
--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling


From: Ewout ter Hoeven ***@***.***>
Date: Tuesday, September 19, 2023 at 10:53 AM
To: NetLogo/NetLogo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [NetLogo/NetLogo] NetLogo 6.3.0 not using bundled Java 17 by default on Linux (Issue #2171)

Description:

After updating to NetLogo 6.3.0, which now bundles Java 17, I observed that the application is not utilizing its bundled Java version by default. Instead, it seems to be attempting to use the system's default Java. A clear indication of this issue arose when trying to run the netlogo-headless.sh script, which produced an error suggesting that the Java executable could not be found in the expected location.

Steps to Reproduce:

  1.  Install NetLogo 6.3.0 on an Ubuntu system.
  2.  Run NetLogo headless (netlogo-headless.sh --version)

Optionally, you can point JAVA_HOME specifically to /opt/netlogo/lib/runtime, but then it attempts to use /opt/netlogo/lib/runtime/bin/java which doesn't exists.

Expected Behavior:

The script should run successfully, displaying the version information and utilizing the bundled Java 17.

Actual Behavior:

Received the following error message:

/opt/netlogo/netlogo-headless.sh: line 35: /opt/netlogo/lib/runtime/bin/java: No such file or directory

Additional Information:

Upon further inspection, it seems that there might have been a change in the directory structure of the bundled Java, causing the netlogo-headless.sh script to look for the Java executable in a non-existent location. This is further suggested by the presence of three folders (conf, legal, lib) and a release file in the /opt/netlogo/lib/runtime directory.

Considering that this version of NetLogo transitioned to bundling Java 17, it's plausible that changes in the directory structure or other settings related to Java 17 are responsible for this discrepancy.

Suggested Solution:

I think three things should be checked:

  *   Is Java 17 correctly bundled?
  *   Is netlogo-headless.sh compiled correctly considering the (updated) bundled Java?
  *   Is the installation documentation up to date, including setting JAVA_HOME?
