### ISSUE TITLE
Opening separate code tab with compilation error causes exception

### ISSUE THREAD

**Issue by brandesNW** [NetLogo/NetLogo#2174]
To reproduce
Open a model
Edit the code tab so that it will give a compilation error
Click the Code Tab in separate window checkbox

The following error will occur. An empty separate code tab open and focus will go to the Interface Tab. If you open the regular code and uncheck the separate window box you can then fix the error and execute the code as usual.

Note: The compiler error will show if you click on the code tab. You can correct
java.lang.IllegalArgumentException: component not found in tabbed pane
 at java.desktop/javax.swing.JTabbedPane.setSelectedComponent(Unknown Source)
 at org.nlogo.app.AppTabManager.setSelectedCodeTab(AppTabManager.scala:104)
 at org.nlogo.app.Tabs.handle(Tabs.scala:236)
 at org.nlogo.window.Events$CompiledEvent.beHandledBy(Events.java:223)
 at org.nlogo.window.Event.doRaise(Event.java:206)
 at org.nlogo.window.Event.raise(Event.java:122)

**Comment by brandesNW** [comment]
This can probably be fixed by making sure compilation does not happen when a code tab is separated.
When the separate code tab code runs the code tab must be removed from the Tabs JTabbed pane and added to the CodeTabsPanel. Apparently there is a timing problem with compilation.
