### ISSUE TITLE
OutOfMemoryError (PermGen) when compiling huge model with multiple includes

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/NetLogo#220]
Reported by Andrew Fan. Reproducible with user provided model.

````
java.lang.OutOfMemoryError: PermGen space
 at java.lang.Class.getDeclaredMethods0(Native Method)
 at java.lang.Class.privateGetDeclaredMethods(Class.java:2427)
 at java.lang.Class.privateGetPublicMethods(Class.java:2547)
 at java.lang.Class.privateGetPublicMethods(Class.java:2563)
 at java.lang.Class.privateGetPublicMethods(Class.java:2563)
 at java.lang.Class.privateGetPublicMethods(Class.java:2563)
 at java.lang.Class.getMethods(Class.java:1410)
 at org.nlogo.generator.BytecodeUtils$.getMethods(BytecodeUtils.scala:34)
 at org.nlogo.generator.BytecodeUtils$.isRejiggered(BytecodeUtils.scala:19)
 at org.nlogo.generator.Generator.org$nlogo$generator$Generator$$recurse(Generator.scala:27)
 at org.nlogo.generator.Generator$InstructionGenerator$$anonfun$generateOldStyleCall$1.apply(Generator.scala:208)
 at org.nlogo.generator.Generator$InstructionGenerator$$anonfun$generateOldStyleCall$1.apply(Generator.scala:208)
 at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:233)
 at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:233)
 at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:34)
 at scala.collection.mutable.ArrayOps.foreach(ArrayOps.scala:38)
 at scala.collection.TraversableLike$class.map(TraversableLike.scala:233)
 at scala.collection.mutable.ArrayOps.map(ArrayOps.scala:38)
 at org.nlogo.generator.Generator$InstructionGenerator.generateOldStyleCall(Generator.scala:208)
 at org.nlogo.generator.Generator$InstructionGenerator.generateInstruction(Generator.scala:146)
 at org.nlogo.generator.Generator$InstructionGenerator$$anonfun$generateInstruction$1.apply$mcVI$sp(Generator.scala:167)
 at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:81)
 at org.nlogo.generator.Generator$InstructionGenerator.generateInstruction(Generator.scala:159)
 at org.nlogo.generator.Generator$InstructionGenerator.generateBodyMethod(Generator.scala:112)
 at org.nlogo.generator.Generator$InstructionGenerator.generate(Generator.scala:90)
 at org.nlogo.generator.Generator.org$nlogo$generator$Generator$$recurse(Generator.scala:28)
 at org.nlogo.generator.Generator$$anonfun$generate$1.apply(Generator.scala:24)
 at org.nlogo.generator.Generator$$anonfun$generate$1.apply(Generator.scala:24)
 at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:233)
 at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:233)
 at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:34)
 at scala.collection.mutable.ArrayOps.foreach(ArrayOps.scala:38)

NetLogo 5.0.2
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.6.0_31 (Sun Microsystems Inc.; 1.6.0_31-b04)
operating system: Linux 3.2.0-31-generic (amd64 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Touhou TC Extra V0_8_7 devel uns

05:28:43.252 AddJobEvent (org.nlogo.window.MonitorWidget) AWT-EventQueue-0
05:28:43.252 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
05:28:43.252 AddJobEvent (org.nlogo.window.MonitorWidget) AWT-EventQueue-0
05:28:43.252 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
05:28:43.252 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
05:28:43.252 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
05:28:43.252 AddJobEvent (org.nlogo.window.MonitorWidget) AWT-EventQueue-0
05:28:43.252 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
05:28:43.252 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
05:28:43.252 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
````

As a side effect (which I haven't been able to reproduce yet), after getting this error and closing a .nls file, the user get this when trying to quit NetLogo:

````
java.util.NoSuchElementException: None.get
 at scala.None$.get(Option.scala:274)
 at scala.None$.get(Option.scala:272)
 at org.nlogo.app.Tabs.getIndexOfComponent(Tabs.scala:160)
 at org.nlogo.app.Tabs.closeTemporaryFile(Tabs.scala:163)
 at org.nlogo.app.TemporaryProceduresTab$$anonfun$close$1.apply$mcV$sp(TemporaryProceduresTab.scala:89)
 at org.nlogo.app.TemporaryProceduresTab$$anonfun$close$1.apply(TemporaryProceduresTab.scala:86)
 at org.nlogo.app.TemporaryProceduresTab$$anonfun$close$1.apply(TemporaryProceduresTab.scala:86)
 at scala.util.control.Exception$Catch.apply(Exception.scala:88)
 at org.nlogo.app.TemporaryProceduresTab.close(TemporaryProceduresTab.scala:86)
 at org.nlogo.app.TemporaryProceduresTab.handle(TemporaryProceduresTab.scala:78)
 at org.nlogo.window.Events$AboutToQuitEvent.beHandledBy(Events.java:17)
 at org.nlogo.window.Event.doRaise(Event.java:198)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.app.FileMenu.quit(FileMenu.java:638)
 at org.nlogo.app.AppFrame$$anon$4.windowClosing(App.scala:964)
 at java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:332)
 at java.awt.Window.processWindowEvent(Window.java:1871)
 at javax.swing.JFrame.processWindowEvent(JFrame.java:274)
 at java.awt.Window.processEvent(Window.java:1829)
 at java.awt.Component.dispatchEventImpl(Component.java:4744)
 at java.awt.Container.dispatchEventImpl(Container.java:2141)
 at java.awt.Window.dispatchEventImpl(Window.java:2489)
 at java.awt.Component.dispatchEvent(Component.java:4572)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:704)
 at java.awt.EventQueue.access$400(EventQueue.java:82)
 at java.awt.EventQueue$2.run(EventQueue.java:663)
 at java.awt.EventQueue$2.run(EventQueue.java:661)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:98)
 at java.awt.EventQueue$3.run(EventQueue.java:677)
 at java.awt.EventQueue$3.run(EventQueue.java:675)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:674)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
````

**Comment by mrerrormessage** [comment]
In 5.2.2, we're bundling Java 8. It's possible that models that failed in this bug will still fail, but it will no longer be due to PermGen. @nicolaspayette , do you happen to have a copy of the model that caused this, or can you point me to the appropriate bugs/feedback thread?

**Comment by nicolaspayette** [comment]
Model attached here (private link):
https://ccl.northwestern.edu/mailman/private/ccl-bugs/2012/031856.html

**Comment by mrerrormessage** [comment]
just tested. Compiles fine in 5.3. Closing
