### ISSUE TITLE
new

### ISSUE THREAD

**Issue by Sirena0225** [NetLogo/NetLogo#2212]
NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 

java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
 at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
 at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
 at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
 at java.base/java.util.Objects.checkIndex(Unknown Source)
 at java.base/java.util.ArrayList.get(Unknown Source)
 at java.desktop/javax.swing.JTabbedPane.setForegroundAt(Unknown Source)
 at org.nlogo.app.Tabs.clearForeground$1(Tabs.scala:212)
 at org.nlogo.app.Tabs.$anonfun$handle$4(Tabs.scala:217)
 at org.nlogo.app.Tabs.$anonfun$handle$4$adapted(Tabs.scala:217)
 at scala.collection.mutable.HashSet.foreach(HashSet.scala:79)
 at org.nlogo.app.Tabs.forAllCodeTabs(Tabs.scala:336)
 at org.nlogo.app.Tabs.clearErrors$1(Tabs.scala:217)
 at org.nlogo.app.Tabs.handle(Tabs.scala:241)
 at org.nlogo.window.Events$CompiledEvent.beHandledBy(Events.java:223)
 at org.nlogo.window.Event.doRaise(Event.java:206)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.window.CompilerManager$.$anonfun$$lessinit$greater$default$4$1(CompilerManager.scala:20)
 at org.nlogo.window.CompilerManager$.$anonfun$$lessinit$greater$default$4$1$adapted(CompilerManager.scala:20)
 at org.nlogo.window.CompilerManager.raiseEvent(CompilerManager.scala:34)
 at org.nlogo.window.CompilerManager.compileProcedures(CompilerManager.scala:221)
 at org.nlogo.window.CompilerManager.compileAll(CompilerManager.scala:173)
 at org.nlogo.window.CompilerManager.handle(CompilerManager.scala:137)
 at org.nlogo.window.Events$CompileAllEvent.beHandledBy(Events.java:185)
 at org.nlogo.window.Event.doRaise(Event.java:206)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.app.codetab.CodeTab.compile(CodeTab.scala:163)
 at org.nlogo.app.codetab.CodeTab.handle(CodeTab.scala:144)
 at org.nlogo.app.common.Events$SwitchedTabsEvent.beHandledBy(Events.java:41)
 at org.nlogo.window.Event.doRaise(Event.java:206)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.app.Tabs$$anon$1.windowGainedFocus(Tabs.scala:114)
 at java.desktop/java.awt.Window.processWindowFocusEvent(Unknown Source)
 at java.desktop/java.awt.Window.processEvent(Unknown Source)
 at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
 at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
 at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
 at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
 at java.base/java.security.AccessController.doPrivileged(Unknown Source)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
 at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
 at java.base/java.security.AccessController.doPrivileged(Unknown Source)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

NetLogo 6.4.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
OpenJDK 64-Bit Server VM 17.0.8.1 (BellSoft; 17.0.8.1+1-LTS)
operating system: Mac OS X 14.1.1 (x86_64 processor)
Scala version 2.12.18
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Untitled

09:57:41.014 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:57:40.986 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
09:57:40.662 RemoveAllJobsEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
09:57:40.662 CompileAllEvent (org.nlogo.app.codetab.MainCodeTab) AWT-EventQueue-0
09:57:40.660 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
09:57:40.556 ModelSavedEvent (org.nlogo.app.MenuBar) AWT-EventQueue-0
09:57:40.541 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:57:40.289 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:57:40.088 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:57:39.883 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

**Comment by brandesNW** [comment]
Hi,
We are sorry you have encountered this problem.
Please send us detailed steps as to how to reproduce it, so we can find a solution. If you need to include a NetLogo model please include the .nlogo file in a zip file.
Thanks,
Aaron


--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling


From: Sirena0225 ***@***.***>
Date: Thursday, February 1, 2024 at 8:59 PM
To: NetLogo/NetLogo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [NetLogo/NetLogo] new (Issue #2212)

NetLogo is unable to supply you with more details about this error. Please report the problem
at https://github.com/NetLogo/NetLogo/issues<https://urldefense.com/v3/__https:/github.com/NetLogo/NetLogo/issues__;!!Dq0X2DkFhyF93HkjWTBQKhk!WxXG4B-SJslnz3zfFHpPkUvr1Aqb-p2QuhA71slf4kR6J7RVvQvtrIqa_Xy3TlfspaZZV13imKJfvUDsLcic5j15YCqJA7Aeaw$>, or to ***@***.******@***.***>, and paste the
contents of this window into your report.

java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
at java.base/java.util.Objects.checkIndex(Unknown Source)
at java.base/java.util.ArrayList.get(Unknown Source)
at java.desktop/javax.swing.JTabbedPane.setForegroundAt(Unknown Source)
at org.nlogo.app.Tabs.clearForeground$1(Tabs.scala:212)
at org.nlogo.app.Tabs.$anonfun$handle$4(Tabs.scala:217)
at org.nlogo.app.Tabs.$anonfun$handle$4$adapted(Tabs.scala:217)
at scala.collection.mutable.HashSet.foreach(HashSet.scala:79)
at org.nlogo.app.Tabs.forAllCodeTabs(Tabs.scala:336)
at org.nlogo.app.Tabs.clearErrors$1(Tabs.scala:217)
at org.nlogo.app.Tabs.handle(Tabs.scala:241)
at org.nlogo.window.Events$CompiledEvent.beHandledBy(Events.java:223)
at org.nlogo.window.Event.doRaise(Event.java:206)
at org.nlogo.window.Event.raise(Event.java:122)
at org.nlogo.window.CompilerManager$.$anonfun$$lessinit$greater$default$4$1(CompilerManager.scala:20)
at org.nlogo.window.CompilerManager$.$anonfun$$lessinit$greater$default$4$1$adapted(CompilerManager.scala:20)
at org.nlogo.window.CompilerManager.raiseEvent(CompilerManager.scala:34)
at org.nlogo.window.CompilerManager.compileProcedures(CompilerManager.scala:221)
at org.nlogo.window.CompilerManager.compileAll(CompilerManager.scala:173)
at org.nlogo.window.CompilerManager.handle(CompilerManager.scala:137)
at org.nlogo.window.Events$CompileAllEvent.beHandledBy(Events.java:185)
at org.nlogo.window.Event.doRaise(Event.java:206)
at org.nlogo.window.Event.raise(Event.java:122)
at org.nlogo.app.codetab.CodeTab.compile(CodeTab.scala:163)
at org.nlogo.app.codetab.CodeTab.handle(CodeTab.scala:144)
at org.nlogo.app.common.Events$SwitchedTabsEvent.beHandledBy(Events.java:41)
at org.nlogo.window.Event.doRaise(Event.java:206)
at org.nlogo.window.Event.raise(Event.java:122)
at org.nlogo.app.Tabs$$anon$1.windowGainedFocus(Tabs.scala:114)
at java.desktop/java.awt.Window.processWindowFocusEvent(Unknown Source)
at java.desktop/java.awt.Window.processEvent(Unknown Source)
at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
at java.base/java.security.AccessController.doPrivileged(Unknown Source)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
at java.base/java.security.AccessController.doPrivileged(Unknown Source)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

NetLogo 6.4.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
OpenJDK 64-Bit Server VM 17.0.8.1 (BellSoft; 17.0.8.1+1-LTS)
operating system: Mac OS X 14.1.1 (x86_64 processor)
Scala version 2.12.18
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Untitled

09:57:41.014 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:57:40.986 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
09:57:40.662 RemoveAllJobsEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
09:57:40.662 CompileAllEvent (org.nlogo.app.codetab.MainCodeTab) AWT-EventQueue-0
09:57:40.660 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
09:57:40.556 ModelSavedEvent (org.nlogo.app.MenuBar) AWT-EventQueue-0
09:57:40.541 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:57:40.289 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:57:40.088 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:57:39.883 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

**Comment by brandesNW** [comment]
Hi,
Your problem may be the same as https://github.com/NetLogo/NetLogo/issues/2104, which is currently being fixed.
Please let us know.
Thanks,
Aaron


--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling


From: Sirena0225 ***@***.***>
Date: Thursday, February 1, 2024 at 8:59 PM
To: NetLogo/NetLogo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [NetLogo/NetLogo] new (Issue #2212)

NetLogo is unable to supply you with more details about this error. Please report the problem
at https://github.com/NetLogo/NetLogo/issues<https://urldefense.com/v3/__https:/github.com/NetLogo/NetLogo/issues__;!!Dq0X2DkFhyF93HkjWTBQKhk!WxXG4B-SJslnz3zfFHpPkUvr1Aqb-p2QuhA71slf4kR6J7RVvQvtrIqa_Xy3TlfspaZZV13imKJfvUDsLcic5j15YCqJA7Aeaw$>, or to ***@***.******@***.***>, and paste the
contents of this window into your report.

java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
at java.base/java.util.Objects.checkIndex(Unknown Source)
at java.base/java.util.ArrayList.get(Unknown Source)
at java.desktop/javax.swing.JTabbedPane.setForegroundAt(Unknown Source)
at org.nlogo.app.Tabs.clearForeground$1(Tabs.scala:212)
at org.nlogo.app.Tabs.$anonfun$handle$4(Tabs.scala:217)
at org.nlogo.app.Tabs.$anonfun$handle$4$adapted(Tabs.scala:217)
at scala.collection.mutable.HashSet.foreach(HashSet.scala:79)
at org.nlogo.app.Tabs.forAllCodeTabs(Tabs.scala:336)
at org.nlogo.app.Tabs.clearErrors$1(Tabs.scala:217)
at org.nlogo.app.Tabs.handle(Tabs.scala:241)
at org.nlogo.window.Events$CompiledEvent.beHandledBy(Events.java:223)
at org.nlogo.window.Event.doRaise(Event.java:206)
at org.nlogo.window.Event.raise(Event.java:122)
at org.nlogo.window.CompilerManager$.$anonfun$$lessinit$greater$default$4$1(CompilerManager.scala:20)
at org.nlogo.window.CompilerManager$.$anonfun$$lessinit$greater$default$4$1$adapted(CompilerManager.scala:20)
at org.nlogo.window.CompilerManager.raiseEvent(CompilerManager.scala:34)
at org.nlogo.window.CompilerManager.compileProcedures(CompilerManager.scala:221)
at org.nlogo.window.CompilerManager.compileAll(CompilerManager.scala:173)
at org.nlogo.window.CompilerManager.handle(CompilerManager.scala:137)
at org.nlogo.window.Events$CompileAllEvent.beHandledBy(Events.java:185)
at org.nlogo.window.Event.doRaise(Event.java:206)
at org.nlogo.window.Event.raise(Event.java:122)
at org.nlogo.app.codetab.CodeTab.compile(CodeTab.scala:163)
at org.nlogo.app.codetab.CodeTab.handle(CodeTab.scala:144)
at org.nlogo.app.common.Events$SwitchedTabsEvent.beHandledBy(Events.java:41)
at org.nlogo.window.Event.doRaise(Event.java:206)
at org.nlogo.window.Event.raise(Event.java:122)
at org.nlogo.app.Tabs$$anon$1.windowGainedFocus(Tabs.scala:114)
at java.desktop/java.awt.Window.processWindowFocusEvent(Unknown Source)
at java.desktop/java.awt.Window.processEvent(Unknown Source)
at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
at java.base/java.security.AccessController.doPrivileged(Unknown Source)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
at java.base/java.security.AccessController.doPrivileged(Unknown Source)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

NetLogo 6.4.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
OpenJDK 64-Bit Server VM 17.0.8.1 (BellSoft; 17.0.8.1+1-LTS)
operating system: Mac OS X 14.1.1 (x86_64 processor)
Scala version 2.12.18
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Untitled

09:57:41.014 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:57:40.986 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
09:57:40.662 RemoveAllJobsEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
09:57:40.662 CompileAllEvent (org.nlogo.app.codetab.MainCodeTab) AWT-EventQueue-0
09:57:40.660 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
09:57:40.556 ModelSavedEvent (org.nlogo.app.MenuBar) AWT-EventQueue-0
09:57:40.541 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:57:40.289 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:57:40.088 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:57:39.883 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

**Comment by ERSUCC** [comment]
I don't think this bug is relevant anymore, but just in case, I added some failsafes in the commit above.
