### ISSUE TITLE
Issue when running Behaviorspace runs in parallel

### ISSUE THREAD

**Issue by silly-koalas** [NetLogo/NetLogo#2218]
Hey!

In running an ABM in Behaviorspace, I get the following error report when trying to do runs in parallel. The issue does not appear when using just one thread, and as far as I've explored the problem does not seem to be sensitive to model settings. The number of parallel runs does not seem to influence whether the error appears or not either, as soon as I do more than one run at the time it appears. If useful, I can share the model privately.

```
NetLogo is unable to supply you with more details about this error.  Please report the problem 
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 


java.lang.IndexOutOfBoundsException: 15
 at scala.collection.immutable.Vector.checkRangeConvert(Vector.scala:131)
 at scala.collection.immutable.Vector.apply(Vector.scala:122)
 at org.nlogo.core.LogoList.get(LogoList.scala:36)
 at org.nlogo.prim.MultiLet$.next(_multilet.scala:21)
 at org.nlogo.prim._asm_procedureexpandonestepbranch_setprocedurevariable_1.perform(:2)
 at org.nlogo.nvm.Context.callReporterProcedure(Context.java:254)
 at org.nlogo.prim._asm_procedureevaluatetreemontecarlo_setprocedurevariable_78.perform(:2)
 at org.nlogo.nvm.Context.callReporterProcedure(Context.java:254)
 at org.nlogo.prim._asm_procedurechoosesubcoalitionmcts_setprocedurevariable_5.perform(:2)
 at org.nlogo.nvm.Context.runExclusive(Context.java:133)
 at org.nlogo.nvm.ExclusiveJob.run(ExclusiveJob.scala:39)
 at org.nlogo.nvm.Context.runExclusiveJob(Context.java:177)
 at org.nlogo.prim._asm_procedurego_ask_2.perform(:1)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
 at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
 at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
 at scala.util.control.Exception$Catch.apply(Exception.scala:228)
 at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:66)

NetLogo 6.4.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
OpenJDK 64-Bit Server VM 17.0.8.1 (BellSoft; 17.0.8.1+1-LTS)
operating system: Windows 11 10.0 (amd64 processor)
Scala version 2.12.18
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: AcemogluEtal2008_ABM_minmax_MCTS

01:18:43.222 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
01:18:43.217 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
01:18:43.127 RuntimeErrorEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
01:18:43.101 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
01:18:43.101 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
01:18:43.096 TickStateChangeEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
01:18:43.022 TickStateChangeEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
01:18:43.018 OutputEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
01:18:42.935 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
01:18:40.949 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
```

**Comment by LaCuneta** [comment]
@silly-koalas Thanks for reporting this issue, and sorry you ran into it!  From reading that stack trace it isn't exactly clear why the error is happening as it is in BehaviorSpace.  If you can send the model to `bugs@ccl.northwestern.edu` that'd be very useful.  If it has any accessory files (CSV or GIS data), zipping it into a single archive might make emailing it easier.

**Comment by LaCuneta** [comment]
@silly-koalas I investigated the stack trace a little more along with the associated code and I think I see the problem.  The issue is with using the new multi-assign syntax along with BehaviorSpace.  I'll have a permanent fix in for this that will go out in the next NetLogo release that'll get things working correctly.

In the meantime, the workaround for now is to use the old "wordy" syntax:

For example, if you're doing something like `let [a b] report-a-list` then you'd do

```
let temp-list report-a-list
let a (item 0 temp-list)
let b (item 1 temp-list)
```

Apologies for the trouble, but thank you again for reporting this issue so we can correct it.

**Comment by silly-koalas** [comment]
@LaCuneta That was it exactly, thanks for the careful look!

**Comment by LaCuneta** [comment]
Glad to hear the workaround helped!  I'm going to re-open this issue until I have the fix implemented.
