### ISSUE TITLE
Build error with arduino extension

### ISSUE THREAD

**Issue by kodingkoning** [NetLogo/NetLogo#2221]
When I attempt to build from source, I receive an error when attempting to build the arduino extension. I confirmed the submodules are up to date.

```
[info] welcome to sbt 1.9.7 (Private Build Java 17.0.10)
[info] loading settings for project netlogo-build from build.sbt,plugins.sbt ...
[info] loading project definition from /home/erk24/workspace/NetLogo/project
[info] loading settings for project root from build.sbt,classycle.sbt ...
[info] loading settings for project behaviorsearchProject from build.sbt ...
[info] resolving key references (10721 settings) ...
[info] set current project to root (in build file:/home/erk24/workspace/NetLogo/)
[info] creating models/index.conf
[warn] multiple main classes detected: run 'show discoveredMainClasses' to see the list
/home/erk24/workspace/NetLogo/autogen/docs
[info] building extension: arduino
[error] java.io.IOException: Cannot run program "sbt" (in directory "/home/erk24/workspace/NetLogo/extensions/arduino"): error=2, No such file or directory
[error] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
[error] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
[error] 	at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:75)
[error] 	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:104)
[error] 	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang(ProcessBuilderImpl.scala:118)
[error] 	at Extensions$.sbtExec(Extensions.scala:108)
[error] 	at Extensions$.buildExtension(Extensions.scala:98)
[error] 	at Extensions$.$anonfun$settings$17(Extensions.scala:82)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
[error] 	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
[error] 	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33
[error] 	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
[error] 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
[error] 	at Extensions$.$anonfun$settings$15(Extensions.scala:79)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.Execute.work(Execute.scala:292)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:840)
[error] Caused by: java.io.IOException: error=2, No such file or directory
[error] 	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
[error] 	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
[error] 	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
[error] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
[error] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
[error] 	at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:75)
[error] 	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:104)
[error] 	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang(ProcessBuilderImpl.scala:118)
[error] 	at Extensions$.sbtExec(Extensions.scala:108)
[error] 	at Extensions$.buildExtension(Extensions.scala:98)
[error] 	at Extensions$.$anonfun$settings$17(Extensions.scala:82)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
[error] 	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
[error] 	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33
[error] 	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
[error] 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
[error] 	at Extensions$.$anonfun$settings$15(Extensions.scala:79)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.Execute.work(Execute.scala:292)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:840)
[error] (netlogo / extensions) java.io.IOException: Cannot run program "sbt" (in directory "/home/erk24/workspace/NetLogo/extensions/arduino"): error=2, No such file or directory
[error] Total time: 11 s, completed Feb 28, 2024, 4:00:08 PM
```

**Comment by SethTisue** [comment]
Possible duplicate of https://github.com/NetLogo/NetLogo/issues/2189 ?

**Comment by kodingkoning** [comment]
This is a different error than #2189. There, it was a permission denied error, and here the error is that `./sbt` does not exist in the extension subdirectory

**Comment by LaCuneta** [comment]
@kodingkoning The `"No such file or directory"` message makes me thinks it might be one of these:

- Did you run `git submodule update --init` in the root of the NetLogo repo to populate the submodules?
- Do you [have `sbt` installed](https://www.scala-sbt.org/download/) on the machine you're working on (as opposed to using the `sbt` script in the root of the NetLogo folder)?  You can check by running `sbt` in the `extensions/arduino` folder directly (note the lack of dot-slash, as with `./sbt` for NetLogo itself).  

Let me know if the submodules are populated and `sbt` is available to run and I'll try to think of anything else that might help.  Thanks.

**Comment by kodingkoning** [comment]
@LaCuneta Thank you! Your second question (sbt) was the right one.
