### ISSUE TITLE
Error with TestFilePrimsUTF8

### ISSUE THREAD

**Issue by kodingkoning** [NetLogo/NetLogo#2224]
I am building NetLogo on a new machine (via ssh), and when I run `./nightly.sh` before making any changes, I get an error on `org.nlogo.headless.TestFilePrimsUTF8`.

I have not gotten this error on other machines. I confirmed that I did initialize the submodules, install sbt, set JAVA_HOME, and set DISPLAY correctly. I assume there's some sort of UTF8 dependency issue, but I don't know what it is specifically or how to correct it.

```
[info] TestFilePrimsUTF8:
[info] - file-read *** FAILED ***
[info]   "A[������]C" did not equal "A[êñü]C" (TestFilePrimsUTF8.scala:46)
[info]   Analysis:
[info]   "A[������]C" -> "A[êñü]C"
[info]   org.scalatest.exceptions.TestFailedException:
[info]   ...
[info]   at org.nlogo.headless.TestFilePrimsUTF8.$anonfun$new$1(TestFilePrimsUTF8.scala:46)
[info]   at org.nlogo.headless.AbstractTestModels.$anonfun$run$1(AbstractTestModels.scala:97)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[info]   at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[info]   at org.nlogo.headless.AbstractTestModels.run(AbstractTestModels.scala:94)
[info]   at org.nlogo.headless.AbstractTestModels.runModel(AbstractTestModels.scala:78)
[info]   at org.nlogo.headless.AbstractTestModels.runModel$(AbstractTestModels.scala:74)
[info]   ...
[info] - file-read-line *** FAILED ***
[info]   " "A[������]C"" did not equal " "A[êñü]C"" (TestFilePrimsUTF8.scala:60)
[info]   Analysis:
[info]   " "A[������]C"" -> " "A[êñü]C""
[info]   org.scalatest.exceptions.TestFailedException:
[info]   ...
[info]   at org.nlogo.headless.TestFilePrimsUTF8.$anonfun$new$2(TestFilePrimsUTF8.scala:60)
[info]   at org.nlogo.headless.AbstractTestModels.$anonfun$run$1(AbstractTestModels.scala:97)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[info]   at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[info]   at org.nlogo.headless.AbstractTestModels.run(AbstractTestModels.scala:94)
[info]   at org.nlogo.headless.AbstractTestModels.runModel(AbstractTestModels.scala:78)
[info]   at org.nlogo.headless.AbstractTestModels.runModel$(AbstractTestModels.scala:74)
[info]   ...
[info] Run completed in 3 seconds, 810 milliseconds.
[info] Total number of tests run: 2
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 0, failed 2, canceled 0, ignored 0, pending 0
[info] *** 2 TESTS FAILED ***
[error] Failed tests:
[error] 	org.nlogo.headless.TestFilePrimsUTF8
[error] (netlogo / Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 20 s, completed Mar 5, 2024, 11:10:37 AM
```

**Comment by ERSUCC** [comment]
Hi @kodingkoning, this seems like an SSH issue. Make sure you have your connection configured to allow UTF-8 encoding, for example with the following flag: `LANG=en_US.UTF-8`.

**Comment by ERSUCC** [comment]
This was resolved in commit [e95bc73](https://github.com/NetLogo/NetLogo/commit/e95bc737ca2102bfd0df4f20d751f82c756668be). The file was not being read in explicitly as UTF-8 characters, which caused issues if the default character set for the system was not UTF-8.
