### ISSUE TITLE
Error with NetworkUtilsTest findViableInterfaces

### ISSUE THREAD

**Issue by kodingkoning** [NetLogo/NetLogo#2225]
I am running the NetLogo `./nightly.sh` tests on a new local machine, and I am getting an error that I did not get on the local machine I was using before.

I have confirmed that sbt is installed and the submodules and up to date. This is using the hexy branch. 

```
[info] NetworkUtilsTest:
[info] - findViableInterfaces should not return empty
[info] - findViableInterfaces does not return loopback interfaces
[info] - findViableInterfaces does not return disabled interfaces
[info] - findViableInterfaces does not return interfaces which are not multicastable *** FAILED ***
[info]   NetworkUtils.findViableInterfaces.forall(((i: (java.net.NetworkInterface, java.net.InetAddress)) => i._1.supportsMulticast())) was false (NetworkUtilsTest.scala:20)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   ...
[info]   at org.nlogo.hubnet.connection.NetworkUtilsTest.$anonfun$new$6(NetworkUtilsTest.scala:20)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.funsuite.AnyFunSuiteLike$$anon$1.apply(AnyFunSuiteLike.scala:226)
[info]   ...
[info] - findViableInterfaces does not return interfaces with only IP6 addresses
[info] - no interface is recalled after being forgotten
[info] - an interface can be recalled after it has been remembered
[info] Run completed in 1 second, 700 milliseconds.
[info] Total number of tests run: 7
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 6, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed tests:
[error] 	org.nlogo.hubnet.connection.NetworkUtilsTest
[error] (netlogo / Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 6 s, completed Mar 5, 2024, 11:21:08 AM
```

**Comment by LaCuneta** [comment]
Thanks for reporting this!  As far as I can tell from reading the code, this test is simply invalid.  It's just never failed on any of our testing systems before.  I've got a commit to remove it, which I'll merge once the tests pass.
