### ISSUE TITLE
Reset-ticks error

### ISSUE THREAD

**Issue by slingslong** [NetLogo/NetLogo#2248]
[PWR2-main.zip](https://github.com/NetLogo/NetLogo/files/15503296/PWR2-main.zip)

I hope everyone is doing well. I am reporting an error that I cannot seem to fix when running BehaviorSpace:

Metrics condition reporter encountered an error: org.nlogo.nvm.RuntimePrimitiveException: The tick counter has not been started yet. Use RESET-TICKS.

org.nlogo.lab.Worker$Runner$FailedException: Metrics condition reporter encountered an error: org.nlogo.nvm.RuntimePrimitiveException: The tick counter has not been started yet. Use RESET-TICKS.
 at org.nlogo.lab.Worker$Runner.shouldTakeMeasurements$1(Worker.scala:202)
 at org.nlogo.lab.Worker$Runner.callHelper(Worker.scala:275)
 at org.nlogo.lab.Worker$Runner.call(Worker.scala:135)
 at org.nlogo.lab.Worker$Runner.call(Worker.scala:117)
 at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 at java.base/java.lang.Thread.run(Thread.java:840)

NetLogo 6.4.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
OpenJDK 64-Bit Server VM 17.0.11 (Debian; 17.0.11+9-Debian-1deb12u1)
operating system: Linux 6.6.21-01327-gc9107f2d4947 (amd64 processor)
Scala version 2.12.18
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: pwr2 -cleanedup

04:56:46.788 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
04:56:46.788 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
04:56:46.750 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
04:56:46.744 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
04:56:46.744 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
04:56:46.744 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
04:56:46.740 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
04:56:46.740 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
04:56:46.740 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
04:56:46.736 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread

I have attached my model to this email, which includes the experiment that I am running. I tried placing reset-ticks in the stop experiment condition, but the error persisted. The error occurs both on Linux and OSX operating systems.

**Comment by ERSUCC** [comment]
I am unable to reproduce this issue in other models, and when I remove the metrics condition from your experiment and run it, it throws repeated divide by zero and ask nobody errors. There could still be a bug with the metrics condition, but it seems like the primary issue here is that there are bugs in your model code. If you could debug your code and/or provide a minimal reproducible example of the issue you reported in another model, I'll continue to look into the bug.

**Comment by slingslong** [comment]
Hi ERSUCC,

I believe that is the case; it seemed to be a bug in my code. Thanks for looking into it.
