### ISSUE TITLE
System Dynamics GUI exception

### ISSUE THREAD

**Issue by ERSUCC** [NetLogo/NetLogo#2287]
I got the following exception in the System Dynamics editor:

```
java.lang.NullPointerException: Cannot invoke "org.nlogo.sdm.gui.AggregateConnectionTool.mouseUp(java.awt.event.MouseEvent, int, int)" because "this.link" is null
```

To reproduce:

1. Open NetLogo 2D
2. Open the System Dynamics editor
3. Right click on the blank space

Can also be reproduced by adding any number of elements and right clicking on one of the elements.

Everything continues as normal after closing the error, so not a big deal, but it would be better if the null pointer was caught and ignored.

Here is the stack trace:

```
[error]         at org.nlogo.sdm.gui.InspectionTool.mouseUp(InspectionTool.java:100)
[error]         at org.jhotdraw.standard.StandardDrawingView$DrawingViewMouseListener.mouseReleased(Unknown Source)
[error]         at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
[error]         at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
[error]         at java.desktop/java.awt.Component.processEvent(Component.java:6391)
[error]         at java.desktop/java.awt.Container.processEvent(Container.java:2266)
[error]         at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
[error]         at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
[error]         at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
[error]         at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
[error]         at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
[error]         at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
[error]         at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
[error]         at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
[error]         at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
[error]         at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
[error]         at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
[error]         at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
[error]         at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
[error]         at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
[error]         at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
[error]         at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
[error]         at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
[error]         at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
[error]         at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
[error]         at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
[error]         at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
[error]         at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
[error]         at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
[error]         at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
[error]         at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[error]         at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by brandesNW** [comment]
Fixed by https://github.com/NetLogo/NetLogo/pull/2289
