### ISSUE TITLE
The R extension in any version of NetLogo

### ISSUE THREAD

**Issue by JuanBMoscosoM** [NetLogo/NetLogo#2288]
java.lang.UnsupportedClassVersionError: org/nlogo/extension/r/Entry : Unsupported major.minor version 51.0
 at java.lang.ClassLoader.defineClass1(Native Method)
 at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
 at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
 at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
 at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
 at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
 at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
 at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:627)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
 at org.nlogo.workspace.ExtensionManager.getClassManager(ExtensionManager.java:406)
 at org.nlogo.workspace.ExtensionManager.importExtension(ExtensionManager.java:173)
 at org.nlogo.compiler.StructureParser.parseImport(StructureParser.scala:459)
 at org.nlogo.compiler.StructureParser.parse(StructureParser.scala:196)
 at org.nlogo.compiler.CompilerMain$.compile(CompilerMain.scala:25)
 at org.nlogo.compiler.Compiler$.compileProgram(Compiler.scala:28)
 at org.nlogo.window.CompilerManager.compileProcedures(CompilerManager.java:107)
 at org.nlogo.window.CompilerManager.compileAll(CompilerManager.java:87)
 at org.nlogo.window.CompilerManager.handle(CompilerManager.java:309)
 at org.nlogo.window.Events$CompileAllEvent.beHandledBy(Events.java:175)
 at org.nlogo.window.Event.doRaise(Event.java:198)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.app.ProceduresTab$CompileAction.actionPerformed(ProceduresTab.scala:60)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1995)
 at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2318)
 at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:387)
 at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:242)
 at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:236)
 at java.awt.Component.processMouseEvent(Component.java:6297)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3275)
 at java.awt.Component.processEvent(Component.java:6062)
 at java.awt.Container.processEvent(Container.java:2039)
 at java.awt.Component.dispatchEventImpl(Component.java:4660)
 at java.awt.Container.dispatchEventImpl(Container.java:2097)
 at java.awt.Component.dispatchEvent(Component.java:4488)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4575)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4236)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4166)
 at java.awt.Container.dispatchEventImpl(Container.java:2083)
 at java.awt.Window.dispatchEventImpl(Window.java:2489)
 at java.awt.Component.dispatchEvent(Component.java:4488)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:674)
 at java.awt.EventQueue.access$400(EventQueue.java:81)
 at java.awt.EventQueue$2.run(EventQueue.java:633)
 at java.awt.EventQueue$2.run(EventQueue.java:631)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:98)
 at java.awt.EventQueue$3.run(EventQueue.java:647)
 at java.awt.EventQueue$3.run(EventQueue.java:645)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:644)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

NetLogo 5.0.5
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) Server VM 1.6.0_45 (Sun Microsystems Inc.; 1.6.0_45-b06)
operating system: Windows 8 6.2 (x86 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Untitled

03:09:03.436 RemoveAllJobsEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
03:09:03.436 CompileAllEvent (org.nlogo.app.MainProceduresTab) AWT-EventQueue-0
03:09:03.311 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
03:09:03.111 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
03:09:02.909 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
03:09:02.708 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
03:09:02.505 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
03:09:02.490 DirtyEvent (org.nlogo.app.MainProceduresTab) AWT-EventQueue-0
03:09:02.099 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
03:09:01.898 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

**Comment by SethTisue** [comment]
offhand, it looks to me like you're trying to use the extension with a too-old version of NetLogo. are you sure that the extension is documented as expected to work with NetLogo 5.0.5?

**Comment by brandesNW** [comment]
We are sorry you ran into this problem. You are using NetLogo 5.0.5, which is a very old version. Please use NetLogo 6.4.0, our most recent release, which can be downloaded [here](https://ccl.northwestern.edu/netlogo/download.shtml).
If you continue to have problems with the R extension, I suggest you try out the Simple R
extension which has a simple point and click configuration menu for telling
the extension about the location on your system of your R install. It is
more straightforward to set up than the bundled R extension which requires
the manual creation of a configuration file.
You can install the Simple R extension using NetLogo's built-in [extension](http://ccl.northwestern.edu/netlogo/docs/extension-manager.htm)
[manager](http://ccl.northwestern.edu/netlogo/docs/extension-manager.htm).
Examples showing how to use it can be found [here](https://github.com/NetLogo/SimpleR-Extension?tab=readme-ov-file#using).
Information on switching to Simple R from the bundled R extension is [here](https://github.com/NetLogo/SimpleR-Extension?tab=readme-ov-file#transitioning-from-the-old-r-extension).

In case you want to know more about your error message, the basic problem is that the Java version for NetLogo 5 is very old. Each JDK Release comes with its class file version. Class files are backward compatible. But class files compiled for newer JDK releases cannot be executed and will result in an UnsupportedClassVersionError. Java 7 class files are version 51.0, Java 8 class files are version 52.0. As of NetLogo 6.3.0 all code, including extensions, is compiled using Java 17 with Java 11 compatability. Java 17 class files are version 61.0, Java 11 class files are version 55.0

Please let us know if this does not solve your problem, and we will look
further into the issue.
Thanks,
Aaron

**Comment by JuanBMoscosoM** [comment]
> offhand, it looks to me like you're trying to use the extension with a too-old version of NetLogo. are you sure that the extension is documented as expected to work with NetLogo 5.0.5?

Hello, I usually use version 6.3.0, which was the one that first gave me an error. I started trying older versions because I got another error saying the extension used NetLogo Extension API 5.0 and that the version was not compatible. Recently, I also tried NetLogo 6.4.0 with the same results. Anyway, now I'm testing with the Simple R extension, which has worked for me. Thanks for your help.

**Comment by JuanBMoscosoM** [comment]
> We are sorry you ran into this problem. You are using NetLogo 5.0.5, which is a very old version. Please use NetLogo 6.4.0, our most recent release, which can be downloaded [here](https://ccl.northwestern.edu/netlogo/download.shtml). If you continue to have problems with the R extension, I suggest you try out the Simple R extension which has a simple point and click configuration menu for telling the extension about the location on your system of your R install. It is more straightforward to set up than the bundled R extension which requires the manual creation of a configuration file. You can install the Simple R extension using NetLogo's built-in [extension](http://ccl.northwestern.edu/netlogo/docs/extension-manager.htm) [manager](http://ccl.northwestern.edu/netlogo/docs/extension-manager.htm). Examples showing how to use it can be found [here](https://github.com/NetLogo/SimpleR-Extension?tab=readme-ov-file#using). Information on switching to Simple R from the bundled R extension is [here](https://github.com/NetLogo/SimpleR-Extension?tab=readme-ov-file#transitioning-from-the-old-r-extension).
> 
> In case you want to know more about your error message, the basic problem is that the Java version for NetLogo 5 is very old. Each JDK Release comes with its class file version. Class files are backward compatible. But class files compiled for newer JDK releases cannot be executed and will result in an UnsupportedClassVersionError. Java 7 class files are version 51.0, Java 8 class files are version 52.0. As of NetLogo 6.3.0 all code, including extensions, is compiled using Java 17 with Java 11 compatability. Java 17 class files are version 61.0, Java 11 class files are version 55.0
> 
> Please let us know if this does not solve your problem, and we will look further into the issue. Thanks, Aaron

Hello, the reason I tried that version was because in an error message that appeared before the one I initially sent, it said the following: "You are attempting to open a NetLogo extension file that was created for a different version of the NetLogo Extension API. (This NetLogo uses Extension API 6.1; the extension uses NetLogo Extension API 5.0) NetLogo can try to load the extension, but it might not work." This happened with version 6.4.0, but the same issue occurred with all the versions I tried.
Anyway, I followed your recommendation and tried Simple R, which has been working well for me so far. Thank you very much for your help.
