### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by minnesota9910** [NetLogo/NetLogo#2300]
This is what I was getting when I exported results from my program. 
Hopefully someone could help me out.

NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 

java.util.NoSuchElementException: next on empty iterator
 at scala.collection.Iterator$$anon$2.next(Iterator.scala:41)
 at scala.collection.Iterator$$anon$2.next(Iterator.scala:39)
 at scala.collection.IterableLike.head(IterableLike.scala:109)
 at scala.collection.IterableLike.head$(IterableLike.scala:108)
 at scala.collection.mutable.ArrayBuffer.scala$collection$IndexedSeqOptimized$$super$head(ArrayBuffer.scala:49)
 at scala.collection.IndexedSeqOptimized.head(IndexedSeqOptimized.scala:129)
 at scala.collection.IndexedSeqOptimized.head$(IndexedSeqOptimized.scala:129)
 at scala.collection.mutable.ArrayBuffer.head(ArrayBuffer.scala:49)
 at scala.collection.TraversableLike.last(TraversableLike.scala:627)
 at scala.collection.TraversableLike.last$(TraversableLike.scala:626)
 at scala.collection.mutable.ArrayBuffer.scala$collection$IndexedSeqOptimized$$super$last(ArrayBuffer.scala:49)
 at scala.collection.IndexedSeqOptimized.last(IndexedSeqOptimized.scala:135)
 at scala.collection.IndexedSeqOptimized.last$(IndexedSeqOptimized.scala:135)
 at scala.collection.mutable.ArrayBuffer.last(ArrayBuffer.scala:49)
 at org.nlogo.lab.SpreadsheetExporter$Run.lastMeasurement(SpreadsheetExporter.scala:176)
 at org.nlogo.lab.SpreadsheetExporter.$anonfun$writeSummary$9(SpreadsheetExporter.scala:101)
 at org.nlogo.lab.SpreadsheetExporter.$anonfun$writeSummary$9$adapted(SpreadsheetExporter.scala:100)
 at org.nlogo.lab.SpreadsheetExporter.$anonfun$foreachRun$2(SpreadsheetExporter.scala:55)
 at org.nlogo.lab.SpreadsheetExporter.$anonfun$foreachRun$2$adapted(SpreadsheetExporter.scala:54)
 at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
 at scala.collection.immutable.Range.foreach(Range.scala:158)
 at scala.collection.TraversableLike.map(TraversableLike.scala:286)
 at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
 at scala.collection.AbstractTraversable.map(Traversable.scala:108)
 at org.nlogo.lab.SpreadsheetExporter.$anonfun$foreachRun$1(SpreadsheetExporter.scala:54)
 at org.nlogo.lab.SpreadsheetExporter.$anonfun$foreachRun$1$adapted(SpreadsheetExporter.scala:51)
 at scala.collection.immutable.List.flatMap(List.scala:366)
 at org.nlogo.lab.SpreadsheetExporter.foreachRun(SpreadsheetExporter.scala:51)
 at org.nlogo.lab.SpreadsheetExporter.writeSummary(SpreadsheetExporter.scala:100)
 at org.nlogo.lab.SpreadsheetExporter.finish(SpreadsheetExporter.scala:38)
 at org.nlogo.lab.SpreadsheetExporter.experimentCompleted(SpreadsheetExporter.scala:43)
 at org.nlogo.lab.Worker.$anonfun$run$7(Worker.scala:76)
 at org.nlogo.lab.Worker.$anonfun$run$7$adapted(Worker.scala:76)
 at scala.collection.immutable.List.foreach(List.scala:431)
 at scala.collection.generic.TraversableForwarder.foreach(TraversableForwarder.scala:38)
 at scala.collection.generic.TraversableForwarder.foreach$(TraversableForwarder.scala:38)
 at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:47)
 at org.nlogo.lab.Worker.run(Worker.scala:76)
 at org.nlogo.lab.gui.Supervisor$$anon$2.run(Supervisor.scala:68)
 at java.base/java.lang.Thread.run(Unknown Source)

NetLogo 6.4.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
OpenJDK 64-Bit Server VM 17.0.8.1 (BellSoft; 17.0.8.1+1-LTS)
Scala version 2.12.18
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: revised copy

11:31:53.458 WidgetRemovedEvent (org.nlogo.window.PlotWidget) AWT-EventQueue-0
11:31:53.430 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
11:31:53.367 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
11:31:53.367 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
11:31:53.366 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
11:31:53.366 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
11:31:53.366 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
11:31:53.366 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
11:31:53.365 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
11:31:53.365 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread

**Comment by minnesota9910** [comment]
Fixed
