### ISSUE TITLE
BehaviorSpace throws errors when encountering destructuring binds

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/NetLogo#2301]
### Code to Reproduce

```netlogo
globals [a]

to setup
  let [x y] [1 2]
end

to go
end
```

### Steps to reproduce

  * Make a new BehaviorSpace experiment
    * Name: Whatever
    * Vary variables: `["a" 1 2]`
    * Repetitions: 2
    * Measure runs using: `count turtles`
    * Setup: `setup`
    * Go: `go`
    * Time limit: 0
  * Run it

### What should happen

  * Nothing interesting

### What actually happens

> java.lang.IndexOutOfBoundsException: 2
>  at scala.collection.immutable.Vector.checkRangeConvert(Vector.scala:131)
>  at scala.collection.immutable.Vector.apply(Vector.scala:122)
>  at org.nlogo.core.LogoList.get(LogoList.scala:36)
>  at org.nlogo.prim.MultiLet$.next(_multilet.scala:21)
>  at org.nlogo.prim._asm_proceduresetup_setprocedurevariable_2.perform(:2)
>  at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
>  at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
>  at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
>  at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
>  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
>  at scala.util.control.Exception$Catch.apply(Exception.scala:228)
>  at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
>  at org.nlogo.job.JobThread.run(JobThread.scala:66)

### Notes

The required parts seem to be:

  * *Some* parameter sweep in the experiment
  * *Some* metric in the experiment
  * More than 1 repetition
  * Use destructuring bind *somewhere*

**Comment by ERSUCC** [comment]
I also get an error with this case, but I get this one:

```
Run #1, JAVA EXCEPTION: We're trying to get a list value for a multi-assign (let or set), but the list hasn't been set?
[error] java.lang.IllegalStateException: We're trying to get a list value for a multi-assign (let or set), but the list hasn't been set?
[error]         at org.nlogo.prim.MultiAssign$.$anonfun$next$1(_multiassign.scala:41)
[error]         at scala.collection.MapLike.getOrElse(MapLike.scala:131)
[error]         at scala.collection.MapLike.getOrElse$(MapLike.scala:129)
[error]         at scala.collection.AbstractMap.getOrElse(Map.scala:65)
[error]         at org.nlogo.prim.MultiAssign$.next(_multiassign.scala:41)
[error]         at org.nlogo.prim._asm_proceduresetup_setprocedurevariable_1.perform(:2)
[error]         at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
[error]         at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
[error]         at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
[error]         at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error]         at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
[error]         at org.nlogo.job.JobThread.run(JobThread.scala:66)
```

Clearly relates to the same issue, just a slightly different place in the code. Also, it is important to note that this error is not consistently reproducible for me. It only seemed to occur once every 5 runs or so, even without changing the parameters.

**Comment by TheBizzle** [comment]
Fixed by c4dc02ae463581ee7888f272c60e013e5e3be86e
