### ISSUE TITLE
Internal Error Encountered

### ISSUE THREAD

**Issue by Aditi-Gp** [NetLogo/NetLogo#2320]
NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 

java.lang.ArrayIndexOutOfBoundsException: Index 13 out of bounds for length 13
 at org.nlogo.agent.Turtle.realloc(Turtle.java:202)
 at org.nlogo.agent.Turtle.realloc(Turtle.java:172)
 at org.nlogo.agent.Realloc$.realloc(Realloc.scala:41)
 at org.nlogo.agent.CompilationManagement.realloc(CompilationManagement.scala:70)
 at org.nlogo.agent.CompilationManagement.realloc$(CompilationManagement.scala:69)
 at org.nlogo.agent.World2D.realloc(World.scala:137)
 at org.nlogo.window.CompilerManager.compileAll(CompilerManager.scala:180)
 at org.nlogo.window.CompilerManager.handle(CompilerManager.scala:137)
 at org.nlogo.window.Events$CompileAllEvent.beHandledBy(Events.java:185)
 at org.nlogo.window.Event.doRaise(Event.java:206)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.app.codetab.CodeTab.compile(CodeTab.scala:163)
 at org.nlogo.app.codetab.CodeTab$CompileAction$.actionPerformed(CodeTab.scala:198)
 at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
 at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
 at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
 at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
 at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
 at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
 at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
 at java.desktop/java.awt.Component.processEvent(Unknown Source)
 at java.desktop/java.awt.Container.processEvent(Unknown Source)
 at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
 at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
 at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
 at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
 at java.base/java.security.AccessController.doPrivileged(Unknown Source)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
 at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
 at java.base/java.security.AccessController.doPrivileged(Unknown Source)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

NetLogo 6.4.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
OpenJDK 64-Bit Server VM 17.0.8.1 (BellSoft; 17.0.8.1+1-LTS)
operating system: Windows 11 10.0 (amd64 processor)
Scala version 2.12.18
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: EV

05:34:11.157 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:34:11.157 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:34:11.157 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:34:11.157 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
05:34:11.157 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
05:34:11.034 RemoveAllJobsEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
05:34:11.034 CompileAllEvent (org.nlogo.app.codetab.MainCodeTab) AWT-EventQueue-0
05:34:10.883 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:34:10.883 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:34:10.883 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0

**Comment by brandesNW** [comment]
Thanks for reporting this issue, and sorry you ran into it! From reading the stack trace it isn't exactly clear why the error is happening . Please attach the .nlogo model file in a zip file  along with instructions for reproducing the problem so we can be of more help.
