### ISSUE TITLE
netlogo issue

### ISSUE THREAD

**Issue by dolphin981** [NetLogo/NetLogo#2333]
java.io.FileNotFoundException: C:\Users\nehar\Downloads\Consumats on a Network Fall 2024 Final Assignment (1) experiment-table.csv (The process cannot access the file because it is being used by another process)
 at java.base/java.io.FileOutputStream.open0(Native Method)
 at java.base/java.io.FileOutputStream.open(Unknown Source)
 at java.base/java.io.FileOutputStream.<init>(Unknown Source)
 at java.base/java.io.FileOutputStream.<init>(Unknown Source)
 at java.base/java.io.FileWriter.<init>(Unknown Source)
 at org.nlogo.lab.gui.Supervisor.start(Supervisor.scala:168)
 at org.nlogo.lab.gui.ManagerDialog.run(ManagerDialog.scala:153)
 at org.nlogo.lab.gui.ManagerDialog.$anonfun$runAction$1(ManagerDialog.scala:40)
 at org.nlogo.lab.gui.ManagerDialog$$anon$1.actionPerformed(ManagerDialog.scala:31)
 at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
 at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
 at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
 at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
 at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
 at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
 at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
 at java.desktop/java.awt.Component.processEvent(Unknown Source)
 at java.desktop/java.awt.Container.processEvent(Unknown Source)
 at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
 at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
 at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
 at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
 at java.base/java.security.AccessController.doPrivileged(Unknown Source)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
 at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
 at java.base/java.security.AccessController.doPrivileged(Unknown Source)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

NetLogo 6.4.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
OpenJDK 32-Bit Client VM 17.0.8.1 (BellSoft; 17.0.8.1+1-LTS)
operating system: Windows 11 10.0 (x86 processor)
Scala version 2.12.18
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Consumats on a Network Fall 2024 Final Assignment (1)

04:48:16.823 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
04:48:16.823 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
04:48:16.823 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
04:48:16.823 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
04:48:16.823 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
04:48:16.823 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
04:48:16.823 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
04:48:16.823 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
04:48:16.823 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
04:48:16.823 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0

**Comment by brandesNW** [comment]
Hi,
The most likely cause of your problem is that you ran a behaviorspace experiment, left the table csv file open and ran the experiment again with the same output file.
Closing the file should eliminate the problem.

In our next release this issue will be handled better.
Let us know if you have any further questions, and please close the issue if this solves your problem.

  *   Aaron

--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling


From: dolphin981 ***@***.***>
Date: Saturday, December 7, 2024 at 4:52 PM
To: NetLogo/NetLogo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [NetLogo/NetLogo] netlogo issue (Issue #2333)

java.io.FileNotFoundException: C:\Users\nehar\Downloads\Consumats on a Network Fall 2024 Final Assignment (1) experiment-table.csv (The process cannot access the file because it is being used by another process)
at java.base/java.io.FileOutputStream.open0(Native Method)
at java.base/java.io.FileOutputStream.open(Unknown Source)
at java.base/java.io.FileOutputStream.(Unknown Source)
at java.base/java.io.FileOutputStream.(Unknown Source)
at java.base/java.io.FileWriter.(Unknown Source)
at org.nlogo.lab.gui.Supervisor.start(Supervisor.scala:168)
at org.nlogo.lab.gui.ManagerDialog.run(ManagerDialog.scala:153)
at org.nlogo.lab.gui.ManagerDialog.$anonfun$runAction$1(ManagerDialog.scala:40)
at org.nlogo.lab.gui.ManagerDialog$$anon$1.actionPerformed(ManagerDialog.scala:31)
at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
at java.desktop/java.awt.Component.processEvent(Unknown Source)
at java.desktop/java.awt.Container.processEvent(Unknown Source)
at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
at java.base/java.security.AccessController.doPrivileged(Unknown Source)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
at java.base/java.security.AccessController.doPrivileged(Unknown Source)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

NetLogo 6.4.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
OpenJDK 32-Bit Client VM 17.0.8.1 (BellSoft; 17.0.8.1+1-LTS)
operating system: Windows 11 10.0 (x86 processor)
Scala version 2.12.18
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Consumats on a Network Fall 2024 Final Assignment (1)

04:48:16.823 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
04:48:16.823 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
04:48:16.823 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
04:48:16.823 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
04:48:16.823 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
04:48:16.823 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
04:48:16.823 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
04:48:16.823 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
04:48:16.823 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
04:48:16.823 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0

**Comment by brandesNW** [comment]
This seems to be a known issue.
