### ISSUE TITLE
observer command line errors

### ISSUE THREAD

**Issue by turtlemaniac** [NetLogo/NetLogo#241]
Errors i get from using various observer command line inputs:

observer> to test end
ERROR: This doesn't make sense here

observer> test end
ERROR: Expected keyword

observer> test end to
ERROR: You can't use __DONE to name a procedure 

observer> end to test
NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.lang.NullPointerException
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:87)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.java:82)
 at org.nlogo.job.JobThread.org$nlogo$job$JobThread$$runPrimaryJobs(JobThread.scala:143)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply$mcV$sp(JobThread.scala:78)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at scala.util.control.Exception$Catch.apply(Exception.scala:88)
 at org.nlogo.util.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:75)

NetLogo 5.0.3
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) Server VM 1.6.0_33 (Sun Microsystems Inc.; 1.6.0_33-b03)
operating system: Windows 7 6.1 (x86 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Untitled

11:12:18.777 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:12:18.776 AddJobEvent (org.nlogo.app.CommandLine) AWT-EventQueue-0
11:12:18.776 OutputEvent (org.nlogo.app.CommandLine) AWT-EventQueue-0
11:12:18.775 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
11:12:18.655 CompileMoreSourceEvent (org.nlogo.app.CommandLine) AWT-EventQueue-0
11:12:18.483 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:12:18.283 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:12:18.083 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:12:17.883 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:12:17.683 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

**Comment by ERSUCC** [comment]
The primary issue presenting here is that command line input is wrapped in a dummy procedure before compilation. For example, in the example `test end to`, the source sent to the compiler would be something along the lines of `to __commandline [] test end to __done end`. The compiler then gets confused and thinks there are two separate procedures, one called `__commandline` and one called `__done`. It's not immediately obvious to me why the compiler needs the procedure wrap, it would seem more logical to me to just add a separate entry point to the compiler that assumes it will be parsing the contents of a single procedure.

**Comment by TheBizzle** [comment]
I imagine it has something to do with making the command in the Command Center haltable.  Just a guess.

**Comment by ERSUCC** [comment]
The engine clearly has the ability to run code that isn't inside a procedure but is haltable, because the various commands in BehaviorSpace are compiled with no extra wrapping. It throws a very sensible compiler error if you type `end to` in one of the boxes, and you can halt a BehaviorSpace experiment. So I imagine the simplest solution here would be to just copy the logic from BehaviorSpace into the Command Center.

**Comment by ERSUCC** [comment]
The solution I described above ended up being overly complex, whereas a much simpler solution was to just check for keywords whenever the compiler is parsing a single loose procedure from outside of the Code tab. That is the solution referenced in the commit I pushed just now, which now generates the error message "keyword ... cannot be used in this context" for all the examples described in the original issue.
