### ISSUE TITLE
bug: BehaviorSpace permits entry of empty enumerated value set, crashes on re-open

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#252]
so if I put a line like `["governance"]`, with no values, in the experiment setup, like this:

![Screen Shot 2012-12-18 at 3 02 00 PM](https://f.cloud.github.com/assets/161079/20305/efd6618a-494d-11e2-95d2-8bade3a31496.png)

then the resulting file ends up with this XML in it:

```
    <enumeratedValueSet variable="governance"/>
```

which when the model is opened results in:

```
org.xml.sax.SAXParseException: The content of element type "enumeratedValueSet" is incomplete, it must match "(value)+".
 at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:195)
 ...
 at org.nlogo.lab.ProtocolLoader$Loader.load(ProtocolLoader.scala:61)
 ...
 at org.nlogo.window.ModelLoader.load(ModelLoader.scala)
 at org.nlogo.app.FileMenu$1.run(FileMenu.java:766)
 ...
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

NetLogo 5.0.3
```

The model file can be repaired by removing the offending line using a text editor. But the experiment setup should be rejected when first created, so it can never end up being saved.

reported by Sara Levy

**Comment by mrerrormessage** [comment]
Fixed in #1159 .
