### ISSUE TITLE
headless 5.0.3 could not find relative includes

### ISSUE THREAD

**Issue by HughDevlin** [NetLogo/NetLogo#266]
__includes ["foo.nls"]

...works fine in NetLogo 5.0.3 GUI (finds .nls in same dir as .nlogo) but headless seems to be looking in my home dir:

Could not find /home/hugh/foo.nls at position 45 in
at org.nlogo.compiler.CompilerExceptionThrowers$.exception(CompilerExceptionThrower\s.scala:26)
at org.nlogo.compiler.StructureParser.parse(StructureParser.scala:233)
at org.nlogo.compiler.CompilerMain$.compile(CompilerMain.scala:25)
at org.nlogo.compiler.Compiler$.compileProgram(Compiler.scala:28)
at org.nlogo.headless.HeadlessModelOpener.openFromMap(HeadlessModelOpener.scala:53)
at org.nlogo.headless.HeadlessWorkspace.openFromSource(HeadlessWorkspace.scala:532)

circumvention: fully qualified path works both in GUI and headless:

__includes ["/home/hugh/git/myproject/myproject/foo.nls"]

NetLogo 5.0.3, Ubuntu 12.10

**Comment by Idloj** [comment]
This seems to work fine on 6.0.1
