### ISSUE TITLE
NetLogo error upon opening model Library; Mac OSX 10.8.2, latest version java

### ISSUE THREAD

**Issue by dkmj** [NetLogo/NetLogo#283]
NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.nio.charset.MalformedInputException: Input length = 1
 at java.nio.charset.CoderResult.throwException(CoderResult.java:277)
 at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:338)
 at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
 at java.io.InputStreamReader.read(InputStreamReader.java:184)
 at java.io.BufferedReader.fill(BufferedReader.java:154)
 at java.io.BufferedReader.readLine(BufferedReader.java:317)
 at java.io.BufferedReader.readLine(BufferedReader.java:382)
 at scala.io.BufferedSource$BufferedLineIterator.hasNext(BufferedSource.scala:67)
 at scala.collection.Iterator$GroupedIterator.takeDestructively(Iterator.scala:955)
 at scala.collection.Iterator$GroupedIterator.go(Iterator.scala:971)
 at scala.collection.Iterator$GroupedIterator.fill(Iterator.scala:1011)
 at scala.collection.Iterator$GroupedIterator.hasNext(Iterator.scala:1014)
 at scala.collection.Iterator$$anon$22.hasNext(Iterator.scala:457)
 at scala.collection.Iterator$class.foreach(Iterator.scala:772)
 at scala.collection.Iterator$$anon$22.foreach(Iterator.scala:451)
 at org.nlogo.app.ModelsLibraryIndexReader$$anonfun$readInfoMap$1.apply$mcV$sp(ModelsLibraryIndexReader.scala:16)
 at org.nlogo.app.ModelsLibraryIndexReader$$anonfun$readInfoMap$1.apply(ModelsLibraryIndexReader.scala:16)
 at org.nlogo.app.ModelsLibraryIndexReader$$anonfun$readInfoMap$1.apply(ModelsLibraryIndexReader.scala:16)
 at scala.util.control.Exception$Catch.apply(Exception.scala:88)
 at org.nlogo.util.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.app.ModelsLibraryIndexReader$.readInfoMap(ModelsLibraryIndexReader.scala:15)
 at org.nlogo.app.ModelsLibraryIndexReader.readInfoMap(ModelsLibraryIndexReader.scala)
 at org.nlogo.app.ModelsLibraryDialog$5.run(ModelsLibraryDialog.java:128)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:241)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:727)
 at java.awt.EventQueue.access$200(EventQueue.java:103)
 at java.awt.EventQueue$3.run(EventQueue.java:688)
 at java.awt.EventQueue$3.run(EventQueue.java:686)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:697)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:154)
 at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:182)
 at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:221)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:219)
 at java.awt.Dialog.show(Dialog.java:1082)
 at java.awt.Component.show(Component.java:1651)
 at java.awt.Component.setVisible(Component.java:1603)
 at java.awt.Window.setVisible(Window.java:1014)
 at java.awt.Dialog.setVisible(Dialog.java:1005)
 at org.nlogo.swing.ModalProgressTask$.apply(ModalProgressTask.scala:41)
 at org.nlogo.swing.ModalProgressTask.apply(ModalProgressTask.scala)
 at org.nlogo.app.ModelsLibraryDialog.<init>(ModelsLibraryDialog.java:123)
 at org.nlogo.app.ModelsLibraryDialog.open(ModelsLibraryDialog.java:28)
 at org.nlogo.app.FileMenu$ModelsLibraryAction.action(FileMenu.java:162)
 at org.nlogo.app.FileMenu$FileMenuAction.actionPerformed(FileMenu.java:92)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
 at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
 at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
 at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
 at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
 at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:128)
 at java.awt.MenuItem.processActionEvent(MenuItem.java:669)
 at java.awt.MenuItem.processEvent(MenuItem.java:628)
 at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351)
 at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:732)
 at java.awt.EventQueue.access$200(EventQueue.java:103)
 at java.awt.EventQueue$3.run(EventQueue.java:688)
 at java.awt.EventQueue$3.run(EventQueue.java:686)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
 at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
 at java.awt.EventQueue$4.run(EventQueue.java:702)
 at java.awt.EventQueue$4.run(EventQueue.java:700)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:699)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

NetLogo 5.0.3
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.7.0_13 (Oracle Corporation; 1.7.0_13-b20)
operating system: Mac OS X 10.8.2 (x86_64 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Untitled

10:45:55.079 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:45:52.911 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:45:52.710 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:45:52.509 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:45:52.309 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:45:52.107 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:45:51.907 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:45:51.706 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:45:51.505 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:45:51.304 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

**Comment by mrerrormessage** [comment]
NetLogo 5.0.x needs to be run with Apple Java 6 as documented [on the NetLogo faq page](http://ccl.northwestern.edu/netlogo/faq.html). I'm not certain whether that was well-understood at the time this bug was opened, but it is now well-known that attempting to run NetLogo with Oracle Java causes problems.
