### ISSUE TITLE
`ViewManager.framesSkipped` Sometimes Throws an NPE

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/NetLogo#298]
Rumor has it that certain conditions can lead to NPEs being thrown by `ViewManager.framesSkipped`.  It's not yet clear what, exactly, those conditions are, though.

**Comment by mrerrormessage** [comment]
I couldn't replicate this bug in NetLogo 5.3, but I'm fairly certain that this is a threading bug on `ViewManager.views`. `GUIWorkspace.updateDisplay` and `repaintAction` both cause view updates - one is used from the job thread, one from the swing thread. Other methods in `GUIWorkspace` cause `ViewManager.views` to update its state. The data structure underlying `views` is *not* thread-safe. It makes sense to me to try an explicitly threadsafe data structure for `ViewManager.views` and see if that fixes the problem, as long as using such a data structure wouldn't cause a deadlock, which at this point I'm unsure of.

**Comment by mrerrormessage** [comment]
related: #584

**Comment by LaCuneta** [comment]
Received another report from a user on macOS with NetLogo 6.1.0, so it still lurks.  They said they were editing code in the code tab, so I asked if they had more details, and to let us know if they see it again.  Otherwise, I assume the same fix Robert discussed previously would help.

```
NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 


java.lang.NullPointerException
 at java.util.LinkedList$ListItr.next(LinkedList.java:893)
 at org.nlogo.window.ViewManager.framesSkipped(ViewManager.java:40)
 at org.nlogo.window.GUIWorkspace.updateDisplay(GUIWorkspace.java:614)
 at org.nlogo.window.GUIWorkspace.breathe(GUIWorkspace.java:673)
 at org.nlogo.workspace.AbstractWorkspace.breathe(AbstractWorkspace.java:217)
 at org.nlogo.nvm.Context.comeUpForAir(Context.java:321)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:109)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
 at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
 at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
 at scala.util.control.Exception$Catch.apply(Exception.scala:228)
 at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:66)

NetLogo 6.1.0
main: org.nlogo.app.AppFrame
thread: JobThread
Java HotSpot(TM) 64-Bit Server VM 1.8.0_202 (Oracle Corporation; 1.8.0_202-b08)
operating system: Mac OS X 10.14.6 (x86_64 processor)
Scala version 2.12.8
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: unit4first-fixed (kopia)

11:27:27.202 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
11:27:27.097 RuntimeErrorEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:27:27.084 WidgetRemovedEvent (org.nlogo.app.tools.AgentVarEditor) AWT-EventQueue-0
11:27:27.084 RemoveJobEvent (org.nlogo.app.tools.AgentVarEditor) AWT-EventQueue-0
11:27:27.084 WidgetRemovedEvent (org.nlogo.app.tools.AgentVarEditor) AWT-EventQueue-0
11:27:27.084 RemoveJobEvent (org.nlogo.app.tools.AgentVarEditor) AWT-EventQueue-0
11:27:27.084 WidgetRemovedEvent (org.nlogo.app.tools.AgentVarEditor) AWT-EventQueue-0
11:27:27.084 RemoveJobEvent (org.nlogo.app.tools.AgentVarEditor) AWT-EventQueue-0
11:27:27.084 WidgetRemovedEvent (org.nlogo.app.tools.AgentVarEditor) AWT-EventQueue-0
11:27:27.084 RemoveJobEvent (org.nlogo.app.tools.AgentVarEditor) AWT-EventQueue-0
```

**Comment by TheBizzle** [comment]
@ERSUCC submitted a fix for this, once upon a time.  It went as follows:

```patch
diff --git a/netlogo-gui/src/main/window/ViewManager.java b/netlogo-gui/src/main/window/ViewManager.java
index e1d7675a3..bd0f8a59b 100644
--- a/netlogo-gui/src/main/window/ViewManager.java
+++ b/netlogo-gui/src/main/window/ViewManager.java
@@ -38,7 +38,8 @@ public class ViewManager {

   void framesSkipped() {
     for (ViewInterface v : views) {
-      v.framesSkipped();
+      if (v != null)
+        v.framesSkipped();
     }
   }
```

However, I don't want to use that as a fix for this issue.  It might fix the error message, but it doesn't fix the error.  I think it risks us hiding the error and making it harder to track down.

We should find a reliable way to reproduce the issue before going forward with any fix to it.  That said, as far as I can tell, it's been 5 years since anyone reported it.

**Comment by ERSUCC** [comment]
I found a way to reproduce the issue pretty reliably, and it's very clear now that it's a multithreading bug, as @mrerrormessage theorized. Unfortunately, synchronizing the relevant methods on the list of views causes a deadlock, so it may require some more careful tracing and restructuring to ensure a proper fix.

**Comment by SethTisue** [comment]
> synchronizing the relevant methods on the list of views causes a deadlock

@TheBizzle just curious, your fix is somehow different and doesn't have this problem...?

(UPDATE: oops, I see Jason merged it but isn't the fix author)

**Comment by ERSUCC** [comment]
I just spoke too soon and had the wrong list of "relevant" methods. After tracing where various calls were coming from, I found a setup that didn't deadlock.
