### ISSUE TITLE
file-read and read-from-string don't support extension types (e.g. tables and arrays)

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#39]
so for example `read-from-string (word table:make)` results in:

``` text
java.lang.NumberFormatException: For input string: "[]"
 at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
 at java.lang.Long.parseLong(Long.java:410)
 at java.lang.Long.parseLong(Long.java:468)
 at org.nlogo.extensions.table.TableExtension.readExtensionObject(TableExtension.java:406)
 at org.nlogo.workspace.ExtensionManager.readExtensionObject(ExtensionManager.java:504)
 at org.nlogo.compiler.ConstantParser.parseConstantLiteral(ConstantParser.scala:140)
```

this isn't just a bug, it's a missing feature.

we may need to rethink our whole approach on serializing extension types; see also #12, #13

**Comment by ERSUCC** [comment]
Still reproducible in NetLogo 7.
