### ISSUE TITLE
patch sizes < 1 are accepted, but poorly supported

### ISSUE THREAD

**Issue by turtlemaniac** [NetLogo/NetLogo#409]
To reproduce:
1)open a empty netlogo file
2)set-patch-size .5 resize-world -300 300 -300 300
3)mark the left or bottom view window border with a widget for visualization purposes
4)save file and reopen it

The view window should now appear as if the patches were size 1. however patch-size is still .5

To correct this behaviour set-patch-size 1, save and reopen the file.

System:
NetLogo 5.0.4 (March 19, 2013)
Extension API version: 5.0
Java HotSpot(TM) Server VM 1.6.0_41 (Sun Microsystems Inc.; 1.6.0_41-b02)
operating system: Windows 7 6.1 (x86 processor)
Scala version 2.9.2
Java heap: used = 107 MB, free = 816 MB, max = 923 MB

JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)

Also error in case running:
resize-world -300 300 -300 300 set-patch-size .5

java.lang.reflect.InvocationTargetException
 at java.awt.EventQueue.invokeAndWait(EventQueue.java:1086)
 at java.awt.EventQueue.invokeAndWait(EventQueue.java:1063)
 at org.nlogo.awt.EventQueue$.invokeAndWait(EventQueue.scala:19)
 at org.nlogo.swing.ModalProgressTask$Boss.run(ModalProgressTask.scala:50)
Caused by: java.lang.OutOfMemoryError: Java heap space
 at java.awt.image.DataBufferInt.<init>(DataBufferInt.java:41)
 at java.awt.image.Raster.createPackedRaster(Raster.java:458)
 at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1015)
 at java.awt.image.BufferedImage.<init>(BufferedImage.java:321)
 at org.nlogo.render.TrailDrawer.setUpDrawingImage(TrailDrawer.java:88)
 at org.nlogo.render.TrailDrawer.rescaleDrawing(TrailDrawer.java:103)
 at org.nlogo.window.WorldViewSettings2D$1.run(WorldViewSettings2D.java:89)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:199)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:672)
 at java.awt.EventQueue.access$400(EventQueue.java:81)
 at java.awt.EventQueue$2.run(EventQueue.java:633)
 at java.awt.EventQueue$2.run(EventQueue.java:631)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:642)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:178)
 at java.awt.Dialog$1.run(Dialog.java:1052)
 at java.awt.Dialog$3.run(Dialog.java:1104)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.awt.Dialog.show(Dialog.java:1102)
 at java.awt.Component.show(Component.java:1591)
 at java.awt.Component.setVisible(Component.java:1543)
 at java.awt.Window.setVisible(Window.java:843)
 at java.awt.Dialog.setVisible(Dialog.java:987)
 at org.nlogo.swing.ModalProgressTask$.apply(ModalProgressTask.scala:41)
 at org.nlogo.swing.ModalProgressTask.apply(ModalProgressTask.scala)
 at org.nlogo.window.WorldViewSettings2D.resizeWithProgress(WorldViewSettings2D.java:109)
 at org.nlogo.window.GUIWorkspace.resizeView(GUIWorkspace.java:302)
 at org.nlogo.prim.etc._resizeworld$2.run(_resizeworld.java:52)
 at org.nlogo.window.ThreadUtils$$anonfun$waitFor$2.apply$mcV$sp(ThreadUtils.scala:29)

NetLogo 5.0.4
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) Server VM 1.6.0_41 (Sun Microsystems Inc.; 1.6.0_41-b02)
operating system: Windows 7 6.1 (x86 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Untitled

08:53:23.900 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
08:53:22.278 ResizeViewEvent (org.nlogo.window.ViewWidget) AWT-EventQueue-0
08:53:22.278 PatchesCreatedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
08:53:22.215 AddJobEvent (org.nlogo.app.CommandLine) AWT-EventQueue-0
08:53:22.215 OutputEvent (org.nlogo.app.CommandLine) AWT-EventQueue-0
08:53:22.215 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
08:53:22.184 CompileMoreSourceEvent (org.nlogo.app.CommandLine) AWT-EventQueue-0
08:53:22.122 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
08:53:21.919 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
08:53:21.716 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

**Comment by felixhelix** [comment]
Hi, I would be very useful to have patch sizes smaller than one if working with higher resolution GIS images. By now one has to reset the size every time when opening such a model.
Is there a way to make this work?

**Comment by LaCuneta** [comment]
There is a workaround to use a patch size < 1.  Just add a `startup` procedure and use `set-patch-size` there:

```netlogo
to startup
  set-patch-size 0.2
end
```

The view will "flash" between the sizes (1 to 0.2) on load, but at least it'll be ready to go once it's done.  Obviously you'll still have the quirks with editing and loading models afterwards (see #1317).

**Comment by ERSUCC** [comment]
Fixed in commit [729dbda](https://github.com/NetLogo/NetLogo/commit/729dbda06176b0309458d7b5d0936e885efe33c5).
