### ISSUE TITLE
error while undoing

### ISSUE THREAD

**Issue by turtlemaniac** [NetLogo/NetLogo#450]
NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

javax.swing.undo.CannotUndoException
 at javax.swing.text.GapContent$InsertUndo.undo(GapContent.java:856)
 at javax.swing.undo.CompoundEdit.undo(CompoundEdit.java:46)
 at javax.swing.text.AbstractDocument$DefaultDocumentEvent.undo(AbstractDocument.java:2788)
 at javax.swing.undo.CompoundEdit.undo(CompoundEdit.java:46)
 at javax.swing.undo.UndoManager.undoTo(UndoManager.java:320)
 at javax.swing.undo.UndoManager.undo(UndoManager.java:398)
 at org.nlogo.editor.UndoManager.undo(UndoManager.java:63)
 at org.nlogo.editor.UndoManager$UndoAction.actionPerformed(UndoManager.java:139)
 at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1639)
 at javax.swing.JComponent.processKeyBinding(JComponent.java:2859)
 at javax.swing.JComponent.processKeyBindings(JComponent.java:2894)
 at javax.swing.JComponent.processKeyEvent(JComponent.java:2822)
 at java.awt.Component.processEvent(Component.java:6074)
 at java.awt.Container.processEvent(Container.java:2039)
 at java.awt.Component.dispatchEventImpl(Component.java:4660)
 at java.awt.Container.dispatchEventImpl(Container.java:2097)
 at java.awt.Component.dispatchEvent(Component.java:4488)
 at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1856)
 at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:722)
 at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1000)
 at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:865)
 at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:686)
 at java.awt.Component.dispatchEventImpl(Component.java:4532)
 at java.awt.Container.dispatchEventImpl(Container.java:2097)
 at java.awt.Window.dispatchEventImpl(Window.java:2489)
 at java.awt.Component.dispatchEvent(Component.java:4488)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:674)
 at java.awt.EventQueue.access$400(EventQueue.java:81)
 at java.awt.EventQueue$2.run(EventQueue.java:633)
 at java.awt.EventQueue$2.run(EventQueue.java:631)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:98)
 at java.awt.EventQueue$3.run(EventQueue.java:647)
 at java.awt.EventQueue$3.run(EventQueue.java:645)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:644)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

NetLogo 5.0.4
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) Server VM 1.6.0_41 (Sun Microsystems Inc.; 1.6.0_41-b02)
operating system: Windows 7 6.1 (x86 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: 0

12:28:35.037 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
12:28:34.834 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
12:28:34.819 DirtyEvent (org.nlogo.app.MainProceduresTab) AWT-EventQueue-0
12:28:34.819 DirtyEvent (org.nlogo.app.MainProceduresTab) AWT-EventQueue-0
12:28:34.819 DirtyEvent (org.nlogo.app.MainProceduresTab) AWT-EventQueue-0
12:28:34.631 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
12:28:34.429 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
12:28:34.226 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
12:28:34.023 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
12:28:33.992 DirtyEvent (org.nlogo.app.MainProceduresTab) AWT-EventQueue-0

**Comment by Idloj** [comment]
Can you give some info about what you did or how to reproduce?

**Comment by mrerrormessage** [comment]
We should be catching this exception in `UndoManager$UndoAction.actionPerformed`. This should be a simple try-catch.

**Comment by mrerrormessage** [comment]
Fixed in #957
