### ISSUE TITLE
ConcurrentModificationException when closing 3D view

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#584]
this happened when I closed the 3D view when some code was still running in the Command Center

```
error (ConcurrentModificationException)
 while observer running ASK
  called by Command Center

NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.util.ConcurrentModificationException
 at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:761)
 at java.util.LinkedList$ListItr.next(LinkedList.java:696)
 at org.nlogo.window.ViewManager.framesSkipped(ViewManager.java:40)
 at org.nlogo.window.GUIWorkspace.updateDisplay(GUIWorkspace.java:588)
 at org.nlogo.window.GUIWorkspace.breathe(GUIWorkspace.java:647)
 at org.nlogo.nvm.Context.comeUpForAir(Context.java:358)
 at org.nlogo.nvm.Context.runExclusive(Context.java:121)
 at org.nlogo.nvm.ExclusiveJob.run(ExclusiveJob.java:57)
 at org.nlogo.nvm.Context.runExclusiveJob(Context.java:162)
 at org.nlogo.prim._asm_commandcenter_ask_0.perform(:1)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:91)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.java:82)
 at org.nlogo.job.JobThread.org$nlogo$job$JobThread$$runPrimaryJobs(JobThread.scala:143)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply$mcV$sp(JobThread.scala:78)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at scala.util.control.Exception$Catch.apply(Exception.scala:88)
 at org.nlogo.util.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:75)

NetLogo 5.0.5
main: org.nlogo.app.AppFrame
thread: JobThread
Java HotSpot(TM) 64-Bit Server VM 1.6.0_65 (Apple Inc.; 1.6.0_65-b14-462-11M4609)
operating system: Mac OS X 10.9.2 (x86_64 processor)
Scala version 2.9.2
JOGL: 1.1.1
OpenGL graphics: NVIDIA GeForce GT 750M OpenGL Engine
OpenGL version: 2.1 NVIDIA-8.24.9 310.40.25f01
OpenGL vendor: NVIDIA Corporation
model: Untitled

09:13:04.881 RuntimeErrorEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:13:04.861 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
09:13:04.794 Enable2DEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:13:04.614 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:13:04.413 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:13:04.212 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:13:04.012 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:13:03.812 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:13:03.611 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:13:03.410 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
```

**Comment by LaCuneta** [comment]
I stumbled on a similar error in 6.0.4 and 6.1.0-RC2, so looks like it's still an issue:

- Open NetLogo 3D.
- Open Wolf Sheep Predation (2D version) from the models library.
- Switch to `wolves-sheep-grass` version (so the model keeps running longer).  Setu, and go!
- Edit the 3D view with the model still running.  Change the Z max to 1 (Z min becomes -1).
- Hit okay, get exception.

```
java.util.ConcurrentModificationException
 at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1211)
 at java.util.TreeMap$ValueIterator.next(TreeMap.java:1256)
 at org.nlogo.agent.TreeAgentSet$Iterator.next(TreeAgentSet.scala:135)
 at org.nlogo.agent.TurtleManagement.clearTurtles(TurtleManagement.scala:104)
 at org.nlogo.agent.TurtleManagement.clearTurtles$(TurtleManagement.scala:95)
 at org.nlogo.agent.World.clearTurtles(World.scala:109)
 at org.nlogo.window.WorldViewSettings3D$ResizeRunner.run(WorldViewSettings3D.scala:216)
 at org.nlogo.swing.ModalProgressTask$.$anonfun$onUIThread$1(ModalProgressTask.scala:26)
 at org.nlogo.swing.ModalProgressTask$.$anonfun$onUIThread$1$adapted(ModalProgressTask.scala:24)
 at org.nlogo.swing.ModalProgressTask$.$anonfun$display$1(ModalProgressTask.scala:18)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
 at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
 at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
 at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
 at java.awt.Dialog.show(Dialog.java:1084)
 at java.awt.Component.show(Component.java:1671)
 at java.awt.Component.setVisible(Component.java:1623)
 at java.awt.Window.setVisible(Window.java:1014)
 at java.awt.Dialog.setVisible(Dialog.java:1005)
 at org.nlogo.swing.ModalProgressTask$.display(ModalProgressTask.scala:20)
 at org.nlogo.swing.ModalProgressTask$.onUIThread(ModalProgressTask.scala:24)
 at org.nlogo.window.WorldViewSettings3D.resizeWithProgress(WorldViewSettings3D.scala:248)
 at org.nlogo.window.WorldViewSettings3D.editFinished(WorldViewSettings3D.scala:197)
 at org.nlogo.properties.EditDialog.$anonfun$$init$$1(EditDialog.scala:53)
 at org.nlogo.swing.Implicits$$anon$5.actionPerformed(Implicits.scala:16)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
 at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
 at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
 at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
 at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
 at java.awt.Component.processMouseEvent(Component.java:6533)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
 at java.awt.Component.processEvent(Component.java:6298)
 at java.awt.Container.processEvent(Container.java:2237)
 at java.awt.Component.dispatchEventImpl(Component.java:4889)
 at java.awt.Container.dispatchEventImpl(Container.java:2295)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
 at java.awt.Container.dispatchEventImpl(Container.java:2281)
 at java.awt.Window.dispatchEventImpl(Window.java:2746)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.awt.EventQueue$4.run(EventQueue.java:729)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
 at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
 at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
 at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
 at java.awt.Dialog.show(Dialog.java:1084)
 at java.awt.Component.show(Component.java:1671)
 at java.awt.Component.setVisible(Component.java:1623)
 at java.awt.Window.setVisible(Window.java:1014)
 at java.awt.Dialog.setVisible(Dialog.java:1005)
 at org.nlogo.properties.EditDialog.$init$(EditDialog.scala:114)
 at org.nlogo.properties.EditDialogFactory$$anon$1.<init>(EditDialogFactory.scala:14)
 at org.nlogo.properties.EditDialogFactory.canceled(EditDialogFactory.scala:14)
 at org.nlogo.app.interfacetab.InterfaceToolBar.$anonfun$handle$3(InterfaceToolBar.scala:94)
 at org.nlogo.app.interfacetab.InterfaceToolBar.$anonfun$handle$3$adapted(InterfaceToolBar.scala:85)
 at scala.Option.foreach(Option.scala:257)
 at org.nlogo.app.interfacetab.InterfaceToolBar.handle(InterfaceToolBar.scala:85)
 at org.nlogo.window.Events$EditWidgetEvent.beHandledBy(Events.java:255)
 at org.nlogo.window.Event.doRaise(Event.java:198)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.gl.view.Picker$$anon$1.actionPerformed(Picker.scala:26)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
 at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
 at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
 at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
 at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
 at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
 at com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
 at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
 at java.awt.Component.processMouseEvent(Component.java:6533)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
 at java.awt.Component.processEvent(Component.java:6298)
 at java.awt.Container.processEvent(Container.java:2237)
 at java.awt.Component.dispatchEventImpl(Component.java:4889)
 at java.awt.Container.dispatchEventImpl(Container.java:2295)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
 at java.awt.Container.dispatchEventImpl(Container.java:2281)
 at java.awt.Window.dispatchEventImpl(Window.java:2746)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.awt.EventQueue$4.run(EventQueue.java:729)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

NetLogo 3D 6.0.4
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_152 (Oracle Corporation; 1.8.0_152-b16)
operating system: Mac OS X 10.14.4 (x86_64 processor)
Scala version 2.12.4
JOGL: 2.3.2
OpenGL graphics: Intel(R) Iris(TM) Graphics 6100
OpenGL version: 2.1 INTEL-12.8.38
OpenGL vendor: Intel Inc.
model: Wolf Sheep Predation

01:40:19.067 RemoveAllJobsEvent (org.nlogo.window.ViewWidget) AWT-EventQueue-0
01:40:18.994 WidgetEditedEvent (org.nlogo.window.ViewWidget) AWT-EventQueue-0
01:40:18.959 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:40:18.959 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:40:18.959 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:40:18.959 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:40:18.959 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:40:18.959 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:40:18.959 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:40:18.956 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
```
