### ISSUE TITLE
Error in "Code" tab during editing

### ISSUE THREAD

**Issue by mlk5060** [NetLogo/NetLogo#608]
The following error occurred after I had copied and pasted a few lines of code in the "Code" tab of the main Netlogo program.  Pasting produces an extremely jumbled list of characters.  

Verbatim error message follows and a picture of the jumbled list of characters follows this:

NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.lang.IllegalStateException: javax.swing.text.BadLocationException: Length must be positive
 at org.nlogo.editor.BracketMatcher.caretUpdate(BracketMatcher.java:100)
 at javax.swing.text.JTextComponent.fireCaretUpdate(JTextComponent.java:399)
 at javax.swing.text.JTextComponent$MutableCaretEvent.fire(JTextComponent.java:4411)
 at javax.swing.text.JTextComponent$MutableCaretEvent.stateChanged(JTextComponent.java:4433)
 at javax.swing.text.DefaultCaret.fireStateChanged(DefaultCaret.java:802)
 at javax.swing.text.DefaultCaret.changeCaretPosition(DefaultCaret.java:1274)
 at javax.swing.text.DefaultCaret.handleSetDot(DefaultCaret.java:1173)
 at javax.swing.text.DefaultCaret.setDot(DefaultCaret.java:1154)
 at javax.swing.text.DefaultCaret.setDot(DefaultCaret.java:1051)
 at javax.swing.text.DefaultCaret$Handler.insertUpdate(DefaultCaret.java:1690)
 at javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:201)
 at javax.swing.text.AbstractDocument$DefaultDocumentEvent.undo(AbstractDocument.java:2806)
 at javax.swing.undo.CompoundEdit.undo(CompoundEdit.java:63)
 at javax.swing.undo.UndoManager.undoTo(UndoManager.java:335)
 at javax.swing.undo.UndoManager.undo(UndoManager.java:413)
 at org.nlogo.editor.UndoManager.undo(UndoManager.java:63)
 at org.nlogo.editor.UndoManager$UndoAction.actionPerformed(UndoManager.java:139)
 at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)
 at javax.swing.JComponent.processKeyBinding(JComponent.java:2879)
 at javax.swing.JComponent.processKeyBindings(JComponent.java:2926)
 at javax.swing.JComponent.processKeyEvent(JComponent.java:2842)
 at java.awt.Component.processEvent(Component.java:6304)
 at java.awt.Container.processEvent(Container.java:2234)
 at java.awt.Component.dispatchEventImpl(Component.java:4883)
 at java.awt.Container.dispatchEventImpl(Container.java:2292)
 at java.awt.Component.dispatchEvent(Component.java:4705)
 at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
 at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
 at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
 at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
 at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
 at java.awt.Component.dispatchEventImpl(Component.java:4754)
 at java.awt.Container.dispatchEventImpl(Container.java:2292)
 at java.awt.Window.dispatchEventImpl(Window.java:2739)
 at java.awt.Component.dispatchEvent(Component.java:4705)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
 at java.awt.EventQueue.access$400(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:697)
 at java.awt.EventQueue$3.run(EventQueue.java:691)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
 at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
 at java.awt.EventQueue$4.run(EventQueue.java:719)
 at java.awt.EventQueue$4.run(EventQueue.java:717)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: javax.swing.text.BadLocationException: Length must be positive
 at javax.swing.text.AbstractDocument.getText(AbstractDocument.java:768)
 at org.nlogo.editor.EditorArea.getLineText(EditorArea.java:214)
 at org.nlogo.editor.BracketMatcher.caretUpdate(BracketMatcher.java:70)
 ... 52 more

NetLogo 5.0.5
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) Server VM 1.8.0_05 (Oracle Corporation; 1.8.0_05-b13)
operating system: Linux 3.13.0-24-generic (i386 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: ChrestTileworld

06:56:29.938 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
06:56:29.938 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
06:56:29.737 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
06:56:29.737 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
06:56:29.537 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
06:56:29.537 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
06:56:29.337 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
06:56:29.337 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
06:56:29.136 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
06:56:29.136 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

![image](https://cloud.githubusercontent.com/assets/2189207/2988521/b4482120-dc5a-11e3-8e06-705d02ae1c00.png)

**Comment by mrerrormessage** [comment]
The NetLogo codetab editor has been replaced with a new backend (based on RSytaxTextArea) so it should no longer display this error. We still use `BracketMatcher` in the various widget (and other auxiliary) code editors, so this bug may still occur there.
