### ISSUE TITLE
Recurrent Bug: “unknown widget type: org.nlogo.widget.SwitchWidget”

### ISSUE THREAD

**Issue by pabolo19** [NetLogo/NetLogo#624]
This bug is recurrent.
Could anybody help me?

java.lang.IllegalStateException: unknown widget type: org.nlogo.widget.SwitchWidget[,0,0,163x33,invalid,layout=java.awt.FlowLayout,alignmentX=0.0,alignmentY=0.0,border=javax.swing.border.CompoundBorder@58df4ab2,flags=16777225,maximumSize=,minimumSize=,preferredSize=](Output_file?)
 at org.nlogo.window.NetLogoListenerManager.handle(NetLogoListenerManager.java:66)
 at org.nlogo.window.Events$InterfaceGlobalEvent.beHandledBy(Events.java:379)
 at org.nlogo.window.Event.doRaise(Event.java:198)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.widget.SwitchWidget.isOn_$eq(SwitchWidget.scala:46)
 at org.nlogo.widget.Switch$Channel$$anon$3.mousePressed(Switch.scala:123)
 at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:262)
 at java.awt.Component.processMouseEvent(Component.java:6411)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3275)
 at java.awt.Component.processEvent(Component.java:6179)
 at java.awt.Container.processEvent(Container.java:2084)
 at java.awt.Component.dispatchEventImpl(Component.java:4776)
 at java.awt.Container.dispatchEventImpl(Container.java:2142)
 at java.awt.Component.dispatchEvent(Component.java:4604)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4618)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4276)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4209)
 at java.awt.Container.dispatchEventImpl(Container.java:2128)
 at java.awt.Window.dispatchEventImpl(Window.java:2492)
 at java.awt.Component.dispatchEvent(Component.java:4604)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:717)
 at java.awt.EventQueue.access$400(EventQueue.java:82)
 at java.awt.EventQueue$2.run(EventQueue.java:676)
 at java.awt.EventQueue$2.run(EventQueue.java:674)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:690)
 at java.awt.EventQueue$3.run(EventQueue.java:688)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:687)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

NetLogo 5.0.5
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.6.0_65 (Apple Inc.; 1.6.0_65-b14-462-11M4609)
operating system: Mac OS X 10.9.3 (x86_64 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: INDISIM-PARACOCCUS (V5)c5a

11:59:10.747 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:59:10.747 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:59:10.747 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:59:10.747 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:59:10.747 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:59:10.747 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:59:10.747 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:59:10.747 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:59:10.747 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:59:10.747 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0

**Comment by Idloj** [comment]
Does the bug still exist on 5.2?

**Comment by SethTisue** [comment]
I'm going to close this since we don't have enough information to even be sure there is a bug or whether it exists in any NetLogo version that is still maintained.
