### ISSUE TITLE
ConcurrentModificationException when running `with` block having side effects on agentset

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/NetLogo#646]
```
to setup
  ca
  crt 10
  show turtles with [ has-hatched? ]
end

to-report has-hatched?
  hatch 1
  report true
end
```

When running `setup`:

```
error (ConcurrentModificationException)
 while observer running SHOW
  called by procedure SETUP
  called by Command Center

NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.util.ConcurrentModificationException
 at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1100)
 at java.util.TreeMap$ValueIterator.next(TreeMap.java:1145)
 at org.nlogo.agent.TreeAgentSet$Iterator.next(TreeAgentSet.java:209)
 at org.nlogo.prim._asm_proceduresetup_with_1.report(:1)
 at org.nlogo.prim.etc._show.perform(_show.scala:13)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:91)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.java:82)
 at org.nlogo.job.JobThread.org$nlogo$job$JobThread$$runPrimaryJobs(JobThread.scala:143)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply$mcV$sp(JobThread.scala:78)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at scala.util.control.Exception$Catch.apply(Exception.scala:88)
 at org.nlogo.util.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:75)

NetLogo 5.0.5
main: org.nlogo.app.AppFrame
thread: JobThread
Java HotSpot(TM) 64-Bit Server VM 1.6.0_45 (Sun Microsystems Inc.; 1.6.0_45-b06)
operating system: Linux 3.13.0-35-generic (amd64 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: exception

12:30:49.903 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
12:30:49.902 RuntimeErrorEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
12:30:49.900 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
12:30:49.900 TickStateChangeEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
12:30:49.900 OutputEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
12:30:49.894 AddJobEvent (org.nlogo.app.CommandLine) AWT-EventQueue-0
12:30:49.894 OutputEvent (org.nlogo.app.CommandLine) AWT-EventQueue-0
12:30:49.894 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
12:30:49.886 CompileMoreSourceEvent (org.nlogo.app.CommandLine) AWT-EventQueue-0
12:30:49.741 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
```

Tested with 5.0.5 and 5.1.

**Comment by ERSUCC** [comment]
Some clarifications about the fix I just pushed: Yes, this does potentially decrease performance, although not by an appreciable amount for a typical number of turtles. I did some cursory benchmarks and didn't see a significant slowdown, and it still seems to perform better than `ArrayAgentSet` for the same `with` block. But the more important consideration is that when using `with` on an `ArrayAgentSet`, no exception occurs. For example:

```
to setup
  clear-all
  create-turtles 10
  show (turtle-set turtles) with [ hatched ]
end

to-report hatched
  hatch 1
  report true
end
```

This example runs just fine and prints "(agentset, 10 turtles)" to the Command Center. There's no reason why users should expect different behavior with `turtles` than with other agentsets, and it certainly isn't logical to change the behavior for the case that already works, so it seems that the best course of action for now is to match the behavior of `TreeAgentSet` to that of `ArrayAgentSet`.

EDIT: I realized that my example above doesn't really prove much, because `turtle-set turtles` doesn't represent the same agentset as `turtles`. So perhaps a better example is the following:

```
globals [ ts ]

to setup
  clear-all
  create-turtles 10
  set ts turtle-set turtles
  show ts with [ hatched ]
end

to-report hatched
  hatch 1 [ set ts (turtle-set ts self) ]
  report true
end
```

This also runs with no exception and prints "(agentset, 10 turtles)" to the Command Center. From the user's perspective, they have an agentset called `ts`, and during the execution of the `with` block, they add turtles to it and everything is fine. Obviously the reason this works is because `turtle-set` creates a new agentset instance each time and the `with` block is still using the original instance. But all the user really knows is that they modify the variable during the `with` block and it doesn't see the updates until after the `with` block returns. So it seems reasonable to expect similar behavior with the `turtles` agentset.
