### ISSUE TITLE
Long very narrow worlds exceed VM limit

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/NetLogo#686]
I got the following exception for a world 36500x1 while 365x100 was fine. Patch size 1.

java.lang.reflect.InvocationTargetException
 at java.awt.EventQueue.invokeAndWait(EventQueue.java:1086)
 at java.awt.EventQueue.invokeAndWait(EventQueue.java:1063)
 at org.nlogo.awt.EventQueue$.invokeAndWait(EventQueue.scala:19)
 at org.nlogo.swing.ModalProgressTask$Boss.run(ModalProgressTask.scala:61)
Caused by: java.lang.OutOfMemoryError: Requested array size exceeds VM limit
 at scala.collection.mutable.ArrayBuilder$ofDouble.mkArray(ArrayBuilder.scala:498)
 at scala.collection.mutable.ArrayBuilder$ofDouble.resize(ArrayBuilder.scala:504)
 at scala.collection.mutable.ArrayBuilder$ofDouble.sizeHint(ArrayBuilder.scala:509)
 at scala.Array$.tabulate(Array.scala:300)
 at org.nlogo.agent.RootsTable.<init>(RootsTable.scala:10)
 at org.nlogo.agent.World.createPatches(World.java:697)
 at org.nlogo.window.WorldViewSettings2D$1.run(WorldViewSettings2D.java:76)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:199)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:672)
 at java.awt.EventQueue.access$400(EventQueue.java:81)
 at java.awt.EventQueue$2.run(EventQueue.java:633)
 at java.awt.EventQueue$2.run(EventQueue.java:631)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:642)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:178)
 at java.awt.Dialog$1.run(Dialog.java:1052)
 at java.awt.Dialog$3.run(Dialog.java:1104)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.awt.Dialog.show(Dialog.java:1102)
 at java.awt.Component.show(Component.java:1591)
 at java.awt.Component.setVisible(Component.java:1543)
 at java.awt.Window.setVisible(Window.java:843)
 at java.awt.Dialog.setVisible(Dialog.java:987)
 at org.nlogo.swing.ModalProgressTask$.apply(ModalProgressTask.scala:43)
 at org.nlogo.swing.ModalProgressTask.apply(ModalProgressTask.scala)
 at org.nlogo.window.WorldViewSettings2D.resizeWithProgress(WorldViewSettings2D.java:109)
 at org.nlogo.window.WorldViewSettings2D.editFinished(WorldViewSettings2D.java:34)
 at org.nlogo.properties.EditDialog$$anonfun$1.apply$mcV$sp(EditDialog.scala:51)
 at org.nlogo.swing.Implicits$$anon$5.actionPerformed(Implicits.scala:15)

NetLogo 5.1.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) Server VM 1.6.0_45 (Sun Microsystems Inc.; 1.6.0_45-b06)
operating system: Windows 7 6.1 (x86 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Untitled

11:35:53.632 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:35:53.609 RemoveAllJobsEvent (org.nlogo.window.ViewWidget) AWT-EventQueue-0
11:35:53.544 DirtyEvent (org.nlogo.app.InterfacePanel) AWT-EventQueue-0
11:35:53.543 WidgetEditedEvent (org.nlogo.window.ViewWidget) AWT-EventQueue-0
11:35:53.419 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:35:53.219 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:35:53.019 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:35:52.819 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:35:52.619 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:35:52.419 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

**Comment by frankduncan** [comment]
Indeed, the reason seems to be in the RootsTable code (https://github.com/NetLogo/NetLogo/blob/5.x/src/main/org/nlogo/agent/RootsTable.scala#L10), which makes sense since it causes an array allocation of over a billion elements (36500^2), whereas the other only does 140000 elements.

Though what roots table is and why we allocate it like this requires some history, of which I don't have.  Can @SethTisue illuminate?

My strong guess is that the code is working as designed, unless there's a different, deeper bug here.

**Comment by qiemem** [comment]
It looks like it handles finding a root outside its bound gracefully. Why not put a hard max on its size?

**Comment by SethTisue** [comment]
added a comment (over in the NetLogo-Headless repo) explaining the purpose of this code. https://github.com/NetLogo/NetLogo-Headless/commit/6663c1a42a72467e75df5e8d21b9d01aa26fecb4

**Comment by qiemem** [comment]
Makes sense.

Seems like degrading performance would be better than OOMing at the extremes though. As I said before, we should just be able to set a max on the size just under the max array size. That way, performance will stay just as good as it is now (even on big worlds), it just won't die. Patch distance checks at huge distances won't be as fast as at reasonable distances, but considering you can't even create worlds of those dimensions right now, that seems pretty okay.

I am a little confused about why we're hitting the max array length though (we're hitting the max array length, not running out heap space or anything). The array should be 1,332,250,001, but I thought the max array length is `Integer.MAX_VALUE`, or 2,147,483,647. Looking at the scala source for `tabulate`, it doesn't look like it's padding at all. At a scala console, I was able to create the table just fine... Once I set my heap big enough that is. Nonetheless, setting a max on the table seems to only make things better.
