### ISSUE TITLE
Cannot load 3D view

### ISSUE THREAD

**Issue by bwepngong** [NetLogo/NetLogo#691]
I rescently installed NetLogo on my 32-bit kali. I always get the following error when i try to load a model.
NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.lang.reflect.InvocationTargetException
 at java.awt.EventQueue.invokeAndWait(EventQueue.java:1076)
 at java.awt.EventQueue.invokeAndWait(EventQueue.java:1053)
 at org.nlogo.awt.EventQueue$.invokeAndWait(EventQueue.scala:19)
 at org.nlogo.swing.ModalProgressTask$Boss.run(ModalProgressTask.scala:61)
Caused by: java.io.FileNotFoundException: models/index.txt (No such file or directory)
 at java.io.FileInputStream.open(Native Method)
 at java.io.FileInputStream.<init>(FileInputStream.java:137)
 at scala.io.Source$.fromFile(Source.scala:91)
 at scala.io.Source$.fromFile(Source.scala:76)
 at scala.io.Source$.fromFile(Source.scala:54)
 at org.nlogo.app.ModelsLibraryIndexReader$.readInfoMap(ModelsLibraryIndexReader.scala:14)
 at org.nlogo.app.ModelsLibraryIndexReader.readInfoMap(ModelsLibraryIndexReader.scala)
 at org.nlogo.app.ModelsLibraryDialog$5.run(ModelsLibraryDialog.java:128)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:216)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:673)
 at java.awt.EventQueue.access$300(EventQueue.java:96)
 at java.awt.EventQueue$2.run(EventQueue.java:634)
 at java.awt.EventQueue$2.run(EventQueue.java:632)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:108)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:643)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:275)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:200)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:194)
 at java.awt.Dialog$1.run(Dialog.java:1079)
 at java.awt.Dialog$3.run(Dialog.java:1133)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.awt.Dialog.show(Dialog.java:1131)
 at java.awt.Component.show(Component.java:1571)
 at java.awt.Component.setVisible(Component.java:1523)
 at java.awt.Window.setVisible(Window.java:951)
 at java.awt.Dialog.setVisible(Dialog.java:1013)
 at org.nlogo.swing.ModalProgressTask$.apply(ModalProgressTask.scala:43)
 at org.nlogo.swing.ModalProgressTask.apply(ModalProgressTask.scala)
 at org.nlogo.app.ModelsLibraryDialog.<init>(ModelsLibraryDialog.java:123)
 at org.nlogo.app.ModelsLibraryDialog.open(ModelsLibraryDialog.java:28)
 at org.nlogo.app.FileMenu$ModelsLibraryAction.action(FileMenu.java:165)
 at org.nlogo.app.FileMenu$FileMenuAction.actionPerformed(FileMenu.java:95)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2012)
 at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2335)
 at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:404)
 at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
 at javax.swing.AbstractButton.doClick(AbstractButton.java:374)
 at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:829)
 at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:873)
 at java.awt.Component.processMouseEvent(Component.java:6288)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3267)
 at java.awt.Component.processEvent(Component.java:6053)
 at java.awt.Container.processEvent(Container.java:2045)
 at java.awt.Component.dispatchEventImpl(Component.java:4649)
 at java.awt.Container.dispatchEventImpl(Container.java:2103)
 at java.awt.Component.dispatchEvent(Component.java:4475)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4633)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4297)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4227)
 at java.awt.Container.dispatchEventImpl(Container.java:2089)
 at java.awt.Window.dispatchEventImpl(Window.java:2587)
 at java.awt.Component.dispatchEvent(Component.java:4475)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:675)
 at java.awt.EventQueue.access$300(EventQueue.java:96)
 at java.awt.EventQueue$2.run(EventQueue.java:634)
 at java.awt.EventQueue$2.run(EventQueue.java:632)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:108)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:119)
 at java.awt.EventQueue$3.run(EventQueue.java:648)
 at java.awt.EventQueue$3.run(EventQueue.java:646)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:108)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:645)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:275)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:200)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:190)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:185)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:177)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:138)

NetLogo 5.1.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-2
OpenJDK Client VM 1.6.0_27 (Sun Microsystems Inc.; 1.6.0_27-b27)
operating system: Linux 3.12-kali1-686-pae (i386 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Untitled

02:55:39.829 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-2
02:55:38.973 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-2
02:55:38.773 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-2
02:55:38.570 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-2
02:55:38.370 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-2
02:55:38.169 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-2
02:55:37.969 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-2
02:55:37.769 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-2
02:55:37.568 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-2
02:55:37.368 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-2

**Comment by frankduncan** [comment]
Did you build from source or download NetLogo?

**Comment by SethTisue** [comment]
Are you starting NetLogo using the provided shell script `netlogo.sh`? This error message is typical when someone tries some other method.

And/or, try a newer OpenJDK, and/or, use Oracle Java.

**Comment by bwepngong** [comment]
Thanks very much!
I downloaded netlogo and am using jre8
I was using a .desktop file to start the application.
Using the netlogo.sh all is well now
Thanks for your help

On 1/22/15, Seth Tisue <notifications@github.com> wrote:
> Are you starting NetLogo using the provided shell script `netlogo.sh`? This
> error message is typical when someone tries some other method.
>
> And/or, try a newer OpenJDK, and/or, use Oracle Java.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/NetLogo/NetLogo/issues/691#issuecomment-71110995


-- 
Wepngong Ngeh Benaiah

**Comment by SethTisue** [comment]
yay!
