### ISSUE TITLE
JPG Error

### ISSUE THREAD

**Issue by li-norman-1997** [NetLogo/NetLogo#694]
Hello.

I'm a TA (Teacher's Assistant) that assists other students with Computer Science. While helping them debug and test their final projects, I frequently encounter the error below (example).

An example of said final project is provided below with permission of its author:
Git Clone Links:
```
HTTPS: https://github.com/Phionx/SmashBashNetlogo.git
SSH: git@github.com:Phionx/SmashBashNetlogo.git
Subversion: https://github.com/Phionx/SmashBashNetlogo
```

(Not sure if this matters, but I generally receive Netlogo files and their respective auxiliary files such as images from Windows and Mac OS users. I run them on an Ubuntu 14.10 box with the latest version of Netlogo. )

```
NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.lang.UnsatisfiedLinkError: com.sun.imageio.plugins.jpeg.JPEGImageReader.initReaderIDs(Ljava/lang/Class;Ljava/lang/Class;Ljava/lang/Class;)V
 at com.sun.imageio.plugins.jpeg.JPEGImageReader.initReaderIDs(Native Method)
 at com.sun.imageio.plugins.jpeg.JPEGImageReader.<clinit>(JPEGImageReader.java:96)
 at com.sun.imageio.plugins.jpeg.JPEGImageReaderSpi.createReaderInstance(JPEGImageReaderSpi.java:85)
 at javax.imageio.spi.ImageReaderSpi.createReaderInstance(ImageReaderSpi.java:320)
 at javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:529)
 at javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:513)
 at javax.imageio.ImageIO.read(ImageIO.java:1443)
 at javax.imageio.ImageIO.read(ImageIO.java:1352)
 at org.nlogo.render.TrailDrawer.importDrawing(TrailDrawer.java:162)
 at org.nlogo.render.TrailDrawer.importDrawing(TrailDrawer.java:210)
 at org.nlogo.window.GUIWorkspace.importDrawing(GUIWorkspace.java:186)
 at org.nlogo.workspace.AbstractWorkspace$3.doImport(AbstractWorkspace.java:577)
 at org.nlogo.workspace.AbstractWorkspace.doImport(AbstractWorkspace.java:613)
 at org.nlogo.workspace.AbstractWorkspace.importDrawing(AbstractWorkspace.java:571)
 at org.nlogo.prim.etc._importdrawing.perform(_importdrawing.java:26)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:91)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.java:82)
 at org.nlogo.job.JobThread.org$nlogo$job$JobThread$$runPrimaryJobs(JobThread.scala:143)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply$mcV$sp(JobThread.scala:78)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at scala.util.control.Exception$Catch.apply(Exception.scala:88)
 at org.nlogo.util.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:75)

NetLogo 5.1.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
OpenJDK 64-Bit Server VM 1.8.0_40-internal (Oracle Corporation; 1.8.0_40-internal-b09)
operating system: Linux 3.16.0-29-generic (amd64 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Final_Project_Final_Version

03:06:58.954 AddJobEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
03:06:58.873 InputBoxLoseFocusEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
03:06:58.767 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
03:06:58.567 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
03:06:58.366 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
03:06:58.166 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
03:06:57.965 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
03:06:57.765 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
03:06:57.564 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
03:06:57.557 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
```

**Comment by SethTisue** [comment]
Maybe an OpenJDK vs Oracle Java thing?

**Comment by SethTisue** [comment]
closed because...?

**Comment by li-norman-1997** [comment]
@SethTisue I updated OpenJDK and Netlogo and this issue no longer occurs.

**Comment by SethTisue** [comment]
cool, thanks for letting us know

**Comment by li-norman-1997** [comment]
No problem! :)

Sorry for the sparse response before. First time opening and closing an issue. :)
