### ISSUE TITLE
Extensions 

### ISSUE THREAD

**Issue by mattsap** [NetLogo/NetLogo#714]
I was following the extensions tutorial. I created a jar (example.jar) and put it in the Netlogo 5.0/extensions/example directory.

I got the following error:
NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.lang.UnsupportedClassVersionError: SampleExtension : Unsupported major.minor version 51.0
 at java.lang.ClassLoader.defineClass1(Native Method)
 at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
 at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
 at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
 at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
 at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
 at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
 at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:627)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
 at org.nlogo.workspace.ExtensionManager.getClassManager(ExtensionManager.java:406)
 at org.nlogo.workspace.ExtensionManager.importExtension(ExtensionManager.java:173)
 at org.nlogo.compiler.StructureParser.parseImport(StructureParser.scala:459)
 at org.nlogo.compiler.StructureParser.parse(StructureParser.scala:196)
 at org.nlogo.compiler.CompilerMain$.compile(CompilerMain.scala:25)
 at org.nlogo.compiler.Compiler$.compileProgram(Compiler.scala:28)
 at org.nlogo.window.CompilerManager.compileProcedures(CompilerManager.java:107)
 at org.nlogo.window.CompilerManager.compileAll(CompilerManager.java:87)
 at org.nlogo.window.CompilerManager.handle(CompilerManager.java:309)
 at org.nlogo.window.Events$CompileAllEvent.beHandledBy(Events.java:175)
 at org.nlogo.window.Event.doRaise(Event.java:198)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.app.ProceduresTab$CompileAction.actionPerformed(ProceduresTab.scala:60)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2028)
 at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2351)
 at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:387)
 at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:242)
 at ch.randelshofer.quaqua.QuaquaButtonListener.mouseReleased(QuaquaButtonListener.java:110)
 at java.awt.Component.processMouseEvent(Component.java:6414)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3275)
 at java.awt.Component.processEvent(Component.java:6179)
 at java.awt.Container.processEvent(Container.java:2084)
 at java.awt.Component.dispatchEventImpl(Component.java:4776)
 at java.awt.Container.dispatchEventImpl(Container.java:2142)
 at java.awt.Component.dispatchEvent(Component.java:4604)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4618)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4279)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4209)
 at java.awt.Container.dispatchEventImpl(Container.java:2128)
 at java.awt.Window.dispatchEventImpl(Window.java:2492)
 at java.awt.Component.dispatchEvent(Component.java:4604)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:717)
 at java.awt.EventQueue.access$400(EventQueue.java:82)
 at java.awt.EventQueue$2.run(EventQueue.java:676)
 at java.awt.EventQueue$2.run(EventQueue.java:674)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:690)
 at java.awt.EventQueue$3.run(EventQueue.java:688)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:687)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

NetLogo 5.1.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.6.0_65 (Apple Inc.; 1.6.0_65-b14-462-11M4609)
operating system: Mac OS X 10.9.5 (x86_64 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Untitled

04:25:12.801 RemoveAllJobsEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
04:25:12.801 CompileAllEvent (org.nlogo.app.MainProceduresTab) AWT-EventQueue-0
04:25:12.784 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:25:12.582 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:25:12.382 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:25:12.180 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:25:11.980 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:25:11.778 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:25:11.686 DirtyEvent (org.nlogo.app.MainProceduresTab) AWT-EventQueue-0
04:25:11.578 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

**Comment by SethTisue** [comment]
this is covered at https://github.com/netlogo/netlogo/wiki/extensions-api
