### ISSUE TITLE
Loading old model should not throw a NumberFormatException

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/NetLogo#715]
Loading 

http://modelingcommons.org/browse/one_model/2387#model_tabs_browse_info

causes the following exception at load time:

NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.lang.reflect.InvocationTargetException
 at java.awt.EventQueue.invokeAndWait(EventQueue.java:1086)
 at java.awt.EventQueue.invokeAndWait(EventQueue.java:1063)
 at org.nlogo.awt.EventQueue$.invokeAndWait(EventQueue.scala:19)
 at org.nlogo.swing.ModalProgressTask$Boss.run(ModalProgressTask.scala:61)
Caused by: java.lang.NumberFormatException: For input string: "CC-WINDOW"
 at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
 at java.lang.Integer.parseInt(Integer.java:449)
 at java.lang.Integer.parseInt(Integer.java:499)
 at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:231)
 at scala.collection.immutable.StringOps.toInt(StringOps.scala:31)
 at org.nlogo.workspace.WorldLoader.load(WorldLoader.scala:28)
 at org.nlogo.workspace.AbstractWorkspace.loadWorld(AbstractWorkspace.java:696)
 at org.nlogo.window.WorldViewSettings.load(WorldViewSettings.java:211)
 at org.nlogo.window.ViewWidget.load(ViewWidget.java:437)
 at org.nlogo.app.InterfacePanel.loadWidget(InterfacePanel.java:267)
 at org.nlogo.app.InterfacePanel.loadWidget(InterfacePanel.java:231)
 at org.nlogo.app.WidgetPanel.loadWidgets(WidgetPanel.java:716)
 at org.nlogo.app.InterfacePanel.handle(InterfacePanel.java:375)
 at org.nlogo.window.Events$LoadSectionEvent.beHandledBy(Events.java:471)
 at org.nlogo.window.Event.doRaise(Event.java:198)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.window.ModelLoader$Loader$$anonfun$loadHelper$1.apply(ModelLoader.scala:101)
 at org.nlogo.window.ModelLoader$Loader$$anonfun$loadHelper$1.apply(ModelLoader.scala:101)
 at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
 at scala.collection.immutable.List.foreach(List.scala:76)
 at org.nlogo.window.ModelLoader$Loader.loadHelper(ModelLoader.scala:101)
 at org.nlogo.window.ModelLoader$.load(ModelLoader.scala:16)
 at org.nlogo.window.ModelLoader.load(ModelLoader.scala)
 at org.nlogo.app.FileMenu$1.run(FileMenu.java:804)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:199)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:672)
 at java.awt.EventQueue.access$400(EventQueue.java:81)
 at java.awt.EventQueue$2.run(EventQueue.java:633)
 at java.awt.EventQueue$2.run(EventQueue.java:631)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:642)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:178)
 at java.awt.Dialog$1.run(Dialog.java:1052)
 at java.awt.Dialog$3.run(Dialog.java:1104)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.awt.Dialog.show(Dialog.java:1102)
 at java.awt.Component.show(Component.java:1591)
 at java.awt.Component.setVisible(Component.java:1543)
 at java.awt.Window.setVisible(Window.java:843)
 at java.awt.Dialog.setVisible(Dialog.java:987)
 at org.nlogo.swing.ModalProgressTask$.apply(ModalProgressTask.scala:43)
 at org.nlogo.swing.ModalProgressTask.apply(ModalProgressTask.scala)
 at org.nlogo.app.FileMenu.openFromMap(FileMenu.java:814)
 at org.nlogo.app.FileMenu.openFromSource(FileMenu.java:786)
 at org.nlogo.app.FileMenu.openFromPath(FileMenu.java:740)
 at org.nlogo.app.App$$anonfun$open$1.apply$mcV$sp(App.scala:803)
 at org.nlogo.app.App$$anonfun$open$1.apply(App.scala:803)
 at org.nlogo.app.App$$anonfun$open$1.apply(App.scala:803)
 at org.nlogo.app.App.dispatchThreadOrBust(App.scala:1021)
 at org.nlogo.app.App.open(App.scala:803)
 at org.nlogo.app.App.loadDefaultModel(App.scala:504)
 at org.nlogo.app.App.org$nlogo$app$App$$finishStartup(App.scala:443)
 at org.nlogo.app.App$$anonfun$main$1.apply$mcV$sp(App.scala:150)
 at org.nlogo.swing.Implicits$$anon$17.run(Implicits.scala:12)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:199)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:672)
 at java.awt.EventQueue.access$400(EventQueue.java:81)
 at java.awt.EventQueue$2.run(EventQueue.java:633)
 at java.awt.EventQueue$2.run(EventQueue.java:631)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:642)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

NetLogo 5.2-RC3
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) Server VM 1.6.0_45 (Sun Microsystems Inc.; 1.6.0_45-b06)
operating system: Windows 7 6.1 (x86 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Transportation

02:21:43.292 LoadSectionEvent (org.nlogo.window.ModelLoader$Loader (java.lang.Object)) AWT-EventQueue-0
02:21:43.221 DirtyEvent (org.nlogo.app.InfoTab) AWT-EventQueue-0
02:21:43.219 DirtyEvent (org.nlogo.app.InfoTab) AWT-EventQueue-0
02:21:43.206 LoadSectionEvent (org.nlogo.window.ModelLoader$Loader (java.lang.Object)) AWT-EventQueue-0
02:21:43.206 RemoveAllJobsEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
02:21:43.206 CompileAllEvent (org.nlogo.app.MainProceduresTab) AWT-EventQueue-0
02:21:43.206 DirtyEvent (org.nlogo.app.MainProceduresTab) AWT-EventQueue-0
02:21:43.205 DirtyEvent (org.nlogo.app.MainProceduresTab) AWT-EventQueue-0
02:21:43.202 DirtyEvent (org.nlogo.app.MainProceduresTab) AWT-EventQueue-0
02:21:43.200 DirtyEvent (org.nlogo.app.MainProceduresTab) AWT-EventQueue-0

**Comment by frankduncan** [comment]
Ah, this model is so old that it defines widgets without spaces between them!  4.0-pre8, it looks like.  I'm going to keep this bug open since it is an issue for very old models, but the likelihood of this being fixed is pretty low with the current widget reading code acting like it does.

**Comment by SethTisue** [comment]
it may be necessary in some cases for users with *really, really* old models to upgrade them a version at a time, like take a 3.0 model and resave it in 4.1, then open it in 5.0 and resave, and so forth. it simply isn't practical to have enough test coverage on old-model-formats support to prevent this from happening at least some of the time.

**Comment by ToonTalk** [comment]
How difficult would it be to catch this kind of problem and give the user advice such as Seth's above?

**Comment by frankduncan** [comment]
Rather difficult.  We don't have a good handle on which version to which version would run into these problems.  We'd have to suss out what versions of models any given version of netlogo could successfully upgrade, then encode that.  I don't think it's worth the time and effort for the number of times users are going to run into this.

**Comment by SethTisue** [comment]
closing as extremely unlikely to ever be addressed
