### ISSUE TITLE
`user-one-of` with empty list of choices raises `IndexOutOfBoundsException`

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/NetLogo#731]
In 5.2RC3:

```
show user-one-of "message" []
```
Results in an exception when the user clicks OK.

(Maybe it should fail with a proper error message before the dialog is even showed to the user?)

Here is the exception:

```
error (IndexOutOfBoundsException)
 while observer running SHOW
  called by Command Center

NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.lang.IndexOutOfBoundsException: -1
 at scala.collection.immutable.Vector.checkRangeConvert(Vector.scala:140)
 at scala.collection.immutable.Vector.apply(Vector.scala:130)
 at org.nlogo.api.LogoList.get(LogoList.scala:29)
 at org.nlogo.prim.gui._useroneof.report(_useroneof.scala:34)
 at org.nlogo.prim.etc._show.perform(_show.scala:13)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:91)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.java:82)
 at org.nlogo.job.JobThread.org$nlogo$job$JobThread$$runPrimaryJobs(JobThread.scala:143)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply$mcV$sp(JobThread.scala:78)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at scala.util.control.Exception$Catch.apply(Exception.scala:88)
 at org.nlogo.util.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:75)

NetLogo 5.2-RC3
main: org.nlogo.app.AppFrame
thread: JobThread
Java HotSpot(TM) 64-Bit Server VM 1.6.0_45 (Sun Microsystems Inc.; 1.6.0_45-b06)
operating system: Linux 3.13.0-46-generic (amd64 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Arduino Example

07:21:09.771 RuntimeErrorEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
07:21:09.768 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
07:21:09.768 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
07:21:07.838 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
07:21:07.838 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
07:21:07.834 AddJobEvent (org.nlogo.app.CommandLine) AWT-EventQueue-0
07:21:07.833 OutputEvent (org.nlogo.app.CommandLine) AWT-EventQueue-0
07:21:07.832 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
07:21:07.825 CompileMoreSourceEvent (org.nlogo.app.CommandLine) AWT-EventQueue-0
07:21:07.645 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
```

**Comment by frankduncan** [comment]
Fail with proper message or be equivalent to hitting "halt"?

**Comment by nicolaspayette** [comment]
I'd rather have an explicit error message. I think that, in most models, calling `user-one-of` with an empty list will be indicative of a bug in the model (a bug which could be hard to track down if `user-one-of` just fails silently).

`one-of` also gives an error when called with an empty, so that would be consistent.

**Comment by SethTisue** [comment]
agree this should be a runtime error. I think it was just an oversight.
