### ISSUE TITLE
Calling NetLogo Dictionary from "Help" causes Internal Error

### ISSUE THREAD

**Issue by Rob2037** [NetLogo/NetLogo#758]
When I click on NetLogo Dictionary under the Help tab, I get an Internal Error.

The report is:

NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.lang.IllegalStateException: java.io.IOException: openURL not supported on this platform
 at org.nlogo.swing.BrowserLauncher.openURL(BrowserLauncher.java:29)
 at org.nlogo.swing.BrowserLauncher.openURL(BrowserLauncher.java:13)
 at org.nlogo.app.HelpMenu$$anonfun$launch$1.apply$mcV$sp(HelpMenu.scala:24)
 at org.nlogo.app.HelpMenu$$anon$1.actionPerformed(HelpMenu.scala:21)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
 at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
 at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
 at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
 at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
 at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:125)
 at java.awt.MenuItem.processActionEvent(MenuItem.java:669)
 at java.awt.MenuItem.processEvent(MenuItem.java:628)
 at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351)
 at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:754)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:702)
 at java.awt.EventQueue$3.run(EventQueue.java:696)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
 at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
 at java.awt.EventQueue$4.run(EventQueue.java:724)
 at java.awt.EventQueue$4.run(EventQueue.java:722)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.io.IOException: openURL not supported on this platform
 at net.roydesign.mac.MRJAdapter.openURL(MRJAdapter.java:748)
 at org.nlogo.swing.BrowserLauncher.openURL(BrowserLauncher.java:52)
 at org.nlogo.swing.BrowserLauncher.openURL(BrowserLauncher.java:21)
 ... 31 more

NetLogo 5.2.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_40 (Oracle Corporation; 1.8.0_40-b27)
operating system: Mac OS X 10.10.3 (x86_64 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Untitled

04:03:16.833 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:03:16.633 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:03:16.432 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:03:16.230 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:03:16.027 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:03:15.823 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:03:15.618 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:03:15.413 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:03:15.212 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:03:15.009 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

**Comment by SethTisue** [comment]
How are you launching NetLogo? Somehow you're getting Java 8 instead of Java 6. Normally NetLogo should start up under NetLogo 6 on OS X.

(Regardless, `openURL` should be fixed to work on Java 8.)

**Comment by Rob2037** [comment]
Seth

I think that I'm in a bind. I have Java 8 installed because RNetLogo, the
package that calls NetLogo from R, prefers Java 8. I have Java 6 installed
and Gephi recognises this (and will not work with Java 8). Can I force
NetLogo to use one Java, rather than another?

Rob

Rob Nicholls |  m +61 4 1264 6477 | e rob.mmc@gmail.com

**Comment by Rob2037** [comment]
Seth

Of course, there is no real problem as I can open the relevant URLs
manually!

Rob

Rob Nicholls |  m +61 4 1264 6477 | e rob.mmc@gmail.com

**Comment by SethTisue** [comment]
see #659 for discussion.

RNetLogo specifically, I can't speak to.

the goal is for NetLogo 6.0 to fully support Java 7 and Java 8, but no release date has been set.

**Comment by mrerrormessage** [comment]
5.3, releasing next week, will bundle Java 8. It should be possible to get it to use a shared java installation, but it will take a bit of doing. I'm closing this bug since it will be irrelevant in 5.3, but feel free to open a new one (or better, send a quick message to the netlogo-devel google group) if further assistance is needed getting RNetLogo to work with 5.3.
