### ISSUE TITLE
problems with gogoboard and netlogo

### ISSUE THREAD

**Issue by Shelibenmoshe** [NetLogo/NetLogo#772]
I m trying to connect my gogoboard with netlogo  not very  successfully
the gogo board respond to the gogomonitor
but not to the net logo model
 i install the drivers needed
my current version of netlogo is 5.1

**Comment by Shelibenmoshe** [comment]
this is the content of the message i get in netlogo:

NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path
 at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1738)
 at java.lang.Runtime.loadLibrary0(Runtime.java:823)
 at java.lang.System.loadLibrary(System.java:1028)
 at gnu.io.CommPortIdentifier.<clinit>(CommPortIdentifier.java:123)
 at org.nlogo.extensions.gogo.GoGoController.listPorts(GoGoController.java:135)
 at org.nlogo.extensions.gogo.GoGoController.availablePorts(GoGoController.java:123)
 at org.nlogo.extensions.gogo.GoGoExtension$GoGoListPorts.report(GoGoExtension.java:167)
 at org.nlogo.prim._externreport.report(_externreport.java:50)
 at org.nlogo.prim.etc._print.perform(_print.scala:13)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:91)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.java:82)
 at org.nlogo.job.JobThread.org$nlogo$job$JobThread$$runPrimaryJobs(JobThread.scala:143)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply$mcV$sp(JobThread.scala:78)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at scala.util.control.Exception$Catch.apply(Exception.scala:88)
 at org.nlogo.util.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:75)

NetLogo 5.1.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) Server VM 1.6.0_45 (Sun Microsystems Inc.; 1.6.0_45-b06)
operating system: Windows 7 6.1 (x86 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Untitled

01:43:41.352 AddJobEvent (org.nlogo.app.CommandLine) AWT-EventQueue-0
01:43:41.352 OutputEvent (org.nlogo.app.CommandLine) AWT-EventQueue-0
01:43:41.352 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
01:43:40.821 CompileMoreSourceEvent (org.nlogo.app.CommandLine) AWT-EventQueue-0
01:43:40.727 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
01:43:40.524 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
01:43:40.321 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
01:43:40.118 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
01:43:39.914 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
01:43:39.711 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

**Comment by nicolaspayette** [comment]
Have you tried with [NetLogo 5.2](https://ccl.northwestern.edu/netlogo/5.2/) instead of 5.1? I know that the GoGo extension has been updated in 5.2, so perhaps it would help...

**Comment by Shelibenmoshe** [comment]
hello, 

,I did and it solved the problem"apparently my board considered  "serialthank'ssheli
Date: Mon, 4 May 2015 15:10:03 -0700

**Comment by nicolaspayette** [comment]
Glad that it helped!
