### ISSUE TITLE
Attempting to load an extension with a dependency from a networked folder in Windows results in a noclassdef

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#776]
To reproduce:

1. Create a folder in a networked folder in Windows
2. Put some extension that has more than one jar there (the CSV extension works well since it's simple).
3. Create a model that uses the extension, and attempt to use a primitive that would rely on the extension's dependency (with csv, `csv:from-row "one,two"` will do the trick)

You'll get something like the following:

```
NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.lang.NoClassDefFoundError: org/apache/commons/csv/CSVFormat
 at org.nlogo.extensions.csv.CSVExtension.csvFormat(CSVExtension.scala:17)
 at org.nlogo.extensions.csv.CSVExtension$ParserPrimitive.report(CSVExtension.scala:36)
 at org.nlogo.extensions.csv.CSVExtension$ParserPrimitive.report(CSVExtension.scala:33)
 at org.nlogo.prim._externreport.report(_externreport.java:50)
 at org.nlogo.prim.etc._show.perform(_show.scala:13)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:91)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.java:82)
 at org.nlogo.job.JobThread.org$nlogo$job$JobThread$$runPrimaryJobs(JobThread.scala:143)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply$mcV$sp(JobThread.scala:78)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at scala.util.control.Exception$Catch.apply(Exception.scala:88)
 at org.nlogo.util.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:75)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.csv.CSVFormat
 at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
 at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:627)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
 ... 14 more

NetLogo 5.2.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) Server VM 1.6.0_45 (Sun Microsystems Inc.; 1.6.0_45-b06)
operating system: Windows 8 6.2 (x86 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Untitled

07:05:57.822 AddJobEvent (org.nlogo.app.CommandLine) AWT-EventQueue-0
07:05:57.822 OutputEvent (org.nlogo.app.CommandLine) AWT-EventQueue-0
07:05:57.822 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
07:05:57.712 CompileMoreSourceEvent (org.nlogo.app.CommandLine) AWT-EventQueue-0
07:05:57.634 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
07:05:57.431 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
07:05:57.228 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
07:05:57.025 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
07:05:56.822 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
07:05:56.619 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
```

**Comment by mrerrormessage** [comment]
Delightful! Apparently [java.io.File.isDirectory returns false on network paths on windows](http://stackoverflow.com/questions/22289304/java-file-isdirectory-returns-false-on-network-paths), which happens to be one of the checks we make in determining [which auxiliary jars to load](https://github.com/NetLogo/NetLogo/blob/5.x/src/main/org/nlogo/workspace/ExtensionManager.java#L649).

It isn't clear to me what the long-term solution should be here. As a workaround, extension developers could package their extensions into a single jar with all dependencies using the [Apache Maven Assembly Plugin](http://maven.apache.org/plugins/maven-assembly-plugin/), the [sbt-assembly plugin](https://github.com/sbt/sbt-assembly), or [a clever jar task in Apache Ant](http://www.mkyong.com/ant/ant-create-a-fat-jar-file/).

**Comment by SethTisue** [comment]
sad trombone

**Comment by mrerrormessage** [comment]
I can't find any record of this bug in the Java bug database, which makes me think that there is *probably* some way to get around this limitation, possibly with `getCanonicalFile` or `java.nio.<something>`. Someone would just have to play around on a Windows machine until they figured it out.

**Comment by ERSUCC** [comment]
This issue would be accidentally resolved by commit [55e5b1b](https://github.com/NetLogo/NetLogo/commit/55e5b1b6b4d03b2680c502e7871790f43191e54e). Not sure if this issue is still reproducible, so if that commit gets abandoned, this could still be a problem.
