### ISSUE TITLE
running "PD Basic Evolutionary" model on default settings without clicking on "setup" results in an error

### ISSUE THREAD

**Issue by matkoniecz** [NetLogo/NetLogo#785]
```
COUNT expected a true/false value from (patch 3 -12), but got 0 instead.
error while patch 3 -13 running COUNT
  called by procedure INTERACT
  called by procedure GO
  called by Button 'go'

org.nlogo.nvm.EngineException: COUNT expected a true/false value from (patch 3 -12), but got 0 instead.
 at org.nlogo.prim._asm_procedureinteract_setprocedurevariable_0.perform(:2)
 at org.nlogo.nvm.Context.runExclusive(Context.java:119)
 at org.nlogo.nvm.ExclusiveJob.run(ExclusiveJob.java:57)
 at org.nlogo.nvm.Context.runExclusiveJob(Context.java:162)
 at org.nlogo.prim._asm_procedurego_ask_0.perform(:1)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:91)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.java:82)
 at org.nlogo.job.JobThread.org$nlogo$job$JobThread$$runPrimaryJobs(JobThread.scala:143)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply$mcV$sp(JobThread.scala:78)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at scala.util.control.Exception$Catch.apply(Exception.scala:88)
 at org.nlogo.util.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:75)

NetLogo 5.2.0
main: org.nlogo.app.AppFrame
thread: JobThread
Java HotSpot(TM) Server VM 1.8.0_45 (Oracle Corporation; 1.8.0_45-b14)
operating system: Linux 3.13.0-53-generic (i386 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: PD Basic Evolutionary

05:00:19.626 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
05:00:19.623 RuntimeErrorEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
05:00:19.590 AddJobEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
05:00:19.567 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:00:19.565 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:00:19.565 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
05:00:19.494 InputBoxLoseFocusEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
05:00:19.365 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:00:19.364 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
05:00:19.364 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
```

I am using NetLogo 5.2 on Lubuntu 14.04.

Probably the proper solution is to either run at the beginning "Setup" without interaction from user or at least show more useful error message.

**Comment by nicolaspayette** [comment]
Thanks for reporting! This is a case of needing to disable the GO button until ticks start. I'll fix it.
