### ISSUE TITLE
On Ubuntu 14.04 LTS Netlogo does not display the GUI correctly when using two monitors

### ISSUE THREAD

**Issue by octavio-orozco2** [NetLogo/NetLogo#791]
Hi,

On Ubuntu 14.04 LTS, Netlogo does not display the GUI correctly when using two monitors. If you physically disconnect one of them, then the GUI is displayed correctly, however the "Internal error" included a the end, appears. Although this internal error is thrown by AppFrame on awt, it also seems related to a similar issue with swing's JFrame, which makes it require to be centered on the display:  "setLocationByPlatform(true)". Hopefully this will give you a cue to solve this issue.

The same behavior is observable trying to load an existing "prueba" (simple test with a button, which does nothing, in the GUI) netlogo model.

Kind Regards,
Octavio.

************************
"Internal error":
************************

NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.lang.ClassCastException: sun.awt.image.BufImgSurfaceData cannot be cast to sun.java2d.xr.XRSurfaceData
 at sun.java2d.xr.XRPMBlitLoops.cacheToTmpSurface(XRPMBlitLoops.java:145)
 at sun.java2d.xr.XrSwToPMBlit.Blit(XRPMBlitLoops.java:353)
 at sun.java2d.SurfaceDataProxy.updateSurfaceData(SurfaceDataProxy.java:498)
 at sun.java2d.SurfaceDataProxy.replaceData(SurfaceDataProxy.java:455)
 at sun.java2d.SurfaceData.getSourceSurfaceData(SurfaceData.java:233)
 at sun.java2d.pipe.DrawImage.renderImageCopy(DrawImage.java:574)
 at sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:67)
 at sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:1022)
 at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3318)
 at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3296)
 at org.nlogo.window.View.paintComponent(View.java:243)
 at javax.swing.JComponent.paint(JComponent.java:1053)
 at org.nlogo.window.View.paint(View.java:214)
 at javax.swing.JComponent.paintChildren(JComponent.java:886)
 at javax.swing.JComponent.paint(JComponent.java:1062)
 at javax.swing.JComponent.paintChildren(JComponent.java:886)
 at javax.swing.JComponent.paint(JComponent.java:1062)
 at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
 at javax.swing.JComponent.paintChildren(JComponent.java:886)
 at javax.swing.JComponent.paint(JComponent.java:1062)
 at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
 at javax.swing.JComponent.paintChildren(JComponent.java:886)
 at javax.swing.JComponent.paint(JComponent.java:1062)
 at javax.swing.JViewport.paint(JViewport.java:728)
 at javax.swing.JComponent.paintChildren(JComponent.java:886)
 at javax.swing.JComponent.paint(JComponent.java:1062)
 at javax.swing.JComponent.paintChildren(JComponent.java:886)
 at javax.swing.JSplitPane.paintChildren(JSplitPane.java:1047)
 at javax.swing.JComponent.paint(JComponent.java:1062)
 at javax.swing.JComponent.paintChildren(JComponent.java:886)
 at javax.swing.JComponent.paint(JComponent.java:1062)
 at javax.swing.JComponent.paintChildren(JComponent.java:886)
 at javax.swing.JComponent.paint(JComponent.java:1062)
 at javax.swing.JComponent.paintChildren(JComponent.java:886)
 at javax.swing.JComponent.paint(JComponent.java:1062)
 at javax.swing.JComponent.paintChildren(JComponent.java:886)
 at javax.swing.JComponent.paint(JComponent.java:1062)
 at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
 at javax.swing.JComponent.paintChildren(JComponent.java:886)
 at javax.swing.JComponent.paint(JComponent.java:1062)
 at javax.swing.JComponent.paintToOffscreen(JComponent.java:5223)
 at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:290)
 at javax.swing.RepaintManager.paint(RepaintManager.java:1265)
 at javax.swing.JComponent._paintImmediately(JComponent.java:5171)
 at javax.swing.JComponent.paintImmediately(JComponent.java:4982)
 at javax.swing.RepaintManager$4.run(RepaintManager.java:847)
 at javax.swing.RepaintManager$4.run(RepaintManager.java:807)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
 at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:807)
 at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:782)
 at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:731)
 at javax.swing.RepaintManager.access$1300(RepaintManager.java:64)
 at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1720)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
 at java.awt.EventQueue.access$400(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:697)
 at java.awt.EventQueue$3.run(EventQueue.java:691)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

NetLogo 5.2.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_20 (Oracle Corporation; 1.8.0_20-b26)
operating system: Linux 3.13.0-34-generic (amd64 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: prueba

10:57:45.985 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:57:45.784 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:57:45.584 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:57:45.384 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:57:45.183 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:57:44.983 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:57:44.783 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:57:44.582 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:57:44.382 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:57:44.181 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

**Comment by SethTisue** [comment]
this appears to be a bug in the Java Virtual Machine itself: https://bugs.openjdk.java.net/browse/JDK-7172749

**Comment by octavio-orozco2** [comment]
That's right Seth. Fortunately i found as a workaround: First use the
laptop to display the netlogo gui, then move the gui to the larger display.
That's how i am using netlogo 5.2 while the bug is addressed.
Thank you for the feedback.

Kind regards,
Octavio.


2015-06-09 17:33 GMT-05:00 Seth Tisue <notifications@github.com>:

**Comment by SethTisue** [comment]
glad to hear you found a workaround. having it recorded here may help others.

**Comment by mrerrormessage** [comment]
The original bug posted here was listed fixed in the openjdk tracker, but we have another user reporting it and we'll need the fix to be in for [JDK-8170986](https://bugs.openjdk.java.net/browse/JDK-8170986) before we declare this fixed. Note that this appears to be fixed in JDK 9, so upgrading to Java 9 would probably also fix this problem.
