### ISSUE TITLE
uncaught .ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by alan-isaac** [NetLogo/NetLogo#810]
This happened when a power outage shut down the second monitor connected to my laptop.

java.lang.ArrayIndexOutOfBoundsException: 1
 at sun.awt.Win32GraphicsEnvironment.getDefaultScreenDevice(Win32GraphicsEnvironment.java:86)
 at sun.awt.windows.WWindowPeer.updateGC(WWindowPeer.java:384)
 at sun.awt.windows.WWindowPeer.displayChanged(WWindowPeer.java:413)
 at sun.awt.SunDisplayChanger.notifyListeners(SunDisplayChanger.java:102)
 at sun.awt.Win32GraphicsDevice.displayChanged(Win32GraphicsDevice.java:471)
 at sun.java2d.d3d.D3DGraphicsDevice.displayChanged(D3DGraphicsDevice.java:467)
 at sun.awt.Win32GraphicsEnvironment.displayChanged(Win32GraphicsEnvironment.java:159)
 at sun.awt.windows.WToolkit$3.run(WToolkit.java:737)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:672)
 at java.awt.EventQueue.access$400(EventQueue.java:81)
 at java.awt.EventQueue$2.run(EventQueue.java:633)
 at java.awt.EventQueue$2.run(EventQueue.java:631)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:642)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

NetLogo 5.2.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) Server VM 1.6.0_45 (Sun Microsystems Inc.; 1.6.0_45-b06)
operating system: Windows 7 6.1 (x86 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Untitled

08:28:20.439 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
08:28:20.239 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
08:28:20.039 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
08:28:19.839 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
08:28:19.639 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
08:28:19.439 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
08:28:19.239 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
08:28:19.038 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
08:28:18.838 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
08:28:18.638 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

**Comment by SethTisue** [comment]
seems like almost certainly a JVM bug and not a NetLogo bug. (and if so, then hopefully fixed in Java 7 or 8. Java 6 came out in 2006!)

**Comment by SethTisue** [comment]
similar issue, but on Mac OS X: https://github.com/NetLogo/NetLogo/issues/541

**Comment by mrerrormessage** [comment]
The mac analog of this was fixed in 5.3. I'm marking this as closed. If you're continuing to see this, please comment and we'll reopen.
