### ISSUE TITLE
Need help to cope with the Netlogo error message

### ISSUE THREAD

**Issue by arvietrida** [NetLogo/NetLogo#818]
Dear NetLogo Team,

I am a PhD student in Loughborough University - UK and I am using NetLogo as the main platform of my modelling.
However, I got an error message and I do really need your help to interpret the error. I copied the error message below my email. 
Could you assist me for this, please...?

I would be very grateful for any of your great help for this.
Thank you very much for your very kind attention and response.

Best wishes,
Niniet
===================
Here is the message :
-----------------------------------------------------------
NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

org.nlogo.api.ValueConstraint$Violation: Value must be one of: ["Random" "Closest firm"]
 at org.nlogo.agent.ChooserConstraint.assertConstraint(ChooserConstraint.scala:31)
 at org.nlogo.agent.Observer.assertVariableConstraint(Observer.java:112)
 at org.nlogo.agent.Observer.setObserverVariable(Observer.java:119)
 at org.nlogo.agent.World.setObserverVariableByName(World.java:1349)
 at org.nlogo.lab.Worker$Runner$$anonfun$setVariables$1$4.apply(Worker.scala:128)
 at org.nlogo.lab.Worker$Runner$$anonfun$setVariables$1$4.apply(Worker.scala:122)
 at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
 at scala.collection.immutable.List.foreach(List.scala:76)
 at org.nlogo.lab.Worker$Runner.setVariables$1(Worker.scala:122)
 at org.nlogo.lab.Worker$Runner.callHelper(Worker.scala:166)
 at org.nlogo.lab.Worker$Runner.call(Worker.scala:91)
 at org.nlogo.lab.Worker$Runner.call(Worker.scala:74)
 at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
 at java.util.concurrent.FutureTask.run(FutureTask.java:138)
 at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
 at java.lang.Thread.run(Thread.java:662)

NetLogo 5.1.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) Server VM 1.6.0_45 (Sun Microsystems Inc.; 1.6.0_45-b06)
operating system: Windows 7 6.1 (x86 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Experiment 1.2.14 improving adjustposition

09:07:39.433 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
09:07:39.433 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
09:07:39.433 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
09:07:39.433 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
09:07:39.433 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
09:07:39.433 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
09:07:39.433 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
09:07:39.433 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
09:07:39.433 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
09:07:39.433 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0

**Comment by Idloj** [comment]
Do you set the value of a chooser's variable from code to something that isn't one of the choices?

**Comment by SethTisue** [comment]
It is itself a NetLogo bug that this results in the "NetLogo is unable to supply you with more details about this error" dialog. It ought to be an ordinary runtime error. Looks like a BehaviorSpace bug specifically.

**Comment by Idloj** [comment]
I think it's related to #551

**Comment by SethTisue** [comment]
Yes, good call.

**Comment by nicolaspayette** [comment]
Thanks for reporting this, @arvietrida! We have identified that the way NetLogo reported the error to you is a bug, but we haven't really helped you with your problem yet. This is not the right place to do it, however. Could you post the code that triggered the error at https://stackoverflow.com/questions/tagged/netlogo ? One of us will try to help you there.

**Comment by arvietrida** [comment]
Many thanks for your great responses for this! I have tried to trace the
error and it comes from my experimental design in the Behavior Space. I
just separated the string : [ "Random" "Closest firm" ] in two different
experiments and it works. Many thanks!!
