### ISSUE TITLE
BehaviorSpace allows Negative world dimensions

### ISSUE THREAD

**Issue by mrerrormessage** [NetLogo/NetLogo#939]
For instance `["min-pxcor" 1]`, `["max-pxcor" -1]` will result in a rather nasty stacktrace (see below). The provided world values should either be verified or raise a semantic exception during world setup which can then be provided to the user to allow for correction. Note that this bug is not possible to generate through the UI because the view validates that the world coordinates are sane before applying them.

```
ava.lang.NegativeArraySizeException
 at org.nlogo.agent.World.createPatches(World.java:725)
 at org.nlogo.agent.World.createPatches(World.java:684)
 at org.nlogo.headless.HeadlessWorkspace.setDimensions(HeadlessWorkspace.scala:237)
 at org.nlogo.workspace.WorldLoader.load(WorldLoader.scala:35)
 at org.nlogo.workspace.AbstractWorkspace.loadWorld(AbstractWorkspace.java:706)
 at org.nlogo.headless.HeadlessModelOpener$WidgetParser$.parseGraphicsWindow$1(HeadlessModelOpener.scala:210)
 at org.nlogo.headless.HeadlessModelOpener$WidgetParser$$anonfun$parseWidgets$2.apply(HeadlessModelOpener.scala:226)
 at org.nlogo.headless.HeadlessModelOpener$WidgetParser$$anonfun$parseWidgets$2.apply(HeadlessModelOpener.scala:217)
 at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
 at scala.collection.immutable.List.foreach(List.scala:76)
 at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:30)
 at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:44)
 at org.nlogo.headless.HeadlessModelOpener$WidgetParser$.parseWidgets(HeadlessModelOpener.scala:217)
 at org.nlogo.headless.HeadlessModelOpener.openFromMap(HeadlessModelOpener.scala:38)
 at org.nlogo.headless.HeadlessWorkspace.openString(HeadlessWorkspace.scala:531)
 at org.nlogo.app.App$$anon$6.newInstance(App.scala:123)
 at org.nlogo.lab.gui.Supervisor$$anonfun$start$1.apply$mcVI$sp(Supervisor.scala:90)
 at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:78)
 at org.nlogo.lab.gui.Supervisor.start(Supervisor.scala:89)
 at org.nlogo.lab.gui.ManagerDialog.org$nlogo$lab$gui$ManagerDialog$$run(ManagerDialog.scala:90)
 at org.nlogo.lab.gui.ManagerDialog$$anonfun$6.apply$mcV$sp(ManagerDialog.scala:27)
 at org.nlogo.lab.gui.ManagerDialog$$anon$2.actionPerformed(ManagerDialog.scala:21)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
 at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
 at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
 at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
 at ch.randelshofer.quaqua.QuaquaButtonListener.mouseReleased(QuaquaButtonListener.java:112)
 at java.awt.Component.processMouseEvent(Component.java:6535)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
 at java.awt.Component.processEvent(Component.java:6300)
 at java.awt.Container.processEvent(Container.java:2236)
 at java.awt.Component.dispatchEventImpl(Component.java:4891)
 at java.awt.Container.dispatchEventImpl(Container.java:2294)
 at java.awt.Component.dispatchEvent(Component.java:4713)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
 at java.awt.Container.dispatchEventImpl(Container.java:2280)
 at java.awt.Window.dispatchEventImpl(Window.java:2750)
 at java.awt.Component.dispatchEvent(Component.java:4713)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.awt.EventQueue$4.run(EventQueue.java:729)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

NetLogo 5.3
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_72 (Oracle Corporation; 1.8.0_72-b15)
operating system: Mac OS X 10.11.3 (x86_64 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Wolf Sheep Predation

11:25:37.608 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:25:37.608 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:25:37.608 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:25:37.608 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:25:37.608 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:25:37.608 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:25:37.608 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
11:25:37.608 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:25:37.608 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
11:25:37.608 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
```

**Comment by Harvey-Theking** [comment]
How can this bug be generated for the HeadlessWorkspace case? I generated the bug for the GUIWorkspace case by loading a model from the library and setting the world dimensions above.

**Comment by mrerrormessage** [comment]
@Harvey-Theking , sorry to leave you hanging for so long. I'm going to come up with a way to generate this in headless, I'm just working through a PR backlog and this wasn't at the top of my list. Hopefully I'll get back to you by tomorrow.

**Comment by mrerrormessage** [comment]
@Harvey-Theking , to get this to happen in `HeadlessWorkspace`, take the model you used for GUIWorkspace and save it. Then open `sbt` and run the following:
```
runMain org.nlogo.headless.Main --model /path/to/your/model.nlogo --experiment <your experiment name> --table foo.csv
```
You should see an error.

If you would like to write a test in scalatest, that would be another way to test it and I can provide more information for you if you would like to go that route.
