### ISSUE TITLE
BehaviorSpace crashes when running on 160 cpus

### ISSUE THREAD

**Issue by rfmvh** [NetLogo/NetLogo#942]
When running any BehaviorSpace experiment on a machine with many CPUs (160 in my case), the netlogo-headless crashes. For example using a simple experiment created within the "Fire" sample model (app/models/Sample Models/Earth Science/Fire.nlogo).

I discovered that disabling most of the processors leaving "more sane" number of them online (4 or 8) works around the issue, so netlogo runs on that box, but one cannot take advantage of the power.

Cutting the threads by '--threads' option helps as well.

I am using RHEL 7.2 with java-1.8.0-openjdk-1.8.0.71.

Sometimes I got PermGen error, but usually the following one:

----------------------------------------------------

$ ./netlogo-headless.sh --model DATA/Fire.nlogo --experiment experiment --table RESULTS/fire.csv 
Exception in thread "JobThread" Exception in thread "JobThread" Exception in thread "JobThread" Exception in thread "main" Exception in thread "JobThread" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.ArrayList.iterator(ArrayList.java:834)
	at java.util.Collections$SynchronizedCollection.iterator(Collections.java:2031)
	at org.nlogo.job.JobThread.org$nlogo$job$JobThread$$compact(JobThread.scala:195)
	at org.nlogo.job.JobThread$$anonfun$run$1.apply$mcV$sp(JobThread.scala:77)
	at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
	at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
	at scala.util.control.Exception$Catch.apply(Exception.scala:88)
	at org.nlogo.util.Exceptions$.handling(Exceptions.scala:41)
	at org.nlogo.job.JobThread.run(JobThread.scala:75)
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.ArrayList.iterator(ArrayList.java:834)
	at java.util.Collections$SynchronizedCollection.iterator(Collections.java:2031)
	at org.nlogo.job.JobThread.org$nlogo$job$JobThread$$compact(JobThread.scala:195)
	at org.nlogo.job.JobThread$$anonfun$run$1.apply$mcV$sp(JobThread.scala:77)
	at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
	at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
	at scala.util.control.Exception$Catch.apply(Exception.scala:88)
	at org.nlogo.util.Exceptions$.handling(Exceptions.scala:41)
	at org.nlogo.job.JobThread.run(JobThread.scala:75)
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Observable.<init>(Observable.java:69)
	at org.nlogo.agent.Agent.<init>(Agent.java:38)
	at org.nlogo.agent.Patch.<init>(Patch.java:70)
	at org.nlogo.agent.World.createPatches(World.java:735)
	at org.nlogo.agent.World.createPatches(World.java:684)
	at org.nlogo.headless.HeadlessWorkspace.setDimensions(HeadlessWorkspace.scala:237)
	at org.nlogo.workspace.WorldLoader.load(WorldLoader.scala:35)
	at org.nlogo.workspace.AbstractWorkspace.loadWorld(AbstractWorkspace.java:706)
	at org.nlogo.headless.HeadlessModelOpener$WidgetParser$.parseGraphicsWindow$1(HeadlessModelOpener.scala:210)
	at org.nlogo.headless.HeadlessModelOpener$WidgetParser$$anonfun$parseWidgets$2.apply(HeadlessModelOpener.scala:226)
	at org.nlogo.headless.HeadlessModelOpener$WidgetParser$$anonfun$parseWidgets$2.apply(HeadlessModelOpener.scala:217)
	at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
	at scala.collection.immutable.List.foreach(List.scala:76)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:30)
	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:44)
	at org.nlogo.headless.HeadlessModelOpener$WidgetParser$.parseWidgets(HeadlessModelOpener.scala:217)
	at org.nlogo.headless.HeadlessModelOpener.openFromMap(HeadlessModelOpener.scala:38)
	at org.nlogo.headless.HeadlessWorkspace.openString(HeadlessWorkspace.scala:531)
	at org.nlogo.headless.HeadlessWorkspace.open(HeadlessWorkspace.scala:513)
	at org.nlogo.headless.Main$.newWorkspace$1(Main.scala:19)
	at org.nlogo.headless.Main$$anonfun$runExperiment$1.apply(Main.scala:24)
	at org.nlogo.headless.Main$$anonfun$runExperiment$1.apply(Main.scala:24)
	at org.nlogo.lab.Lab$$anonfun$1.apply(Lab.scala:33)
	at org.nlogo.lab.Lab$$anonfun$1.apply(Lab.scala:33)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:233)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:233)
	at scala.collection.immutable.Range.foreach(Range.scala:78)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:233)
	at scala.collection.immutable.Range.map(Range.scala:46)
	at org.nlogo.lab.Lab.run(Lab.scala:33)
	at org.nlogo.headless.Main$.runExperiment(Main.scala:24)
	at org.nlogo.headless.Main$$anonfun$main$1.apply(Main.scala:14)
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.ArrayList.iterator(ArrayList.java:834)
	at java.util.Collections$SynchronizedCollection.iterator(Collections.java:2031)
	at org.nlogo.job.JobThread.org$nlogo$job$JobThread$$compact(JobThread.scala:195)
	at org.nlogo.job.JobThread$$anonfun$run$1.apply$mcV$sp(JobThread.scala:77)
	at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
	at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
	at scala.util.control.Exception$Catch.apply(Exception.scala:88)
	at org.nlogo.util.Exceptions$.handling(Exceptions.scala:41)
	at org.nlogo.job.JobThread.run(JobThread.scala:75)
java.lang.OutOfMemoryError: GC overhead limit exceeded

**Comment by rfmvh** [comment]
...happens with NetLogo 5.2.1 as well as with 5.3.

**Comment by SethTisue** [comment]
this is working as expected. if you want to do 160 model runs at once, you need a heap which is 160 times as large. See http://ccl.northwestern.edu/netlogo/docs/faq.html#howbig and http://ccl.northwestern.edu/netlogo/docs/behaviorspace.html . the latter says: "doing runs in parallel will multiply the experiment's memory requirements accordingly. You may need to increase NetLogo's memory ceiling"

**Comment by rfmvh** [comment]
Do you mean using something like '-Xmx256G'? Yes, I tried that too. It didn't help anyway. I have 982 GB of free RAM on that machine, so I still can give it more memory than 1 GB per thread. However, this didn't help. I gave it up to 512 GB RAM, but when watching the RAM consumption via top, I haven't noticed any higher usage before the falls. It never took more than 0.2-0.3.

Is there anything else (logs, debugging info, ...) I can provide?

Might the problem be in the Java RE itself (not being configured/able/... to use so huge resources)?

**Comment by SethTisue** [comment]
> Might the problem be in the Java RE itself

right. I think your issue is not NetLogo specific. I can't offered detailed support on configuring your JVM for large heap.

**Comment by mrerrormessage** [comment]
I notice your error specifically mentions "GC overhead limit exceeded". You might try using the `-XX:-UseGCOverheadLimit` option, which disables GC overhead checks. **Be aware that this may lead to significantly longer runtimes, as the GC overhead limit is designed to keep the GC times reasonable**. 

You might also play around with the Java GC settings, including tweaking the java GC algorithm. [This blog post](http://www.cubrid.org/blog/dev-platform/how-to-tune-java-garbage-collection/) offers some of the options that may be useful. Chances are you will have to do some experimenting to figure out what works best for your particular machine and workload.
