### ISSUE TITLE
Primitive class absent from hexy branch

### ISSUE THREAD

**Issue by Harvey-Theking** [NetLogo/NetLogo#978]
The stack trace below was generated when loading the Sound Machines model. It works though under the 5.x branch. It seems the Primitive class is absent.

```
java.lang.reflect.InvocationTargetException
 at java.awt.EventQueue.invokeAndWait(EventQueue.java:1321)
 at java.awt.EventQueue.invokeAndWait(EventQueue.java:1296)
 at org.nlogo.awt.EventQueue$.invokeAndWait(EventQueue.scala:19)
 at org.nlogo.swing.ModalProgressTask$Boss.run(ModalProgressTask.scala:70)
Caused by: java.lang.NoClassDefFoundError: org/nlogo/api/Primitive
 at java.lang.Class.getDeclaredConstructors0(Native Method)
 at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
 at java.lang.Class.getConstructor0(Class.java:3075)
 at java.lang.Class.newInstance(Class.java:412)
 at org.nlogo.workspace.JarLoader.extensionClassManager(JarLoader.scala:48)
 at org.nlogo.workspace.ExtensionManager$$anonfun$7.apply(ExtensionManager.scala:155)
 at org.nlogo.workspace.ExtensionManager$$anonfun$7.apply(ExtensionManager.scala:153)
 at scala.Option.getOrElse(Option.scala:121)
 at org.nlogo.workspace.ExtensionManager.importExtension(ExtensionManager.scala:153)
 at org.nlogo.parse.StructureParser$$anonfun$parsingWithExtensions$1.apply(StructureParser.scala:67)
 at org.nlogo.parse.StructureParser$$anonfun$parsingWithExtensions$1.apply(StructureParser.scala:66)
 at scala.collection.immutable.List.foreach(List.scala:381)
 at org.nlogo.parse.StructureParser$.parsingWithExtensions(StructureParser.scala:66)
 at org.nlogo.parse.StructureParser$.parseSources(StructureParser.scala:34)
 at org.nlogo.parse.FrontEndMain$class.frontEnd(FrontEnd.scala:28)
 at org.nlogo.parse.FrontEnd.frontEnd(FrontEnd.scala:16)
 at org.nlogo.compiler.CompilerMain$.compile(CompilerMain.scala:28)
 at org.nlogo.compiler.Compiler.compileProgram(Compiler.scala:38)
 at org.nlogo.window.CompilerManager.compileProcedures(CompilerManager.java:108)
 at org.nlogo.window.CompilerManager.compileAll(CompilerManager.java:86)
 at org.nlogo.window.CompilerManager.handle(CompilerManager.java:70)
 at org.nlogo.window.Events$LoadEndEvent.beHandledBy(Events.java:448)
 at org.nlogo.window.Event.doRaise(Event.java:198)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.window.ModelLoader$Loader$$anonfun$loadHelper$1.apply(ModelLoader.scala:102)
 at org.nlogo.window.ModelLoader$Loader$$anonfun$loadHelper$1.apply(ModelLoader.scala:102)
 at scala.collection.immutable.List.foreach(List.scala:381)
 at org.nlogo.window.ModelLoader$Loader.loadHelper(ModelLoader.scala:102)
 at org.nlogo.window.ModelLoader$.load(ModelLoader.scala:17)
 at org.nlogo.window.ModelLoader.load(ModelLoader.scala)
 at org.nlogo.app.FileMenu$1.run(FileMenu.java:764)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
 at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
 at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
 at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
 at java.awt.Dialog.show(Dialog.java:1084)
 at java.awt.Component.show(Component.java:1673)
 at java.awt.Component.setVisible(Component.java:1625)
 at java.awt.Window.setVisible(Window.java:1014)
 at java.awt.Dialog.setVisible(Dialog.java:1005)
 at org.nlogo.swing.ModalProgressTask$.apply(ModalProgressTask.scala:43)
 at org.nlogo.swing.ModalProgressTask.apply(ModalProgressTask.scala)
 at org.nlogo.app.FileMenu.openFromMap(FileMenu.java:773)
 at org.nlogo.app.FileMenu.openFromSource(FileMenu.java:745)
 at org.nlogo.app.FileMenu$ModelsLibraryAction.action(FileMenu.java:168)
 at org.nlogo.app.FileMenu$FileMenuAction.actionPerformed(FileMenu.java:94)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
 at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
 at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
 at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
 at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
 at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
 at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
 at java.awt.Component.processMouseEvent(Component.java:6535)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
 at java.awt.Component.processEvent(Component.java:6300)
 at java.awt.Container.processEvent(Container.java:2236)
 at java.awt.Component.dispatchEventImpl(Component.java:4891)
 at java.awt.Container.dispatchEventImpl(Container.java:2294)
 at java.awt.Component.dispatchEvent(Component.java:4713)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
 at java.awt.Container.dispatchEventImpl(Container.java:2280)
 at java.awt.Window.dispatchEventImpl(Window.java:2750)
 at java.awt.Component.dispatchEvent(Component.java:4713)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.awt.EventQueue$4.run(EventQueue.java:729)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: org.nlogo.api.Primitive
 at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
 at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
 ... 96 more

NetLogo 6.0-M1
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_72 (Oracle Corporation; 1.8.0_72-b15)
operating system: Linux 4.2.0-30-generic (amd64 processor)
Scala version 2.11.7
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Sound Machines

03:34:07.708 RemoveAllJobsEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
03:34:07.665 LoadEndEvent (org.nlogo.window.ModelLoader$Loader (java.lang.Object)) AWT-EventQueue-0
03:34:07.665 LoadSectionEvent (org.nlogo.window.ModelLoader$Loader (java.lang.Object)) AWT-EventQueue-0
03:34:07.664 LoadSectionEvent (org.nlogo.window.ModelLoader$Loader (java.lang.Object)) AWT-EventQueue-0
03:34:07.664 LoadSectionEvent (org.nlogo.window.ModelLoader$Loader (java.lang.Object)) AWT-EventQueue-0
03:34:07.664 LoadSectionEvent (org.nlogo.window.ModelLoader$Loader (java.lang.Object)) AWT-EventQueue-0
03:34:07.641 LoadSectionEvent (org.nlogo.window.ModelLoader$Loader (java.lang.Object)) AWT-EventQueue-0
03:34:07.641 LoadSectionEvent (org.nlogo.window.ModelLoader$Loader (java.lang.Object)) AWT-EventQueue-0
03:34:07.640 WidgetAddedEvent (org.nlogo.widget.NoteWidget) AWT-EventQueue-0
03:34:07.637 WidgetAddedEvent (org.nlogo.widget.NoteWidget) AWT-EventQueue-0
```

**Comment by SethTisue** [comment]
looks like you switched branches without rebuilding extensions?

**Comment by qiemem** [comment]
Yup, make sure you run `git submodule update --init` at the command line to
get the latest extensions, and then `extensions` in SBT to compile the
extensions.

**Comment by Harvey-Theking** [comment]
I tried to update  as you said and I ran into this 
```error: Your local changes to the following files would be overwritten by checkout:
        test/exclude-dangling-link.graphml
Please, commit your changes or stash them before you can switch branches.
Aborting
Unable to checkout '320ef83356958cd5030b4bc490a34479ce5229b4' in submodule path 'extensions/nw'```

There are no changes to stash or commit and cleaning doesn't help.

**Comment by mrerrormessage** [comment]
@Harvey-Theking , try checking out `hexy` and then running `nightly.sh`. You can stop as soon as it starts loading sbt. It will ensure that all submodules are clean and fully up-to-date. I've also seen the `test/exclude-dangling-link.graphml` error before and I will open a new ticket to fix it. In the meantime, I'm closing this issue.

**Comment by Harvey-Theking** [comment]
Ok thanks.
